tloncorp/tlon-apps

packages/shared/src/api/channelsApi.ts
packages/shared/src/db/queries.ts
packages/shared/src/store/sync.ts

Fixes TLON-2064 by updating the logic around channel join updates on the channel subscription.
Also fixes an issue with initial sync if the ship doesn't know about any channels with writer roles (don't attempt to update unless we actually have something to insert, otherwise we'll fail because we're trying to insert nothing).
Attempted to handle channel leaves, but it looks like there might be a backend issue with leaving channels right now. Chatting with hunter about it.

native: correctly handle channel join updates

---

apps/tlon-web/src/components/Leap/useLeap.tsx
apps/tlon-web/src/dms/DMOptions.tsx
apps/tlon-web/src/logic/channel.ts
apps/tlon-web/src/state/unreads.ts

Previously only DMs and groups were fully reactive to their children, meaning that we took into account the client-side unread status of each child as a sum, so if a child was seen and it was the last source of unreads, the dot would go away. However, we weren't accounting for notify in the channel case which we always want to badge with a blue dot, but when I fixed that in tloncorp/tlon-apps#3589 this made blue dots stickier because channels weren't fully reactive to children.
This PR fixes TLON-2072 by making all sources fully reactive to their children's statuses.
PR Checklist

unreads: make all sources fully reactive to children

---

packages/ui/src/components/Channel/index.tsx
packages/ui/src/components/ChatMessage/ChatMessage.tsx
packages/ui/src/components/KeyboardAvoidingView.tsx
packages/ui/src/components/MessageInput/index.tsx
packages/ui/src/components/PostScreenView.tsx

Fixes TLON-2055
Fixes TLON-2073

native: reduce space within/between chat messages, fix keyboard offset in thread view

---

apps/tlon-mobile/src/screens/ChannelScreen.tsx
packages/shared/src/db/queries.ts
packages/shared/src/db/query.ts
packages/shared/src/store/postActions.ts
packages/shared/src/store/sync.ts

- Prevents replies from showing up in main scroll
- Fixes situation where conversations could become stuck when loading older posts
- Fixes issue where replies confused our channel cursor tracking, which could cause new posts to fail to appear
- Prevents channel cursor from changing after initially set, preventing some extraneous refreshes
Fixes TLON-2050

native: small sync fixes

---

desk/app/activity.hoon
desk/lib/activity-json.hoon
desk/lib/mark-warmer.hoon
desk/mar/activity/feed-init.hoon
desk/mar/activity/feed.hoon
desk/sur/activity.hoon
packages/shared/src/urbit/activity.ts

This adds two endpoints specifically for the activity tab with pagination.
`/activity/feed/init/{count}.json` gives latest items limited by count for each tab
`/activity/feed/{type}/{count}/{start}?.json`
- count: `@ud` representing number of items you wish to receive
- start: `@ud` or `@da` optional parameter, will only get events before this time
- type: `all | mentions | replies`
- `all`: any post, reply, dm, or dm reply that I was notified for
- `mentions`: any message that mentions me
- `threads`: any replies for which I was notified for
Also updates the `add` update to include source and the stringified form of source.
Fixes TLON-2036
PR Checklist

activity: feed endpoints

---

apps/tlon-mobile/src/screens/ChatListScreen.tsx
packages/ui/src/components/ChatList.tsx

From the department of "things nobody asked for."
- Updates the ChatListScreen's header to say "Home" by default.
- Changes the ChatListScreen's header text based on the user's scroll position in ChatList. Updates based on the title of the section, which could be out of view.
- Adds an isValidListItem check to filter out section headers (which aren't *technically* valid list items—the isGroup check will always fail without an ID when extracting the key).
- Resets the title to "Home" when the user has reached the top of the SectionList scroll.
Video attached.
https://github.com/tloncorp/tlon-apps/assets/748181/4aed4f12-93bd-4a5f-a102-aab3d4375648

native: "sticky" section headers on ChatListScreen

---

packages/shared/src/api/channelsApi.ts
packages/shared/src/api/groupsApi.ts
packages/shared/src/api/initApi.ts
packages/shared/src/db/migrations/0000_lean_ultragirl.sql
packages/shared/src/db/migrations/meta/0000_snapshot.json
packages/shared/src/db/migrations/meta/_journal.json
packages/shared/src/db/migrations/migrations.js
packages/shared/src/db/queries.ts
packages/shared/src/db/schema.ts

Right now the way we determine if you're a member of a channel is by seeing if you have an unread for it. This is similar to what we do on web, except that web also looks to see at least one of your roles is in the _readers_ array for that channel if the _readers_ array isn't empty.
We were only tracking channel writers on mobile, not readers. This adds support for storing readers and uses a check against read entries when setting `currentUserIsMember`.
Tested by checking that channels I didn't have access to were absent after the change.
Fixes TLON-2081

native: properly track channel membership

---

packages/ui/src/components/ChatMessage/ChatEmbedContent.tsx

fixes TLON-2085
We didn't need to use `canOpenUrl` here, that's not what it's for, and it was breaking the ability to open links in other apps that support them (i.e., a github link wouldn't open at all if you had github installed on your android phone, now it will open in the app).

native: fix link open issue

---

packages/ui/src/components/ContentRenderer.tsx

Fixes TLON-2086 (code blocks breaking out of their container on android)
Fixes TLON-2041 (other content appearing on the same line as a code block)

native: fix code block rendering issues

---

apps/tlon-mobile/src/components/AddGroupSheet.tsx
apps/tlon-mobile/src/lib/nativeDb.ts
apps/tlon-mobile/src/screens/ProfileScreen.tsx
packages/ui/src/components/AddChats/AddDmSheet.tsx
packages/ui/src/components/Channel/index.tsx
packages/ui/src/components/ProfileScreenView.tsx

Bit of a hodgepodge. 
Biggest piece is fixing a few Android bugs. Namely the new create/join sheets crashing due to an issue with Tamagui Sheet's ["modal" property](https://github.com/gorhom/react-native-portal/issues/34) and one where the empty channel message was showing up rotated.
Also adds the ability to log out and display hidden dev info by clicking the _Profile_  page avatar 5 times rapidly
Fixes TLON-1935
Fixes TLON-2042

native: android fixes, logout, & view build number

---

apps/tlon-web/src/chat/ChatMessage/ChatMessage.tsx
apps/tlon-web/src/chat/ChatThread/ChatThread.tsx
apps/tlon-web/src/chat/ChatWindow.tsx
apps/tlon-web/src/chat/UnreadAlerts.tsx
apps/tlon-web/src/dms/DMThread.tsx
apps/tlon-web/src/dms/DmWindow.tsx
apps/tlon-web/src/state/channel/channel.ts
apps/tlon-web/src/state/chat/chat.ts
apps/tlon-web/src/state/unreads.ts

This cleans up how we were clearing unreads when navigating away because it wasn't firing in all the cases we wanted. Also fixes the unread marker never going away because we weren't actually checking status for it exactly. Also fixed reply meta updating as well as replies not showing up in threads.
Fixes TLON-2096
PR Checklist

unreads: clear lingering unread markers

---

desk/app/activity.hoon

This fixes TLON-2087 by checking to see if the group has a setting and if so we don't set the old "default" on channels under that group.
Tested by setting a group volume with `:groups &volume-set [[%group ~nibset-napwyn %tlon] %loud]` and then running the migration
PR Checklist

activity: dont set channel defaults if group has setting during migration

---

packages/shared/src/db/queries.ts

We have an ordering bug if the last message sent was from you. Right now we cue off unread recency, but messages sent by you don't trigger changes in `%activity`. 
I believe Hunter is working on a fix for this at the agent level, but we can also utilize the `lastPostAt` which we already have and should be more up to date in the case of messages sent by you. This PR simply updates the ordering for the chat list query to coalesce the two columns instead of purely relying on unread data.
Fixes TLON-2101

native: fix chat list ordering bug

---

apps/tlon-web/src/state/chat/chat.ts

Fixes TLON-2107. We were attempting to use `time` (which is null when we create a new reply) as a key for optimistically adding a new reply on a parent message. We used to use `sent` on `memo` to do this (not sure why this changed), reverting back to using `memo.sent` here fixes the issue.

web: fix issue with sending DM replies

---

apps/tlon-web/src/logic/useMessageSelector.ts

Fixes TLON-2114. We were finding the first unread that matched `ship/${theShip}` and then returning that unread key as the existing DM. This got inserted into the route as `/new/ship/~sampel-palnet`, which puts `new` in the `:ship` parameter place. the `Message` component then checks if the `:ship` parameter is a patp. If it's not, it assumes multidm. We then routed the user to the MultiDm component, and since they're not in a MultiDM with that ID we show the invite accept/reject page (which won't work because this isn't a mutidm and that isn't a valid multidm ID).
The fix is just to return only the patp from the unread key, chopping off the `ship/` portion.

web: fix bug with new dm creation

---

apps/tlon-web/src/components/Sidebar/GroupsSidebarItem.tsx
apps/tlon-web/src/components/Sidebar/Sidebar.tsx
apps/tlon-web/src/groups/GroupActions.tsx
apps/tlon-web/src/state/unreads.ts

Fixes TLON-2109 by:
a) including all children starting from the top (i.e., groups will have channels as children, channels will have threads, this will be accessible from the group unread itself. Before, groups would have channels and the channels would not have their own children).
b) making sure we rollup status/count/notify when nested children call for it (i.e., someone has replied to you in a thread).

web: include all children, as appropriate, in combined unread data

---

desk/app/chat.hoon

We forgot to add an activity entry for clubs when they're initialized. Fixes TLON-2117
PR Checklist

chat: add club invites

---

packages/ui/src/components/Channel/Scroller.tsx

Fixes TLON-2126. We weren't accounting for the empty post that gets added to gallery channels when we have unreads, so the scrollToIndex was always given an index that was out of range, causing an error to be thrown.

native: fix for crash in galleries with unread posts

---

packages/shared/src/db/queries.ts
packages/shared/src/logic/utils.ts

- Replaces `isSameDay` with a faster, numeric version (previously it was taking up an inordinate amount of time during render).
- Optimizes `setLastPosts` and `setPostGroups` to only update changed rows, which prevents database traffic jams when posts are updated.

native: small perf optimizations

---

packages/shared/src/api/activityApi.ts
packages/ui/src/components/MessageInput/index.native.tsx
patches/@10play__tentap-editor@0.4.55.patch
pnpm-lock.yaml

Fixes TLON-2130.
This is an attempt to catch all the ways that the editor webview could fail and then force a reload. The particular issue that was happening with TLON-2130 seems to have been a race condition with setting up tiptap within tentap (not all extensions were loaded in time, which seems like it shouldn't happen, but is). I patched tentap to catch any errors with tiptap and send a message to the native side if it happens, the native side then reloads the webview.
We also reload for other various failure modes, and inject some JS in the webview to try catch any errors that might be happening in the JS running within the webview.

native: catch issues w/input webview and force reload

---

packages/ui/src/components/MessageInput/index.native.tsx
packages/ui/src/tamagui.config.ts

fixes TLON-2130 (again). Previously we were reloading anytime the editor wasn't ready, but this could cause extraneous reloads that then caused other issues. Now we'll only reload the webview if we *know* it has crashed.
Also changes the font used in the system font, happened upon this issue while looking at the xcode console (the app was endlessly spamming the console with: `Unrecognized font family 'System, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Ubuntu, 'Helvetica Neue', sans-serif'`)

native: only reload input webview if we know we have an issue

---

apps/tlon-mobile/src/App.main.tsx
packages/shared/src/db/migrations/0000_productive_vision.sql
packages/shared/src/db/migrations/meta/0000_snapshot.json
packages/shared/src/db/migrations/meta/_journal.json
packages/shared/src/db/migrations/migrations.js
packages/shared/src/db/queries.ts
packages/shared/src/db/query.ts
packages/shared/src/db/schema.ts
packages/shared/src/debug.ts
packages/shared/src/store/sync.ts
packages/shared/src/store/useChannelPosts.ts
packages/ui/src/components/Channel/Scroller.tsx

This PR includes a bunch of small improvements that have come out of debugging message sending.
- Improves performance of `insertChannelPosts`
- Ensures that migrations errors propagate to the error boundary
- Logs timings by default
- Fixes a bug that could cause `useChannelPosts` to fail to fetch a newer page.
- Deduplicates `addPost` events from the api (they're usually duplicated)
- Memoizes the scroller
Will hopefully address TLON-2141, but need to verify.

native: message send improvements

---

apps/tlon-mobile/src/App.main.tsx

Previously, we were throwing a generic, uninformative error.

throw actual error on migration failure

---

apps/tlon-mobile/src/lib/nativeDb.ts

This PR fixes migration failure issues by removing a duplicate call to `runMigrations`.

fix migration error

---

packages/shared/src/api/activityApi.ts
packages/shared/src/api/initApi.ts
packages/shared/src/db/queries.ts
packages/shared/src/store/sync.ts
packages/ui/src/components/ContentReference/GroupReference.tsx
packages/ui/src/components/GroupListItem/GroupListItemContent.tsx
packages/ui/src/components/GroupPreviewSheet.tsx

Bit of a hodgepodge, stumbled upon these while investigating missing unreads. I was testing joining/leaving groups and noticing we could get stuck in inconsistent states.
- fixes empty info list item for invites to groups with missing metadata (falls back to displaying the group ID)
- ensures query powering the chat list only considers group channels where you're joined to the group
- adds behavior to reconcile group and channel joins & leaves in cases where we don't explicitly hear the fact
- adds more early returns for `inArray` based queries if the array is empty
Fixes TLON-1946

native: a few fixes

---

packages/ui/src/components/Channel/Scroller.tsx

Fixes TLON-2148, we need to make sure we have an index great than zero, otherwise we'll try to scroll to -1 when the firstUnread is at the 0 position.

native: fix crash on navigating to gallery with one unread

---

apps/tlon-web/src/chat/ChatInput/ChatInput.tsx
apps/tlon-web/src/state/unreads.ts
desk/app/activity.hoon
desk/app/channels.hoon
desk/app/chat.hoon
desk/sur/activity.hoon

Fixes TLON-2088 by changing the way we give recency values in that if the "read" floor is greater than the last message, make that the recency. However to get our %read action to put a value other than the last message time, I had to change the action type slightly. 
PR Checklist

activity: self activity should change recency

---

apps/tlon-web/src/groups/GroupAdmin/PrivacySelector.tsx

Fixes TLON-2177 by making sure that the frontend doesn't accidentally clear the cordon when swapping between private/secret
PR Checklist

privacy-selector: dont accidentally clear cordon

---

apps/tlon-mobile/src/navigation/GroupSettingsStack.tsx
apps/tlon-mobile/src/navigation/RootStack.tsx
apps/tlon-mobile/src/screens/ChatListScreen.tsx
apps/tlon-mobile/src/screens/GroupSettings/GroupMembersScreen.tsx
apps/tlon-mobile/src/screens/GroupSettings/GroupMetaScreen.tsx
apps/tlon-mobile/src/screens/GroupSettings/GroupRolesScreen.tsx
apps/tlon-mobile/src/screens/GroupSettings/InvitesAndPrivacyScreen.tsx
apps/tlon-mobile/src/screens/GroupSettings/ManageChannelsScreen.tsx
apps/tlon-mobile/src/screens/GroupSettings/useGroupContext.ts
apps/tlon-mobile/src/types.ts
packages/shared/src/db/queries.ts
packages/ui/src/components/GroupOptionsSheet.tsx

- Adds the long press sheet back for groups, updating it to match current wireframes.
- Adds a new stack navigator for group settings and new stub screens (some of these screens could end up being navigators themselves).
- Adds useGroupContext where we'll pull data or functions for setting data, with probably nearly all of the functions stubbed out.
Fixes TLON-2181

native: tee up group settings work

---

apps/tlon-web/src/state/broadcasts.ts

The type of `Unread` was changed slightly before #3535 got merged. Here, we update `cohortToUnread` to construct a proper new `Unread` object.

broadcasts: update cohortToUnread for new Unread

---

packages/shared/src/db/queries.ts
packages/ui/src/components/Channel/Scroller.tsx

Currently, when the first unread of a channel is a deleted message, the channel screen will appear blank. This PR fixes that by:
- Modifying the `getChannelPosts` query so that it can retrieve posts around a given post, even if that post has been deleted, as long as it's covered by a window. If the post is deleted, it will get posts around where the post would have been.
- Adding logic to the `Scroller` that will make it visible once we've rendered the first page of posts, even if we haven't found our anchor post.
Fixes TLON-2142

native: handle deleted unread

---

apps/tlon-web/src/replies/ReplyMessage.tsx
desk/app/activity.hoon
desk/app/chat.hoon
desk/desk.docket-0

Fixes TLON-2103 by adding some cleanup to the on-load arm. This is some of the most wild juggling, but I'm not sure how to do it any better.
The basic idea is go through all our sources that come from clubs that are dms or dm threads. For DMs we just need to comb through the stream and correct any keys we find. 
For threads we have to do more work since the source identifiers themselves have bad keys. So first we gather all the source index pairs that share the same message ID, then we go through the entire list of threads and look to see what was gathered under the ID they shared. If we don't have an entry for that source yet we create one and merge all the data collected under that same ID. Then we keep going until we have the real threads. Finally once we come back around to actually …

activity: correct bad activity keys 

---

packages/shared/src/logic/utils.ts
packages/shared/src/store/sync.ts

Adds retry logic to the individual pieces of our fetching startup sequence. If after retrying we still fail, we'll pop the error boundary to prevent app use in an unknown state.
Once we support offline mode (where failure here would make sense), we'll need to be more careful about deciding when exactly to throw. But for now, we lock the screen if there's no network connection anyhow.
Fixes TLON-2183

native: sync start robustness

---

desk/app/activity.hoon

activity: handle scry poles correctly

---

desk/app/activity.hoon

After discussion with @latter-bolden, we decided to change how `count` in activity summaries gets tallied to better reflect what expect UX-wise, aka ignoring threads that don't involve us. 
We refresh all summaries on load since that shouldn't take very long and likely should be done anytime the agent changes, and in this case we have to for those counts to get updated immediately.
PR Checklist

activity: refine combined count for channels

---

desk/app/channels-server.hoon
desk/app/groups.hoon

As discussed out of band with @arthyn, we should have some more of these. This is a start.
We see crash traces for all kinds of things. Currently, we print poke and watch nack traces to the user's terminal. These by themselves only point at the codepath, but don't explicate the crash reason (which could also be deduced from the trace) or the resource that was operated on (which might not be recoverable in cases where we don't have/print the wire).
Here, we add a couple of trace hints, to print subscription paths and resource identifiers in common crash pathways.

various: add resource-id-ing ~| into common paths

---

desk/app/activity.hoon

Instead of incrementing the atom, add a proper fraction to it. This way, we don't end up with crazy long `@da` renderings all over the place.

activity: increment time-ids in "better" steps

---

packages/shared/src/api/activityApi.ts
packages/shared/src/api/unreads.test.ts
packages/shared/src/db/queries.ts
packages/ui/src/components/Activity/ChannelActivitySummary.tsx
packages/ui/src/components/ChannelListItem/index.tsx

OTT
The way @arthyn updated the backend, changes needed here are actually pretty light!
Fixes TLON-2157

native: include involved threads in group/channel count

---

apps/tlon-web/src/chat/ChatMessage/ChatMessage.tsx
apps/tlon-web/src/chat/ChatMessage/ChatMessageOptions.tsx
apps/tlon-web/src/chat/ChatMessage/DeletedChatMessage.tsx
apps/tlon-web/src/chat/ChatScroller/ChatScroller.tsx
apps/tlon-web/src/dms/MessagesList.tsx
apps/tlon-web/src/dms/MessagesSidebarItem.tsx
apps/tlon-web/src/logic/useScrollerMessages.ts
desk/app/channels.hoon

This fixes TLON-2188 by showing a deleted message placeholder so that the unread marker can be displayed. Additionally this stops the %channels agent from sending edits as activity events. If we want this in the future, we'll probably want to handle it differently.
PR Checklist

activity: allow clearing unreads for deleted messages

---

apps/tlon-mobile/src/App.main.tsx

iOS is barking about not supporting custom traces quite yet

native: remove custom perf trace

---

packages/shared/src/api/activityApi.ts
packages/ui/src/components/ChatMessage/ChatMessageReplySummary.tsx

I missed versioning the new unreads scry, so we were getting correct data on init but pulling incorrect data on updates. This fixes it to consistently use the new API.
Also leaves unread thread indicator dots gray if you're uninvolved (not just muted)
Fixes TLON-2212

native: unreads hotfix

---

packages/shared/src/db/changeListener.ts

We were invalidating on changes to the post and post reactions tables, but not the unread. Symptom was you'd have to leave the channel to see the thread marked as read.
Fixes TLON-2214

native: account for changes in thread unreads when using live post

---

apps/tlon-mobile/src/hooks/useImageUpload.ts

The deleted code has been there for a while, but interacts poorly with the newly added effect on line 39. Since we clear the file uploader after setting the `uploadedImage`, that effect conditional will always immediately reset the state (at least in the case of the channel attachment input flow).
Unclear to me what case that new logic is meant to combat (@patosullivan maybe we can chat about this on Monday). That said, I don't think we need to be clearing the uploader immediately either, not sure why I originally had that line there. 
After removing, I tested situations that might intersect with removing this code (clearing the attachment and adding another, navigating away without sending). Couldn't find any breakages. 
Fixes TLON-2218

native: fix image upload

---

packages/shared/src/db/queries.ts

More prevention against running array based DB operations when the array is empty. In particular, this targets `insertGroups` which is a spot where we're seeing crashlytics start sync issues. Not positive this will resolve those, but I think this is worth including in the next build and should be a low risk change.
Fixes TLON-2224 (hopefully)

native: more empty array checks on `insertGroups`

---

packages/shared/src/debug.ts
packages/shared/src/store/useChannelPosts.ts

Refactors + significantly simplifies `useChannelPosts` to fix an issue where posts could sometimes appear out of order.
- Removed `queryClient` based update logic
- Added a `newPosts` array, tracked separately from query results
- When new posts come in, they get merged into the array, which is manually resorted to preserve order.
- When merging `newPosts` and `queryPosts`:
- We only include `newPosts` that are newer than the newest `queryPost` to prevent duplicates.
- This also handles the case where the channel query is invalidated. On refetch, the query will load all posts up the newest in the database, so older `newPosts` will be ignored.
- Not highly optimized, could have perf issues at some point, but seemed fine in testing up to 100 new posts.
Fixes TLON-2243 and TLON-2205

native: ensure new posts in channel render in correct order

---

packages/shared/src/store/useChannelPosts.ts

Fixes the failure to load Pat found last night. Turned out to be super easy to reproduce/fix in channels with unreads. We were shortcircuiting loads based on whether we had newest posts, regardless of where in the scrollback we were trying to load.
Fixes TLON-2249

fix load regression

---

packages/ui/src/components/ContentReference/ChannelReference.tsx
packages/ui/src/components/ContentReference/ChatReferenceWrapper.tsx
packages/ui/src/components/ContentReference/index.tsx

We weren't passing the replyId into ChannelReference or ChatReferenceWrapper, previously.
Fixes TLON-2213.

native: fix reply references

---

desk/app/activity.hoon

witness my sin, accidentally used map instead of mop leading to out of order issues
PR Checklist

activity: dont mix maps and mops

---

apps/tlon-mobile/src/screens/ChatListScreen.tsx
packages/shared/src/store/sync.ts

Fixes TLON-2133 (kinda) by fetching pins on focus of the main list. We don't have a subscription for pin events, so this is the best we can do for a quick fix.

native: fetch pins on main list focus

---

apps/tlon-web/src/components/References/NoteReference.tsx
apps/tlon-web/src/components/Sidebar/util.tsx

OTT, if you currently click a ref in the messages tab that goes to notebook or gallery item it just sends you to blank page.
PR Checklist

nav-within-tab: make sure we send groups only stuff to the right place

---

desk/desk.docket-0
packages/ui/src/components/ContentReference/ChannelReference.tsx
packages/ui/src/components/ContentReference/NotebookReference.tsx
packages/ui/src/components/ContentReference/NotebookReferenceWrapper.tsx
packages/ui/src/components/ContentRenderer.tsx

Fixes TLON-2255
Will cause some merge conflicts with my other PR, but nbd.

native: implement notebook refs

---

desk/app/chat.hoon
desk/app/notify.hoon
desk/lib/notify.hoon

Fixes TLON-2269 by changing the paths we send to hark. Also includes the `@da` version of the activity ID that we send to Twilio so that we can use it instead of the old `@uv` version. Either version is supported in notify so this is just some cleanup.
PR Checklist

notify/chat: correct dm thread paths and prep for activity cutover

---

apps/tlon-mobile/src/screens/ShipLoginScreen.tsx
apps/tlon-mobile/src/screens/SignUpEmailScreen.tsx
apps/tlon-mobile/src/screens/TlonLoginScreen.tsx

Prevents users from logging in to the app with a Tlon-hosted ship URL and +code. This means we don't have to do suspension detection and revival in this login flow as well.
Also adds "Back" buttons to all login screens to allow the user to flip between methods without force-killing the app (!).
Fixes TLON-2285

native: prevent URL and +code login for Tlon-hosted ships

---

packages/shared/src/db/queries.ts

While adding offline state visualization, I noticed that in my app the session was never initializing. On investigation, it was because `insertBlockedContacts` was consistently failing, which was because `conflictUpdateSet` didn't properly handle columns where the js name differed from the camelCase version of the sqlite column name. This PR fixes that issue.

fix blocked users insert

---

apps/tlon-mobile/src/fixtures/GroupList.fixture.tsx
apps/tlon-mobile/src/screens/ChatListScreen.tsx
packages/ui/src/components/ChatList.tsx

Fixes TLON-2378 by adding a button to show the filters rather than relying entirely on the animation. Left the animation in since we may want to keep that functionality on iOS and fix the issue with Android later.

native: add button for showing chat list filters

---

apps/tlon-mobile/src/fixtures/Channel.fixture.tsx
apps/tlon-mobile/src/fixtures/DetailView.fixture.tsx
apps/tlon-mobile/src/fixtures/MessageInput.fixture.tsx
apps/tlon-mobile/src/fixtures/PostScreen.fixture.tsx
apps/tlon-mobile/src/screens/ChannelScreen.tsx
apps/tlon-mobile/src/screens/useChannelContext.ts
packages/shared/src/api/postsApi.ts
packages/shared/src/store/postActions.ts
packages/ui/src/components/Channel/Scroller.tsx
packages/ui/src/components/Channel/index.tsx
packages/ui/src/components/ChatMessage/ChatMessage.tsx
packages/ui/src/components/ContentRenderer.tsx
packages/ui/src/components/DetailView/DetailView.tsx
packages/ui/src/components/MessageInput/MessageInputBase.tsx
packages/ui/src/components/MessageInput/index.native.tsx
packages/ui/src/components/PostScreenView.tsx
packages/ui/src/contexts/requests.tsx

Fixes TLON-2332, which addressed an issue where reply edits were not being processed and any edits, if processed, were not triggering a re-render of the post.
summary:
1. the parentId is now sent to the editPost function, which allows us to actually edit them.
2. updated the types to accurately reflect that editPost and sendPost are async.
3. added memo comparison functions and updated useLivePost to ensure that the latest post is always rendered.
4. added new loggers in postsApi and postActions.

native: fix post editing issues

---

packages/ui/src/components/MessageInput/index.native.tsx

We don't want to `await` the `send` because we need to clear the editor content and the draft immediately.
fixes TLON-2386

native: clear message input immediately on send

---

apps/tlon-mobile/android/app/src/main/java/io/tlon/landscape/api/TalkApi.java
apps/tlon-mobile/ios/Landscape/Networking/PocketNotificationsAPI.swift

Updates the Swift and Java code to use the new endpoint with Mark's delivery instrumentation. 
Tested on iOS with posts and threads for groups and DMs. I don't have local testing setup for Android notifications, but will confirm it's working on that platform after merging.
Fixes TLON-2226

native: update notifications to use instrumented endpoint

---

apps/tlon-web/src/state/storage/upload.ts
packages/shared/src/store/storage/storage.ts
packages/shared/src/store/storage/upload.ts
packages/shared/src/store/storage/utils.ts

Uses the new memex endpoint from [this PR](https://github.com/tloncorp/ylem/pull/1995) to handle file uploads without relying on redirect semantics. Confirmed this works on iOS sim and resolved our issue on Android (checked via emulator). Will confirm it also resolves the issue with hosted uploads on web once it hits wannec.
We should hold on merging until the hosting PR makes it to prod (tested against staging).
Fixes TLON-2241
Fixes TLON-2365

native and web: use new memex upload endpoint

---

desk/app/activity.hoon

Classic case of rendering nouns that we won't print unless a flag is set. Noun renders can be quite slow for bigger nouns, and turns out we're printing a good handful of those. This should resolve the worst of the performance problems people were seeing.
(Activity still isn't fast by any means, summarizing unreads may still take over a second, but the impact of noun rendering was just egregious.)

activity: only render logs if we need them

---

apps/tlon-web/src/state/storage/upload.ts

Web image upload is finally working (locally). I need to have this pushed to a hosted ship so we can do further testing.
For context, there were two remaining issues:
1. The bucket was misconfigured, which was causing the cors issues seen when using the new memex `upload` endpoint. The pre-existing cors config was
```
$ gcloud storage buckets describe gs://tlon-test-memex-assets --format="default(cors_config)"
cors_config:
- maxAgeSeconds: 3600
method:
- GET
- PUT
origin:
- '*'
responseHeader:
- Content-Type
```
I initially changed that to have 
```
responseHeader:
- Content-Type
- Access-Control-Allow-Origin
```
and later
```
responseHeader:
- Content-Type
- Access-Control-Allow-Origin
- Access-Control-Allow-Methods
```
Both of these didn't work. What worked was updating it to the …

web: fix image upload content-length

---

desk/lib/activity.hoon

Previously, we were giving all sources as children of base. But this doesn't fit with our source hierarchy, and is not how `+get-children` is used in `/app/activity`.
Now, we only return `%group` and `%dm` sources as children of %base, and let the code iterate further on those for deeper processing.
With this change, we no longer do repeated processing of `%thread` and `%dm-thread` sources, resulting in (on ~palfun) a 20% speedup in unread summarization.

activity: only direct kids from +get-children

---

packages/shared/src/api/postsApi.ts
packages/shared/src/logic/utils.ts
packages/shared/src/store/postActions.ts
packages/shared/src/store/sync.ts
packages/ui/src/components/MessageInput/index.native.tsx
packages/ui/src/contexts/references.tsx

Fixes TLON-2338. We need to keep track of any attachments (images, references) to messages we're editing and make sure they're not overwritten when we insert the existing post content into the editor.

native: fix issue with non-inline content clearing on edit

---

apps/tlon-mobile/src/lib/hostingApi.ts
apps/tlon-mobile/src/navigation/RootStack.tsx
apps/tlon-mobile/src/screens/ManageAccountScreen.tsx

After you manage your account, we need to make sure you didn't delete it and log you out if you did. False positives (where you get logged out when you shouldn't) were happening too frequently, so this adds retry logic to avoid that situation.
Fixes TLON-2396

native: avoid erroneous logout after managing account

---

apps/tlon-mobile/src/screens/ChannelScreen.tsx
packages/ui/src/components/MessageInput/index.native.tsx

Should fix the issue Pat reported where hitting send with an image attached left the image preview open even though the message _was_ actually sent. Believe this is related to the recent async changes there.
Fixes TLON-2392

native: reset image attachment after sending

---

packages/shared/src/db/queries.ts
packages/shared/src/store/dbHooks.ts
packages/shared/src/store/useKeyFromQueryDeps.ts
packages/ui/src/components/Activity/ChannelActivitySummary.tsx

This was happening because of a stale reference to the unread. Avoids this by way of a new `useLiveUnread` hook to avoid refetching the full activity query anytime unreads change. 
Fixes TLON-2234

native: fix lingering blue dots on activity items after clicking into them

---

apps/tlon-mobile/src/screens/ChannelScreen.tsx
packages/shared/src/api/postsApi.test.ts
packages/shared/src/db/migrations/0000_curvy_exodus.sql
packages/shared/src/db/migrations/meta/0000_snapshot.json
packages/shared/src/db/migrations/meta/_journal.json
packages/shared/src/db/migrations/migrations.js
packages/shared/src/db/queries.test.ts
packages/shared/src/db/schema.ts
packages/shared/src/store/channelActions.ts
packages/shared/src/store/groupActions.ts
packages/shared/src/store/sync.test.ts
packages/shared/src/test/helpers.ts
packages/shared/src/test/setup.ts
packages/ui/src/components/Channel/EmptyChannelNotice.tsx

fixes TLON-1970
- Added `channels` sqlite columns: `last_viewed_at`, `is_default_welcome_channel`
- Only show welcome notice when all are true: (1) visiting the channel for the first time, and (2) we know that this is the channel we autocreated on this client during a group creation, and (3) user is admin

native: dynamic channel welcome notice

---

packages/shared/src/api/channelsApi.ts
packages/shared/src/db/migrations/0000_overrated_leopardon.sql
packages/shared/src/db/migrations/meta/0000_snapshot.json
packages/shared/src/db/migrations/meta/_journal.json
packages/shared/src/db/migrations/migrations.js
packages/shared/src/db/queries.ts
packages/shared/src/db/schema.ts
packages/shared/src/store/postActions.ts
packages/shared/src/store/sync.ts
packages/ui/src/components/Channel/Scroller.tsx
packages/ui/src/components/ChatMessage/ChatMessage.tsx
packages/ui/src/components/GalleryPost/GalleryPost.tsx
packages/ui/src/components/NotebookPost/NotebookPost.tsx

Fixes TLON-2339
Also disables the ability to long press on the message once it is marked as deleted.
Looks like this in chat:

native: show 'delete message' when post has been deleted, clear out content in db

---

packages/ui/src/components/ChatList.tsx

Fixes TLON-2388 by:
- Making the search more performant using fuse.js
- Making sure the search re-runs when we change tabs
- Using a single `displayData` object for data in the section list.

native: fix searching within filters on chat list

---

desk/app/chat.hoon

Did this for DMs but forgot to do for clubs. Fixes TLON-2358
PR Checklist

chat: self group dm should bump

---

desk/desk.docket-0

since my filter search PR went to develop

develop -> staging

---

apps/tlon-web/src/app.tsx
apps/tlon-web/src/chat/ChatMessage/ChatMessage.tsx
apps/tlon-web/src/chat/ChatMessage/DeletedChatMessage.tsx
apps/tlon-web/src/chat/ChatScroller/ChatScroller.tsx
apps/tlon-web/src/replies/ReplyMessage.tsx
apps/tlon-web/src/state/activity.ts
apps/tlon-web/src/state/local.ts

This didn't have an issue, but it was old behavior we had that I think is better than what's currently in there. Basically there's three situations:
- tab is out of focus, so don't do any read marking and let them accumulate
- tab is in focus, and we're at the bottom of the channel, automatically mark read w/o showing markers
- tab is in focus, but we're not at the bottom of the channel, don't automatically mark read, let the normal "seeing" trigger mark read
PR Checklist

activity: don't mark read if tab not focused and automatically mark read at chat bottom

---

apps/tlon-web/src/styles/components.css

As reported in Tlon Local, links with classes were getting pasted in and showing up with no underline
PR Checklist

chat-input: fix invisible links

---

apps/tlon-mobile/src/components/AuthenticatedApp.tsx
apps/tlon-mobile/src/hooks/useAppForegrounded.ts
apps/tlon-mobile/src/screens/ChatListScreen.tsx
packages/ui/src/components/ChatList.tsx

- pad the bottom so no groups at the end of the list are obscured by the bottom nav
- stop refetching unreads anytime you return to the chatlist. Instead, only rerun that scry defensively whenever you foreground the app

native: a few ChatList fixes

---

packages/shared/src/store/sync.ts
packages/shared/src/store/useActivityFetchers.ts

After moving to activity v4, there was an issue with the partial unread updates we get from activity causing a full reconfiguration of which channels we're joined to.
This just adds an optional flag to specify when you do and do not have the full set of unreads and accordingly branches on that when deciding to update channel joins.
Fixes TLON-2420

native: fix joined channel detection

---

apps/tlon-mobile/src/fixtures/Channel.fixture.tsx
apps/tlon-mobile/src/fixtures/DetailView.fixture.tsx
apps/tlon-mobile/src/fixtures/PostScreen.fixture.tsx
apps/tlon-mobile/src/screens/ChannelScreen.tsx
apps/tlon-mobile/src/screens/PostScreen.tsx
packages/shared/src/api/postsApi.ts
packages/shared/src/db/modelBuilders.ts
packages/shared/src/db/queries.ts
packages/shared/src/store/postActions.ts
packages/ui/src/components/Channel/Scroller.tsx
packages/ui/src/components/Channel/index.tsx
packages/ui/src/components/ChatMessage/ChatMessage.tsx
packages/ui/src/components/DetailView/DetailView.tsx
packages/ui/src/components/DetailView/GalleryDetailView.tsx
packages/ui/src/components/DetailView/NotebookDetailView.tsx
packages/ui/src/components/GalleryPost/GalleryPost.tsx
packages/ui/src/components/NotebookPost/NotebookPost.tsx
packages/ui/src/components/PostScreenView.tsx

Fixes TLON-2407 by notifying a user when the post failed to send and allowing them to tap the post that will show a sheet which allows them to retry or delete the post.

native: allow user to retry or delete posts that failed to send

---

apps/tlon-web/src/chat/ChatScroller/ChatScroller.tsx
apps/tlon-web/src/chat/ChatThread/ChatThread.tsx
apps/tlon-web/src/chat/ChatWindow.tsx
apps/tlon-web/src/chat/useChatStore.ts
apps/tlon-web/src/components/Settings/Settings.tsx
apps/tlon-web/src/components/VolumeSetting.tsx
apps/tlon-web/src/dms/BroadcastWindow.tsx
apps/tlon-web/src/dms/DMThread.tsx
apps/tlon-web/src/dms/DmWindow.tsx
apps/tlon-web/src/notifications/Notifications.tsx
apps/tlon-web/src/state/activity.ts

Fixes TLON-2419 by mimicking what mobile does, basically clearing the bell any time you visit and bringing it back upon new relevant activity. This also fixes optimistic reads which were not happening because we defaulted `variables.action` in the mutation function and didn't account for that later on.
Button moved to settings but not sure what language we want here:
PR Checklist

activity: web match mobile bell tab

---

packages/shared/src/api/landscapeApi.ts

We now check the response for the authentication request. Bad access code returns `400`, so we just look to see that the response falls within the `200`s. The throw causes red error text to be displayed on the login screen and the user can try again.
Fixes TLON-2262

native: handle failed authentication

---

apps/tlon-web/src/chat/ChatScroller/ChatScroller.tsx
apps/tlon-web/src/chat/ChatThread/ChatThread.tsx
apps/tlon-web/src/chat/ChatWindow.tsx
apps/tlon-web/src/chat/useChatStore.ts
apps/tlon-web/src/dms/BroadcastWindow.tsx
apps/tlon-web/src/dms/DMThread.tsx
apps/tlon-web/src/dms/DmWindow.tsx
apps/tlon-web/src/logic/utils.ts
apps/tlon-web/src/state/activity.ts
desk/desk.docket-0

This re-enables the behavior and fixes it so it actually marks stuff read lol. Required some light changes to `ChatScroller` so will need to make sure this doesn't break any chat loading.
PR Checklist

activity: re-enable auto marking active chats/threads

---

apps/tlon-mobile/src/fixtures/MessageInput.fixture.tsx
packages/ui/src/components/Channel/index.tsx
packages/ui/src/components/ChatMessage/ChatMessage.tsx
packages/ui/src/components/ContentRenderer.tsx
packages/ui/src/components/DetailView/DetailView.tsx
packages/ui/src/components/MessageInput/MessageInputBase.tsx
packages/ui/src/components/MessageInput/index.native.tsx
packages/ui/src/components/PostScreenView.tsx

fixes TLON-2416
Only affects images/refs inserted into the story at the time the message is sent. Feels cleaner than modifying the content renderer with a special case for chat.

native: make sure images/refs always appear before text in chat messages

---

apps/tlon-web/src/chat/ChatThread/ChatThread.tsx
apps/tlon-web/src/diary/DiaryChannel.tsx
apps/tlon-web/src/state/activity.ts

In my last PR https://github.com/tloncorp/tlon-apps/pull/3780 I fixed optimistic reading, but there was a bug exposed now that it's being used. This fixes the issue where threads were unable to be read. Also noticed notebooks weren't marking recursively so added that in too.
PR Checklist

activity: fix thread marking

---

apps/tlon-web/src/logic/useScrollerMessages.ts
apps/tlon-web/src/notifications/DMNotification.tsx
apps/tlon-web/src/notifications/Notifications.tsx
apps/tlon-web/src/state/chat/chat.ts
desk/app/groups.hoon

We had some weird spacing on mobile here so I removed some of the padding to help it have more room. Also found the issue with group preview fetching (although I still think there are other problems with it). Also fixed an issue where the author row wouldn't show up after a notice.
PR Checklist

misc: cleanup activity layout and fix groups preview fetch

---

desk/app/activity.hoon
desk/app/channels.hoon

OTT, this was happening occasionally when you reply to a thread and then the OP or someone else responds. This was putting an invalid source in our activity map which was overriding the activity sent to the frontend making it look "read".
PR Checklist

activity: fix bump hiding unreads

---

apps/tlon-mobile/ios/Landscape.xcodeproj/project.pbxproj
apps/tlon-mobile/ios/Podfile.lock

checked the xcode boxes for "iPad" and "Mac (designed for iPad)", gives a more sane UI on iPad and a resizable window on silicon macs.
Podfile change seems to be there just because I ran a clean build after Dan's changes the other day w/tentap.

native: support ipad (and silicon mac, but "designed for ipad")

---

apps/tlon-mobile/ios/Landscape/UrbitModule.swift
apps/tlon-mobile/src/components/AuthenticatedApp.tsx
apps/tlon-mobile/src/screens/ChannelScreen.tsx
apps/tlon-mobile/src/screens/ChatListScreen.tsx
apps/tlon-mobile/src/screens/GroupSettings/useGroupContext.ts
apps/tlon-mobile/src/screens/useChannelContext.ts
packages/shared/src/api/postsApi.ts
packages/shared/src/db/queries.ts
packages/shared/src/logic/utils.ts
packages/shared/src/store/sync.ts
packages/shared/src/store/syncQueue.ts
packages/shared/src/store/useChannelPosts.ts
packages/shared/src/urbit/ui.ts
packages/ui/src/components/GroupOptionsSheet.tsx

Before
After (critical info pops in faster + total duration is ~3-4s less)

streamline init sync

---

apps/tlon-web/src/app.tsx
apps/tlon-web/src/components/Sidebar/util.tsx
apps/tlon-web/src/groups/GroupSidebar/GroupSidebar.tsx
apps/tlon-web/src/groups/useGroupJoin.ts

This was an issue with navigation logic. The path in our router for modals requires `location.state.backgroundLocation` to be present. There was a bug in a navigation helper that causes that prop not to get set _if_  there's pre-existing location state. When navigating to the gallery detail view, we set the preloaded block to `location.state` causing that bugged conditional to override the prop we care about. This just tweaks the logic to avoid that override. 
After tracing around a bit, I'm still unsure why this is only happening now. Seemed like none of the chokepoints have been touched in the last ~3 months.
Also fixes a tiny issue I noticed while testing. If you click a group reference from a DM, it was failing to navigate if you're already joined.
Fixes TLON-2441
Fixes TLON-2445

web: fix routing from group reference to group preview modal

---

apps/tlon-mobile/src/screens/ChannelScreen.tsx
apps/tlon-mobile/src/screens/ChannelSearchScreen.tsx
packages/shared/src/api/channelsApi.ts
packages/shared/src/store/syncQueue.ts
packages/shared/src/store/useChannelSearch.ts
packages/ui/src/components/AuthorRow.tsx
packages/ui/src/components/ChannelSearch/SearchResults.tsx
packages/ui/src/components/ChatMessage/ChatMessage.tsx

- display normal chat message affordances in search results (contact info, date, etc.)
- include and route to thread search results
- make search results clickable again
- fix `selectedPostId` updates not carrying through to the `useChannelPosts` hook
- improve rendering performance for the search result list
There's more optimization that could be done around avoiding jitter in the results, but anecdotally it's less noticeable for real world searches. The scroller thrashing while anchoring on the selected post after clicking remains the dominating pain point, as is the case elsewhere.
Fixes TLON-2052

native: search fixes

---

desk/app/activity.hoon
desk/lib/activity.hoon
desk/lib/test-agent.hoon
desk/tests/app/activity.hoon

Fixes TLON-2447 by adding a new state transition that will run a fix. The fix looks for any DM or channel sources with only one event which should be either `%dm-invite` or `%chan-init` and sets the floor to the `last-read` time from the old agents. If this is actually an invite pending, then it will stay unread which is what we want. If it's not pending and they had in fact previously interacted and read that channel, then it will be marked read.
Unfortunately, to call these migration methods I had to factor them out to be pure so that we could call them on old state. Sync reads tests still pass, going to write some for this fix scenario.
PR Checklist

activity: fix init unreads

---

desk/app/activity.hoon
desk/tests/app/activity.hoon

This changes the init fix to use unreads. It turns out the last-read/recency comparisons we were doing are invalid because of the way the old agents calculate unreads, so instead we just the unreads themselves.
PR Checklist

activity: use unreads to determine which sources should change

---

apps/tlon-mobile/src/screens/ChannelSearchScreen.tsx
packages/shared/src/api/channelsApi.ts
packages/shared/src/store/useChannelSearch.ts
packages/ui/src/components/Channel/index.tsx

A couple lingering search issues from the PR last week:
- Fixes search for DM's (1:1 and group)
- Resolves the issue with message presses overeagerly navigating you to the thread
- restores previous behavior of needing to click the reply summary or long press to start a new thread

native: more search fixes

---

apps/tlon-mobile/src/screens/ChannelScreen.tsx
apps/tlon-mobile/src/screens/GroupChannelsScreen.tsx
packages/ui/src/components/Channel/BaubleHeader.tsx
packages/ui/src/components/GroupChannelsScreenView.tsx
packages/ui/src/contexts/groupOptions.tsx
packages/ui/src/contexts/index.ts

Move from in-app context/drilled props to GroupOptionsContext + provider.
Uses group option sheet + new provider + hook in ChannelScreen -> BaubleHeader.
Fixes TLON-2451

native: relocate group options context + actions

---

apps/tlon-mobile/ios/Landscape/UrbitModule.m
apps/tlon-mobile/ios/Landscape/UrbitModule.swift
apps/tlon-mobile/src/contexts/ship.tsx

#3813 changed `UrbitModule.setUrbit`'s signature in JS + iOS because iOS does not use one of the params, but the change was not reflected in the Android native module. This change makes the signature the same for both Android/iOS, and just ignores the unused param in iOS.
I built this on iOS, but I have not built it on Android

native: revert UrbitModule signature to match Android

---

desk/app/groups-docket-proxy.hoon
desk/desk.bill

Some of the upcoming frontend code needs access to functionality the browser only enables in the presence of specific headers on the responses serving the source code files.
Docket serves our frontend files, but does not have any affordances for specifying custom headers. But it serves from globs, a non-trivial task to take over, even if we were to run a custom fork of it.
Instead, here we introduce a local proxy that watches on the endpoint docket would normally serve on. It passes requests through unaltered, but injects the desired headers into responses before sending them back to the client.
This approach will stop working if docket ever injects responses on this endpoint into the eyre cache, which means we can't trivially capture them in userspace anymore. However, vere 3.1 never …

docket-proxy: mitm docket to inject custom headers

---

desk/app/activity.hoon

This was posted in Homestead. The Bulletins channel was randomly getting bumped to the top. We use a null `time` in the `read` action to signify "latest", however if we came up with no events we were erroneously saying set it to `now.bowl`. Since the floor gets taken into account for the recency, this was bumping sources to the top that were empty themselves or contained empty sources. This instead leaves the floor unchanged if there are no events.
PR Checklist

activity: dont use now.bowl when reading

---

apps/tlon-web/src/notifications/Notification.tsx
desk/app/activity.hoon

Fixes TLON-2423 by adjusting the paths we send people to, reflecting the actual routes instead of all trying to be chats. Also fixed two issues encountered when testing.
- Creating a post and then commenting on it yourself was crashing because the source didn't exist
- Sometimes the feed would produce bundles where the latest time didn't match any event in the bundle, which makes no sense. So I changed it to always pull the "latest" value from the list of events it sends with the bundle (instead of the event on which we built this bundle which may not be present in the bundle itself)
PR Checklist

activity: fix notification paths

---

apps/tlon-web/externalResourceScript.ts
apps/tlon-web/injectCrossOriginScript.ts
apps/tlon-web/tsconfig.json
apps/tlon-web/vite.config.mts

This pulls what @patosullivan did out of the cross-compile branch tloncorp/tlon-apps#3805 which should fix the problems we saw with tloncorp/tlon-apps#3810 however some images will still break that don't have proper CORS headers like currently the Tlon icon is missing some key headers https://storage.googleapis.com/assets.tlon.io/tlon-co-group-icon.svg. However most any public image URL should have these headers.
PR Checklist
Fixes TLON-2505

external-resources: add crossorigin anonymous to everything dynamically

---

packages/ui/src/components/Channel/index.tsx
packages/ui/src/components/PostScreenView.tsx

Hides the three dots menu in detail views (also hides it from the channel view, where it shouldn't have been visible anyway).

native: hide menu button on detail views

---

packages/ui/src/components/Activity/ActivityHeader.tsx
packages/ui/src/components/Activity/ActivityScreenView.tsx
packages/ui/src/components/Activity/ActivitySourceContent.tsx
packages/ui/src/components/Activity/ActivitySummaryMessage.tsx
packages/ui/src/components/Activity/ChannelActivitySummary.tsx
packages/ui/src/components/Activity/GroupActivitySummary.tsx
packages/ui/src/components/ContentReference/ContentReference.tsx
packages/ui/src/components/ContentRenderer.tsx

- Correctly references `props.viewMode` in ContentReference to correctly size reference text in the activity context (we were relying on a similarly-named `useReferenceContext` hook which only gives us the immediate parent `viewMode`, not the one we're passing down through the Activity screen).
- Renames a prop for ContactName (we use `size` rather than `fontSize`) so we don't have medium-sized ship nicknames in the activity item content (which is small-sized)
- Cleans up the inter-item layout of the Activity screen to prevent unsightly wrapping and  margin inconsistencies
- Restores the faint blue background for unread items
- Left-aligns the screen title
Before & after:

Visual tweaks for Activity screen

---

apps/tlon-web/index.html

Will from shrub team reported this, seems that the way we referenced favicons didn't work in some cases this should resolve that.
PR Checklist

web: reference assets correctly

---

packages/shared/src/db/queries.ts
packages/ui/src/components/Channel/EmptyChannelNotice.tsx
packages/ui/src/components/Channel/index.tsx

This was an issue with permissions not getting initially configured correctly. There was a bugged early return preventing writer role insertion. Also fixes a bug I noticed while working on this with the empty channel message still getting displayed inverted.
Fixes TLON-2561

native: fix channel write permission check

---

apps/tlon-mobile/src/screens/FeatureFlagScreen.tsx
packages/app/features/top/ChatListScreen.tsx
packages/app/hooks/useChannelContext.ts
packages/app/lib/featureFlags.ts
packages/app/package.json
pnpm-lock.yaml

- Changes backing store of feature flags to a Zustand store (publishes changes easily, can be accessed from outside of React, and was already installed)
- Flag changes are written to local storage whenever Zustand store is mutated
- Added `useFeatureFlag` hook that acts like `useState`, but for feature flags
- Update call sites to use reactive API
I tested by toggling the experimental channel switcher flag, checking that it took effect in the app, toggled it back off, did the same and quit the app, checked my pref was saved.
I also inserted a console.log in the subscription and checked that it doesn't appear to double-trigger after navigating around the app. Hypothetical bug here (which I did not see, but not convinced it's a non-issue): since we're registering a listener in the top-level …

native: use zustand for feature flags to enable reactivity

---

desk/app/activity.hoon
desk/app/channels-server.hoon
desk/app/channels.hoon
desk/sur/channels.hoon

OTT, this PR adds a new version of the `changes` endpoint `/v2/{kind}/{ship}/{name}/posts/changes/{start}/{end}/{after}`
The endpoint has three parameters:
- `start`: the beginning of the range of posts we care about, a `@ud` or `@da` value corresponding to a post ID
- `end`: the end of the range of posts we care about, a `@ud` or `@da` value corresponding to a post ID
- `after`: the point at which we start caring about updates, basically when did we last "sync"
It returns a `paged-posts` type, with cursors pointing at the post IDs adjacent to start and end if there are any.
Also fixes a compiler issue in the current dev branch with activity import.
PR Checklist

channels: store updated times for changes endpoint

---

apps/tlon-web/src/diary/PrismCodeBlock.tsx
package.json
pnpm-lock.yaml

Fixes TLON-2600
Turns out this was caused by a version mismatch for prosemirror-state that was causing the history plugin in tiptap not to load/work.
Tested to make sure everything still works w/the mobile input and in the new app, all works fine.

old web: fix backspace issue in input

---

apps/tlon-mobile/src/screens/AppInfo.tsx
packages/app/features/top/ChatListScreen.tsx
packages/app/lib/platformHelpers.ts
packages/shared/src/store/errorReporting.ts

OTT
Since we're now using Expo updates, we need insight into whether or not those are running to help with support and debugging. 
This is a first step that just adds that information on the _App Info_ screen & whenever a crash report is filed with Crashlytics.

native: capture current EAS update ID

---

packages/ui/src/components/Channel/Scroller.tsx
packages/ui/src/components/ChatMessage/ChatMessage.tsx

I noticed we had code that would unnecessarily allocate stuff on every render – not a huge deal, but could build up and cause unnecessary GC since these are being rendered for every channel post. Also deleted some dead code while here.
I've run this code in a simple group channel and it looks okay to me.

native: reduce allocations in ChannelMessage codepath

---

apps/tlon-mobile/src/navigation/GroupSettingsStack.tsx
apps/tlon-mobile/src/screens/GroupSettings/GroupPrivacyScreen.tsx
apps/tlon-mobile/src/screens/GroupSettings/InvitesAndPrivacyScreen.tsx
apps/tlon-mobile/src/types.ts
packages/app/hooks/useChatSettingsNavigation.native.ts
packages/app/hooks/useChatSettingsNavigation.ts
packages/shared/src/api/groupsApi.ts
packages/shared/src/store/groupActions.ts
packages/ui/src/components/ChatOptionsSheet.tsx
packages/ui/src/components/Form/inputs.tsx
packages/ui/src/components/GroupPrivacySelector.tsx
packages/ui/src/contexts/chatOptions.tsx
packages/ui/src/index.tsx

Adds an option to the _Group Options Sheet_ to modify the group's privacy if you're an admin. Looks like this:
https://github.com/user-attachments/assets/78f75d1e-893c-4959-9a5f-066223786d5e
Note, in the mocks there was also group invite functionality on this screen, but that has its own ticket (TLON-1717).
Fixes TLON-1713

native: editable group privacy

---

apps/tlon-mobile/src/components/AuthenticatedApp.tsx
apps/tlon-mobile/src/lib/refreshHostingAuth.ts
apps/tlon-mobile/src/screens/ManageAccountScreen.tsx
packages/app/lib/hostingApi.ts
packages/app/utils/hosting.ts

Hosting is changing the way they handle cookies. All current ones will become invalid and the new system will use a token that lasts a full year but expires after 30 days of no use. We want to make sure this doesn't immediately impact app users.
This PR adds a check whenever the app returns from background that pings hosting once a day to make sure we continue refreshing the cookie and track whether our hosting session is expired. 
At the moment the only place where we require hosting auth is on the _Manage Account_ screen. For that case, if your hosting session is expired we pop an alert informing the user that they'll need to log back in if they want to manage their account (in which case we'll have a fresh session).
Fixes TLON-2605

native: account for new hosting auth

---

.github/helpers/glob.sh
desk/mar/jpg.hoon

Fixes TLON-2590 by adding the wasm mark to the globber. Tested locally by creating a glob, uploading it to my own s3, then pointing the desk.docket-0 file at the glob and committing it on a local moon.
Also needed to add a jpg.hoon mark (which apparently has never existed? wat) because the new-web-app includes `welcome_flowers.jpg` in the dist (because it's referenced in `WelcomeSheet.web.tsx`).

new web: update globber

---

packages/ui/src/components/ChatList.tsx

`useAnimatedStyle` was missing a dependency which caused the filters to fail to open. The `tamagui-ignore` the top of the file was an earlier attempt to fix the issue, so is now extraneous.

fix filter open

---

apps/tlon-web/src/diary/DiaryContent/DiaryContent.tsx

Fixes bug where lists are too spaced out because there's an extra line break added to the end of every item.
The data retrieved from the backend includes line breaks at the end of every item in a list. Rendering this line break as a <br> makes the items in a list too spaced out, because <li> elements already have their own vertical spacing.
This PR filters line breaks at the end of list items on the front end, instead of changing the back end code. I'm not sure if this is the preferred solution, so merge at your discretion. 
Before:
After:
The state with said line breaks:
Tested locally with fakeship
PR Checklist

Disable newlines in ListingContent

---

packages/ui/src/components/EditProfileScreenView.tsx

Adds `shouldDirty: true` to onSetCoverURL and onSetIconURL in the profile editor, which enables the Save button (which only does anything if the form itself is dirty).
Also hides the Save button until the form is dirty to stay on-pattern w/ elsewhere in the app.

profile: allow saving avatar/cover changes

---

apps/tlon-mobile/.env.sample
apps/tlon-mobile/metro.config.js
packages/app/lib/devMenuItems.ts
packages/app/package.json
pnpm-lock.yaml

| Simulator | Physical device |
| --- | --- |
| <img width="300" src="https://github.com/user-attachments/assets/ad0a44c6-5bfe-44bd-935d-d03837c6d915" /> | <img width="300" src="https://github.com/user-attachments/assets/e19e7ce2-994b-4785-a650-f4d2fd259a20" /> |
- Restores / adds dev menu items to dump / restore SQLite database, relying on database paths on Metro host
- Adds `.env` entries (illustrated in `.env.sample`) for dump / restore paths
- Adds check to dev menu setup to only add simulator-exclusive items when `DeviceInfo.isEmulator`

native: dump/restore SQLite database via dev menu

---

packages/app/contexts/ship.tsx

Looks like change from https://github.com/tloncorp/tlon-apps/pull/3815 was overwritten - this restores it.
I got an error for this recently – I don't know why this wasn't throwing errors regularly. After making this change, I stopped getting the error.
I imagine this was caused by the code moving to `packages/app` – I did a diff on packages/app/contexts/ship.tsx against the last version of https://github.com/tloncorp/tlon-apps/blob/f657fb57ab44c790a6a6ad24cdb74ad743b1da4a/apps/tlon-mobile/src/contexts/ship.tsx and this was the only line. I don't know how one would do a more comprehensive diff against `tlon-mobile` x `app`.

native: fix JS call to UrbitModule.setUrbit again

---

packages/ui/src/components/ActionSheet.tsx
packages/ui/src/components/AddChats/AddDmSheet.tsx
packages/ui/src/components/ChatMessage/ViewReactionsPane.tsx
packages/ui/src/components/ChatOptionsSheet.tsx

Uses a new strategy for Sheets that maintains the modal like feel while avoiding portal'ing the component to another location in the tree. This means context passing works as expected on both platforms.
I updated existing components that were using context instantiation hacks. The one exception is _AddGroupSheet_ which mounts its own navigation container making a refactor to use the now standard _ActionSheet_ non-trivial. I don't think we should use that pattern elsewhere (we should mimic that effect in Reanimated where needed) , but rewriting it entirely seemed outside the scope of this PR.
I tried to audit all the existing sheets to make sure this didn't cause any display weirdness, but let me know if anyone sees any regressions during review!
Fixes chat actions and reaction viewing on …

native: fix context passing for Sheets

---

packages/shared/src/store/postActions.ts

On edit, we weren't stringifying the JSON content before writing to the DB as part of the optimistic update. This broke things after the recent content render changes due to an unprotected JSON parse.
Fixes TLON-2627

native: fix editing messages

---

desk/app/chat.hoon

Ames guarantees message ordering only within the same flow. Using a different duct stack creates a new flow. The wire used by the agent shows up in the duct stack for the messages it sends.
Previously, we were putting DM message identifiers into the poke wire, resulting in a unique flow for each message. We need this because when we eventually get a (n)ack for the poke, we may need to correlate that with the sent message, to handle failure cases gracefully (and potentially to track delivery status if we ever want it).
Recently, ~palfun has been under load, spending lots of time processing whatever, and dropping many packets in the process. One of the symptoms this resulted in was receiving DMs out of order, sometimes with egregious delays between them. My working theory here is that, …

chat: obtain better dm ordering guarantees

---

packages/ui/src/components/AttachmentSheet.tsx

Ugly hotfix for an issue where the pickImage and takePicture functions are attempting to access the PHPickerViewController in the current view hierarchy, but the AttachmentSheet detaches itself (hides) before the controller can fire.
Will look into moving the image picker logic higher up into the component tree so we can ensure it's always attached. I can do this in a follow-up PR, or amend this one (or abandon if you have better ideas, @dnbrwstr).
Fixes TLON-2665

AttachmentSheet: wait 300ms before popping image picker/camera

---

packages/app/features/top/ChannelScreen.tsx

https://github.com/tloncorp/tlon-apps/pull/3878 added code to block pagination requests while a load was already in-progress. This has the potential to get a user stuck, unable to load more content.
I wasn't able to trigger this bug – it's dependent on query timing; it needs a specific initial chat state; and the existing content in the chat must maintain a stable height during render (which is not true of most of our chat posts). But removing this load-blocking code only has the effect of loading slightly more posts than we want on each pagination, so it seems worth it. See https://linear.app/tlon/issue/TLON-2670/reduce-double-loads-when-hitting-bottom-of-channel-scroll for more about the downsides of this double-load.

native: stop blocking concurrent post loads

---

package.json
packages/ui/src/components/Channel/Scroller.tsx
patches/react-native@0.73.4.patch
pnpm-lock.yaml

Fixes these bugs:
<details>
<summary>Inconsistent autoscroll-to-bottom behavior</summary>
We've specified that chats should scroll to the bottom whenever new content arrives.
In reality, the client decides whether to scroll to the bottom of the channel using some inscrutable logic.
</details>
<details>
<summary>Newly-sent message is placed below the bottom of scroll</summary>
1. Enter a chat channel
2. Don't scroll
3. Send a text message
Expected: Chat scrolls down to show your newly-sent message
Actual: Message is placed below bottom of scroll – offscreen until scrolled to
</details>
- Applied https://github.com/facebook/react-native/pull/38245 to make autoscroll-to-bottom via `autoscrollToTopThreshold`.
- #3878 changed the [`autoscrollToTopThreshold`](https://reactnative.dev/docs/scrollv …

native: fix broken autoscrollToTopThreshold

---

apps/tlon-mobile/ios/Landscape.xcodeproj/project.pbxproj
apps/tlon-mobile/ios/Notifications/Notifications-preview.entitlements

/1/chan/chat/~bitpyx-dildus/interface/msg/170141184506991177237640404063485952000

native: use separate .entitlements file, app group for preview NSE

---

packages/ui/src/components/MessageInput/index.native.tsx
packages/ui/src/components/MessageInput/index.tsx

This was a weird one to nail down the repro for since it was working inconsistently in testing. Turns out if your draft is empty when you enter the channel, we don't mark `setHasSetInitialContent` as true. This means once you do paste something in, it gets saved as a draft and loaded back into the input as a raw text overwrite. This PR just tweaks that logic to always mark initialized after entering the draft/edit content conditional.
I tried to make sure this doesn't break things elsewhere, but @patosullivan you might have more context there. Let me know if you foresee any issues.
Fixes TLON-2660

native: fix link pasting

---

apps/tlon-mobile/src/fixtures/Channel.fixture.tsx
packages/ui/src/components/Channel/EmptyChannelNotice.tsx
packages/ui/src/components/Channel/Scroller.tsx
packages/ui/src/components/Channel/index.tsx

https://github.com/facebook/react-native/issues/21196 seems like it has regressed a few times. We previously manually flipped the broken empty list view to counteract the bugged transform; but this ends up with a bugged flipped view if the bug is fixed (which may likely happen without being marked as a breaking release).
To avoid Tlon breaking whenever the upstream bug gets fixed, disabled FlatList's `inverted` when we're showing an empty list – i.e. avoid dealing with any transforms.
I tested by running the new empty chat channel fixture on iOS and Android simulators. I also temporarily changed the `chatWithSimulatedLoad` to show an empty indicator when no posts are loaded, and checked that going from empty -> non-empty had no visible jank.

native: make inverted empty FlatList resilient to upstream fixes 

---

packages/ui/src/components/ActionList/ListFrame.android.tsx
packages/ui/src/components/Channel/Scroller.tsx
packages/ui/src/components/ChatMessage/ChatMessageActions/Component.android.tsx
packages/ui/src/components/Overlay.tsx

This fixes TLON-2694. To do so I had to rip out the `delay` we were passing to the animations. This also cleans up the fact that menu had sharp corners and had a bad shadow animation. Apparently `elevation` has issues with being animated so the shadow for the menu would pop first so you just see a black box until the actual menu contents fade in. Seems to be a long standing issue https://github.com/facebook/react-native/issues/23090 I tried their fixes to no avail.
Also removed the shrink animation on the active message because it felt like too many things were moving at once. Feels smoother now.  
PR Checklist

action-menu: cleanup all animations involved with opening action menu

---

apps/tlon-mobile/ios/Landscape.xcodeproj/project.pbxproj
apps/tlon-mobile/ios/Landscape/PrivacyInfo.xcprivacy
apps/tlon-mobile/ios/Podfile.lock
apps/tlon-mobile/package.json
pnpm-lock.yaml

This PR upgrades react native from 0.73.4 to 0.73.9 in order to fix copying / logging of JSON in the chrome debugger.
The privacy manifest is autogenerated by the new version of React Native from our dependency pods. It looks appropriately conservative/accurate (write files in app group, use timers, that kind of thing), and I believe is required, so I'm leaving it, but we should research the ins + outs -- I'm not super familiar.

bump react native to 0.73.9

---

packages/editor/src/MessageInputEditor.tsx
packages/ui/src/components/BigInput.native.tsx
packages/ui/src/components/MessageInput/index.native.tsx

Fixes TLON-2112
Fixes TLON-2719
Fixes an issue with the input not being scrollable (which is a big problem in notebooks where there might be a lot of text).
Replaces Scrollview (which was originally included because of an animation) that wraps the message input in BigInput with View.
Fixes an issue where a very long message would cause the input to fill the screen and cause the send message and add attachment buttons to no longer be visible.
Memoizes some values in the message input

input: fix input height and scrolling issues when input is 'full'

---

packages/app/features/top/ChatListScreen.tsx
packages/shared/src/store/session.ts
packages/shared/src/store/sync.ts
packages/ui/src/components/ScreenHeader.tsx

Small update to change the indicator on the home screen while the app is running through it's bootstrap logic. Also removes the empty session grey dimmer. Keeping things simple for now, but we can layer in offline status, error states, etc. down the line
Connecting = still scaffolding initial subscriptions
Syncing = still running through initial data fetching
Loading = still fetching the actual data needed to power the screen from the local DB
Fixes TLON-2679
https://github.com/user-attachments/assets/9c9f4992-8ca5-41a2-ab03-4ab5d48669b3

native: better communicate initial app loading state

---

apps/tlon-mobile/src/App.main.tsx
apps/tlon-mobile/src/hooks/useDeepLinkListener.ts
apps/tlon-mobile/src/screens/Onboarding/SignUpEmailScreen.tsx
apps/tlon-mobile/src/screens/Onboarding/SignUpPasswordScreen.tsx
apps/tlon-mobile/src/screens/Onboarding/WelcomeScreen.tsx
packages/app/contexts/branch.tsx
packages/app/lib/nativeDb.ts
packages/shared/src/logic/branch.ts
packages/shared/src/store/lure.ts
packages/ui/src/components/AppInviteDisplay.tsx
packages/ui/src/components/Avatar.tsx
packages/ui/src/components/ListItem/ListItem.tsx
packages/ui/src/index.tsx

- adds information about the inviting user & group to the Branch link
- reads that information after making it to the app and stores it alongside the lure ID
- adds placeholder visual for displaying the new metadata during the onboarding process
Fixes TLON-2712

native: add lure metadata to Branch & display during onboarding

---

apps/tlon-web/src/state/lure/lure.ts

On web we weren't generating your individualized link automatically if you weren't the one toggling to "enable lure links".
PR Checklist

lure: make sure we generate a url if you aren't the one toggling

---

apps/tlon-web/src/groups/LureInviteBlock.tsx
apps/tlon-web/src/logic/branch.ts
apps/tlon-web/src/state/lure/lure.ts
packages/shared/src/store/lure.ts
packages/ui/src/components/InviteUsersWidget.tsx

This uses the new endpoint in tloncorp/landscape#286 to fetch URLs instead of the scry since we want to wait for the confirmation to come through from the provider so we give the correct URL. Updates both web and mobile
PR Checklist

lure: better url fetching

---

packages/ui/src/components/Channel/index.tsx
packages/ui/src/components/PostScreenView.tsx

Fixes an inconsistency where post detail views have Channel-level action menus (which have nothing to do with the post itself), and Channels have no menu whatsoever (so muting a channel involves navigating into a child post and accessing the menu in the incorrect place).
Note that this adds a '...' button to the channel header. This is probably correct and not reflected in design.

Posts, Channels: relocate overflow menu

---

packages/ui/src/components/MessageInput/MessageInputBase.tsx

Makes some changes to MessageInputBase:
- Returns an entirely different Y-stack/wrapper if we are in editing mode; the conditionals were becoming unwieldy and component memoization made it impossible to adjust styling properties by themselves
- Changes the opacity of the UpArrow send button to 0.5 rather than 0 when the user has not inputted any text or made any changes to the MessageInput field
---
No input:
---
With input:
---
Editing a chat message:

MessageInput: gray out button before send, cosmetic changes to edit mode

---

apps/tlon-mobile/src/App.main.tsx
apps/tlon-mobile/src/components/AuthenticatedApp.tsx
apps/tlon-mobile/src/screens/Onboarding/ReserveShipScreen.tsx
apps/tlon-mobile/src/screens/Onboarding/SetNicknameScreen.tsx
apps/tlon-mobile/src/screens/Onboarding/SetTelemetryScreen.tsx
apps/tlon-mobile/src/screens/Onboarding/SignUpPasswordScreen.tsx
apps/tlon-mobile/src/types.ts
packages/app/contexts/signup.tsx
packages/app/hooks/usePostSignup.ts
packages/shared/src/api/userApi.ts

The code that tries to thread through nickname via screen props wasn't working. It was also calling out to a non-standard legacy helpers for setting profile data.
I extracted signup configuration into its own context and pulled post-signup logic up into _AutheticatedApp_ so we can work with our normal api client & store methods. I think this will be more agile moving forward compared to passing along screen props and bundling the logic into the final onboarding screen.
Confirmed setting the nickname worked by running through a full signup.
Fixes TLON-2744

native: fix onboarding nickname

---

apps/tlon-web/src/state/lure/lure.ts
packages/shared/src/store/lure.ts
packages/ui/src/components/InviteUsersWidget.tsx

This fixes an issue on mobile where you'd never get the "Invite friends who aren't on Tlon" because the current group had an "old" lure link. This makes sure we regenerate any old links so everyone gets the new behavior.
PR Checklist

lure: regenerate old links

---

packages/ui/src/components/InviteUsersWidget.tsx

Now that the updated group creation flow is in and we display the invite in the channel itself, we don't need the skip button in the sheet. This will help avoid confusion since it was always shown and doesn't make sense outside the group creation context.

native: remove skip button in invite sheet

---

packages/app/features/top/ChannelScreen.tsx

I was confused by this, so I thought I'd add a comment for future readers. There's a small code change, but I think it's equivalent.

native: add comment about `hasCachedNewest`

---

apps/tlon-mobile/src/controllers/ChatListScreenController.tsx
apps/tlon-mobile/src/hooks/useDeepLinkListener.ts
apps/tlon-mobile/src/types.ts
packages/app/contexts/branch.tsx
packages/app/features/top/ChatListScreen.tsx
packages/app/hooks/useNavigationLogger.ts
packages/shared/src/store/dbHooks.ts
packages/shared/src/store/groupActions.ts

Adds logic to handle the case where you click a lure link after already being authenticated. Instead of triggering the automatic join + dm, we treat it as a deeplink to that group and pop a preview sheet.
Fixes TLON-2758

native: handle Lure link click when already signed in

---

packages/ui/src/components/UserProfileScreenView.tsx

Eliminates the "An enigma" bio block for ships that don't have about text set.

profile: hide block if no bio text, no placeholder

---

desk/app/groups.hoon

This fixes TLON-2180 (and the other case this was happening like when you get kicked/banned)
PR Checklist

groups: make sure we leave channels in all cases of leaving a group

---

desk/app/expose/page.hoon
desk/app/expose/render.hoon
desk/app/expose/style/page.css
desk/app/expose/style/widget.css
desk/app/profile/widgets.hoon

when we can. Right now, we only know this for the local ship, where it's simply /profile, assuming the public profile agent is running.
Still pending some styling adjustments from @jamesacklin.

expose: make author link to local /profile

---

apps/tlon-mobile/src/hooks/useDeepLinkListener.ts
packages/app/contexts/branch.tsx
packages/shared/src/logic/branch.ts
packages/shared/src/logic/deeplinks.ts
packages/shared/src/logic/index.ts
packages/shared/src/store/lure.ts
packages/ui/src/components/InviteFriendsToTlonButton.tsx
packages/ui/src/components/InviteUsersWidget.tsx
packages/ui/src/components/MessageInput/helpers.ts
packages/ui/src/components/MessageInput/index.native.tsx
packages/ui/src/components/MessageInput/index.tsx

We've seen users get confused about how to properly link to a group. Dropping an off-network share link into chat is a reasonable instinct that we should support. This PR adds the ability to extract group refs from Lure deeplinks in the same way we do if you paste a copied cite ref. Handles links at the branch level (_join.tlon.io_) and after fallback redirect (_tlon.network/lure_).
I tried to add support in a way that would make it easier to add more of these paste handlers down the road, but I could use eyes on the extracted logic — @patosullivan I think you're most familiar?
Fixes TLON-2760

native: handle pasting Lure deeplinks in chat

---

packages/ui/src/components/ChatList.tsx

Removes the flapping between "Pinned" and "Home" on ChatList. Should help with performance a bit.

ChatList: remove native scroll events and title-swapping

---

packages/app/features/top/ChannelScreen.tsx
packages/ui/src/components/ActionSheet.tsx
packages/ui/src/components/ChatOptionsSheet.tsx

- Guards against channel hosts being able to leave channels they host. This would fail to complete on the back-end but would be reflected in the client and in SQLite. (Fixes TLON-2785)
- Moves "Back" in notification level options to sheet header, adjusts title (fixes TLON-2737)
- Adds active selection icons for notification level selections (fixes TLON-2737)
- Changes ActionSheet to render (optional) accent styling for individual actions within a group (which can have its own accent)
- Provides a "positive" accent to the active selection for notification level in ChatOptionsSheet
I can now no longer leave a channel I host:
Changes to the notification selection menu(s):

ChatOptionsSheet: fixes for notifications, leave

---

desk/app/expose.hoon
desk/app/profile.hoon
desk/sur/contacts.hoon

This is a detail that appears on most of the pages that we publish, that the user has control over, so we should reflect is accurately in a timely fashion.
We don't care too much right now about cache busting in response to other people's profile detail changes, because we don't display comments/replies, and publishing someone else's content isn't a primary/supported use-case. If we ever do want that, probably better to just periodically refresh the cache.
Also makes some small adjustments to how the contacts scry helper works, and makes /app/profile use that instead of its own code.
(Doesn't account for doing the contacts subscription on existing instances of exposé, @jamesacklin if you or anyone internal wants the reactivity there you'll need to nuke & restart the agent.)

expose: refresh for local profile changes

---

packages/ui/src/components/ChatOptionsSheet.tsx
packages/ui/src/components/InviteFriendsToTlonButton.tsx
packages/ui/src/components/InviteUsersWidget.tsx

Fixes TLON-2856 by disallowing non-admins of private and secret groups from sending invitations (both on-network and issuing Lure invites). On-network invites fail on the back-end; off-network invites fail when the user logs in and sees no invite. Only admins can perform inviting actions in non-public groups, so we should take them out of the UI.
Also drastically simplifies the InviteUsersWidget by breaking apart the primary button into distinct on- and off-network invitation buttons. Makes good reuse of InviteFriendsToTlonButton (which contains all the hooks we need).
Here is what a non-admin member of a private||secret group will see:
Here is what admins of private||secret groups and everyone in public groups will see:

ChatOptions, InviteUsersWidget: guard against non-admins of private||secret groups

---

apps/tlon-mobile/src/fixtures/AddGroupSheet.fixture.tsx
apps/tlon-mobile/src/fixtures/FindGroups.fixture.tsx
apps/tlon-mobile/src/types.ts
packages/app/features/top/ContactHostedGroupsScreen.tsx
packages/app/features/top/FindGroupsScreen.tsx
packages/app/hooks/useGroupNavigation.ts
packages/app/navigation/RootStack.tsx
packages/app/navigation/types.ts
packages/shared/src/api/groupsApi.ts
packages/shared/src/db/queries.ts
packages/shared/src/store/dbHooks.ts
packages/ui/src/components/AddChats/ViewUserGroupsWidget.tsx
packages/ui/src/components/AddGroupSheet.tsx
packages/ui/src/components/Avatar.tsx
packages/ui/src/components/Button.tsx
packages/ui/src/components/ContactBook.tsx
packages/ui/src/components/ContactRow.tsx
packages/ui/src/components/CreateGroupView.tsx
packages/ui/src/components/Emoji/EmojiPickerSheet.tsx
packages/ui/src/components/FindGroupsView.tsx
packages/ui/src/components/Form/inputs.tsx
packages/ui/src/components/SearchBar.tsx
packages/ui/src/components/SectionList.tsx
packages/ui/src/index.tsx

This PR reworks the add groups sheet to improve visual hierarchy + better match spec. It also breaks out the list of a user's groups in the "find groups" screen into its own screen.
| Before | After |
|--------|------|
|<img src="https://github.com/user-attachments/assets/34e08c39-b6b6-4549-be2a-f37b4fd9c79b" width=300> | <img src="https://github.com/user-attachments/assets/521aa8cb-0f6b-47a7-a61b-4476f00fb1f7" width=300>|

add groups sheet style tweaks

---

apps/tlon-mobile/ios/Landscape.xcodeproj/project.pbxproj

The notification service extension had a min iOS deployment target of 17.0, while the host app has a target of 16.0. There's no reason for the mismatch – changed all targets to 16.0.
Before this change, users <17.0 would not get the behavior of the NSE (falling back to our legacy notification path).

native: match NSE min iOS version to host min iOS version

---

packages/shared/src/store/sync.ts

Fixes TLON-2797.
Previously, if we synced a channel and requested 15 (for example, the default count for a channel) posts and got back 0 actual posts and Y deleted posts, and Y was equal to 15, we would insert nothing into the db since the actual posts array would be empty. This is a problem if there are not-deleted posts "behind" those deleted posts. We would think we're up to date with everything in that channel when we're not.
If we're in that state, we need to call syncPosts again with a greater count to check to see if there are more posts behind it (and again if we end up in the same situation).
A good example where this was occurring is the "Books" channel in Tlon Studio, which had over 50 deleted posts after the first three posts.

syncPosts: handle situation where deleted posts total in response == count

---

apps/tlon-mobile/android/app/src/main/java/io/tlon/landscape/api/TalkApi.java
apps/tlon-mobile/android/app/src/main/java/io/tlon/landscape/models/Yarn.java
apps/tlon-mobile/android/app/src/main/java/io/tlon/landscape/notifications/TalkNotificationManager.java
apps/tlon-mobile/ios/Landscape.xcodeproj/project.pbxproj
apps/tlon-mobile/ios/Landscape/AppDelegate.mm
apps/tlon-mobile/ios/Shared/Models/Group.swift
apps/tlon-mobile/ios/Shared/Models/TlonError.swift
apps/tlon-mobile/ios/Shared/Models/Yarn.swift
apps/tlon-mobile/ios/Shared/Networking/PocketChatAPI.swift
apps/tlon-mobile/ios/Shared/Notifications/PushNotificationManager.swift
apps/tlon-mobile/ios/Shared/Storage/GroupStore.swift
desk/lib/activity.hoon
desk/lib/notify.hoon

This fixes TLON-2223 and TLON-2531. This PR allows group invites and post notifications to come through the activity agent. We also had to special case group invites in the notify conversion (we really should move away from hark/yarn format). 
Finally we modify both native notification handlers for iOS and Android so that we can display group invite notifications. The only issue I've seen so far is that the iOS push notification always does the fallback "TLON! You have a new message", but the background notification also fires with the correct information. @davidisaaclee any insight here would be great.
PR Checklist

notifications: get group invites working as pushes

---

packages/app/features/top/ChannelScreen.tsx

fixes TLON-2868
We were depending on the existence of the `group` property on the `channelFromParams`, which doesn't always exist. We know we'll get a `group` from `useChannelContext` if it exists, so we should just use that.

channel screen: make sure we actually mark the group as visited if it's new

---

apps/tlon-mobile/src/screens/Onboarding/SetTelemetryScreen.tsx
packages/app/features/top/ChannelScreen.tsx
packages/ui/src/components/AddChats/CreateGroupWidget.tsx
packages/ui/src/components/AddGroupSheet.tsx
packages/ui/src/components/Channel/EmptyChannelNotice.tsx
packages/ui/src/components/ChatOptionsSheet.tsx
packages/ui/src/components/ContactBook.tsx
packages/ui/src/components/Form/Form.tsx
packages/ui/src/components/InviteFriendsToTlonButton.tsx

- Adds additional icon and label states to InviteFriendsToTlonButton (fixes TLON-2881).
- Adds an "Invite people" button to ChannelOptions in the correct administrative/privacy contexts (fixes TLON-2880).
- Moves the "Next" button in SetTelemetryScreen from the header to a full-width button in the screen content (fixes TLON-2883).
- Always show InviteFriendsToTlonButton in EmptyChannelNotice for admins on subsequent visits to an empty channel (fixes TLON-2879).
- Adds padding to the top of form field validation messages (fixes TLON-2815).
- Fixes an issue where screen elements were too wide in group creation (fixes TLON-2877).

native: small-fix omnibus

---

packages/ui/src/components/ChannelNavSections.tsx
packages/ui/src/components/GroupChannelsScreenView.tsx

Fixes TLON-2883 by popping ChatOptionsSheet for a long-pressed channel on GroupChannelsScreenView.

GroupChannelsScreenView: long-press channel for options

---

packages/ui/src/components/Channel/Scroller.tsx

fixes TLON-2666
We just need to make sure we kill the modal that's rendering ChatMessageActions before attempting to render the ViewReactionsSheet (which itself contains a modal since it's using ActionSheet).

message actions: fix the view reactions button

---

apps/tlon-mobile/src/fixtures/UserProfileScreen.fixture.tsx
packages/app/features/top/UserProfileScreen.tsx
packages/ui/src/components/UserProfileScreenView.tsx

Does what it says on the tin. Tap a group in a profile, see the GroupPreviewSheet. You can either navigate to the group or join the group from here.
Also changes "Message" to be a hero button in order to distinguish it from "Block," which is a piece of feedback @galenwp had a while back.

profile: tap group to open GroupPreviewSheet

---

packages/ui/src/components/InviteFriendsToTlonButton.tsx

We were changing the button text to show when the lure status was stale, but users have no idea what that means. When we're stale we're going to fetch a new link anyway, so this is really "loading" as far as a user is concerned.

invite button: users don't care if the link is stale

---

desk/app/chat.hoon

This fixes TLON-2401 (the rest of it) by preventing us from sending any invites if we haven't accepted the DM or if we've been invited and the notification being sent is an invite. 
The reason we're getting continuous "Someone has invited you..." notifs was because we were mistakenly switching the `concern` to `%invite` in the new message code path if your current state was `%invited`. Now you'll only ever get one invite notification.
Additionally because we're synthesizing hark notifications from the new activity flows, and we never ripped out passing stuff to hark we were getting duplicate invites initially. This rips out all the calls to hark that were easy to strip.
PR Checklist

chat: only send notifications if dm accepted or we're sending an invite

---

apps/tlon-mobile/ios/Podfile.lock
packages/shared/src/store/postActions.ts
packages/shared/src/store/storage/storageActions.ts

fixes TLON-2866 by a) presigning headers b) only sending additional unsigned headers if the s3 provider is DigitalOcean (because DO spaces require the `x-amz-acl` header to be present and unsigned, apparently).
Tested with a DO bucket, an AWS bucket, and a minio instance.

s3: fix uploads for amazon s3 buckets

---

packages/ui/src/components/Avatar.tsx

Fixes the crashing we were seeing on scroll in the ChatList in iOS 18 (may have been happening on other iOS versions, but iOS 18 was the only one we noticed) by adding a key to the UrbitSigil in SigilAvatar.
Fixes a bug that would cause high CPU usage while apparently idle, which was caused by rendering SVG icons for groups/contacts (we now just no-op on SVG icons, at some later date we could dig into this and figure out which kinds of SVGs could be causing this issue and maybe figure out how to sanitize them).

perf: no-op on svg avatars, add a key to image and sigil avatars

---

apps/tlon-mobile/src/hooks/useNotificationListener.ts
packages/shared/src/api/harkApi.ts

Adds protections to avoid breaking on notification payload parsing from the RN side. This should resolve the one crash report we have from Corrina.
Tried to streamline validation and cleanup some of the legacy naming while I was in there.

native: avoid notification parsing crash

---

packages/ui/src/components/ChatMessage/ChatMessage.tsx
packages/ui/src/components/MessageInput/index.native.tsx

fixes TLON-2900
Just wrapped the editor in a ParentAgnosticKeyboardAvoidingView. I also updated the input so that it will focus if we know we're editing, since it's annoying to have to tape once to get into editing mode and then tap again to actually start editing.

editing: make sure edit input is visible and focused when edit button is pressed

---

apps/tlon-mobile/src/fixtures/DetailView/detailViewFixtureBase.tsx
apps/tlon-mobile/src/fixtures/PostScreen.fixture.tsx
packages/ui/src/components/Channel/ChannelFooter.tsx
packages/ui/src/components/Channel/Scroller.tsx
packages/ui/src/components/Channel/index.tsx
packages/ui/src/components/DetailView.tsx
packages/ui/src/components/PostScreenView.tsx
packages/ui/src/components/draftInputs/GalleryInput.tsx
packages/ui/src/components/draftInputs/NotebookInput.tsx
packages/ui/src/components/draftInputs/shared.ts

Removes the floating action button for Notebook and Gallery channels if the header mode isn't "next." Plumbs this through draftInputContext from the parent channel.
Also fixes the safe-area insets of channel indexes with the experimental channel switcher.
This doesn't touch the visual presentation of detail views; those components all have the right headerMode prop now but the layout is still busted. Saving for another time.
| Header mode | Notebook | Gallery |
| ----------- | -------- | ------- |
| Default | ![image](https://github.com/user-attachments/assets/4b0901dc-6549-4b44-bba7-4a75b7a8278c) | ![image](https://github.com/user-attachments/assets/6680e86a-0590-4c1a-b2c6-a13063da26ba) |
| Next | ![Screenshot 2024-10-04 at 10 06 …

GalleryInput, NotebookInput: plumb headermode through draftInputContext

---

packages/ui/src/components/ChatMessage/ChatMessageActions/MessageContainer.tsx
packages/ui/src/components/NotebookPost/NotebookPost.tsx

Hides notebook header images in the long-press menu to ensure the "Edit" action is actually on the screen.
Fixes TLON-2906.

notebooks: make edit long-press item accessible 

---

desk/app/activity.hoon

This fixes TLON-2531 by doing a similar migration to the original whereby we set current group's settings to old default and then set the new default gloablly.
PR Checklist

activity: use new default when migrating

---

packages/ui/src/components/draftInputs/GalleryInput.tsx
packages/ui/src/components/draftInputs/NotebookInput.tsx

React was raising a warning here – added a `key` to fix. @patosullivan figured you have most context since you reviewed the PR that introduced this

native: add missing key prop for useRegisterChannelHeaderItem children

---

apps/tlon-mobile/src/screens/Onboarding/PasteInviteLinkScreen.tsx

On the invite prompt screen, if you paste a valid invite link we automatically transition to the next screen where you get a preview of the invited group and can enter your email to signup. However if they click the link instead of copy/pasting, we don't show a preview and leave the paste/waitlist form visible.
This just tweaks the logic to automatically transition to the _signup with invite_ screen on link click the same way we do with paste.

native: better handling for invite click instead of paste

---

packages/ui/src/components/MetaEditorScreenView.tsx

Fixes the metadata editor screen by actually calling the function handleSubmit passes in.
https://github.com/user-attachments/assets/14a1139a-8111-4320-8871-57c900fe4111

MetaEditorScreenView: call handleSubmit as a function

---

packages/app/.eslintrc.cjs
packages/editor/.eslintrc.cjs
packages/shared/.eslintrc.cjs
packages/ui/.eslintrc.cjs

/1/chan/chat/~bitpyx-dildus/interface/msg/170141184507029324882778741826998239232
I was wrong here – the issue of web importing something that eventually imports `ExpoImageManipulator` is not caught by this, since it's not a circular import – just including a web-only dependency in `shared`. But this still seems useful as a check!
I checked by adding some bad imports to the relevant packages and running `pnpm -r lint --quiet`, and saw that there were errors reported.
(It also seems nice to have a structure for package-specific lint rules. I omitted some packages' configs, since we aren't restricting imports from those packages.)

native: add lint rules enforcing unidirectional imports from workspace packages

---

desk/app/groups.hoon

This fixes TLON-2928 by making sure we only send invites if you aren't already in the group and if you're calling the preview flow from the invite flow.
PR Checklist

groups: make sure you only get one invite

---

apps/tlon-mobile/src/screens/Onboarding/SignUpPasswordScreen.tsx

fixes TLON2-2925
If we detect a recaptcha issue we stop form submission, re-attempt initialization of recaptcha, and attempt form submission again. If the re-init fails, we show a modal to the user letting them know what's going on. They can press "retry" which will allow the reinit and resubmit to run again.
If it continues to fail, we don't really have a way to handle that, it'll just be annoying to the user in that they'll keep seeing that modal and pressing retry. Any thoughts or feedback are appreciated here.
Also, if anyone has a bead on a reliably repro, that would be appreciated. I do wonder how many of these errors are actually coming from the hosting service.

onboarding: better recaptcha error handling

---

apps/tlon-mobile/src/components/AuthenticatedApp.tsx

This logging was causing a lot of `Received SSE` logs, which is noisy for normal client dev.

native: disable verbose logging on urbit http client in dev

---

apps/tlon-web/src/logic/branch.ts
packages/shared/src/logic/branch.ts

[Somehow this commit got cleared](https://github.com/tloncorp/tlon-apps/pull/3944/commits/c8f53fd286ada5034f2521229788da816e13fadc). Adds it back

native: don't use Deeplink fallback...again

---

packages/shared/src/db/modelBuilders.ts
packages/shared/src/db/schema.ts

The `isDmInvite` column of the built model for newly created DMs needs to be explicitly set to false. If it's null, it will fail the check to show up in the chatlist query.
Fixes TLON-2938

native: fix newly created dms missing from chatlist

---

apps/tlon-mobile/src/screens/Onboarding/CheckVerifyScreen.tsx

Fixes pasting verification code on iOS by removing maxLength, which was causing the code to get truncated on paste.
Fixes TLON-2812

fix code paste

---

packages/shared/src/debug.ts
packages/ui/src/components/Channel/Scroller.tsx
packages/ui/src/components/Channel/index.tsx
packages/ui/src/components/ChatMessage/ChatMessage.tsx
packages/ui/src/components/DetailView.tsx
packages/ui/src/components/MessageInput/MessageInputBase.tsx
packages/ui/src/components/MessageInput/index.native.tsx
packages/ui/src/components/PostScreenView.tsx
packages/ui/src/components/draftInputs/ChatInput.tsx

Fixes TLON-2900
Seems to fix all of the weird issues we're seeing on both platforms when we're editing a chat message in an input inside the scroller. Also makes the Scroller and ChatMessage components less complex.
I also went ahead and updated the send button so that it dims when we know we're disconnected.

editing: use the normal chat input for editing chat messages, don't edit in the scroller

---

apps/tlon-mobile/package.json
apps/tlon-mobile/src/components/AuthenticatedApp.tsx
apps/tlon-web-new/src/app.tsx
package.json
packages/app/lib/api.ts
packages/shared/package.json
packages/shared/src/api/urbit.ts
pnpm-lock.yaml

This makes sure we use the handlers that will fire in prod, since all the `on('event')` handlers were actually only intended for debug and require `verbose` to be `true`.
PR Checklist

urbit-client: use appropriate handlers

---

packages/ui/src/components/MessageInput/helpers.ts
packages/ui/src/components/MessageInput/index.native.tsx

I *think* this was caused by a race condition where we might call `editor.getJSON` too soon (editor doesn't know about the pasted text yet, somehow) and then we attempt to process the ref and we don't find anything. I updated `handlePaste` so that we get the json content first and then pass it to `processReferenceAndUpdateEditor`.
Fixes TLON-2847

refs: prevent race condition when processing ref paste

---

packages/app/features/settings/EditProfileScreen.tsx
packages/ui/src/components/EditProfileScreenView.tsx

Fixes TLON2-2978, we skip react-hook-form for the avatar, cover image, and pinned group "fields", we just save them as soon as they're updated without waiting for form submission. Nickname and bio will still require using the "Done" button at the top.

profile editing: autosave non-input fields

---

packages/app/features/groups/GroupMetaScreen.tsx
packages/app/navigation/GroupSettingsStack.tsx

Had to do a bit of "soft" type coercion (what I like to call unwieldy unions) to get this to work, but now navigates back to ChatList (defined in RootStackParams) from the depths of GroupSettingsStack. I see some warnings about passing in the screen as a component but I'm not quite sure else how to pass in a prop to just that screen—@patosullivan maybe you have some ideas?
Fixes TLON-2680
https://github.com/user-attachments/assets/57de62b7-b445-4322-ad2b-d332cba8c133

GroupMetaScreen, GroupSettingsStack: navigate to home on delete

---

packages/ui/src/components/Channel/ChannelHeader.tsx
packages/ui/src/components/GroupChannelsScreenView.tsx
packages/ui/src/components/ScreenHeader.tsx

Truncates the title on GroupChannelsScreenView and everywhere that uses ChannelView. Defaults to 100% (full-width).

ScreenHeader: default title width to 100%, conditionally truncate

---

packages/ui/src/components/AuthorRow.tsx
packages/ui/src/components/ChatMessage/ChatMessage.tsx
packages/ui/src/components/SendPostRetrySheet.tsx

fixes TLON-2913
Adds onPress to the message content so the user can also tap there to trigger it. Truncates the author's contact name if we know we need to display something next to it (like the "Tap to retry" text). Also makes sure we don't allow normal onPress if the message is currently in a failed send state, and adds a negative accent to the "Delete" action in the retry modal.

retry send: make the whole message tappable

---

apps/tlon-mobile/src/fixtures/ActionSheet/GenericActionSheet.fixture.tsx
packages/ui/src/components/ActionSheet.tsx
packages/ui/src/components/ChatOptionsSheet.tsx

Reverts sheet close animation fix. As it turns out, it's only possible to open one native modal at a time, which cause issues in situations where one sheet opened another. Will need a refactoring to fix.

Revert "fix sheet close animations (#4040)"

---

.github/workflows/mobile-build-nightly.yml

Adds a GitHub action to build our mobile app with Expo every night at midnight. Hard-codes the "preview" and "all" options into the EAS build command. Only runs if we see changes to `develop` since the last run.

meta: add nightly mobile builds action

---

packages/app/hooks/useChannelContext.ts
packages/ui/src/components/BigInput.native.tsx
packages/ui/src/components/Channel/index.tsx
packages/ui/src/components/MessageInput/MessageInputBase.tsx
packages/ui/src/components/MessageInput/index.native.tsx
packages/ui/src/components/draftInputs/GalleryInput.tsx
packages/ui/src/components/draftInputs/shared.ts

fixes TLON-2824 by adding an optional parameter used in gallery channels to separate the different types of drafts we can have for gallery posts (either a rich text post or a caption for an image post). Showing draft text for an abandoned rich text post in the input for a new image post is confusing for users.
Note for testing: the AddGalleryPost flow is currently broken on develop because of the sheet changes that were merged yesterday, I recommend testing against develop on a commit behind that one.

drafts: allow storage of different draft types for gallery channels

---

apps/tlon-mobile/src/screens/Onboarding/SetTelemetryScreen.tsx

Adds a line to SetTelemetryScreen indicating what we don't do with users' usage stats.

SetTelemetryScreen: additional assurances

---

packages/ui/src/components/AttachmentSheet.tsx

maybe fixes TLON-3010
Not sure that moving the `onOpenChange(false)` after the launch methods will actually fix the issue that we're seeing, but it seems like it might (maybe the it's an issue with the parent sheet being closed too quickly) and it doesn't break anything.
Also added `logger.trackError` within a try/catch block on each action so we can get some more observability here.

attachments: add error tracking, close sheet after image picker launched

---

apps/tlon-mobile/ios/Landscape.xcodeproj/project.pbxproj

Bumps the "Tlon - Preview" iOS version to 4.0.2 to stay in sync with the production version.

meta: bump preview version to 4.0.2

---

packages/ui/src/components/BigInput.native.tsx
packages/ui/src/components/MessageInput/MessageInputBase.tsx
packages/ui/src/components/MessageInput/index.native.tsx
packages/ui/src/components/PostScreenView.tsx
packages/ui/src/components/draftInputs/ChatInput.tsx

fixes TLON-2995
fixes TLON-2997
fixes TLON-2998
Adds a `shouldAutoFocus` prop to the MessageInput, which we turn on in every case for BigInput (so, when making or editing a notebook post or rich text gallery post) and for the case of starting a new thread in chat.

message input: should autofocus in certain situations

---

desk/app/notify.hoon

Instead of always poking ourselves, and it maybe crashing, resulting in a crash trace being printed due to us not handling the / wire in +on-agent, we should just not poke ourselves if we're not the provider.
Gets rid of the crash trace that shows during groups desk reloads and boot.

notify: self-poke conditional on being provider

---

desk/app/chat.hoon

We assumed that all DMs eventually resolved to `%done`, which was wrong. If you started the DM, you get stuck in the `%inviting` state, so then you wouldn't get any activity for that DM. This fixes TLON-3066 by altering the check so that if you are in the `%inviting` state we still send activity and also transitions you from `%inviting` to `%done`.
PR Checklist

chat: refine activity check and make sure we transition net in DMs

---

packages/ui/src/components/BigInput.native.tsx
packages/ui/src/components/MessageInput/MessageInputBase.tsx
packages/ui/src/components/MessageInput/index.native.tsx

fixes TLON-3072 
Fixes the title input focus issue (without sacrificing the autofocus) by adding a `hasAutoFocused` state to the MessaageInput component and only focusing the editor and setting that value to true if the editor is ready and we haven't previously set it to true.
Fixes the toolbar issue by passing the editor directly to the parent ref rather than passing a local ref of the editor. Also removes the unnecessary `setEditor` method.

notebooks: fix title focus and toolbar issues

---

packages/app/features/top/GroupChannelsScreen.tsx
packages/app/hooks/useGroupContext.ts
packages/shared/src/api/groupsApi.ts
packages/shared/src/db/modelBuilders.ts
packages/shared/src/db/queries.ts
packages/shared/src/store/channelActions.ts
packages/shared/src/store/dbHooks.ts
packages/shared/src/urbit/utils.ts
packages/ui/src/components/GroupChannelsScreenView.tsx
packages/ui/src/components/ManageChannels/CreateChannelSheet.tsx
packages/ui/src/components/ManageChannels/ManageChannelsScreenView.tsx

- While joining, continue showing the group as a pending item with the  _Joining_  label
- this was an issue with correctly interpreting the Urbit types for gangs with ongoing joins
- Stop breaking if you use the same channel name
- we had name collision checking, but the set of channels we were checking against was incomplete. This adds a new query to give you _all_ channels that should also be cheaper to run
- Fix optimistic updates when adding channels
- were failing to set `currentUserIsMember` on the optimistic update or channel fact
Also removes channel description from the _Add Channel Sheet_ — we talked about keeping it lighter weight during design review, but can omit that commit if controversial.
Fixes TLON-2975
Fixes TLON-2949

native: group join & add channel fixes

---

packages/app/hooks/useChatSettingsNavigation.ts
packages/ui/src/components/ChatOptionsSheet.tsx
packages/ui/src/contexts/chatOptions.tsx

fixes TLON-2988 by adding a new `navigateOnLeave` method to useChatSettingsNavigation that gets called from `onPressLeave` within the context regardless of whether we have a group (and now we call onPressLeave for either groups or dms within the chat options actions).

chat options: navigate back to chat list on leave

---

apps/tlon-mobile/src/fixtures/DetailView/detailViewFixtureBase.tsx
apps/tlon-mobile/src/fixtures/PostScreen.fixture.tsx
packages/app/features/top/PostScreen.tsx
packages/ui/src/components/DetailView.tsx
packages/ui/src/components/PostScreenView.tsx

fixes TLON-3090
fixes TLON-2835
We weren't passing in the handlers for these things to PostScreenView or the NavigationProvider. We also didn't have the GroupPreviewSheet or any state to track which group we're previewing, so group refs in galleries (like the community catalog in tlon local) didn't do anything when pressed either.

gallery: navigate appropriately when tapping refs

---

packages/app/features/top/ChannelScreen.tsx
packages/ui/src/components/GalleryPost/GalleryPost.tsx
packages/ui/src/components/NotebookPost/NotebookPost.tsx

fixes TLON-2981
fixes TLON-2982
We weren't representing hidden or deleted states on notebook posts.
Edit: no longer rendering deleted posts. Note that the issue with deleted posts previously was that we would render an "Untitled", empty note.

notebooks: represent hidden and deleted states for posts

---

packages/app/features/top/PostScreen.tsx
packages/app/hooks/useConfigureUrbitClient.ts
packages/app/hooks/useHandleLogout.native.ts
packages/app/hooks/useHandleLogout.ts
packages/app/package.json
packages/shared/package.json
packages/shared/src/api/urbit.ts
packages/shared/src/http-api/Urbit.ts
packages/shared/src/http-api/events.ts
packages/shared/src/http-api/fetch-event-source/fetch.ts
packages/shared/src/http-api/fetch-event-source/index.ts
packages/shared/src/http-api/fetch-event-source/parse.ts
packages/shared/src/http-api/index.ts
packages/shared/src/http-api/types.ts
packages/shared/src/http-api/utils.ts
packages/shared/src/store/channelActions.ts
packages/shared/src/store/groupActions.ts
pnpm-lock.yaml

This fixes TLON-3092 by changing how we detect when to shove you to login page. We now only do so if we receive a 403 in a scry or if we receive an `AuthError` bubbled up from the http-api.
PR Checklist

native: vendor http api

---

packages/shared/src/api/channelsApi.ts
packages/shared/src/store/channelActions.ts
packages/ui/src/components/ChatOptionsSheet.tsx

fixes TLON-2987
We actually didn't have any logic related to leaving a group channel in the mobile app before, and the `leave` action in ChatOptions just assumed we were leaving a dm, so it makes sense that it was failing.

channels: add ability to leave group channels on mobile

---

packages/ui/src/components/ChannelNavSection.tsx
packages/ui/src/components/ChannelNavSections.tsx

OTT, we just weren't passing `onLongPress` to ChannelNavSection and then into ChannelListItem within it.
fixes TLON-3071

group channel list: fix long press on arranged channels

---

packages/ui/src/components/BigInput.native.tsx
packages/ui/src/components/MessageInput/index.native.tsx
packages/ui/src/components/PostScreenView.tsx
packages/ui/src/components/draftInputs/ChatInput.tsx

The issue is that if we call `editor.focus()` (or if we update the editor state directly to focus it), we lose the ability to backspace.
I can see that we get editor content updates when the backspace button is pressed, but the content never updates.
Tried digging into tentap to figure out if the issue is happening there, doesn't seem to be. 
Tried overriding the default backspace functionality and manually deleting the current node when we hear the backspace key in the webview, doesn't work.
Have ruled out the idea that we're focusing more than once, or attempting to focus when the editor is ready, or we're focusing to the wrong selection.
Have looked through the tentap and tiptap repos for issues that seem similar, can't find any.
Figuring out why this is happening is going to take a …

input: disable autofocus to fix backspace issue

---

packages/app/hooks/useConfigureUrbitClient.ts
packages/app/platform/polyfills.native.ts
packages/app/platform/polyfills.ts

A recent change to useConfigureUrbitClient (introduction of some RN polyfill imports which have no RN web equivalent) was causing the new web app build to fail.
This PR moves the native-only polyfill imports out to a `.native.ts` specific file and adds a `polyfill.ts` file that will work for web.
* [`packages/app/hooks/useConfigureUrbitClient.ts`](diffhunk://#diff-bc28930250131b199032e24e30a8d22cbb30dcfb09b0162d69ee70da46f181e2L5-R13): Replaced individual polyfill calls with `initializePolyfills` and changed the fetch method to `platformFetch`. [[1]](diffhunk://#diff-bc28930250131b199032e24e30a8d22cbb30dcfb09b0162d69ee70da46f181e2L5-R13) [[2]](diffhunk://#diff-bc28930250131b199032e24e30a8d22cbb30dcfb09b0162d69ee70da46f181e2L52-R46)
* …

new web: fix build issue

---

packages/shared/src/types/PostCollectionConfiguration.ts
packages/ui/src/components/Channel/Scroller.tsx
packages/ui/src/components/Channel/index.tsx
packages/ui/src/components/DetailView.tsx

Hardcodes detail view layout instead of adding to `layoutTypeFromChannel`. We may want to revert this in the future to customize detail view layouts, but I would prefer to avoid the complication until we need it – we don't have enough usage yet to know if this is the config "shape" we want yet, and by hardcoding, we can be more agile with the base collection layout type code.
This is a followup from #4087 – [context](https://github.com/tloncorp/tlon-apps/pull/4087#pullrequestreview-2378872029)
Screenshots proving that this still works:
| Notebook detail view | Gallery detail view |
| --- | --- |
| ![Simulator Screenshot - iPhone 16 Pro - 2024-10-22 at 12 07 01](https://github.com/user-attachments/assets/f7852bb0-0f7b-4b06-9c82-ec2e25624688) | ![Simulator Screenshot - iPhone 16 Pro - …

native: hardcode detail view layout

---

.github/workflows/deploy.yml

I've set up our protection rule to allow deploy keys to bypass checks. I've also added a `DEPLOY_KEY` secret to our actions config. This PR modifies the glob deploy action to use that key when updating the repo.

fix glob deploy + update

---

.github/workflows/mobile-update.yml
apps/tlon-mobile/app.config.ts

Updates the mobile update script from the old repo to account for needed environment variables. Note: whenever we add new ones, we'll need to do so both here and on Expo.
Also switches posthog to switch projects for preview vs prod.
Tested by using the action to trigger a preview app OTA.

ops: update Expo OTA script to account for build environment

---

apps/tlon-mobile/src/screens/Onboarding/SignUpPasswordScreen.tsx

Does what it says on the tin! This was reported a few times by users; I personally find it annoying when testing.

onboarding: add show/hide to password fields

---

apps/tlon-mobile/src/screens/Onboarding/WelcomeScreen.tsx

Right now we only fire the _Invite Link Added_ event if they add it on the paste invite screen. If branch properly captured the invite after install OR you clicked the link while still on the welcome screen, we won't hear about it. This just updates that event to also get sent from the welcome screen.

analytics: track invite added on welcome screen

---

packages/shared/src/logic/index.ts
packages/shared/src/logic/tiptap.ts
packages/ui/src/components/BareChatInput.tsx
packages/ui/src/components/BareChatInput/helpers.ts
packages/ui/src/components/BareChatInput/index.tsx
packages/ui/src/components/BareChatInput/useMentions.tsx
packages/ui/src/components/MessageInput/index.native.tsx
packages/ui/src/components/MessageInput/index.tsx
packages/ui/src/components/PostScreenView.tsx
packages/ui/src/components/draftInputs/ChatInput.tsx

If we were to use a bare text input for chat input, this is what it might look like.
~Rendering mentions in the input itself works fine, the biggest remaining pieces here, afaict right now, are:~
~- Adding basic markdown for italics/bold~
~- Parsing the text into inlines for the backend.~
~- New chat draft storage that doesn't use the JSONContent type from tiptap.~
Fixes TLON-3128
Fixes TLON-2867

use bare text input for chat input

---

.github/workflows/deploy-canary.yml
.github/workflows/deploy-internal.yml
.github/workflows/deploy.yml

Fixes TLON-3140
There were a few places that still didn't point to the new frontend, and we needed to add the ssh-key to the glob and commit step for the new frontend glob and commit action.
I also noticed some tm-alpha directory permissions issues on wannec, went in and fixed those.
Also adds an internal deploy action since we'll need that soon.
Copilot summary:
This pull request includes several updates to the deployment workflows to improve the deployment process and add new deployment steps. The most important changes include adding a new deployment step for the internal environment, updating the paths for artifacts, and modifying the git add commands.
* [`.github/workflows/deploy-internal.yml`](diffhunk://#diff-fc5ecbf361628e32305ee4f8c2662c3a905701d0dd9699a3127e4ac8d3b8afeeR29-R47): …

fix tlon-web-new deploy issues and add internal deploy

---

apps/tlon-mobile/src/screens/Onboarding/ShipLoginScreen.tsx
apps/tlon-mobile/src/screens/Onboarding/TlonLoginScreen.tsx

More password-entry friendliness. Allows users to show/hide text entry for their Tlon login and their self-hosted +code.

login: show tlon password, +code

---

packages/ui/src/components/PostScreenView.tsx

Looks like we didn't pass these props with the old input either.

input: show ref previews and allow attachments in chat threads

---

desk/app/groups-ui.hoon
desk/mar/ui/hide-contact.hoon
desk/mar/ui/import-pals.hoon
desk/mar/ui/show-contact.hoon

This grabs both our pals and our DMs and uses those to make contacts. For pals we take all `targets` which are people we've asked to be pals. For DMs, we take anyone you've DM'd in the last 30 days that has more than 10 messages. This will only run once upon receiving the update.
Fixes TLON-3146
PR Checklist

groups-ui: suggested contacts and pal import

---

apps/tlon-mobile/src/fixtures/ChannelConfigurationBar.fixture.tsx
packages/shared/src/api/channelContentConfig.ts
packages/shared/src/index.ts
packages/shared/src/store/sync.test.ts
packages/shared/src/store/useCreateChannel.ts
packages/shared/src/types/JSONValue.ts
packages/shared/src/types/PostCollectionConfiguration.ts
packages/ui/src/components/Channel/DraftInputView.tsx
packages/ui/src/components/Channel/PostView.tsx
packages/ui/src/components/Channel/index.tsx
packages/ui/src/components/ManageChannels/CreateChannelSheet.tsx
packages/ui/src/components/PostCollectionView.tsx
packages/ui/src/components/YellPost.tsx
packages/ui/src/components/draftInputs/shared.ts
packages/ui/src/components/postCollectionViews/StrobePostCollectionView.tsx
packages/ui/src/components/postCollectionViews/shared.tsx
packages/ui/src/contexts/componentsKits.tsx
packages/ui/src/contexts/postCollection.ts

> I'm not super happy with how this PR turned out, it feels like way more code than it should be. I think this is because I didn't use a strict pattern when implementing inputs vs collections vs post content config – these all ended up looking almost identical, but we reference them in slightly different ways, so I needed to add adapters whenever trying to operate over all of them.
> But in the interest of having a demo, here's the diff:
- Changed component configs in `ChannelContentConfiguration` (`draftInput` / `defaultCollectionRendererId` / `defaultPostContentRendererId`) from type `ID` -> `ID | { id: ID, configuration?: Record<string, JSONValue> }` – this was to avoid breaking existing channels (which I think would be okay to do, but it wasn't _that_ hard to maintain backwards …

custom channels: add parameters to component configurations

---

packages/ui/src/components/BareChatInput/index.tsx

Does what it says on the tin. TextInput is much more stable now.

BareChatInput: revert line-height torturing

---

apps/tlon-mobile/ios/Intents/ChannelEntity.swift
apps/tlon-mobile/ios/Intents/OpenAppIntent.swift
apps/tlon-mobile/ios/Intents/ShortcutsManager.swift
apps/tlon-mobile/ios/Landscape.xcodeproj/project.pbxproj
apps/tlon-mobile/ios/Landscape/AppDelegate.mm
apps/tlon-mobile/ios/SQLiteDB.swift
packages/app/contexts/branch.tsx
packages/app/features/top/ChannelScreen.tsx
packages/app/hooks/useGroupNavigation.ts
packages/app/lib/nativeDb.ts
packages/app/navigation/types.ts
packages/ui/src/components/Channel/index.tsx
packages/ui/src/components/draftInputs/NotebookInput.tsx
packages/ui/src/components/draftInputs/shared.ts

related discussion: https://forums.swift.org/t/can-inits-of-noncopyable-types-be-throwing/66892/4 probably should end up with a similar solution so we can keep `~Copyable`
that said, https://github.com/swiftlang/swift-evolution/blob/main/proposals/0427-noncopyable-generics.md says that this was implemented in Swift 6, and I did not get this error on my Xcode builds – which makes me think that we're using Swift 5 in builds, which I think is unnecessary.

native: manually close database instead of using deinit

---

apps/tlon-web-new/src/logic/useAppUpdates.ts

We weren't accounting for whether the app was at `/apps/tm-alpha/` vs `/apps/groups/`

desktop: fix issue with base path on service worker update redirect

---

apps/tlon-mobile/src/fixtures/Channel.fixture.tsx
packages/app/features/top/ChannelScreen.tsx
packages/app/features/top/ChatListScreen.tsx
packages/shared/src/api/groupsApi.ts
packages/shared/src/store/dbHooks.ts
packages/shared/src/store/sync.ts
packages/ui/src/components/Channel/index.tsx
packages/ui/src/components/ContentReference/ContentReference.tsx
packages/ui/src/contexts/requests.tsx

Fixes TLON-3130 by creating a new useChannelPreview hook that works similarly to useGroupPreview, but uses the `/chan/${channelId}` subscribeOnce path in %groups to grab a `ChannelPreview`. We used this same path/subscribeOnce for the same purpose in the old web app.
copilot description:
This pull request focuses on replacing the `useChannel` hook with a new `useChannelPreview` hook across various files to improve the handling of channel previews. Additionally, it introduces new functions to support the functionality of channel previews.
* Replaced `useChannel` with `useChannelPreview` in `Channel.fixture.tsx` [[1]](diffhunk://#diff-8c819e75a2f7a08e39352817cd38138e1e3dac6c4680e357062ce2841111f5cdL3-R3) [[2]](diffhunk://#diff-8c819e75a2f7a08e39352817cd38138e1e3dac6c4680e357062ce2841111f5cdL …

refs: allow users to join groups from content refs

---

apps/tlon-mobile/ios/Landscape.xcodeproj/project.pbxproj
apps/tlon-mobile/package.json
packages/ui/src/tamagui.config.ts
pnpm-lock.yaml

Fix TLON-3174
Doesn't break web, fixes the warning we were seeing on mobile.
See tamagui docs here: https://tamagui.dev/docs/core/configuration#setup-media-query-driver

mobile: fix missing tamagui media query driver

---

packages/app/features/top/UserProfileScreen.tsx
packages/ui/src/components/UserProfileScreenView.tsx

Clicking the "Message" button on a user profile would crash the app with a "Cannot read property 'split' of undefined" error. This occurred because we were passing the full channel object to navigation instead of just the channel ID that the Channel screen expects.
- Adds validation to ensure channel ID exists before navigation.
- Also adds error handling around DM channel creation and navigation
https://github.com/user-attachments/assets/8a3a153b-8780-4e7e-a593-7c1c50191266
Fixes TLON-3197

profile: pass channelId when navigating to DMs

---

packages/ui/src/components/ActionList/ListFrame.tsx
packages/ui/src/components/Channel/Scroller.tsx
packages/ui/src/components/ChatMessage/ChatMessage.tsx
packages/ui/src/components/ChatMessage/ChatMessageActions/Component.android.tsx
packages/ui/src/components/ChatMessage/ChatMessageActions/Component.tsx
packages/ui/src/components/ChatMessage/ChatMessageActions/EmojiToolbar.tsx
packages/ui/src/components/ChatMessage/ChatMessageActions/MessageActions.tsx
packages/ui/src/components/ChatMessage/ChatMessageActions/MessageContainer.tsx
packages/ui/src/components/Embed/AudioEmbed.native.tsx
packages/ui/src/components/Emoji/EmojiPickerSheet.tsx
packages/ui/src/components/Form/inputs.tsx
packages/ui/src/components/ImageViewerScreenView.tsx
packages/ui/src/components/ListItem/InteractableChatListItem.tsx
packages/ui/src/components/SearchBar.tsx
packages/ui/src/hooks/useOnEmojiSelect.tsx
packages/ui/src/utils/hapticIds.ts
packages/ui/src/utils/haptics.native.ts

fixes TLON-3170
On desktop we now render a modal for chat message actions, and a separate modal for the emoji picker.
Also fixed the input outline issue in the BaseTextInput component and an issue with the way the close button was displayed in the SearchBar after the inclusion of the Pressable component there.
copilot description:
This pull request introduces several changes to improve the user experience on different screen sizes and platforms, particularly focusing on handling narrow windows and web-specific behaviors. The key changes involve the addition of hooks to detect window size, modifications to the behavior of modals and action sheets, and the enhancement of emoji picker functionality.
* [`packages/ui/src/components/ActionList/ListFrame.tsx`](diffhunk://#diff-c2bff9e7dd5b287de6f …

desktop: render desktop appropriate chat message actions

---

apps/tlon-mobile/src/hooks/useNotificationListener.ts
packages/app/features/settings/FeatureFlagScreen.tsx
packages/app/features/top/GroupChannelsScreen.tsx
packages/app/lib/featureFlags.ts
packages/app/utils/posthog.ts
packages/shared/src/store/dbHooks.ts

- Hardcode custom channels flag to show only if user is a Tlon employee
- Change custom channels flag key to invalidate for all existing installs (to avoid case where flag was enabled by non-Tlon-employee, disappears for them from this PR, but remains logically/invisibly enabled)
- [extra] I had a hard-to-see bug in my first pass where I did something like
```ts
const isTlonEmployee = useIsTlonEmployee();
if (isTlonEmployee) {
// do something
}
```
This would always run the if-block because `isTlonEmployee` is actually a react-query query result – i.e. a non-null object, which is truthy. 6d928f46d1327baf0fd2f0342338f1651cd9b1dc changes this to just return an optional boolean.
- [extra] [8666ec8](https://github.com/tloncorp/tlon-apps/pull/4159/commits/8666ec84d5d290986d87d6ac7980c12dae1139d …

native: show custom channels flag only if user is tlon employee

---

apps/tlon-mobile/android/app/build.gradle
apps/tlon-mobile/ios/Landscape.xcodeproj/project.pbxproj
packages/ui/src/components/UserProfileScreenView.tsx

User row's width got collapsed as part of the lonpress/pressable refactor. Just resets that so it displays normally.
That's the only regression I'm seeing, but trying to check for other similar cases

native: fix user info on profile screen

---

packages/ui/src/components/ContactRow.tsx

Fixes the issue where pressing a ContactRow does nothing.
The problem was that we were passing `{...rest}` into ListItem, which included `pressStyle`, which ended up making ListItem the pressable element rather than Pressable.
To fix, I pulled `pressStyle` out of props and passed it to Pressable instead, along with some style related props.

pressable: fix onPress issue in ContactRow

---

desk/lib/test-agent.hoon

Most importantly, failing to initialize/set the agent core prior to running your tests could've resulted in false successes. Here we make sure that there's always a crashing skeleton core there, and that crashes with empty traces still result in failing tests.
Additionally, we add a `+do-as` helper for temporarily changing the `src.bowl`. Very convenient for tests that simulate multiple parties interacting with the same agent.

tests: various /lib/test-agent improvements

---

.eslintrc.cjs
apps/tlon-mobile/src/hooks/useNotificationListener.ts
packages/app/features/groups/GroupMembersScreen.tsx
packages/app/features/top/ChannelSearchScreen.tsx
packages/app/features/top/UserProfileScreen.tsx
packages/app/hooks/useChannelNavigation.ts
packages/app/navigation/types.ts
packages/app/navigation/utils.ts

fixes TLON-3220
fixes TLON-3198
First, this fixes navigating to a DM from the ProfileSheet that is accessible via the group member list by passing a channelId rather than a channel param.
The reason this wasn't caught before was because we were using CommonActions.reset() to reset the navigation state (which makes sense given the context, we don't necessarily know where we're going to be navigating from in that sheet). Because we were doing that, we didn't have any type safety around the route/params.
To reset the navigation state in a typesafe way, I added a `createTypedReset` function that we can use to create a reset function using our navigation types. I also created some helper hooks (`useTypedReset`, `useResetToChannel`, etc.) to reduce the boilerplate associated with using it and …

navigation: fix navigate to dm from members list, fix navigate to search results

---

packages/ui/src/components/ChatOptionsSheet.tsx

OTT, looks like we were just mistakenly calling both group and channel leave here.
Fixes TLON-3222

native: don't leave group when leaving channel

---

packages/shared/src/db/queries.ts

OTT
May have been resolved with the pressable fixes, because it looks like unbans are going through fine. Weren't reflecting changes to the banned users table in the groups query however, so this just fixes the optimistic UI update.
Fixes TLON-3221

native: fix unban action

---

apps/tlon-mobile/src/screens/Onboarding/SignupScreen.tsx
apps/tlon-mobile/src/screens/Onboarding/TlonLogin.tsx

- Adds onSubmitEditing props to email fields so the user can press "enter" to submit the form via the system soft-keyboard
- Relocates the "Next…" button on signup and login screens to a hero button beneath the field
Signup screen:
Tlon login screen:

onboarding: "next" usability 

---

packages/shared/src/db/modelBuilders.ts

Fixes issue with creating notes immediately after creating a channel. The optimistically generated channel ids for notebooks + galleries were incorrect, which meant that they wouldn't function correctly until updated from the server. This PR fixes that, so they can now be posted to immediately.
Fixes TLON-3211

fix optimistically generated notebook + gallery ids

---

packages/ui/src/components/Channel/Scroller.tsx
packages/ui/src/contexts/scroll.tsx

Looks like this was showing on send since we scroll slightly as part of rendering the new message. The hook we're using interprets any non-zero scroll whatsoever as worthy of signaling "not at bottom".
This just updates that hook to use a configurable threshold instead (as implemented, uses height of the screen/viewport). As a side effect, this also prevents us from showing the go to bottom button unless you've scrolled back a little further in the chat which is probably preferable?
https://github.com/user-attachments/assets/ae2aca72-9b1b-437c-9065-fb31d1e2dd85
Fixes TLON-3205

native: avoid showing "scroll to" button on message send

---

packages/ui/src/components/BareChatInput/index.tsx

fixes TLON-3209
When we switched to using an uncontrolled text input on native, we lost the ability to filter out reference strings from the displayed text after processing them into attachments. This PR restores that functionality by using setNativeProps to manually update the text input's value, but only when reference strings are detected. The input remains uncontrolled in all other cases to avoid render loops.

chat input: fix reference handling on native

---

packages/app/hooks/useConfigureUrbitClient.ts
packages/shared/src/http-api/Urbit.ts

Text streaming requests perform much worse than normal ones in react native, which was causing freezes during loading of init data. This data modifies the urbit client so that only the `eventSource` request uses text streaming mode.
Fixes TLON-3201.

fix load freeze

---

apps/tlon-mobile/src/hooks/useNotificationListener.ts
packages/app/features/top/ActivityScreen.tsx
packages/app/features/top/ChannelScreen.tsx
packages/app/features/top/ChatListScreen.tsx
packages/app/features/top/PostScreen.tsx
packages/app/navigation/RootStack.tsx
packages/app/navigation/desktop/HomeNavigator.tsx
packages/app/navigation/linking.ts
packages/app/navigation/types.ts
packages/app/navigation/utils.ts

fixes TLON-3168 by adding new Screens/routes (`DM` and `GroupDM`) that just point to `ChannelScreen`. Also adds a new helper function, `screenNameFromChannelId` to use in situations where we could navigate to any kind of channel (a normal `Channel`, a `DM`, or a `GroupDM`).
copilot description:
This pull request introduces changes to improve the navigation handling in the app, specifically by distinguishing between different types of channels (DM, GroupDM, and Channel) and updating the navigation logic accordingly. The most important changes include adding new screen names, updating navigation calls, and modifying the linking configuration.
* Added new screen names `DM` and `GroupDM` to `RootStack` and `HomeNavigator` components. …

nav: add routes for DMs and GroupDMs

---

packages/app/features/settings/AppInfoScreen.tsx
packages/app/features/settings/BlockedUsersScreen.tsx
packages/app/features/settings/ManageAccountScreen.tsx
packages/app/features/settings/PushNotificationSettingsScreen.tsx
packages/app/features/settings/UserBugReportScreen.tsx
packages/app/navigation/desktop/ProfileScreenNavigator.tsx
packages/app/navigation/desktop/TopLevelDrawer.tsx
packages/ui/src/components/ChatOptionsSheet.tsx
packages/ui/src/components/FeatureFlagScreenView.tsx

fixes TLON-3224
Adds a new stack navigator for the profile screen on desktop, fixes the "Leave" button on channels (which used the react-native `Alert` dialog, which doesn't work on web).

desktop: fix profile screen navigation, leave chat button

---

desk/app/activity.hoon
desk/app/channels.hoon
desk/mar/channels-2.hoon
desk/mar/channels-3.hoon

This pulls the work done by @mikolajpp in tloncorp/tlon-apps#4175 out to just get this migration fix in. @pkova was hoping to get this soon for pill creation also.
PR Checklist

channels: add missing scry and update usage in activity

---

packages/ui/src/components/PostContent/BlockRenderer.tsx

Fixes a regression introduced in #4160 where Gallery blocks (in 2-column grid format) had their aspect ratio explicitly set and were not square-cropped as before.
This looks to the 'unset' aspect set in SmallContentRenderer (which is used in Gallery blocks) and passed down through props. If the aspect ratio is explicitly unset, we set nothing in the style prop for `Pressable`.
Proof:

BlockRenderer: avoid setting aspect ratio if unset

---

packages/shared/src/api/channelContentConfig.ts
packages/shared/src/types/JSONValue.ts
packages/ui/src/components/Channel/PostView.tsx
packages/ui/src/components/ChatOptionsSheet.tsx
packages/ui/src/components/postCollectionViews/shared.tsx

Without this PR, older custom channels have authors and replies hidden by default.
- Set param defaults when parsing `StructuredChannelDescriptionPayload`
- In same code block, add any missing fields to `ChannelContentConfiguration` (missing fields here was causing a crash in one of my test channels)
- Hide `Configure view` menu item when config is missing (this would cause a crash otherwise)
- Apply standard params (`Show replies`, `Show authors`) on legacy post types (we were not doing this before)

custom channels: fix handling of omitted standard parameters

---

packages/ui/src/components/ChatOptionsSheet.tsx

Adds a "mark as read" option to the channel actions menu, which handles whole groups, channels, DMs, and group-DMs. 
Video:
https://github.com/user-attachments/assets/e1f8b81c-137c-4ddc-92a2-684bc69f037d
Fixes TLON-2720

ChatOptionsSheet: mark group/channel/DM/groupDM as read

---

packages/app/features/groups/EditChannelScreen.tsx
packages/app/features/groups/ManageChannelsScreen.tsx
packages/app/features/top/GroupChannelsScreen.tsx
packages/ui/src/components/ChatOptionsSheet.tsx
packages/ui/src/components/ManageChannels/EditChannelScreenView.tsx

Does what it says on the tin; fixes TLON-3134, which is a bit of an edge-case.
If the user tries to delete the last channel in a group, we pop a warning and tell them to create another channel (or delete the entire group).
This is a particularly interesting bug—it was possible to enter the channel manager _from_ a channel, delete that channel, then .goBack() your way out of it only to be dumped into a channel that doesn't exist (and therefore get a blank screen). 
To complicate matters, you get to the channel manager from ChatOptionsSheet, which is either (A) in the channel itself via the "..." menu, or (B) from GroupChannelsScreen via the "..." menu, or (C) from long-pressing the group on the ChatList screen.
I brute-forced this and just made all the back-navigation explicit for these …

channel manager: prevent deleting last channel in group

---

packages/app/features/top/ChatListScreen.tsx
packages/shared/src/api/activityApi.ts
packages/shared/src/store/groupActions.ts
packages/ui/src/components/ChatOptionsSheet.tsx

Adds an optional prop to readGroup in activityApi to either mark the group read "deeply" or not (we badge it for new members requesting approval and clear the dot when navigating to it via Activity—this has nothing to do with unread messages in channels).
Adds a menu item to the ChatOptionsSheet for groups with unreads to deep-mark as read.
Fixes TLON-3240

ChatOptionsSheet: mark group as read

---

packages/app/features/settings/ManageAccountScreen.tsx
packages/ui/src/components/ProfileScreenView.tsx

Wraps the check if the account was deleted in a try/catch block on ManageAccountScreen. This avoids crashing the app if we press the back button. Also eliminates the spinner in the navigation.
Here's a video of the back action working (!):
https://github.com/user-attachments/assets/a61041cb-a8b7-4e99-9fb1-b5225e90d8b9

ManageAccount: wrap wasDeleted in try/catch, avoid crashing

---

packages/ui/src/components/BareChatInput/helpers.ts

We were unnecessarily adding `https://` before any single word sent that looked like a URL. This would result in messages such as `https://support@tlon.io` when the user simply typed `support@tlon.io`.
Screenshot from simulator.

BareChatInput: avoid aggressive prefixing for link-like words

---

packages/ui/src/components/BareChatInput/index.tsx

fixes TLON-3234 by forcing the TextInput to update using setNativeProps *without* setting any `text`, which is apparently additive, and which also causes onChangeText to fire again, which was causing the loop.
I also renamed `text` to `controlledText` for clarity's sake.

chat input: fix infinite loop on ref

---

packages/ui/src/components/Channel/index.tsx
packages/ui/src/components/MessageInput/MessageInputBase.tsx

fixes tlon-3111 (the symptom, anyway).
Looks like this is related to this issue https://github.com/tamagui/tamagui/issues/2856
I attempted updating to the latest tamagui, no dice. I tried setting `fastSchemeChange:false` in the tamagui config, didn't work.
It seems like the issue is happening only with the Channel/index.tsx and and MessageInputBase.tsx components in particular. The backgrounds just don't update when the theme context changes.
If we pull the background variable out manually with getVariableValue(useTheme().background)) it always updates appropriately. I did that here.
We could go with this for now and figure out why this is happening later, or I could keep digging to try to figure out the root cause and hopefully fix that. Fine with me either way.

native: fix issue with dark/light mode switching

---

packages/ui/src/components/ListItem/ListItem.tsx

Another case of the Tamagui background color sticking between light/dark mode.

ListItem: fix light/dark mode switch

---

apps/tlon-mobile/package.json

I didn't see that the script to start Cosmos had changed locations, so I was running this script, which "works" but is missing a lot of fixtures (and hangs on "waiting for renderer").

Remove tlon-mobile `cosmos` script

---

desk/app/channels-server.hoon
desk/app/groups.hoon

Problems with channel auto-join were two-fold:
First, channels-server was always poking the local groups agent with the creation command, instead of the groups agent on the host of the group. Here we make sure to poke the appropriate ship.
Second, groups agent was explicitly no-opping when a channel was added to a group it hosts itself. Here, we remove that condition, letting that case proceed into channel joining logic unhindered.
Closes TLON-3151.

groups: auto-join new channels in all cases

---

desk/app/activity.hoon
desk/app/chat.hoon
desk/app/groups.hoon
desk/app/profile.hoon
desk/app/profile/widgets.hoon
desk/lib/activity-json.hoon
desk/lib/activity.hoon
desk/lib/contacts.hoon
desk/lib/contacts/json-1.hoon
desk/lib/notify.hoon
desk/sur/activity.hoon
desk/sur/contacts-0.hoon
desk/sur/contacts.hoon

This PR had already been reviewed in https://github.com/tloncorp/tlon-apps/pull/4175 and merged into @latter-bolden `lb/contacts-ui` branch. While it could be merged eventually with @latter-bolden branch, earlier merge allows us to test the integration with corresponding changes to %contacts in the %landscape desk.

Implement %contacts activity

---

packages/app/features/top/GroupChannelsScreen.tsx
packages/shared/src/api/channelsApi.ts
packages/shared/src/db/changeListener.ts
packages/shared/src/db/queries.ts
packages/shared/src/store/channelActions.ts
packages/shared/src/store/dbHooks.ts
packages/ui/src/components/Avatar.tsx
packages/ui/src/components/ChannelNavSection.tsx
packages/ui/src/components/ChannelNavSections.tsx
packages/ui/src/components/ChatOptionsSheet.tsx
packages/ui/src/components/GroupChannelsScreenView.tsx
packages/ui/src/components/ListItem/ChannelListItem.tsx
packages/ui/src/components/ListItem/ListItem.tsx

Fixes TLON-3257
We need to show users the channels they aren't joined to and give them a way to join them.
- Adds a query for channels that are in the group but you aren't joined to.
- Adds channelActions and a tracked poke in the channelsApi for joining a channel in a group.
- Modifies the addJoinedGroupChannel query to avoid collision.
- Adds the result of the unjoined channel query to GroupChannelScreen to create a list of unjoined channels visible to the user.
- Modifies changeListener to account for changes in the db to the channels table and live-update the unjoined channels list.
This produces the following effect:
https://github.com/user-attachments/assets/a1c0fc7b-12a6-4e5a-a8fc-364d7191c2d0

GroupChannelsScreen: show unjoined channels, tap to join

---

desk/app/expose.hoon
desk/app/expose/page.hoon
desk/app/expose/render.hoon
desk/app/profile.hoon
desk/app/profile/widgets.hoon

There were some outdated type references in %expose that were preventing the upgrade. Additionally, both %profile and %expose were using the removed `/contact` API endpoint. For now we just migrate to subscribing to `/news` and filtering on our own profile updates. We should migrate these two agents to use new %contacts API soon.

profile & expose: fix integration with contacts

---

desk/app/activity.hoon
desk/app/channels-server.hoon
desk/app/channels.hoon
desk/app/groups.hoon
desk/app/logs.hoon
desk/desk.bill
desk/lib/logs.hoon
desk/sur/contacts-0.hoon
desk/sur/logs.hoon
desk/ted/posthog.hoon
desk/tests/app/logs.hoon

The %logs agent gathers log events from other agents in the groups desk and submits them as "Backend Log" events to PostHog. Currently the only event supported is the `%fail` event usually generated in agent `+on-fail` arm.
As a trial, in this PR we enable logging of crashes in %channels, %channels-server, %groups and %activity.

logs: new agent to gather and submit app logs

---

packages/app/fixtures/Pressable.fixture.tsx
packages/ui/src/components/Pressable.tsx

_To preface: I don't know if this is a great thing to add to the `Pressable` primitive – opening this for discussion. Alternatives include (1) plumbing a `disabled` prop to `ChatMessage` for my one use case, (2) adding a flag to `Pressable` to opt-in to this behavior, or (3) creating a new `Pressable`-like component with this behavior (`OptionallyPressable`? 🤷 )._
---
I was trying to add a long-press to a container view holding a `ChatMessage` using `Pressable`. My handler wouldn't get called – swapping out `ChatMessage` for a blank `View` worked.
`ChatMessage` has a `Pressable` which has no bound handlers in this scenario, and I expected events to bubble up the stack like on web – but it looks like RN doesn't have that behavior. Here's a recording of the fixture from this PR …

native: simulate pressable event bubbling

---

packages/ui/src/components/GalleryPost/GalleryPost.tsx
packages/ui/src/components/ListItem/ChannelListItem.tsx
packages/ui/src/components/ListItem/GroupListItem.tsx
packages/ui/src/components/ListItem/ListItem.tsx
packages/ui/src/components/TextV2/Text.tsx

edit: now also fixes TLON-3279
fixes TLON-3271
We're now using the new Text component to render text in the chat list, this fixes the line height issue that required setting a specific (larger) height for ListItem on web. Also updates the $label/l value to something less heavy (Dan's recommendation) and updates the margin/position of the overflow menu button (and the count pill next to it).
Looks much more "normal" now:
Also looks good on iOS:
and Android:

desktop: fix ChatList/ChannelList height/space weirdness

---

packages/app/features/top/ChatListScreen.tsx
packages/app/fixtures/GroupList.fixture.tsx
packages/app/fixtures/fakeData.ts
packages/app/hooks/useBootSequence.ts
packages/app/hooks/useGroupContext.ts
packages/shared/src/api/activityApi.ts
packages/shared/src/db/queries.test.ts
packages/shared/src/db/queries.ts
packages/shared/src/db/types.ts
packages/shared/src/logic/utils.ts
packages/shared/src/store/activityActions.ts
packages/shared/src/store/channelActions.ts
packages/shared/src/store/dbHooks.ts
packages/shared/src/store/sync.test.ts
packages/ui/src/components/ChatList.tsx
packages/ui/src/components/ChatOptionsSheet.tsx
packages/ui/src/components/ListItem/ChannelListItem.tsx
packages/ui/src/components/ListItem/ChatListItem.tsx
packages/ui/src/components/ListItem/GroupListItem.tsx
packages/ui/src/components/ListItem/InteractableChatListItem.tsx
packages/ui/src/contexts/chatOptions.tsx

This PR refactors the `getChats` query to simplify rendering logic and add flexibility in querying. It sets up plumbing I'll need for the channel flattening work.

refactor chat query

---

packages/app/features/settings/AppInfoScreen.tsx
packages/app/features/settings/ThemeScreen.tsx
packages/app/features/settings/UserBugReportScreen.tsx
packages/app/features/top/ContactsScreen.tsx
packages/app/hooks/useTelemetry.ts
packages/app/navigation/desktop/HomeNavigator.tsx
packages/app/navigation/desktop/ProfileScreenNavigator.tsx
packages/app/navigation/desktop/TopLevelDrawer.tsx

fixes TLON-3280
fixes TLON-3283
fixes TLON-3284
The crash in the AppInfoScreen was caused by the use of `getCurrentUser` in that screen and the import of the native version of useCurrentUser in the useTelemetry hook.
Updated desktop to now point to the Contacts screen when pressing the profile avatar in the nav, and the settings are now behind the cog like they are on mobile.
I also made desktop work with our themes (and made sure we could navigate to the ThemeScreen on desktop), including adding `backgroundColor` to a few places where we needed it.

desktop: fix routing/crash issues in settings, add contacts, add themes

---

apps/tlon-web-new/src/logic/useAppUpdates.ts
apps/tlon-web-new/src/main.tsx

This morning, a change to the return type of useCurrentChats caused the web app to crash on initial load. This appears to have been happening because the `isFocused` flag defaults to false on first load, which means we disabled the fetch on the useCurrentChats query, which caused us to try to hydrate the ChatListScreenView component with data that doesn't match the return type expected by the component.
In order to prevent this sort of thing in the future, we now clear the cache before updating the service worker when the user presses the update button in the TopLevelDrawer.
This also changes the cache buster string so we can fix the situation with users who are currently synced to wannec (who have already attempted to update). Not totally sure that'll work, if not those users will have …

desktop: fix issue with stale data breaking the app on first load

---

packages/shared/src/api/contactsApi.ts
packages/shared/src/db/queries.ts
packages/ui/src/components/ContactsScreenView.tsx

Omits the current user from the suggested contacts query. Turns out, if you DM with yourself, you're eligible as a contact!
Furthermore, our condition for showing "You" vs "Add" vs just a caret in the ContactListItem endContent was a little shaky. Made that a little more explicit.
Things are looking better now IMO:

contacts: quick fixes

---

packages/ui/src/components/AuthorRow.tsx
packages/ui/src/components/BigInput.tsx
packages/ui/src/components/Channel/index.tsx
packages/ui/src/components/ChatMessage/ChatMessage.tsx
packages/ui/src/components/ChatMessage/ChatMessageActions/MessageContainer.tsx
packages/ui/src/components/GalleryPost/GalleryPost.tsx
packages/ui/src/components/Image.tsx
packages/ui/src/components/MessageInput/MessageInputBase.tsx
packages/ui/src/components/MessageInput/index.tsx
packages/ui/src/components/NotebookPost/NotebookPost.tsx
packages/ui/src/components/OverflowMenuButton.tsx
packages/ui/src/components/PostScreenView.tsx

fixes TLON-3273 (making the BigInput actually usable on desktop) We weren't accounting for big input height.
Also fixes other issues:
Notebooks weren't wrapped in a Pressable. 
Some bad conditional checks were causing text strings to render outside of Text components/directly within Stack components.
Edits weren't working at all for notebook posts (we weren't filling in the draft content, we weren't passing along the title, and we weren't handling situations where the post had an image).
We were still unnecessarily using a ScrollView for the web version of the BigInput.
We had no way to allow the user to exit the big input editor if they wanted to abandon creating a post.
We were attempting to pass `contentFit` as a prop to `img` tags for web, which isn't a valid attribute, which made the …

desktop: fix big input, and other desktop web issues

---

packages/ui/src/components/ProfileStatusSheet.tsx

Adds a send button to the ProfileStatusSheet and makes the input a single line.

ProfileStatusSheet: add send button

---

packages/ui/src/components/ContactBook.tsx
packages/ui/src/components/ContactRow.tsx

OTT
Fixes TLON-3293
Fixes TLON-3299

contacts: use contacts for populating contact book list, display @p if nickname set

---

apps/tlon-mobile/ios/Shared/Notifications/PushNotificationManager.swift
packages/app/lib/notifications.ts

Getting badge counts dialed is going to take a little longer. Let's leave the notification dismissal logic in place, but omit those for now.

native: remove badging for now

---

packages/shared/src/db/queries.test.ts
packages/shared/src/db/queries.ts
packages/shared/src/test/init.json
packages/ui/src/components/ListItem/listItemUtils.tsx

Ensure that group invitations + requests are show in chat list. Also modifies labelling logic so that joining / error statuses take precedence over invite status. 
Fixes TLON-3362

fix pending group display

---

apps/tlon-mobile/src/components/AuthenticatedApp.tsx
apps/tlon-web-new/src/app.tsx
packages/app/hooks/useFindSuggestedContacts.ts
packages/shared/src/db/keyValue.ts
packages/shared/src/db/queries.ts
packages/shared/src/store/contactActions.ts
packages/shared/src/store/dbHooks.ts
packages/shared/src/store/sync.ts

With the last batch of edits, this was failing to run properly for new signups. Changes a few things:
- moves logic back to joined group count based trigger rather than `syncStart`
- mounted on both native and desktop
- only sets _groups last used_ short-circuit after having found some suggestions
- will only give you new suggestions once per day
- previously if you were joined to under 4 groups, it would keep adding new suggestions continuously until you'd dismissed ever single person with a profile set

contact suggestions: fix trigger

---

packages/app/hooks/useHandleLogout.native.ts
packages/app/hooks/useHandleLogout.ts
packages/shared/src/db/keyValue.ts

Today I got bit by a key value item not getting cleared after logout. Thus far we've been ad hoc adding reset calls to `useHandleLogout`, but I realized this should probably just be a property of `createStorageItem` itself.
Can now pass a `persistAfterLogout` flag in the config, defaults to false.

key value: add option to keep or clear storage items after logout

---

packages/ui/src/components/Image.tsx

fixes TLON-3323
The fact that we didn't provide a default fallback for errored images was most noticeable on web because:
a) the browsers shows a broken image icon
b) we just weren't accounting for broken images at all, no fallback was ever returned there.
This PR adds a new default image fallback that will be returned if an image fails to load. That fallback can be overridden by the `fallback` prop on Image.

images: provide default fallback for errored images

---

packages/app/navigation/BasePathNavigator.tsx
packages/app/navigation/desktop/TopLevelDrawer.tsx
packages/app/navigation/linking.ts
packages/app/navigation/types.ts
packages/app/navigation/utils.ts
packages/app/utils/lastScreen.ts

fixes TLON-3304
Note that while this *will* route you to the right spot (unless you're in a screen nested under the profile screen), you will lose your position in the scroller if you were in a channel.
This also updates the desktop TopLevelDrawer route naming to match desktop (`Profile` is now `Contacts`).
I also found that we were using the wrong check for groupDM ids in `screenNameFromChannelId`, fixed that.

desktop: preserve navigation state when resizing window

---

packages/ui/src/components/Channel/Scroller.tsx

fixes tlon-3316
This makes grid items size correctly by setting their width based on the number of columns (50% for 2 columns, 100% for 1 column) while using aspectRatio to maintain the desired shape.
This was necessary because without an explicit width constraint, the grid items were sizing themselves based on their content's intrinsic dimensions (the full-size images), and even though we had aspectRatio set to create square shapes, the items were becoming too large and creating layout issues. By explicitly setting the width to a percentage of the container and letting aspectRatio determine the height, we make sure that grid items maintain the right proportions while fitting into the grid layout.
Setting the width of the items to 50% in two column mode also requires adding some right …

gallery: fix item size issues on desktop

---

packages/ui/src/components/ListItem/ChannelListItem.tsx
packages/ui/src/utils/channelUtils.tsx

Corrects the nullish check pattern in channelUtils / getChannelMemberName. Tries to get the nickname from the contact, but if that's not available, it falls back to using the contactId (patp).
Also implements a "hasNickname" channelUtil to hide the duplicitous patp subtitle in ChannelListItems.
Here's a DM with someone who has a nickname set:
And without:

ChannelListItem, channelUtils: fix bare patp display in ChatList

---

packages/ui/src/components/ChatList.tsx
packages/ui/src/components/ListItem/ListItem.tsx

This PR fixes initial chatlist animation / rendering jank by more accurately estimating item sizes pre-render.
The jank is a known issue for `FlashList` on web, if it continues to crop up we could switch to `FlatList` on desktop instead.
Fixes TLON-3332

fix desktop chatlist jank

---

desk/app/profile/widgets.hoon

This was still using the old contacts types and scry endpoint. Here, we use the latest instead, and move contact data unpacking up to the top of the file while we're at it.
Resulting widgets confirmed to be exactly equivalent.
(Also sneaked in a small refactoring. Best to review per commit.)

profile: use new contacts type & endpoint

---

packages/ui/src/components/ChatMessage/ChatMessageActions/MessageActions.tsx

fixes tlon-3375
Our fixes for getting rid of the FlashList jank involved setting a definite height on ListItem of `$6xl`. This worked fine for most use cases, but not for our message actions. We just need to override the height in this case with `'auto'`.

fix message action height issue

---

apps/tlon-mobile/src/hooks/useNotificationListener.ts
packages/app/features/top/ActivityScreen.tsx
packages/app/features/top/ChatListScreen.tsx
packages/app/features/top/CreateGroupScreen.tsx
packages/app/features/top/GroupChannelsScreen.tsx
packages/app/features/top/PostScreen.tsx
packages/app/hooks/useChannelNavigation.ts
packages/app/navigation/desktop/HomeNavigator.tsx
packages/app/navigation/types.ts
packages/app/navigation/utils.ts

fixes tlon-3306
This adds some new hooks to our navigation utils, `useNavigateToChannel` and `useNavigateToPost`, that allow us to navigate from the ActivityScreen on desktop into the relevant nested screens within the HomeNavigator.
It also updates our navigation types to account for the fact that Channel in HomeNavigator is a Stack and not just a route, and updates Screen components where appropriate to use the new hooks.
This gets us a bit closer to the abstraction layer for navigation that we've been talking about.

desktop: harden navigation between home/non-home screens and nested screens

---

desk/app/profile.hoon
desk/app/profile/widgets.hoon

types. It checked for the tags on values found in the map. However, it's possible for values to be null, in which case trying to grab the head would crash at runtime.
Here, we update the typecheck to check on the full value as opposed to just the head.
Since this crashing code might have run in response to a contacts subscription update, killing the subscription, we add a bit of logic to +on-load to ensure that the contacts subscription gets set up again if needed.

profile: read contacts fields safely

---

packages/ui/src/components/ChatOptionsSheet.tsx

When pressing the overflow menu in a single-channel group, show group options instead of channel options.
Fixes TLON-3386

flatten chat options for single channel groups

---

packages/ui/src/components/Onboarding/OnboardingInvite.tsx

Micro PR to reset onboarding invite images to normal size for now. A lot of times these Lure groups don't have images anyhow, in which case the first letter fallback is too dominating at 100px.
Fixes TLON-3405

invites: fix onboarding invite preview image size

---

apps/tlon-mobile/src/hooks/useNotificationListener.ts
packages/app/navigation/utils.ts

fixes TLON-3384
Bug was caused by not passing "is desktop" to `getMainGroupRoute` – so we were trying to navigate to a desktop-only route on mobile, which failed. Fixed this by making that argument required, so everyone needs to pass it.
While here, I noticed we're using the `useIsWindowNarrow` for this "is desktop" check – I think `useIsWindowNarrow` makes sense for doing responsive layout, but not for checking which sets of routes the built app is using (e.g. someone could be using desktop with a narrow viewport, then everything will break). Fixed this by adding a context-based `useAppPlatform` hook – replaced all of the navigation-based switches on `useIsWindowNarrow` that I could see.

native: fix navigating to tapped notification

---

apps/tlon-mobile/src/screens/Onboarding/ReserveShipScreen.tsx

Fixes vertical alignment of spinners / ListItem content on ReserveShipScreen.
Red borders for debugging/proof.
Old and bad:
New and good:

ReserveShipScreen: remove unnecessary padding

---

packages/ui/src/components/Button.tsx
packages/ui/src/components/PersonalInviteButton.tsx
packages/ui/src/components/PersonalInviteSheet.tsx

Another totally extra and non-blocking cosmetic PR. :)
- Fixes an issue with hero Buttons where we weren't properly setting icon colors (was returning a hex from button context, not a Tamagui token)
- Does away with the size computation for Button.Icon for simplicity's sake. The Button.Icon component was only used in one other place and it doesn't make a functional difference to have it be its natural size.
- Makes the PersonalInviteButton match InviteFriendsToTlonButton in appearance, but with a hero treatment
- Better aligns the content of PersonalInviteSheet

PersonalInviteSheet cosmetics

---

packages/app/lib/bootHelpers.ts
packages/shared/src/logic/branch.ts
packages/shared/src/logic/deeplinks.ts
packages/shared/src/store/inviteActions.ts
packages/ui/src/components/Onboarding/OnboardingInvite.tsx

If something went wrong creating your link on the invite service/branch, but it went through on the provider, the initial attempt to verify your link would fail but subsequent attempts would succeed. We should never show the invite link unless we positively have it in both places.
This adds extra handling to enforce that invariant.

Personal Invite Link Fix

---

apps/tlon-mobile/src/components/AuthenticatedApp.tsx
packages/app/hooks/useConfigureUrbitClient.ts
packages/app/hooks/usePosthog.base.tsx
packages/app/hooks/usePosthog.native.ts
packages/app/hooks/usePosthog.ts
packages/shared/src/api/urbit.ts
packages/ui/src/components/ChatOptionsSheet.tsx
packages/ui/src/components/EditProfileScreenView.tsx
packages/ui/src/components/PersonalInviteButton.tsx
packages/ui/src/components/PersonalInviteSheet.tsx

This pr cleans up a few existing warnings:
- QRCode prop warning: happened because cached invite link was null before being loaded, which the QR component doesn't like. Fixed by waiting to render until we have a valid invite link.
- ` useFindSuggestedContacts` warning: happened because this hook would sometimes run before the urbit client was ready. Fixed by moving client initialization logic to an outer component (also had to do some deps cleanup as part of this, including memoizing the `usePosthog` result
- Fixed a few of the easier circular import errors.

clean up warnings

---

apps/tlon-web/src/app.tsx
apps/tlon-web/src/components/MobileAppToast.tsx

old web: add TM app banner

---

apps/tlon-mobile/metro.config.js

This PR fixes an issue introduced in #4309 by modifying metro package import settings. Before this change, importing `zustand/middleware` would grab files which contain `import.meta` references, which apparently is invalid in the react native environment.
Android builds will probably fail until this is merged.

fix android build

---

apps/tlon-web/src/components/MobileAppToast.tsx
apps/tlon-web/src/state/settings.ts

- Replaced local storage usage with settings state to manage the visibility of the mobile app toast.
- Introduced a new property `seenMobileAppToast` in the settings state to track if the toast has been dismissed.
- Updated the toast component to conditionally render based on the loading state and the new settings property.
- Modified the dismiss button to update the settings state instead of local storage.

MobileAppToast: use settings state

---

packages/ui/src/components/BareChatInput/index.tsx

While looking into the message send/draft bugs (which I couldn't repro on develop) I got annoyed with the duplicate code and the overall busy-ness of the code in the component itself, so I decided to clean it up a bit.

clean up bare chat input

---

packages/ui/src/components/AuthorRow.tsx

chat: reduce contact tap target to just author/contact name

---

packages/app/hooks/useGroupContext.ts
packages/shared/src/api/groupsApi.ts
packages/shared/src/db/queries.ts
packages/shared/src/store/groupActions.ts
packages/shared/src/store/sync.ts
packages/ui/src/components/ChannelNavSection.tsx
packages/ui/src/components/GroupChannelsScreenView.tsx
packages/ui/src/components/ManageChannels/ManageChannelsScreenView.tsx

fixes tlon-3340
This refines the manage channels screen to:
- use arrows rather than drag and drop
- match (as closely as we can for now) the new ochre design
- look less weird on desktop
- work reliably
It also:
- hardens the associated `groupActions`
- hardens sync updates
- adds a missing db query
- fixes some deps issues on other queries
- and fixes some UI bugs having to do with actually rendering the channels in the right order (according to the index we have on the backend)
Note:
- For now we've disabled the section moving arrows (I added "Edit" and "Delete" buttons on the section title row, though)
- The "default" section (which we currently call "Sectionless") appears at the bottom of the list since this is actually where it appears in the GroupChannelsScreen. If we wanna change …

refine manage channels screen

---

packages/app/lib/bootHelpers.ts
packages/shared/src/logic/analytics.ts
packages/shared/src/store/lure.ts
packages/ui/src/components/InviteFriendsToTlonButton.tsx

Makes sure we're always getting debug context in PostHog while attempting to generate or show existing invite links. Also adds a warning during signup if the invite is missing relevant metadata.
Fixes TLON-3444

invites: enhanced error and debug reporting during invite creation

---

desk/app/activity.hoon
desk/app/channels-server.hoon
desk/app/channels.hoon
desk/app/grouper.hoon
desk/app/groups.hoon
desk/lib/logs.hoon
desk/sur/logs.hoon
desk/ted/posthog.hoon

The Lure backend infrastructure comprises of three agents: %grouper, %reel and %bait. 
This PR augments %grouper with lure redemption tracing, as described in detail in TLON-3378.
(%logs agent functionality is also extended with a new event type, `%tell`, which carrier an `$echo` message with specified volume: `%info`, `%warn` or `%crit`.)

Enable lure flow logging in %grouper

---

packages/shared/src/store/postActions.ts

We were awaiting `sync.syncChannelMessageDelivery` when we didn't need to, and `syncChannelMessageDelivery` is fairly heavy.

chat: fix issue with delay on sending followup messages

---

packages/shared/src/db/storageItem.ts

We figured out the old library was prefixing values with the key `rawData` whereas the new one stores them without prefix. This caused migrated values to get deserialized incorrectly. Notably, authentication details which would cause a logout on app update.
To address, we wrap the `getValue` logic to handle this situation. Next time `setValue` is called, it will be stored without the prefix.
Should confirm we no longer get logged out on TestFlight after merging.
Fixes TLON-3446

keyVal: handle migration from legacy storage library

---

apps/tlon-mobile/ios/Podfile.lock
packages/shared/src/debug.ts
packages/shared/src/logic/analytics.ts

OTT, something we saw failing Friday that we should probably track to see what was happening.
PR Checklist

debug: make sure we track if log upload fails

---

packages/app/navigation/desktop/TopLevelDrawer.tsx

Saves the home tab nav state when a user navigates to another tab in the TopLevelDrawer and then restores it when the user returns back to home.
fixes TLON-3467

Desktop: save home tab nav state when navigating to another tab

---

packages/shared/src/db/storageItem.ts

Was getting errors from this if the value isn't there. Gotta love JS for making `null` an object...

storage: fix legacy prefix check

---

packages/ui/src/components/ProfileRow.tsx
packages/ui/src/components/ProfileSheet.tsx

noticed this while trying to hunt down the "can't kick user from group" issue.
before:
after:
still looks fine on mobile:

web: fix profile sheet height, avatar issue

---

desk/ted/posthog.hoon

It turns out a personal API key can't be used to capture events into Posthog. This PR sadly restores the previous API key, as it seems to be only way to capture events.

logs: fix broken Posthog API key

---

packages/ui/src/components/ChatMessage/ChatMessage.tsx

The new image config we passed to `ChatContentRenderer` to fix sizing on web breaks mobile (the `auto` height/width collapses them). 
This PR just moves that config to be conditionally passed on Web. This seemed simplest, but if we wanted to avoid switching on platform, we could work on a composite image config that works for both.
Fixes TLON-3502

mobile: Fix images in chat

---

apps/tlon-mobile/src/hooks/useDeepLinkListener.ts
packages/ui/src/components/Onboarding/OnboardingInvite.tsx
packages/ui/src/utils/colorUtils.tsx

Addresses some issues that cropped up:
- Avoid crashing on empty string colors in Invite metadata
- If personal invite link clicked while logged in, route to their  _UserProfile_ 
Fixes TLON-3504

mobile: small fixes

---

packages/shared/src/types/ChannelActions.ts
packages/ui/src/components/BareChatInput/helpers.ts
packages/ui/src/components/BareChatInput/index.tsx
packages/ui/src/components/ChatMessage/ChatMessageActions/MessageActions.tsx
packages/ui/src/components/MessageInput/AttachmentPreviewList.tsx
packages/ui/src/contexts/attachment.tsx

Adds a simple "Reply" action to DMs, just inserts a `> [quoted text]` string (with a carriage return) into the chat input.
Also renames the "Quote" message action to "Reply".
I don't expect we'll keep it like this, this is just a stopgap until we get a *real* reply feature into DMs.
Fixes TLON-3515

DMs: add reply action

---

packages/ui/src/components/UserProfileScreenView.tsx

fixes tlon-3330
not sure if this is everything you were looking for @jamesacklin, lmk

desktop: clean up profile screen

---

packages/ui/src/components/BareChatInput/index.tsx

I caused this in my context menus PR by moving `setControlledText` to the finally block in BareChatInput, which was unnecessary.

input: clear controlled text before awaiting send

---

apps/tlon-mobile/ios/Podfile.lock
apps/tlon-mobile/package.json
apps/tlon-mobile/src/components/OnboardingInputs.tsx
apps/tlon-mobile/src/screens/Onboarding/CheckVerifyScreen.tsx
apps/tlon-mobile/src/screens/Onboarding/GettingNodeReadyScreen.tsx
apps/tlon-mobile/src/screens/Onboarding/RequestPhoneVerifyScreen.tsx
packages/app/hooks/useStoppedNodeSequence.ts
packages/app/lib/bootHelpers.ts
pnpm-lock.yaml

Fixes TLON-3513, OTP display issue needed to be carried over to another component.
Fixes TLON-3522, Phone form was never being marked invalid
Fixes TLON-3521, prevent stopped ship sequence from locking up if navigated back while still mounted
Also fixes a recovery issue I noticed where `hostedNodeId` wasn't getting set if we found an existing ship attached to an account.

Onboarding Fixes

---

apps/tlon-mobile/src/screens/Onboarding/CheckOTPScreen.tsx
apps/tlon-mobile/src/screens/Onboarding/TlonLoginLegacy.tsx
packages/shared/src/api/hostingApi.ts

Instead of displaying raw JSON/hosting error, present a custom message for `401` responses (incorrect/expired code).
Fixes TLON-3524

Onboarding: Custom message for incorrect OTP code

---

apps/tlon-mobile/src/lib/signupContext.tsx
packages/app/hooks/useBootSequence.ts

Not resetting this was causing issues if you tried to signup multiple times in a row. Edge case in the wild, but is a confounding variable during testing.

Onboarding: reset boot sequence after completing signup

---

apps/tlon-mobile/src/screens/Onboarding/CheckOTPScreen.tsx
apps/tlon-mobile/src/screens/Onboarding/TlonLogin.tsx

- The fix from this morning for wrong/expired OTP did not catch cases during signup (apparently we pass a `400` there instead of `401` as with login)
- Were erroneously handling bad email/phone errors on the login screen. Now surfaces a nicely formatted message and doesn't progress.
Fixes TLON-3530

Onboarding: fix more onboarding errors

---

.github/workflows/deploy-canary.yml
.github/workflows/deploy.yml

Github deprecated the version we were using, should be same usage in our case https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

ops: update artifact actions since deprecated

---

apps/tlon-mobile/src/hooks/useDeepLinkListener.ts
apps/tlon-mobile/src/hooks/useOnboardingHelpers.ts
packages/app/contexts/branch.tsx
packages/app/contexts/ship.tsx
packages/shared/src/domain/analytics.ts
packages/shared/src/logic/branch.ts
packages/shared/src/store/hostingActions.ts
packages/ui/src/components/Onboarding/OnboardingInvite.tsx

Fixes TLON-3575  by biting the lure if we're not already a member or invited.
Fixes TLON-3577 by adding better lure metadata extraction fallbacks and being more careful about how the invite preview card displays info.

Invite Fixes

---

desk/app/activity.hoon

Fixes TLON-3574, we were erroneously putting the old volume on the side that gets overridden if there already exists a key so we were just always set back to defaults any time activity reloads.

activity: prevent base volume from being reset

---

packages/app/features/top/ChatDetailsScreen.tsx
packages/app/hooks/useChatSettingsNavigation.ts

OTT
fixes tlon-3582
we're expecting this method to be named `onLeaveGroup`, not `navigateOnLeave`.

chat details: fix missing navigation on leaving a group

---

packages/app/features/top/ChannelScreen.tsx
packages/app/features/top/ChatDetailsScreen.tsx
packages/shared/src/domain/analytics.ts
packages/shared/src/store/groupActions.ts
packages/ui/src/components/Channel/ChannelHeader.tsx
packages/ui/src/components/Channel/index.tsx
packages/ui/src/components/ChatOptionsSheet.tsx
packages/ui/src/components/InviteFriendsToTlonButton.tsx
packages/ui/src/components/ListItem/GroupListItem.tsx
packages/ui/src/components/PersonalInviteButton.tsx

- Put invite option back in _GroupOptionsSheet_
- Make invite people CTA clearer in _ChatDetails_
- Open _ChatDetails_ primary action when clicking channel header (possibly controversial)
- Track an event for on network invites
- Nicer preview + just paste the link from native Share sheet
Fixes TLON-3583

Mobile: Invite UX Pass

---

packages/app/lib/nativeDb.ts

Previously, when a large number of changes was made at once, the update hook would trigger for each row all at once, meaning that all of the updates would attempt to read changes before any of the changes were actually cleared, leading to an exponential change handler explosion. This update ensures that previous changes are cleared before the next change handler attempts to read them. 
Fixes TLON-3430.

debounce update hook

---

packages/ui/src/components/ChatMessage/ChatMessageActions/MessageActions.tsx

fixes tlon-3601
we weren't using the `addAttachment` method to add the quote reply for groupDMs before, just DMs. Now we use it for both.

chat: fix reply in chat actions for group dms

---

packages/editor/src/MessageInputEditor.tsx
packages/ui/src/components/MessageInput/index.native.tsx
packages/ui/src/components/MessageInput/index.tsx

This change ensures that we pass the theme value for the text color (and the background) into the webview so that the colors will match the theme (and removes the use of useIsDark in the editor react app). Also updates the web version of the editor to use the appropriate colors.
Fixes tlon-3536

Notebook editor: fix text color on alternative themes

---

apps/tlon-mobile/tests/00-start.yaml
apps/tlon-mobile/tests/01-self-hosted-login.yaml
apps/tlon-mobile/tests/02-home-tab.yaml
apps/tlon-mobile/tests/03-create-group.yaml

Draft PR for observation/comments on Maestro end-to-end tests for the mobile app. These tests assume you're joined to both Tlon Local and ~rilfun-lidlen/fashion, and have a DM with ~ravmel-ropdyl (and have nicknames turned on).
I'll make these parameters configurable in another pass.
- Created initial test suite to clear state and launch the app.
- Implemented self-hosted login flow in 01-self-hosted-login.yaml, including EULA acceptance and login assertions.
- Developed home tab navigation tests in 02-home-tab.yaml, verifying visibility of groups and messages.
- Added group creation test in 03-create-group.yaml, ensuring proper channel setup and visibility.
To run these tests locally:
1. Install [openjdk21](https://formulae.brew.sh/formula/openjdk@21) if you don't have it on your system …

e2e: initial iOS test flows w/ Maestro

---

packages/shared/src/store/session.ts
packages/shared/src/store/sync.ts

Tweaks to initial sync to improve apparent+actual performance:
- Ensure high priority tasks finish before kicking off lower priority
- Ignore syncing status when deciding what header message to show
- Simplify syncing tracking a bit

initial sync tweaks

---

packages/app/hooks/useBootSequence.ts

We've seen a few accept invite aborts where the backend logs indicate the invites were in fact sent.
This just adds some debug logging for PostHog to help us understand the invite state for cases where we should be able to join, but didn't.

Signup: track debug events during invite acceptance loop

---

packages/shared/src/db/migrations/0000_fluffy_cardiac.sql
packages/shared/src/db/migrations/meta/0000_snapshot.json
packages/shared/src/db/migrations/meta/_journal.json
packages/shared/src/db/migrations/migrations.js
packages/shared/src/db/schema.ts
packages/shared/src/store/sync.ts

This PR ensures that we only perform a full group sync once per session -- if the session is intact, we should get all group updates through subscriptions.
Question: are there any changes that *don't* come through updates that we might miss?

prevent unnecessary full group syncs

---

packages/shared/src/api/groupsApi.ts
packages/shared/src/store/sync.ts

Fixes TLON-3653 we were incorrectly setting privacy by not accounting for the current state of the group's privacy. Cordon shut vs open and secret true/false is a combination to get the actual "privacy" of the group. This takes those into account when hearing about updates.

groups: check groups current privacy before setting

---

packages/ui/src/components/Activity/ActivitySourceContent.tsx

OTT, fixes tlon-3659. Afaict this should have never worked before, since we had zero width.

Activity screen: fix width issue with gallery post items

---

desk/app/groups.hoon

A condition added in https://github.com/tloncorp/tlon-apps/commit/6a172f0eb464123c92bbb18a0df80b58d556d572 to prevent double group joins had broken the private group invite flow. 
The following scenario would result in a group invite being permanently stuck
1.  Alice hosts a private group
2. Bob initiates a join request to the group, creating an entry in gangs that is at `%knocking` progress.
3. A group invite send by Alice would now be mistakenly dropped by Bob.

groups: fix broken private group initiated invite flow

---

packages/ui/src/components/ChatOptionsSheet.tsx

Fixes TLON-3657, recent changes accidentally included the sort channels function wrapped with the sheet close when it needs to stay open to advance to the next pane.

group-options: don't close sheet on sort click

---

.maestro/00-start.yaml
.maestro/10-settings.yaml
.maestro/20-profile.yaml
packages/app/features/top/ContactsScreen.tsx
packages/ui/src/components/EditProfileScreenView.tsx
packages/ui/src/components/FavoriteGroupsDisplay.tsx
packages/ui/src/components/NavBar/NavIcon.tsx
packages/ui/src/components/ProfileScreenView.tsx
packages/ui/src/components/ScreenHeader.tsx

Introduces end-to-end tests for basic profile updates and settings menu navigation.
- Uses the hosted Tlon login sub-flow
- Taps on the lower-right sigil menu
- Taps on the gear icon
- Navigates through all Settings menus and verifies that navigation works
- Edits the profile with a test nickname, status, bio, and avatar (avatar is only on iOS; I'm not sure how the camera roll interaction works on Android and if they share identifiers for Maestro's purposes)
- Sets Tlon Local as a pinned group
- Verifies that the changed profile details display both on the self-view and the top of the Contacts list
- Resets the profile
Makes a few changes to verbiage in system dialogs to avoid two elements with the same text on the screen in cases where we can't use an ID. Also adds a few test ID hooks …

e2e: settings menu, profile editor

---

packages/app/features/top/ChannelScreen.tsx
packages/app/navigation/desktop/HomeNavigator.tsx

fixes tlon-3594
Fixing the crashes is easy (make sure we're never checking for a property on an `undefined` value, basically), but forcing the app to always go back to where you expect it to go when using the browser back button is not, especially in the case of going back to another channel from a different channel. I spent most of my time trying to get that functionality to work, but came up short.
The browser back button seems to work fine when moving from a detail screen back to a channel screen, but switching between screens using the back button doesn't work. You'll always get sent back to the "Home" (ChatList with empty main pane) screen.
I think this has to do with our using `navigation.navigate` rather than `push` (which is necessary since we're in a drawer navigator). I tried …

Desktop: fix channel screen nav crashes

---

packages/ui/src/components/FavoriteGroupsDisplay.tsx

fixes tlon-3578
We were rendering GroupListItem in FavoriteGroupsDisplay. GroupListItem renders ChatOptionsSheet if we don't pass the `disableOptions` prop. We weren't passing that prop, so we were rendering ChatOptionsSheet outside of the ChatOptionsProvider. If we try to render ChatOptionsSheet outside of the provider, the app will crash.
Solution: just pass `disableOptions` to GroupListItem.

Desktop: fix crash on editing profile

---

packages/ui/src/components/Activity/ActivitySourceContent.tsx
packages/ui/src/components/GalleryPost/GalleryPost.tsx

fixes tlon-3672
the issue was the fixed width on the scrollview (my mistake yesterday) and the StyleSheet.AbsoluteFill that had been added to the Pressable in GalleryPost (cc: @davidisaaclee will removing this and replacing it with flex={1} break something? looks fine afaict, but I'm not sure if there was some particular case you had in mind when you added it).

Activity: make sure we render multiple gallery post previews when necessary

---

.maestro/30-contacts.yaml
packages/app/features/top/ContactsScreen.tsx
packages/ui/src/components/ContactBook.tsx

Adds an end-to-end test that:
- Logs in via the Tlon Hosted sub-flow
- Navigates to the Contacts screen
- Adds ~zod to contacts
- Adds a nickname and overrides the avatar
- Confirms the nickname is set
- Removes the contact
- Confirms removing the contact unsets the nickname
- Confirms you can start a DM from a profile

e2e: contacts CRUD

---

packages/ui/src/components/ManageChannels/EditChannelScreenView.tsx

OTT, fixes tlon-3589.
(it would look like Admin was still selected, but we'd actually remove it from the `readers` or `writers` form value).

Roles: don't allow admins to be removed from reader/writer roles

---

desk/app/grouper.hoon

A wrong message was logged upon successful join to a public group. This did not generate alerts, but did generate a bunch of confusing group events in Posthog.
Fixes TLON-3667

grouper: fix incorrect log message

---

packages/ui/src/components/ImageViewerScreenView.tsx

OTT, fixes tlon-3686
Apparently I removed a load bearing `flex={1}` the other day while working on the image viewer for web (the prop didn't do anything on web).

fix image viewer on mobile

---

desk/app/chat.hoon

Enables logging in the %chat agent. Closes TLON-3669.

chat: enable logging

---

packages/ui/src/components/ImageViewerScreenView.tsx

earlier fix for mobile brought back the stretched images issue on web, now we only apply `flex={1}` if we're not on web.

web: fix stretched images in image viewer

---

desk/app/chat.hoon

OTT, the new on-fail logging was getting triggered by blocked ships trying to DM the blocker. Because we didn't handle `/logs` in the `agent` arm, it would crash and produce another poke to `/logs` creating a loop. This just no-ops the ack handling of that poke. I checked all other agents in this desk and they are either handling that already or have a different `on-agent` setup that prevents this from happening.

chat: prevent on fail loop

---

packages/app/hooks/useChannelNavigation.ts

fixes TLON-3663 by sidestepping the weirdness we were seeing with post loading and scroller position by just navigating the user directly to the post rather than the channel containing the post (which is probably what the user wants anyway).

Refs: navigate directly to gallery or notebook posts from refs

---

packages/shared/src/store/useChannelPosts.ts

fixes tlon-3663
The issue stems from our `newPosts` state sticking around after we switch channels. Not clear to me why this never cropped up in the past. Clearing `newPosts` when the channelId changes definitely fixes the issue though.
To test: go to some channel, copy a ref link. Go to another channel, post that ref as a message. Press the ref, taking you back to the first channel. The posts in the first channel should look normal, without any of the posts from the second channel "sticking" around.

useChannelPosts: clear `newPosts` state when switching channels

---

packages/ui/src/components/GroupMembersScreenView.tsx

Does what it says on the tin. Avoids showing join requests and banned ships to rank and file members; keeps these sections visible only to group administrators.

members-list: only show join requests and banned members for admins

---

packages/ui/src/components/ChatMessage/ChatMessageActions/Component.tsx
packages/ui/src/components/GalleryPost/GalleryPost.tsx
packages/ui/src/components/NotebookPost/NotebookPost.tsx

Uses the same pattern we use for chat messages. fixes tlon-3688

desktop: show message actions context menu for gallery and notebook posts

---

packages/ui/src/components/Avatar.tsx

fixes tlon-3377
it turns out the `useStyles` on web transforms numeric height/width values into strings (e.g., `56` becomes `'56px`). This breaks the calculation for the `size` prop that gets passed into UrbitSigil, which expects a number.
Tested on iOS and Android as well to make sure this doesn't break anything over there, it's fine.

desktop: fix issue with weird avatar render in profile editing

---

packages/ui/src/components/Form/inputs.tsx

In my sidebar PR I tried fixing the avatar width on desktop, to do so web needed an explicit height set. Doing so however makes the image huge on mobile. So now we only set it on desktop.

edit-profile: fix mobile image input

---

packages/app/lib/devMenuItems.ts

Recent DB trigger changes updated the method to get the db path to be async. The raw promise was getting piped through to the dev tools, not the string we expected.
Just awaits those calls and Studio opens correctly.

Fix Drizzle Studio

---

packages/app/lib/devMenuItems.ts
packages/shared/src/api/groupsApi.ts
packages/shared/src/db/queries.ts

The issue here was keeping `haveRequestedInvite` in sync on the group model. 
If that flag is set, we'll display the group as an unjoined preview at the top of your list (overrides `currentUserIsMember`). The groups serializer was never modifying that column.  If you 1) had requested an invite and 2) accepted that invite on another client, the field would get "stuck" and would continue to seem unjoined.
Updates the serializer to properly set `haveRequestedInvite` and the insert query to allow overwriting it.
Fixes TLON-3707

Mobile: Prevent groups getting stuck in "requested invite" state

---

apps/tlon-web-new/src/app.tsx
apps/tlon-web-new/src/styles/base.css

I use Safari daily and I was getting annoyed with the default non-matching scrollbar appearance (even in dark mode). Adds a "color-scheme" property so Safari 17+ knows how to style its own chrome. As a nice side-quest, I made the scrollbars respect the user's currently selected theme (looks quite nice in the more colorful themes).
Also makes a very basic visual change to the app's loading screen. I didn't do anything too fancy; just want to communicate that something (anything) is happening.

web-new: themed scrollbars, app loader

---

apps/tlon-mobile/android/app/src/main/java/io/tlon/landscape/api/TalkApi.java
apps/tlon-mobile/android/app/src/main/java/io/tlon/landscape/notifications/TalkNotificationManager.java
apps/tlon-mobile/src/hooks/useNotificationListener.ts
packages/app/lib/notifications.ts

extends #4280 to Android
This work was complicated by our custom Android notification handling code. Notably, we are intercepting notifications before expo-notifications has a chance to handle them, which I think means that we can't rely on expo-notifications' guarantees when receiving events or accessing notifications via JS (this is backed up by missing fields in the expo-notifications JS payloads, as if expo-notifications didn't have a chance to add the expected `trigger` data before JS could consume it).
<details>
<summary>more details about how we're breaking expo-notification's guarantees</summary>
I'm new to Android notifications, but here's my understanding:
- We set up a service that responds to FCM events https://github.com/tloncorp/tlon-apps/blob/686ba3a98abf9008754c23ce350e7df1 …

android: post / dm handoff from push

---

packages/shared/src/http-api/fetch-event-source/fetch.ts

OTT, @pkova and I found this when trying to investigate why we were getting stuck in a "Connecting..." state. Basically we were aborting after initiating a bunch of new requests to resubscribe to things. Aborts trigger an error on the fetch which we don't handle, so we were never hitting the code path where the event source gets reinitiated.

http-api: fix order of disposes so we aren't aborting new valid requests

---

packages/app/ui/components/GroupSelector.tsx

OTT, we were crashing because we were attempting to render the chat options in GroupListItem. Just needed to pass `disableOptions`.
fixes tlon-3727

desktop: fix crash on adding pinned group

---

desk/app/channels.hoon

As of 34014ad the library will let pokes through (without crashing) even if the target's version is unknown. We previously had to explicitly +initiate:negotiate to make sure that pokes wouldn't crash, but that is no longer necessary.

channels: don't strictly need to initiate:negotiate

---

packages/app/features/top/CreateChatSheet.tsx

One-liner that fixes TLON-3713, which @Fang- keeps hitting during his end-to-end testing.
We weren't clearing out the selection between group creation button presses, so adds a simple state-clearing in the handler.
I didn't add a useEffect to clear when the user closes the screen without creating a group, figuring they probably want to retain their selection unless they explicitly clear it.

CreateChatSheet: clear selection on group creation

---

apps/tlon-mobile/package.json
apps/tlon-web-new/package.json
apps/tlon-web-new/src/logic/utils.ts
packages/app/ui/components/ManageChannels/EditSectionNameSheet.tsx
packages/shared/src/urbit/utils.ts
pnpm-lock.yaml

This broke when we merged https://github.com/tloncorp/tlon-apps/pull/4408, because `formatUv` was not expecting the value produced by `BigInt`, apparently. ~Using the old `bigInt` and calling `.toString()` made it happy again.~ We needed to bump to the latest @urbit/aura in tlon-mobile and tlon-web-new.
I also noticed we weren't clearing the form on EditSectionNameSheet before closing it, so I added that in here, too.
fixes tlon-3714

channel manager: fix issue with section creation

---

apps/tlon-web-new/src/app.tsx
packages/shared/src/logic/branch.ts
packages/shared/src/store/inviteActions.ts

fixes tlon-3743
We were running `sync.syncStart` multiple times because we were using `useState` and re-running the useEffect after we'd already started a sync, which would then call `sync.syncStart` again with `alreadySubscribed` set to `true` for no reason.
Replacing the useState-based tracking of our sync with a ref ensures we only run it one time, and we should always run `sync.syncStart` with `false` here since we're not in a discontinuity situation.
I also turned off a few loggers that had been left on in other spots.

desktop: make sure we only run syncStart once

---

.github/workflows/mobile-testing.yml
.maestro/00-start.yaml
.maestro/20-profile.yaml
.maestro/30-contacts.yaml
.maestro/40-create-group.yaml
.maestro/41-customize-group.yaml
.maestro/42-group-info-settings.yaml
.maestro/43-roles.yaml
.maestro/subflows/tlon-login.yaml
apps/tlon-mobile/ios/Podfile.lock
packages/app/features/groups/GroupRolesScreen.tsx
packages/app/features/top/ChatListScreen.tsx
packages/app/ui/components/Channel/ChannelHeader.tsx
packages/app/ui/components/FavoriteGroupsDisplay.tsx
packages/app/ui/components/GroupMembersScreenView.tsx
packages/app/ui/components/GroupSelectorSheet.tsx
packages/app/ui/components/ManageChannels/EditChannelScreenView.tsx
packages/app/ui/components/ManageChannels/ManageChannelsScreenView.tsx
packages/app/ui/components/MessageInput/MessageInputBase.tsx

Adds several tests for the creation and customization of groups.
- Tap on the "+" button
- Assert that the creation sheet pops
- Assert that the contacts sheet pops
- Create the group
- Navigate back to Home and assert that the group is created
- Open the Customize group screen from the empty "General" channel
- Change the group name and confirm on the Home screen
- Change the group icon/picture (iOS only)
- Change the group description
- Open the overflow menu from the channel header
- Pin and unpin the group, checking on the Home screen for position
- Copy group reference
- Set group privacy
- Edit the Admin role
- Create a role
- Create a channel
- Move channels up and down
- Rename a channel
- Create a channel section (currently failing due to TLON-3714)
- Set the notification volume …

maestro: add mobile UI test flows for group creation, customization

---

apps/tlon-web-new/src/main.tsx
packages/app/navigation/utils.ts
packages/ui/src/contexts/globalSearch.tsx

Fixes TLON-3744. We weren't always taking into account `lastOpenTab` and also we weren't handling navigations from Activity very well.

nav: fix nav'ing from activity on desktop

---

packages/app/navigation/utils.ts

I noticed leap was broken, the cause was because we were not handling the "root" navigator very well. This fixes that by checking for root and replaces the error with a return of `lastOpenTab` so we CYA in case some weird nav case isn't handled.

nav-utils: better behavior if at root

---

packages/app/ui/components/ChatMessage/ChatMessageReplySummary.tsx

We were using a combination of checking volume settings and the actual `notify` flag on the activity summary. However, that flag already takes settings into account. So we were getting some situations where the client thought thread was "muted" but in reality it was trying to notify.
Should see blue dots more often now in the correct places.

reply-summary: simpler more reliable notify tracking

---

desk/app/groups.hoon

We may in some (hosting) circumstances want to bind the `/` catch-all binding to something we control, so that we can redirect root (and other unhandled pages) back into the groups web app.
Here we make the groups agent handle http requests by redirecting to `/apps/groups/`, setting us up for `|pass [%e %connect [~ /] %groups]` or some equivalent.
This goes into `release-410` because the same is true for tloncorp/landscape#313, which this soft-depends on. The kelvin is a nice boundary for solidifying that relation.
Someone sign off on the trailing `/` on the redirect path for me please.

groups: handle http requests, if we ever get bound

---

apps/tlon-mobile/ios/Podfile.lock
apps/tlon-mobile/package.json
apps/tlon-mobile/src/App.main.tsx
packages/app/hooks/useConfigureUrbitClient.ts
packages/app/lib/backgroundSync.ts
pnpm-lock.yaml

Fixes TLON-3628
Adds a background task which periodically performs an initial sync (i.e. `startSync(true)`).
- When does this task run?
- Android: Runs every 10 minutes; does not run if app has been force-quit or if the app hasn't been opened since last system boot
- iOS: Runs as often as possible, subject to OS's fuzzy scheduling – supposedly every 10-15 minutes. Does not run if app has been force-quit.
- What gets synced?
- Everything we sync on initial sync – which might be too much, but for me, this sync was very fast. On iOS, if sync takes more than 30 seconds, the background task will be killed (and will likely be invoked less often in the future).
- Is this hard on the battery?
- This is hard to tell – I tried checking expo-battery's `Battery.getBatteryLevelAsync` before and after …

native: add periodic background sync

---

packages/app/lib/backgroundSync.ts

We want to use the default value for `minimumInterval`; and since this is such an important parameter for UX, I want to make sure our usage is explicit, so I set `minimumInterval: undefined` to call out that we're using the default value. 
Instead of omitting an `undefined` entry when converting to native code, expo-background-fetch converts this to `"<null>"`, which breaks the native module.
(This change was made in my previous local branch but not included in the final set of commits – double-checked my stash, I didn't see any other omissions.)
context: /1/chan/chat/~bitpyx-dildus/interface/msg/170141184507263636203902727312912678912

native: omit param instead of passing `undefined`

---

.maestro/00-start.yaml
.maestro/40-create-group.yaml
.maestro/50-chat.yaml
.maestro/51-threads.yaml
packages/app/ui/components/ChatMessage/ChatMessageActions/EmojiToolbar.tsx
packages/app/ui/components/ChatMessage/ReactionsDisplay.tsx

Introduces a new test that:
- Creates a new group
- Inserts some text into the General channel and sends it
- Navigates back to the Home screen and asserts that the message preview is visible
- Navigates back into the group
- Long-presses the message and starts a thread
- Sends a message in the thread
- Navigates back to the channel root and asserts that the UI shows 1 reply
- Long-presses the message and reacts with a thumbs-up
- Asserts that a thumbs-up reaction appears below the message
- Taps on the reaction and asserts that it is removed
- Long-presses the message and starts a quote-reply with a reference
- Asserts that the quote-reply is sent
- Sends a message, long-presses on it, hides the message, and asserts that the message is hidden
- Sends a message, long-presses on it, …

e2e: chat channels

---

apps/tlon-mobile/ios/Podfile.lock
packages/app/ui/components/ChatOptionsSheet.tsx
packages/app/ui/components/GroupPreviewSheet.tsx

Fixes TLON-3179 for cases where the join in progress actually errors (stuck private requests were fixed with tloncorp/tlon-apps#4472). I was tempted to refactor the way we track status here because we're juggling a lot of booleans, but decided to push it off for a little longer, although I still think we should change it sooner than later.

groups: make sure we can cancel an errored join

---

packages/app/ui/components/MessageInput/index.tsx

fixes tlon-3766
The issue wasn't just links, we weren't getting any applied formatting from tiptap into our AST. The single call to `editor.getJSON` in the component (and then using the `json` variable throughout) was causing this. If we create the `json` variable everywhere we need it, instead, it works fine.
Also simplified the editor empty state detection.
This issue also effected notebooks on desktop, btw

desktop: fix issue with gallery text formatting not applying

---

packages/app/features/groups/GroupMetaScreen.tsx
packages/app/features/top/ChatDetailsScreen.tsx
packages/app/navigation/desktop/HomeNavigator.tsx

fixes tlon-3769
Now:
- If we navigate to `ChatDetails` (group settings) on desktop we'll also render the group channels list in the sidebar.
- If we press the back button (on desktop) while we're in ChatDetails, and we're in the details for a group, we'll just navigate to the group.
- If we edit the group meta and press save, we'll be navigated back to ChatDetails rather than back to the group.

chat details: fix navigation issues

---

packages/app/ui/components/GalleryPost/GalleryPost.tsx

fixes tlon-3764
fixes tlon-3767
We weren't disabling the onPress for the Pressable when the popover was open. Any selection in the menu would cause the user to be navigated to the post detail view.

desktop: prevent navigating to post on menu press in galleries

---

packages/app/ui/components/ChatMessage/ReactionsDisplay.tsx
packages/app/ui/utils/postUtils.tsx
packages/shared/src/db/queries.ts

fixes tlon-3745
we were just using the bare contactIds before because we weren't including contact data with the reactions subquery. this updates the query def for `getPosts` to pull contact data with reactions, and updates the ReactionsDisplay and component and related types appropriately.

desktop: show contact nicknames in emoji hover tooltip

---

.github/workflows/deploy-canary.yml
.github/workflows/deploy.yml

I noticed new desktop never resolved generating an invite link even though we get a response from reel. Turns out we didn't have the env vars, so I added those in here.

ops: make sure we have env vars

---

desk/app/activity.hoon

We noticed this was making reloading activity take really long. This really doesn't need to be run on every load just between state 7 and 8.

activity: only run fix once

---

desk/app/diary.hoon
desk/app/heap.hoon

OTT, while were debugging found that these are doing a lot of things that simply aren't necessary anymore. This just removes those and no-ops.

heap/diary: removing unnecessary operations on deprecated agents

---

packages/app/features/top/ChannelScreen.tsx
packages/app/features/top/ChatListScreen.tsx
packages/app/features/top/GroupChannelsScreen.tsx
packages/shared/src/domain/analytics.ts
packages/shared/src/logic/utils.ts
packages/shared/src/store/channelActions.ts
packages/shared/src/store/groupActions.ts
packages/shared/src/store/postActions.ts

OTT
Fixes a few limitations that cropped up while analyzing remote telemetry. Also fixes a bug where we were never calling an intended `ChannelScreen` focus effect.

Telemetry: Fix model capture & log chatlist taps

---

packages/app/ui/components/Embed/EmbedWebView.tsx

This wasn't causing an issue on every tweet, and it didn't seem to cause an issue at all on iOS, but it was causing an issue where many tweet embeds would reload continuously on Android. I initially added it in the first iteration of embeds to force the component to remount when we got a height update (and originally it was a key on the WebView itself), but in my testing today it looks like it's unnecessary and just giving us trouble.

embeds: remove key on parent view that was causing re-renders

---

packages/app/features/chat-list/ChatList.tsx

The triple dot icon was overlapping the invite bubble and really didn't make sense to have in the first place. This disables options on pending items.

chat-list: don't show options on invites

---

desk/app/groups.hoon

A %kick on a subscription to a group that had been deleted would crash. This caused a problem in conjunction with the use of lib-negotiate: during first load, the library sends a %kick on every subscription in order to force protocol negotiation. If a subscription was not properly cleaned-up by the agent, the %kick will trigger a crash, interrupting the update.

groups: ignore %kicks for deleted groups

---

packages/app/ui/components/GroupMembersScreenView.tsx

On desktop navigating to the group members screen crashes the app completely. Meanwhile on mobile it somehow doesn't crash, but doesn't show anything that was gated by `currentUserIsAdmin` because it defaults it to false? (I guess idk). Fixes issue about banning failure reported on spreadsheet.

group-members: crashes on desktop, shows incorrectly on mobile

---

packages/app/ui/components/Embed/EmbedWebView.tsx

fixes tlon-3778 by:
- replacing multiple useState hooks with one useReducer for atomic state updates
- eliminating the unnecessary debounced height setter, replaced with direct dispatch calls
- reducing handler dependencies by using refs
- making onLayoutHandler dependency free via refs
- memoizing everything
This should fix the cascading state updates that were causing the re-renders/visual flicker we were seeing in threads (and when loading a chat channel where a tweet was near the bottom of a chat, or the gallery details view).

embeds: webview rerender jihad

---

packages/app/ui/components/Embed/EmbedWebView.web.tsx

we need to add a directive that allows the iframe to open new tabs/windows outside of the iframe context (on web, obv).
https://issues.chromium.org/issues/40275209
h/t to jackson for finding this.

embeds: fix issue with opening embed links on web

---

packages/app/ui/components/GalleryPost/GalleryPost.tsx
packages/app/ui/components/PostScreenView.tsx

Fixes TLON-3791 by adding tap-to-lightbox functionality in the Gallery detail view.
- First and foremost, adds navigation to ImageViewer when an image is pressed
- Memoizes image detection so we can be sure to have the src in hand at all times
- Add fallback image press handling if the navigation fails
- Plenty of logging
In action, with swiping:
https://github.com/user-attachments/assets/4d98e1b1-da3c-4f11-ba4d-4dc50c48b538

GalleryPostDetailView: image tap navigation to lightbox

---

packages/app/features/groups/GroupMetaScreen.tsx
packages/app/hooks/useChatSettingsNavigation.ts
packages/app/navigation/types.ts
packages/app/ui/components/Channel/EmptyChannelNotice.tsx
packages/app/ui/contexts/chatOptions.tsx

Fixes TLON-3794. Updates the GroupSettingsStackParamList type to include an optional fromBlankChannel parameter in the GroupMeta route. GroupMetaScreen now checks for this parameter and handles the navigation differently.
Also updates the useChatSettingsNavigation and ChatOptionsContext to accept the fromBlankChannel parameter. Finally, changes EmptyChannelNotice to pass true when the user taps the Customize button.
Therefore, when a user taps the "Customize" button in a new, blank channel:
1. We'll pass fromBlankChannel=true through the navigation stack
2. When they press "Save", the GroupMetaScreen will detect that fromBlankChannel is true
3. It will go back to the previous screen (the blank channel) instead of navigating to the group settings screen
Desktop behavior is unchanged.

groups: Add support for blank channel group metadata navigation

---

packages/app/ui/components/Embed/EmbedContent.tsx

Our fallback links were rendering with tiny text. This didn't matter when twitter was working, but now we're seeing twitter return failing SSL certs (they seem to be having trouble), so we're seeing the fallback links a lot.

embeds: use ContentRenderer to render fallback links in EmbedContent

---

desk/lib/negotiate.hoon

During the library's +on-load handling, it may simulate %kick events by injecting them directly into the inner agent. This means parts of the inner agent other than +on-load may be getting called during agent loading. This is risky, because scries are brittle during loading scenarios: other agents might not have been brought back up yet, etc.
Here we leave a warning so that we don't forget about this detail.

negotiate: make note of simulated %kick danger

---

packages/app/ui/utils/channelUtils.tsx

Fixes TLON-3799 by returning display name from getChannelMemberName in cases where the user has disabled user-set nicknames, rather than the entire object.
End result:

channelUtils: return actual userID from getChannelMemberName

---

packages/app/ui/components/Channel/Scroller.tsx
packages/app/ui/components/Channel/index.tsx

We weren't accounting for the fact that we're rendering in a stack which means if we load a channel once and then navigate to a different one, that original channel render is still in memory. When we come back to it, the `hasLoaded` flag is still true, so we don't actually mark read. This adds a flag for `isFocused` so we know if this channel comes to focus and can mark read appropriately.

channel: fix mark read on desktop

---

package.json

Seems like Expo builds are failing because some of the new Electron deps expect Node 20+. 
After bumping the `package.json` engine, re-installing and building locally still works fine.

ops: bump node engine

---

apps/tlon-desktop/electron-store-wrapper.cjs
apps/tlon-desktop/src/main/sqlite-service.ts
packages/app/lib/electronDb.ts
packages/shared/src/db/changeListener.ts

We were unable to insert rows into the `activity` table on desktop because better-sqlite3 enforces foreign key constraints by default (our other sqlite implementations don't) and we use a composite primary key in `activity` that we don't properly reference in `activity_events_contact_group_pins`.
Simplest solution here is just to match the other sqlite implementations (this is the default for sqlite in general) and disable the strict fk enforcement.
This PR also fixes an issue with changes not making it into the `handleChange` function on desktop (we were trying to parse a string that was actually already JSON into JSON) and removes some debug logging from the electron-store-wrapper that I had put in earlier.
More on the foreign keys: https://www.sqlite.org/pragma.html#pragma_foreign_keys

electron: fix activity foreign key constraint issue

---

apps/tlon-mobile/ios/Podfile.lock
packages/app/ui/components/Activity/ActivityScreenView.tsx
packages/shared/src/api/settingsApi.ts
packages/shared/src/db/migrations/0000_sour_wonder_man.sql
packages/shared/src/db/migrations/meta/0000_snapshot.json
packages/shared/src/db/migrations/meta/_journal.json
packages/shared/src/db/migrations/migrations.js
packages/shared/src/db/schema.ts
packages/shared/src/store/activityActions.ts
packages/shared/src/store/dbHooks.ts
packages/shared/src/urbit/settings.ts

OTT
Uses settings store to persist your Activity seen marker. Clients pull this down instead of storing a local one.
To test, try running new web and mobile simulator locally. Try navigating to activity on one and see the bell clear on the other.
Fixes TLON-3687

Activity: Sync bell across clients

---

packages/app/lib/electronDb.ts
packages/app/lib/nativeDb.ts
packages/shared/src/db/keyValue.ts

The prod build last night included a DB migration to save the new activity read marker setting. This uncovered a bug with our latest posts logic — when the migration wipes all SQL data, the keyval store keeps its existing `headsSyncedAt` timestamp. This means `syncLatestPost` thinks it already has messages that it doesn't.
To fix, we'll now clear out that key anytime we purge the DB. I tried upgrading from an older version to confirm it works, but wanted to double check with y'all if purge is always called in these migration scenarios?
Another thought I had: if we have more of these sync optimization flags, it might be worth considering an optional `persistAfterMigration` storage item flag (analogous to `persistAfterLogout`).

Fix missing latest posts

---

packages/shared/src/db/queries.ts

This fixes TLON-3823 by making sure inserting settings doesn't override other values when giving a partial set.

desktop: messages filter should stay consistent until changed

---

packages/app/lib/envVars.native.ts
packages/app/lib/envVars.ts
packages/shared/src/api/urbit.ts
packages/shared/src/domain/constants.ts
packages/shared/src/domain/hosting.ts

When checking hosted upload eligibility, we confirm the ship's URL is Tlon controlled. This check was failing on web because the http client's url property is not explicitly set. This updates the method to fall back to window location or env configuration during development.
Fixes TLON-3246

Web: Fix hosted uploads

---

packages/app/features/settings/BlockedUsersScreen.tsx
packages/app/features/top/ContactsScreen.tsx
packages/app/features/top/MessagesFilterMenu.tsx
packages/app/features/top/UserProfileScreen.tsx
packages/app/hooks/useCalmSettings.ts
packages/app/hooks/useFilteredChats.ts
packages/app/provider/AppDataProvider.tsx
packages/shared/src/api/settingsApi.ts
packages/shared/src/db/queries.ts
packages/shared/src/db/schema.ts
packages/shared/src/store/activityActions.ts
packages/shared/src/store/dbHooks.ts
packages/shared/src/store/settingsActions.ts
packages/shared/src/store/sync.ts

The release candidate is crashing on logout. The issue is a race condition with clearing the current user ID before all listeners for the settings table are unmounted.  Current user ID is the primary key for the settings table, but we don't actually store other user's settings (table only ever has the singleton row).
To fix this I changed the primary key for the settings table to a static string. I also updated the query methods to assume you always want to read/write that singleton without needing to manually pass in a row ID.
Fixes TLON-3832

Settings Table Refactor

---

packages/app/navigation/desktop/HomeNavigator.tsx
packages/app/navigation/desktop/MessagesNavigator.tsx
packages/app/ui/components/ImageViewerScreenView.tsx

Fixes TLON-3801 by using a modal to pop the lightbox. This does hide the top level drawer but I figured that was ok. I also removed some cases where images weren't centered or were distorted.

image-viewer: modal to avoid shrinking drawers

---

packages/app/ui/contexts/chatOptions.tsx

The leave operation for DMs was properly unsubscribing from the channel but not navigating away from the screen, leaving the user on a blank, inescapable screen that required a force-quit. This adds the same navigation for when a user leaves a group, thereby fixes TLON-3752.

ChatOptions: navigate home when leaving a DM from within

---

packages/app/ui/components/PostScreenView.tsx
packages/shared/src/api/postsApi.ts
packages/shared/src/store/sync.ts

Fixes TLON-3842, we were using the wrong ID for author here.

threads: use correct authorId

---

packages/app/ui/components/Channel/Scroller.tsx

fixes tlon-3779
we were inserting `<PostBlockSeparator/>` unnecessarily after gallery posts, which shoves an empty View of a defined height after a post or set of posts. Inserting that component makes sense in chat, but not in galleries or notebooks.

gallery: fix issue with shorter gallery posts in index

---

packages/app/ui/components/ChatOptionsSheet.tsx

fixes tlon-3850
This one is super weird. It only shows up in the deployed app (can't repro when running in dev locally, or by building and serving locally), and it only started showing up recently. None of the relevant components have changed recently, afaict.
This *might* fix it, but I suspect something weirder is going on.

chat options menu: set explicit background on popover

---

packages/app/ui/components/Channel/ReadOnlyNotice.tsx
packages/app/ui/components/Channel/index.tsx

Does what it says on the tin. Displays a notice in the root of channels that you can't write to.

channel: display read-only notice if canWrite is false

---

packages/app/ui/components/Embed/EmbedWebView.tsx

fixes tlon-3852 by:
- marking an embed as `loaded` when we mark `hideTweetMedia` as true.
- setting the webview container height to zero while we're still in the `isLoading` state so that we don't render both the webview and the loading UI at the same time.
also added some more logging.

embeds: fix issue with tall tweets not loading, and weird loading height issue

---

packages/app/ui/components/ChatOptionsSheet.tsx

fixes tlon-3850 (finally)
missed a spot when removing the animation props earlier

chat options menu: remove animation prop from popover (again)

---

packages/app/ui/components/Channel/BaubleHeader.tsx
packages/app/ui/components/Channel/ChannelHeader.tsx

When the user in a channel and their long-press actions are disabled, it's not clear what's going on. Since the channel header looks black, things seem fine. When they navigate to the home screen, I can see that the app is 'Connecting…'.
This surfaces the connecting / init / disconnected state in the channel header. If the state is fully connected, we show the channel title and/or the "Loading..." indicator.
Fixes TLON-3662

ChannelHeader: reflect connection state

---

packages/app/ui/components/GalleryPost/GalleryPost.tsx
packages/app/ui/components/NotebookPost/NotebookPost.tsx
packages/app/ui/contexts/componentsKits.tsx

fixes tlon-3836
Fixes the original issue by making sure we pass `onPressEdit` to the `onEditProp` in ChatMessageActions in GalleryPost.
Also does the same thing for notebooks.
While working on this, I noticed that pressing any menu item in the popover for a notebook post in a notebook channel would redirect the user to the detail view for the post. We weren't disabling the onPress on the Pressable in NotebookPost when the popover was open. This also fixes that.
Also cleans up the props on NotebookPost.

desktop: fix context menu issues in gallery and notebook

---

apps/tlon-mobile/ios/Podfile.lock
packages/app/features/top/CreateChatSheet.tsx
packages/app/hooks/useGroupSearch.ts
packages/app/ui/components/ChatMessage/ChatMessageActions/Component.tsx
packages/app/ui/components/GroupPreviewSheet.tsx
packages/shared/src/api/apiUtils.ts
packages/shared/src/logic/utils.ts
packages/shared/src/store/dbHooks.ts

fixes tlon-3849
Adds a new option to the CreateChatSheet that allows the user to "Join a group by code" (thoughts on copy here?). The user can paste either a reference string (`/1/group/~zod/some-group`) or a flag (`~zod/some-group`). If it's valid, they can press "Go" on the text input and we'll fetch the group details and display the GroupPreviewPane (where they can join/request to join the group).
Works on both desktop and mobile. 
I created a new hook called `useGroupSearch` in case we want to add this functionality elsewhere, later on down the line.

Add ability to join group by flag

---

desk/app/lanyard.hoon
desk/app/verifier.hoon
desk/sur/verifier.hoon

Copies over the 410 $feed:jael type into our sur file, because we scry for it in (due to operational weakness) environments in either 411 _or_ 410. This types hould be compatible with both.
We pluck suss out the $seed from the result we receive and operate on it as normal.
We should do a proper 410-only patch here once the situation around that scry endpoint in 410 solidifies.

verifier, lanyard: compat with 410 jael vile scry

---

apps/tlon-web-new/src/app.tsx
packages/shared/src/store/cachedData.ts
packages/shared/src/store/cachedData.web.ts
packages/shared/src/store/sync.ts

It seems the main driver of laggy startup time is waiting for all of `syncStart` to complete. Limiting the UI blocking to high priority sync seemed to alleviate a decent portion of the wait.
The one low priority request we have right now that's required to display the root ChatList view is `syncContacts`. Bumping it up to high priority still nets most of the savings without initially flashing empty contact info in the list.
Going a step further, it also occurred to me that `syncContacts` results are more cacheable than `syncInit` and `syncLatestPosts` — generally you won't have new contacts or contacts with updated avatars/nicknames between webapp opens. I added a basic mechanism to store contacts outside the DB on sync and try loading them from cache during `syncStart`. On web, if we get …

Web: optimize startup time

---

packages/app/features/chat-list/ChatList.tsx
packages/app/ui/components/ContactsScreenView.tsx
packages/app/ui/components/ListItem/ChannelListItem.tsx

Does what it says on the tin. Darker shade for selected, slightly lighter shade for hover.

desktop: proper shades for active/hover states in sidebars

---

apps/tlon-mobile/src/components/AuthenticatedApp.tsx

We added a performance optimization to `syncLatestPosts` that tries to only grab new ones you don't already have. This can be an issue when the DB resets since the `headsSyncedAt` marker is stored separately.
To account for this scenario, we manually reset the marker anytime the DB is purged. However it seems this doesn't cover all cases since we're getting reports of missing posts after app updates where that logic should have been triggered.
Let's make sure this can never happen by always doing a full `syncLatestPosts` whenever the app is first opened (not returning from background). This should make sure we never get partial results after app update or force close while continuing to use the lighter optimized sync most of the time. 
Perf wise, until recently we were _always_ doing a …

latest posts: always do a full sync when the app is freshly opened

---

apps/tlon-mobile/src/screens/Onboarding/WelcomeScreen.tsx
packages/app/ui/components/ImageViewerScreenView.tsx

Fixes TLON-3870 by calling the correct close method. Also avoids open state thrashing by waiting to pop the sheet until reading the real storage value.
Fixes TLON-3875 by only rendering the `Modal` on web. More carefully managing the `Modal` state also worked, but since it's only present to escape the web drawer navigators, I think it's better to avoid using it here on mobile whatsoever.

fix: modal issues

---

apps/tlon-mobile/eas.json
apps/tlon-mobile/src/screens/Onboarding/SignupScreen.tsx
packages/app/ui/components/AttestationPane.tsx
packages/app/ui/components/EditProfile/EditAttestationsDisplay.tsx
packages/app/ui/components/PhoneAttestationPane.tsx
packages/shared/src/domain/attestations.ts

- Fix the issue where phone number can not be submitted multiple times during signup
- Ensure client always sends `E.164` encoded phone numbers to lanyard (cc @Fang- ) and in turn, runs pretty display processing before displaying values read from lanyard
- Explicitly sets `eas` build image for iOS to fix the warning email. 
- Note: this should get resolved automatically before the deadline by the Expo Team, but configuring manually for now should remove the warning

Mobile: bundle of fixes

---

packages/shared/src/api/channelsApi.ts
packages/shared/src/store/sync.ts

This reverts commit b15b1ab0fd1b3f3b987a25b2f18359cdb9b6757f introduced in #4581. This broke live-updating reactions in chat and gallery channels.

Revert "api/store: update reaction handlers"

---

packages/shared/src/logic/utils.ts

OTT, our regex wasn't working for some outputs of `formatUv`. This side steps that with simpler operations that should work every time.
Fixes TLON-3882

utils: fix getrandomid

---

packages/app/ui/components/ContentReference/ContentReference.tsx
packages/app/ui/components/PostContent/BlockRenderer.tsx
packages/app/ui/components/PostContent/ContentRenderer.tsx

fixes tlon-3872
This adds a new, simple context: `IsInsideReferenceContext`. We can use this context to conditionally change the way we render some content in refs. For now, we just show smaller images in refs and we return null for refs-in-refs.
Removes the need for the `renderReferences?` prop in PostContentRenderer.

refs: render smaller images in refs

---

packages/app/fixtures/ActionSheet/AttachmentSheet.fixture.tsx
packages/app/ui/components/AddGalleryPost.tsx
packages/app/ui/components/AttachmentSheet.tsx
packages/app/ui/components/BigInput.native.tsx
packages/app/ui/components/BigInput.tsx
packages/app/ui/components/EditableProfileImages.tsx
packages/app/ui/components/Form/inputs.tsx
packages/app/ui/components/MessageInput/AttachmentButton.native.tsx
packages/app/ui/components/MessageInput/AttachmentButton.tsx
packages/app/ui/components/MessageInput/AttachmentPreviewList.tsx

fixes tlon-3664 by eagerly showing a loading indicator and closing the attachment sheet as soon as the image picker or camera are launched. The hang that users were experiencing had to do with:
1) the sheet staying open until the launcher method returned a promise
2) the attachment preview list not showing any loading indicator (user only saw a gray box when we had the actual attachment ready, and that was just until the image rendered in).
Also, cleans up our use of the `attachAssets` method throughout the app. Rather than passing it in as a prop to AttachmentSheet, we just pull it out of the context there. Components that need to process the attached images can use the `onAttach` prop.

attachments: improve UX while image is being resized and uploaded

---

desk/app/groups.hoon

Classic +roll mistake of accumulating the context core, but then pulling an arm from the context instead of the accumulator, which only ever pulls the arm in the context that exists when the gate gets _created_, not when it gets _called_.
Inspired by ames bug discussion in core blitz, I decided to sanity-check all the `+roll` calls in our codebase. This is the only problem I found.
(I must note for the record that I haven't tested this change in any way yet beyond compiling it, but I guarantee you, dear reviewer, that you'll "oh, yeah" when seeing the change.)
Since we don't really use `/epic` subscriptions anymore, and this code was intending to clean the mup, this isn't a huge deal. I do notice though that we no-op on all `/epic` `+on-agent` calls. Feels to me like, if we intend to …

groups: correctly accumulate /epic %leave cards

---

apps/tlon-mobile/src/hooks/useNotificationListener.ts
apps/tlon-mobile/src/screens/Onboarding/CheckOTPScreen.tsx
apps/tlon-mobile/src/screens/Onboarding/CheckVerifyScreen.tsx
apps/tlon-mobile/src/screens/Onboarding/InventoryCheckScreen.tsx
apps/tlon-mobile/src/screens/Onboarding/JoinWaitListScreen.tsx
apps/tlon-mobile/src/screens/Onboarding/PasteInviteLinkScreen.tsx
apps/tlon-mobile/src/screens/Onboarding/RequestPhoneVerifyScreen.tsx
apps/tlon-mobile/src/screens/Onboarding/ResetPasswordScreen.tsx
apps/tlon-mobile/src/screens/Onboarding/SetNicknameScreen.tsx
apps/tlon-web-new/package.json
apps/tlon-web-new/src/app.tsx
apps/tlon-web-new/src/logic/analytics.ts
apps/tlon-web-new/src/main.tsx
apps/tlon-web-new/tsconfig.json
packages/app/features/top/CreateChatSheet.tsx
packages/app/hooks/usePosthog.ts
packages/app/hooks/useTelemetry.ts
packages/app/lib/envVars.ts
packages/app/lib/notifications.ts
packages/app/package.json
packages/app/tsconfig.json
packages/app/types/telemetry.ts
packages/app/utils/posthog.web.ts
packages/shared/src/debug.ts
packages/shared/src/domain/analytics.ts
packages/shared/src/store/sync.ts
pnpm-lock.yaml

We weren't capturing app events in PostHog from new web, only a few particular events were making it through. 
Updates `posthog-js`, initializes it with our dev loggers, and uses our shared telemetry library for identification and mandatory events.
Also rips off the bandaid with old style `trackEvent` calls.

web: working telemetry

---

packages/app/features/top/CreateChatSheet.tsx

fixes tlon-3886
We were just showing the loading spinner forever in the case of not finding a group or the the subscribeOnce call timing out. For now, we jut show "Group not found" in either case.
Also, we now close the sheet upon successful group join (issue @Fang- saw).

join group sheet: show "no group found" when we fail to find a group, close the sheet on successful join

---

packages/app/features/top/CreateChatSheet.tsx
packages/app/ui/components/ActionSheet.tsx
packages/app/ui/components/ContactBook.tsx
packages/app/ui/components/SearchBar.tsx
packages/app/ui/hooks/contactSorters.ts

OTT
Moves the main interaction into a centered modal with a close button. Height stays fixed even as search results change.
After:
I did remove the built in `Scroller` wrapper for `ActionSheet mode=dialog` because it was collapsing the main content height. Tried to make sure there were no regressions, but let me know if y'all have concerns.

desktop: Create DM/Group modal fixes

---

packages/app/features/settings/AppInfoScreen.tsx
packages/app/hooks/usePosthog.base.tsx
packages/app/hooks/usePosthog.native.ts
packages/app/hooks/usePosthog.ts
packages/app/hooks/useTelemetry.ts
packages/app/navigation/utils.ts
packages/app/types/telemetry.ts
packages/shared/src/db/keyValue.ts

On new web, we're seeing hosted users initialized with Telemetry disabled. I think this is because previous iterations of the web build were hardcoded to unconditionally disable telemetry (PostHog opt out) and we were cueing off that setting when identifying.
This adds a one time forced telemetry reset for new web. Continues to only enable it by default for hosted users.

web: telemetry fix

---

packages/app/lib/envVars.ts

Our branch domain/key were not getting set. Our build action supplies `VITE_BRANCH_KEY_PROD` and `VITE_BRANCH_KEY_TEST` but the web client wasn't coalescing these like it does on native. This issues was masked by the fact that other parts of the invite system use links provided by the invite service which worked despite the mixup.
Just updates the web config to always pull from VITE_BRANCH_KEY_PROD and default to the correct domain.

web: fix branch env

---

apps/tlon-web-new/src/main.tsx
packages/shared/src/api/urbit.ts

This is too noisy to be useful right now. Until we're seeing these infrequently, I don't think it's worth capturing every single one.
Ditto for connection errors which happen consistently and provide no useful diagnostic info

web telemetry: don't track console errors

---

packages/app/ui/components/BareChatInput/index.tsx
packages/app/ui/components/MessageInput/MessageInputBase.tsx
packages/app/ui/components/MessageInput/index.tsx

fixes tlon-3942
I suspect we were just being overly cautious by disabling the send button while we're currently sending? Maybe it was a way to prevent accidental double posts (we clear the message input on send anyway, though)?
Anyway, we were definitely disabling the send button while we were in the `isSending` state. Not sure why we didn't notice this earlier. I guess we didn't notice because messages were getting delivered quickly?

chat: don't disable the send button while we're sending

---

packages/app/features/top/PostScreen.tsx
packages/shared/src/store/useThreadPosts.ts

It looks like the issue here is actually just that we don't have the activity posts already loaded into the DB. If the post does already exist, it works as you'd expect. 
What tipped me off was that it wasn't working on mobile either. My guess is this broke after we refactored screen params to only accept primitive types. Previously activity would scaffold a full post and pass that along.
The post-navigation URL having unserialized objects in the query param seems to have been a red herring. We probably do want to avoid those somehow? But it seems that's not actually what's breaking things here.
Fixes TLON-3927

activity: fix navigating to threads

---

packages/app/ui/components/Channel/ChannelFooter.tsx
packages/app/ui/components/ChatOptionsSheet.tsx
packages/app/ui/components/MessageInput/AttachmentButton.native.tsx

Switches the bare "Add" SVG to use the Icon UI component; makes it reappear on mobile.
Fixes TLON-3938
Also makes the same change in ChatOptionsSheet and ChannelFooter to avoid regressions there.

AttachmentButton.native, others: use Icon component

---

packages/app/ui/components/MessageInput/MessageInputBase.tsx

Fixes TLON-3887, something about the way that Tamagui optimizes this breaks the background from switching correctly when themes change.

input: disable optimization to prevent dark mode issues

---

packages/app/ui/components/MessageInput/index.tsx

fixes tlon-3951
Prosemirror is expecting the `handlePaste` function that we're passing to it (in `packages/editor/src/MessageInputEditor.tsx`) to return `true`.
If we don't return `true` and the user pastes some formatted text into the editor, the editor will send a `content-error` message (concerning `nodeSize` being undefined) back up to the RN MessageEditor component, and that component will assume this error is fatal and refresh the editor webview. 
If we return `true` then we'll no longer get that error message and the editor won't restart, but we'll also never get the content into the editor after paste (because prosemirror will assume we're handling the formatting/insertion externally). We don't want to handle that externally, we want prosemirror to do it for us, otherwise we'll …

notebooks: fix issue with pasting formatted text

---

apps/tlon-web-new/src/app.tsx
packages/app/features/chat-list/ChatList.tsx
packages/app/features/chat-list/GlobalSearch/index.tsx
packages/app/features/top/ChannelScreen.tsx
packages/app/features/top/ChatListScreen.tsx
packages/app/hooks/useFilteredChats.ts
packages/app/hooks/useRenderCount.ts
packages/app/hooks/useResolvedChats.ts
packages/app/navigation/BasePathNavigator.tsx
packages/app/navigation/desktop/HomeNavigator.tsx
packages/app/navigation/desktop/HomeSidebar.tsx
packages/app/navigation/desktop/MessagesNavigator.tsx
packages/app/navigation/desktop/MessagesSidebar.tsx
packages/app/ui/components/ChatOptionsSheet.tsx
packages/app/ui/components/GroupChannelsScreenView.tsx
packages/app/ui/components/ListItem/ChannelListItem.tsx
packages/app/ui/components/ListItem/ChatListItem.tsx
packages/app/ui/components/ListItem/GroupListItem.tsx
packages/app/ui/components/ListItem/InteractableChatListItem.tsx
packages/shared/src/store/dbHooks.ts
packages/ui/src/hooks/useIsWindowNarrow.ts

fixes tlon-3892 (makes it much better anyway). 
We were seeing a lag when quickly switching between channels because of some render perf issues that were triggered by channel switching. HomeSidebar, MessagesSidebar, TopLevelDrawer, ChatList, GroupChannelsScreenView, ChannelOptionsSheetLoader, and some other components were re-rendering several times on every channel switch.
I went through and tried to find every place in the app that was unnecessarily re-rendering when we switched channels. If you run the profiler or the JS performance tool (most noticeable difference), you'll see that we cut the rendering time pretty dramatically by memoizing the crap out of everything.
There's still some noticeable hitching when we're waiting on multiple requests to finish when switching between several …

desktop (mostly): react perf optimization

---

packages/app/ui/components/BareChatInput/index.tsx

fixes tlon-3970
We programmatically adjust the height (with a new method, no longer relying on adjusting the height via onChange) when we know we'll have some text inserted before the user interacts with the input (if we have a draft saved or if we're editing an existing message).

desktop: fix issue with input height not adjusting for drafts

---

apps/tlon-mobile/app.config.ts

We don't much use the test branch environment anymore. Changing these env vars to make sure preview builds (black app) will work with and produce normal invite links.

ops: always default to prod branch env

---

packages/shared/src/db/migrations/0000_curious_squirrel_girl.sql
packages/shared/src/db/migrations/meta/0000_snapshot.json
packages/shared/src/db/migrations/meta/_journal.json
packages/shared/src/db/migrations/migrations.js
packages/shared/src/db/queries.test.ts
packages/shared/src/db/queries.ts
packages/shared/src/db/schema.ts
packages/shared/src/store/sync.ts

What present as the web app breaking and the mobile client not showing contact data, was actually an issue with inserting latest posts. We had multiple `onConflictDoUpdate` clauses which is unsupported in the current drizzle version we're using. On top of this we had a restrictive constraint for `cacheId` which wasn't accurate. Additionally we had a unique constraint on `sentAt` time which doesn't map with the backend. Finally we were bailing if we ended up trying to insert the exact same post window, so now we just no-op since it's already there (the key is the row).
In other words, most of this is just resolving discrepancies between client and backend.
- Post IDs are only unique across a single channel (not addressed in this PR, but looming issue, although it should almost never …

db: make cache ids unique, remove unsupported extra conflict resolver

---

apps/tlon-mobile/ios/Podfile.lock
apps/tlon-mobile/package.json
pnpm-lock.yaml

Bump op-sqlite version in order to fix migration failure we're seeing (newer drizzle version was incompatible with older op-sqlite version we were using).

Fix migration failure

---

packages/app/ui/components/ChatMessage/ChatMessage.tsx

fixes tlon-3972
This isn't really a desktop issue, it's just that nobody noticed it until we rolled out the desktop web app. We had no way of showing if a post had been edited in chat if the message didn't show the author row. This change just ensures that we always show the author row if the post has been edited (just so we can show the edited tag).

chat: show author row with edited tag when a post has been edited

---

desk/app/lanyard.hoon
desk/app/verifier.hoon

Because the `.log` is in the agent core's context, it would get carried along across invocations, as would any changes we made to that core.
Because we set some of those door arguments for logging purposes and never _unset_ them, logs would _always_ have the optional values, just set to the most recent value, unless they changed them themselves.
This is the smallest viable fix. Arguably this is paying for cuteness by being even cuter. The logging pattern here remains really nice though, so it's a bit of a wash...

verifier: don't persist log details across events

---

desk/app/expose.hoon
desk/app/expose/page.hoon
desk/app/expose/render.hoon
desk/app/expose/widget.hoon
desk/lib/channel-utils.hoon

Minimal viable change, to make sure `/app/expose` doesn't crash and burn. It was failing to compile, which would've prevented the upgrade on ships that had it enabled.
Most significantly, `kind-data` was replaced by a `kind=path`, and `author` might have a "bot profile" included. The former we handle by reading the path instead of the tag, the latter by overlaying the bot profile on top of whatever the underlying ship's contact profile is.

expose: update for latest channels content types

---

packages/app/hooks/useResolvedChats.ts

fixes tlon-4010 by triggering an update to the chatSignature when we hear about a new, bigger `lastPostAt` number.

desktop: make useResolvedChats update when lastPostAt updates

---

desk/app/chat.hoon
desk/lib/channel-json.hoon
desk/lib/channel-utils.hoon
desk/sur/channels.hoon

For links that should be rendered as a preview card block element. Contains arbitrary metadata for use in that rendering, but we specify well-known meta keys for clarity.
Haven't tested this end-to-end yet, @latter-bolden's client integration work with `m/link-preview-fetching` is still pending.
Would be good to sneak this content AST change in along with the other protocol changes. This PR has all the changes needed to make our agents and helper libraries compile and makes sure to include the new addition in the json parser. That _should_ cover things, shouldn't it?
Closes TLON-3910.

channels: add %link $block element

---

apps/tlon-mobile/ios/Shared/Notifications/PushNotificationManager.swift

fixes TLON-3932
Detailed context about problem and solution is in Linear ticket + comments.
This approach creates some small bugs:
- All posts in a channel will be in the same notification group: this includes replies inside threads. A notification group may consist of `top-level-post1`, `top-level-post2`, `some-reply-to-top-level-post1`, `top-level-post3`.
- This is true for any channel – not just chats. If you have notifications enabled for a gallery, each new gallery post will get slotted into a single notification grouping.
We'll have more resolution to better group notifications when we are sourcing from activity events, but this should be a significant improvement in the short term.

notifications: use channel ID to group iOS notifications when available

---

packages/app/ui/components/MessageInput/index.tsx
packages/editor/src/MessageInputEditor.tsx
packages/shared/src/logic/tiptap.ts

fixes tlon-3985
We no longer need to override the `enter` or `shift-enter` keys in our tentap editor because `enter` will never send a message in notebooks or galleries (it would in chat, when we used it there), so we can remove the shortcuts bridge. The shortcuts bridge was causing the issue where the user was unable to add a new line within a code block (it would just split the editor, taking the user out of the code block and adding a new paragraph node).
Also, our draft logic was overly complex, which led to issues with restoring drafts. It's already stored in prosemirror AST, we don't need to convert it to a Story and then back to the prosemirror AST.
The last thing I noticed here is that `diaryMixedToJSON` didn't account for the fact that we treat `code` nodes within an `inline` in …

notebook: fix some formatting issues

---

packages/app/features/top/ChannelScreen.tsx
packages/shared/src/store/syncQueue.ts
packages/shared/src/store/useChannelPosts.ts
packages/ui/src/components/ParentAgnosticKeyboardAvoidingView.tsx

Fixes TLON-4032
Adds ability to cancel requests using an `AbortController` signal. We should look for more places to apply this, and may want to abstract some usage patterns as they become clearer.

add ability to cancel requests using AbortController

---

packages/app/features/top/ChannelScreen.tsx
packages/app/navigation/utils.ts
packages/shared/src/db/keyValue.ts
packages/shared/src/db/migrations/0000_shiny_bloodstorm.sql
packages/shared/src/db/migrations/meta/0000_snapshot.json
packages/shared/src/db/migrations/meta/_journal.json
packages/shared/src/db/migrations/migrations.js
packages/shared/src/db/schema.ts

Fixes TLON-4026 by moving `lastVisitedChannelId` out of SQLite and into keyval storage.

store last visited group channel in keyval storage

---

apps/tlon-mobile/ios/Landscape/AppDelegate.mm
apps/tlon-mobile/ios/Landscape/Info.plist
packages/app/contexts/branch.tsx
packages/shared/src/domain/analytics.ts

Updates our branch configuration to work with deferred deeplinking on iOS + telemetry when it's triggered.
Fixes TLON-4017

mobile: handle deferred deep links

---

packages/app/navigation/desktop/HomeSidebar.tsx
packages/app/ui/components/Wayfinding/SplashModal.tsx
packages/shared/src/domain/wayfinding.ts
packages/shared/src/store/dbHooks.ts

The hook that controls if the splash modal is shown on web is supposed to short circuit if you don't have the new wayfinding group. There was a bug with detecting if you had said group — it was checking for a truthy value on a `useQuery` response object, rather than the `useQuery` data itself.
Also removes placeholder slug names.

wayfinding: fix web splash modal display logic

---

packages/app/ui/components/PostContent/contentUtils.tsx

fixes tlon-4003
if the href and the content of the link don't match, we know the user has formatted some content as a link and we should just render the content that way.

embeds: text formatted as a link shouldn't render an embed

---

packages/app/ui/components/MessageInput/InputToolbar.tsx

fixes tlon-4035
This was a bear to track down. The issue is that the `onBlur` from the input was firing before we could register the press to the "Insert" button in the EditLinkBar, so the formatting was just never applied.

desktop: fix link formatting in notebooks

---

packages/app/ui/components/Embed/EmbedWebView.tsx

fixes tlon-4038
This is difficult to repro, but my hypothesis is that this has to do with either a race condition in onNavigationChangeHandler or the fact that we don't cleanup the webview on dismount. This PR attempts to address both of those issues and also adds a catch with a logger.crumb call to get some more observability on why/how frequently we're failing to open embed links in the wild.

embeds: fix issue with embeds losing interactability on mobile

---

packages/app/ui/components/ChatOptionsSheet.tsx
packages/app/ui/contexts/chatOptions.tsx
packages/shared/src/api/activityApi.ts
packages/shared/src/db/queries.ts
packages/shared/src/store/channelActions.ts

Previously, marking a channel as read from the `ChatOptionsSheet` would not that channel's threads as read. Now it does.
Fixes TLON-3839

Mark channel threads read in "Mark read" action

---

.github/workflows/deploy.yml
.github/workflows/mobile-testing.yml

The rapid fire PR commits kinda lock our ships down, so I think this should help with that. It basically will cancel any action currently running that matches the same group.

ops: only deploy/test last commit

---

packages/app/ui/components/ImageViewerScreenView.tsx
packages/app/ui/components/InviteFriendsToTlonButton.tsx

Fixes TLON-4052 by getting Very Serious about the save image prompt. Makes the following changes:
- Adds comprehensive error tracking w/ PostHog
- Adds proper permission state handling
- Cleans up the temporarily-downloaded file
- Adds a bunch of validation checks and handles the errors appropriately
This also prompts the user to visit their app settings to grant permission if they haven't (copied this from where we handle notification prompts)

ImageViewerScreenView: image saving errors

---

api/README.md
api/components/common.yaml
api/components/groups.yaml
api/components/meta.yaml
api/openapi.yaml
api/paths/groups.yaml

This PR lays the foundation of TM API documentation. We use OpenAPI to define the specification of existing backend endpoints. Subsequently, the documentation can be generated with [Redocly](https://redocly.com).
The API coverage so far is minimal and includes only a handful of endpoints of the %groups agent. This was enough to establish a general structure. The specification can now be expanded in the areas we consider most useful. 
I have made an attempt at generating the spec using static code analysis of our Hoon codebase, but for this approach to be practical the code analyser would have to be made more powerful – other things take priority for now.
Fixes TLON-3571

api: OpenAPI scaffolding for TM backend API specification and documentation

---

apps/tlon-web/src/app.tsx

fixes tlon-4053
We were setting the ref prematurely, then comparing the newly set ref against the value we just set it to, which caused us to no-op on setting the channel title.
Also, we should add the "DM" case to the channel routes block, otherwise the title will briefly fallback to "D M" via getFriendlyRouteName before showing the appropriate title (navigator takes us to a route named DM very briefly before taking us to ChannelRoot).
Also removed some vestigial uses of template literals.

web: fix titles

---

packages/app/ui/components/ListItem/ChannelListItem.tsx
packages/app/ui/components/ListItem/GroupListItem.tsx
packages/app/ui/contexts/chatOptions.tsx

fixes tlon-4056
I introduced a change recently (for the context menus) where we call `setChat` from `useChatOptions` in GroupListItem. We also happen to use GroupListItem in the FavoriteGroupsDisplay via the GroupSelectorSheet, where we pass `disableOptions` to the component.
`useChatOptions` will throw an error if it's called outside of a ChatOptions context.
Since we know there are cases where a component might use `useChatOptions` but also allow for the options to be disabled, we need to pass a `disabled` parameter to `useChatOptions` to prevent it from throwing an error when it's called outside of a ChatOptions context.
update: now fixes tlon-4059

profile: fix crash on edit screen

---

packages/shared/src/db/storageItem.ts

fixes tlon-4055
The root cause was a race condition in `storageItem.ts`. The getValue function could read from storage before a pending setValue or resetValue operation (triggered by clearDraft) had completed writing, due to not awaiting the internal updateLock.
This change modifies getValue to await updateLock before reading, ensuring that reads only occur after any pending writes for the same key are finished. This should eliminate the race condition and ensure that drafts are reliably cleared.

chat input: fix issue with drafts not always clearing on send

---

packages/app/ui/components/UserProfileScreenView.tsx

Fixes TLON-4049 by making the click-to-copy ID function in profiles very obvious.
I simplified the ContactName component to handle either the nickname or the patp as the "primary name" for the profile. The secondary line shows the patp normally when a nickname is present and is now responsible for showing the copied indicator. This secondary line is only shown when props.hasNickname is true or if didCopy flips to true.
Quick demo for nickname vs non:

profile: click-to-copy feedback

---

packages/app/ui/components/Channel/Scroller.tsx
packages/app/ui/components/Channel/useAnchorScrollLock.ts

fixes tlon-3632
The issue was that FlatList treats each row in the grid as one logical "item" in the list, and our galleries always have at least two items per row. If we have an item we need to scroll to we can't use the real index of that item because it doesn't correspond to the logical "item" in the FlatList.
For instance, if we have 18 real items and each row has three items, then FlatList will only see six "items" (index 0 to 5), and if we try to scroll to real item 14 it will always be out of range. But, if we use Math.floor(index/columnCount), we adjust the index to 4 (fifth out of 0 to 5) and FlatList scrolls to the fifth row.

gallery: fix issue with scrolling to selected post

---

apps/tlon-mobile/src/components/AuthenticatedApp.tsx
packages/app/hooks/useNavigationLogger.ts
packages/app/navigation/BasePathNavigator.tsx
packages/app/navigation/utils.ts

Fixes TLON-3982, there's some weird behavior in react navigation where any navigate call that doesn't specify `initial: false` will make itself the "initial" route for a particular stack. This caused problems because if you navigated from activity to a thread/post, the initial route for the channel stack would be "Post". So later when we tried to nav with `initial: true` we'd get "Post" instead of "ChannelRoot". I just tried to avoid this implicit behavior by just being specific about what screen we actually wanted.
Also added some more logging.

nav: specify screen to ensure proper nav

---

desk/app/groups.hoon
packages/app/hooks/useResolvedChats.ts
packages/app/ui/components/ListItem/GroupListItem.tsx
packages/app/ui/utils/channelUtils.tsx
packages/shared/src/db/queries.ts

fixes tlon-4022
There were a few issues causing this.
1) We never know the group members when we're invited to a group, and if a title wasn't set we would just show the user "Untitled Group".
2) We weren't getting a full fleet list from the groups-ui init api response because we were purposefully dropping the fleet (with `drop-fleet` in the groups agent) and replacing it with just our own ship to speed the request up. This meant that when the app was initialized (which happens on every refresh on web), every group without a title would just appear as "Untitled Group".
3) After entering the group and triggering `syncGroup`, we grab the specific data for that group from the api and insert it into the db. This *should* have updated the group member list permanently in the db, but it wasn't …

fix "untitled group" issue

---

packages/shared/src/db/storageItem.ts

This reverts commit 316be3a1700adcec1f44160ed32c9ca6fe9a933d.
was causing an issue with `setValue()` calls that passed an updater function.

Revert "chat input: fix issue with drafts not always clearing on send"

---

packages/shared/src/db/storageItem.ts
packages/shared/src/store/usePostDraftCallbacks.ts

fixes tlon-4055
adds an optional `waitForLock` param to `getValue`, we'll pass `true` when we know we wanna wait for the updateLock to resolve before performing the operation.

chat input: fix issue with drafts not always clearing on send (again)

---

packages/app/features/top/ContactsScreen.tsx
packages/app/navigation/desktop/ProfileNavigator.tsx
packages/app/ui/components/Badge.tsx
packages/app/ui/components/ContactsScreenView.tsx

Fixes TLON-3935, a common complaint with suggested contacts. This changes the click/tap handlers for suggested contact rows to immediately add the suggested contact to the user's contacts, rather than navigating them to their profile.

ContactsScreen, ProfileNavigator: immediately add suggested contact

---

packages/app/ui/components/MessageInput/MessageInputBase.tsx

fixes tlon-4075
This is super weird. It turns out this was caused (somehow, I have no idea how. chalk it up to Tamagui weirdness) by using a YStack as the parent container for the MessageInput component within MessageInputBase.
If we use an XStack instead (*not* a View or Stack), it's fine.
That's it, that's the change.

notebooks: fix issue with notebook editor interactivity on Android

---

packages/shared/src/store/storage/storageActions.ts

OTT, fixes tlon-4087.
You should now see the loading spinner on the attachment preview rather than the failure message.

attachments: don't show upload error for fake image uri, no-op instead

---

packages/app/features/top/ChatListScreen.tsx
packages/app/ui/components/ChatOptionsSheet.tsx
packages/app/ui/contexts/chatOptions.tsx

In a recent refactor, we moved the rendering of the ChatOptionsSheet into the `chatOptions` provider itself when on mobile. This broke the invite button because which chat is active for the options sheet is now handled internally rather than at the ChatList level (where the previous invite sheet behavior lived). 
To solve this while matching that new pattern, I pulled the invite sheet into `chatOptions` as well. If the context is not passed an `onInvitePressed` handler, it will display its own internal invite sheet.
The chat options logic is getting quite complicated imo (state is too intermingled between the context hooks and actual components with expected behavior differing by use case and platform). We should try to pull these apart, but that would be outside the scope of this fix. …

mobile: fix invite button in chat option sheet

---

packages/app/hooks/useBootSequence.ts

Micro PR with two small changes to the boot sequence.
1. only add the inviter as a contact once (was leading to console errors on retry)
2. force group re-sync when checking for joined status on the invited group (previously would only check once per session)

onboarding: boot sequence fixes

---

desk/app/groups.hoon
packages/app/ui/utils/channelUtils.tsx

fixes tlon-4142
we just sort alphabetically on the frontend instead.

groups agent: remove sort w/alphabetical ordering from drop-fleet

---

desk/mar/group/create-thread.hoon
desk/sur/groups-thread.hoon
desk/ted/group/create.hoon

The `-group-create` thread aids in creating and initializing a group based on supplied presets. 
Closes TLON-4132

groups: implement -group-create thread

---

packages/app/ui/components/BareChatInput/useMentions.tsx
packages/app/ui/components/ListItem/ContactListItem.tsx
packages/app/ui/components/MentionPopup.tsx
packages/app/ui/components/UserProfileScreenView.tsx

Fixes TLON-4130 where trying to search a mention with regex chars would break the app, and a few other things I found when working with mentions:
- we didn't allow you to select a mention if you only typed the trigger character and didn't search
- we were triggering mentions if you put a mention trigger character in the middle of the word. I think its fine to make it require whitespace before it (or be first character) 
- when mentioning the mention in the input would only be the patp not the nickname
- we tend to not show the full ID which in most cases won't matter for normal users, but for power users who have moons this made it impossible to know which moon it was
- if someone had never modified their profile and was in the group with you and never posted, they would be missing from …

mention: oddities omnibus

---

apps/tlon-mobile/android/app/src/main/java/io/tlon/landscape/notifications/ActivityEvent.kt
apps/tlon-mobile/android/app/src/main/java/io/tlon/landscape/notifications/NotificationManager.kt
apps/tlon-mobile/android/app/src/main/java/io/tlon/landscape/notifications/TalkNotificationManager.java

_currently pointed at #4665_
I'd recommend reviewing the first commit a8a16cbbb8cf0c0e57dd69bcfd5fb699656727ba separately – that commit just translates old Java code into Kotlin (using an automatic IDE-provided translation), and messes with the diff.
---
| Expanded | Collapsed |
| --- | --- |
| ![Screenshot 2025-04-29 at 11 11 30 AM](https://github.com/user-attachments/assets/4efe94c2-075c-47d9-a940-a7ac561bf633) | These notifications auto-collapse when new notifications come in: ![Screenshot 2025-04-29 at 11 11 49 AM](https://github.com/user-attachments/assets/ebd26d7a-3092-463c-8a2b-f390d8774270) |
Groups subsequent notifications from the same channel or thread into "conversations" in the Android notification drawer.
iOS accumulates notifications posted to the same `threadIdentifier` …

android: group notifications by conversation

---

apps/tlon-mobile/package.json
apps/tlon-web/package.json
packages/app/package.json
packages/ui/package.json
pnpm-lock.yaml

Resolves a mismatch in versions of `react-native-safe-area-context` which was causing a crash in production on web.

fix safe area bug

---

packages/app/ui/components/BareChatInput/useMentions.tsx

Because of the way we break text up to convert it back to our backend data type, mentions break if you have spaces in your nickname. This just reverts that change and places the id in the input.

mentions: revert change to show nicknames in input box

---

packages/app/ui/components/BareChatInput/helpers.ts
packages/app/ui/components/PostContent/InlineRenderer.tsx
packages/app/ui/components/PostContent/contentUtils.tsx
packages/shared/src/http-api/Urbit.ts

Allows us to show nicknames in text input when selecting mentions. When doing this noticed that we accidentally we're removing text nodes with just spaces when they were in between distinct non-text nodes. This should fix the issue we have where special formatted nodes get slammed together.

mentions: allow spaces

---

desk/app/verifier.hoon
desk/sur/verifier.hoon

Two small fixes.
We weren't including the `src.bowl` in the logs for user queries, leading to "rate limited" info logs without the affected ship being legible.
Shared pool rate limiting allowance was being set through `$_`'s implicit bunt, but this interferes with the `;;` we do for dbug safety purposes, so we switch to doing a proper `$~` instead. (Same change as 3429eda.)

verifier: logging & maintenance details

---

packages/shared/src/domain/analytics.ts
packages/shared/src/store/groupActions.ts
packages/shared/src/store/sync.ts

Fixes TLON-4187. We were accidentally calling the API here when hearing a fact to update our local DB, but sending this to the API created a new fact which then triggered the same flow over and over. This switches that handling to only modify local DB.

groups: dont loop on section moves

---

packages/shared/src/api/urbit.ts
packages/shared/src/domain/analytics.ts
packages/shared/src/http-api/Urbit.ts
packages/shared/src/http-api/events.ts
packages/shared/src/http-api/fetch-event-source/fetch.ts
packages/shared/src/http-api/types.ts

OTT
Thread `POST`s will no longer fail due to SSE disruption. Also adds more telemetry for thread failures and channel reconnects.

http-api: fix thread abort signal

---

packages/app/ui/components/ContentReference/Reference.tsx

fixes tlon-4149
Both errored refs and "not found" refs now just say "Content not available".

references: update copy for unavailable references

---

desk/app/verifier.hoon

For investigating supposed twitter api flakiness, we'll want to know the kinds of responses we get back. Include the status code and response body in the logs.
Already pushed this onto the service, but PRing for persistence.

verifier: log twitter api responses

---

packages/app/features/settings/EditProfileScreen.tsx
packages/app/features/top/UserProfileScreen.tsx
packages/app/navigation/desktop/ActivityNavigator.tsx

fixes tlon-4074
There was no way to get to user profiles from the Activity tab on desktop, so clicking on a status update (or avatar change) activity item would do nothing.
EditProfileScreen comes along for the ride too so that users can edit nicknames/avatars for their contacts.

desktop: show user profile in ActivityNavigator

---

packages/app/features/settings/PrivacyScreen.tsx

There's a race condition with the toggle not showing to the proper value if the attestation hasn't loaded by the time the component state is initialized. 
This adds an effect to update the toggle state to match the attestation in the DB. We'll still optimistically update it on press in addition to listening for DB updates.

privacy settings: fix phone discoverability toggle

---

packages/app/hooks/usePosthog.ts

fixes tlon-4119.
I think these users have posthog blocked, which is causing `posthog.has_opted_out_capturing()` to be undefined, so they were getting the default value of `false` for `getIsOptedOut` when it should have been `true`.
What are the other implications for this change, though?

web/privacy: prevent telemetry toggle from showing true when we don't know

---

packages/app/ui/components/PostContent/contentUtils.tsx
packages/shared/src/urbit/activity.ts
packages/shared/src/urbit/channel.ts
packages/shared/src/utils/assertNever.ts
packages/shared/src/utils/index.ts
packages/shared/src/utils/utilityTypes.d.ts

fixes TLON-4222
`convertContent` did not have a branch for `cite` blocks. To avoid this kind of bug happening in the future, I moved the conditional to use a new helper, and added an `assertNever` to raise a type error if we miss a case (e.g. if another block type is added).
I checked that a `cite` (created by "copy link to message" -> paste in message input) rendered correctly in:
- iOS notification body (should be the same for Android, just didn't check)
- latest message preview in chat list
- actual post view in chat scroll

native: parse cite block correctly in convertContent

---

packages/app/hooks/useTelemetry.ts

Right now we only append the user identity as the distinct ID but this can't be used as an event filter when charting insights. By additionally tacking it on as a user property, we can effectively filter on it.
Also correlates actual user ID unconditionally if _share usage statistics_ is on (which remains the primary privacy control mechanim)

telemetry: separate property for userId

---

packages/shared/src/http-api/Urbit.ts
packages/shared/src/utils/index.ts
packages/shared/src/utils/timeoutSignal.ts

Instead of relying on `PostHog` to ad-hoc polyfill this for us, implements a basic timeout-based abort signal for use with `fetch`.

http-api: rely on included timeout signal

---

cosmos.imports.ts
packages/app/fixtures/contentHelpers.tsx
packages/app/ui/components/GalleryPost/GalleryPost.tsx

fixes tlon-4124
if a list appeared as the second item in the `content` array it never rendered because we were slicing to grab just the first item from the array (which makes sense on image posts, we want the image and we don't want the caption, doesn't make sense for text-only posts).
Also updates the gallery post fixture so that we render a `postWithList` that has both an inline *and* a list after the inline, which is the case that was failing here.

gallery: render all text on text posts

---

packages/shared/src/store/useChannelPosts.ts

Small first PR for improving channel load telemetry -- this tracks a posthog error when we fail to retrieve posts for any reason.

track errors when attempting to load posts

---

packages/app/ui/components/Channel/Scroller.tsx

Fixes TLON-3132 where deleting the first message in a sequence wouldn't move the AuthorRow to the second one, making it appear as though the person above you sent your second message. showAuthor was mostly just checking to see if the previous message was sent by the same author and wasn't taking the live state of the previous post into account (i.e. deleting).
- Adjusts the showAuthor logic to account for deleted posts preceding the current one.
- Uses useLivePost inside BaseScrollerItem to get the current state of the previous post and looks for the isDeleted flag.
- Tracks if the live version of the previous post exists and if it's deleted. If so, forces showAuthor to true.
- If the previous message was simply edited and not deleted, we fall back to the original showAuthor logic.
I …

scroller: move AuthorRow when deleting first message in sequence

---

apps/tlon-web/src/state/settings.ts
packages/app/features/settings/ThemeScreen.tsx
packages/app/provider/index.tsx
packages/app/types/theme.ts
packages/app/ui/utils/index.ts
packages/app/ui/utils/themeUtils.tsx
packages/shared/src/api/settingsApi.ts
packages/shared/src/domain/analytics.ts
packages/shared/src/index.ts
packages/shared/src/store/dbHooks.ts
packages/shared/src/store/settingsActions.ts
packages/shared/src/urbit/settings.ts

Fixes TLON-4118 by storing the theme on the back-end and syncing across clients.
- Adds proper settings bucket support for themes
- Syncs across devices by listening for changes to the theme setting
- Appropriately handles the "auto" (null) theme selection
- Adds logging for theme setting + errors
https://github.com/user-attachments/assets/47412726-be97-4db6-9e9c-5bcffc28d389

settings: set theme on back-end, update across clients

---

packages/app/ui/components/PostContent/InlineRenderer.tsx
packages/ui/src/components/TextV2/Text.tsx

Fixes TLON-4184 by adding a context to `InlineRenderer` to track the parent style, then pass it to `InlineText` and conditionally render code blocks differently.
React Native styles don't automatically cascade to children, so recent changes to `InlineText` blew away the delicate balance of prop inheritance we had in place. 
We ended up with something to the effect of:
```
<CodeText> (monospace font)
<RawText> (default font - overriding parent)
"text content"
</RawText>
</CodeText>
```
The RawText component was created with `unstyled: true`, making it ignore parent styling context altogether.
I had Copilot check to see if this plays nicely with #4752 and it seems to be fine; tagging @davidisaaclee in for good measure.

InlineRenderer: styling code blocks

---

packages/app/fixtures/ChatOptionsSheet.fixture.tsx
packages/app/ui/components/ChatOptionsSheet.tsx

Fixes TLON-4183 by adding a simple check to see if the user is the channel host; if not, then we display a message that they have to delete the channel and can't leave it on their own accord.
This also adds a pretty robust fixture for the ChatOptionsSheet, which:
- Splits the demonstration out into three cases: individual channel, group, and DM
- Adds options for unread counts to show and hide the "Mark all as read" option
- Adds options for group privacy to toggle invite availability for members
- Adds an option for host/member status to test TLON-4183 ;)

ChatOptionsSheet: disable channel leave for hosts

---

packages/app/ui/components/GalleryPost/GalleryPost.tsx

Fixes TLON-4253.
Looks like `height: 100%` got accidentally removed in the preview update.

fix gallery image previews

---

desk/lib/channel-json.hoon
desk/lib/channel-utils.hoon
desk/mar/channel/response-1.hoon
desk/sur/channels.hoon

The recursive changes to the $inline type (specifically the %sect addition) and the presence of both $inline and $block in $listing had gone unnoticed, resulting in mark types changing unintentionally.
Here, we make sure all affected types get a proper entry in +v7 in /sur/channels, and that mark files use that older type version as necessary.
Mandatory utils and json changes included.
Note that the %channel-update and %channel-checkpoint marks, which are emitted by channels-server, still change due to the protocol changes. Since these marks only ever come out of channels-server, and interaction with that agent is (intended to be) gated behind version negotiation, we just let that happen.

channels: retain mark types across protocol change

---

desk/app/lanyard.hoon

For usage during manual testing and for hosting to do clean-up while recycling ships.

lanyard: %revoke-all poke

---

packages/shared/package.json
pnpm-lock.yaml

OTT
We published the new version with the changes that required us to use the git tag.

ops: bump nockjs version

---

packages/shared/src/logic/content-helpers.test.ts
packages/shared/src/logic/content-helpers.ts

OTT reported by in support channel

content-helpers: make sure we extract the text for code blocks

---

packages/shared/package.json
packages/ui/src/components/ErrorBoundary.tsx
packages/ui/src/components/Image.tsx
packages/ui/src/index.ts
pnpm-lock.yaml

After switching to `expo-image` on web, we're seeing a crash if the passed image `source` is a hex code instead of a URL. There are some legacy agent states that have image meta set to colors.
To prevent this, the image component validates the source string is a URL before attempting to render. I also added an error boundary that uses the existing fallbacks in case we encounter other errors — a crashing image component should never take down the whole app like it did in this case.
Fixes TLON-4287

images: prevent crash from bad image source

---

apps/tlon-mobile/src/App.main.tsx

OTT
We fixed the queryclient ordering on `develop`, but it's still breaking mobile on the protocol upgrade branch

ops: copy provider ordering fix onto release branch

---

packages/app/ui/components/ChatMessage/ChatMessageActions/EmojiToolbar.tsx
packages/app/ui/components/ChatMessage/ReactionsDisplay.tsx
packages/app/ui/components/Emoji/EmojiPickerSheet.tsx
packages/ui/package.json
packages/ui/src/components/Emoji/SizableEmoji.tsx
packages/ui/src/components/Emoji/data.ts
packages/ui/src/components/Emoji/utils.ts
pnpm-lock.yaml

The new backend sends either unicode emojis (in subscription updates) or shortcodes (in the version of the scry we currently use for outlines).
For now, rather than refactor the way the frontend deals with emojis entirely we can just patch the way we render them in SizableEmoji.
If `emojiInput` can't be found in our map of shortcodes -> emojis and if it matches a unicode emoji pattern, we just render it directly.
fixes tlon-4279.
Later on we should probably move away from shortcodes on the frontend.

protocol change: patch the frontend to handle rendering either unicode emojis or shortcodes

---

packages/app/ui/components/ChatMessage/ChatMessage.tsx
packages/app/ui/components/GalleryPost/GalleryPost.tsx
packages/app/ui/components/NotebookPost/NotebookPost.tsx

This issue actually exists on develop as well. Since we weren't setting `isHovered` to false the ChatMessageActions menu would continue to show even after the `dismiss` function in MessageActions.tsx was called for the action, since `onDismiss` did not also call `setIsHovered` with `false`.
The issue wasn't that we were navigating to the notebook post when pressing the "copy ref" action, it was that we were navigating to it if we pressed that action *twice*.

Close message actions menu after selection is made on desktop

---

desk/app/metagrab.hoon

Primarily: the url in the location header is allowed to be relative. We need to make sure to resolve it against the base url before working with it.
(`+expand-url` resolves absolute urls to themselves, no concerns there.)

metagrab: better redirect handling

---

packages/app/ui/components/BareChatInput/index.tsx
packages/app/ui/components/draftInputs/GalleryInput.tsx
packages/app/ui/components/draftInputs/LinkInput.tsx

OTT
- form deletion was just a logic bug with it re-inserting the default title if it detected the input was empty
- chat was not attempting to block send while loading, now it does via a state variable
- gallery was attempting to block, but it wasn't effective until the debounce triggered
Fixes TLON-4276
Fixes TLON-4297

links: fix form deletion + block send while loading

---

packages/app/tsconfig.json
packages/app/ui/components/ChatMessage/ChatMessage.tsx
packages/app/ui/components/GalleryPost/GalleryPost.tsx
packages/app/ui/components/PostContent/BlockRenderer.tsx
packages/ui/src/components/Image.tsx

A number of visual fixes for link display:
- Fix double borders on link blocks in galleries
- Set max width on link blocks in chat channels
- Remove descriptions from link blocks in galleries and chat channels
- Better handling for links with missing titles, descriptions, or images
- Reconcile max widths of images + other blocks
- Fix extra space above references in galleries
- Improves image component types

link display tweaks

---

desk/app/metagrab.hoon

Two things:
First, we update the user-agent logic to pull the user-agent string from the user's original request. Only if that's absent do we fall back to the hardcoded fake chrome string.
Second, we add a small set of heuristics for the experimental feature of detecting when our request gets rejected for bot/scraper protection reasons. In that case, we put a `possibly-blocked` string in the `result` field (for `status: 400` results). The client might be able to use this to message differently about the failure, or retry in some other way.

metagrab: rejected/challenged request handling

---

packages/app/ui/components/AttachmentSheet.tsx
packages/shared/src/store/storage/storageActions.ts
packages/ui/src/components/Image.tsx

It looks like these weren't being properly detected by our validator. For data URIs, it has a built in method which we instead use. For file URIs, it doesn't like certain forms (_file:///_) so we detect manually.
Also noticed the placeholder asset behavior on mobile looked wonky with the fallback. Special cased that while I was in there.

image: fix detection for file/data URIs

---

packages/app/features/settings/PrivacyScreen.tsx
packages/app/ui/components/BareChatInput/index.tsx
packages/app/ui/components/PostContent/BlockRenderer.tsx
packages/shared/src/api/metagrabApi.ts
packages/shared/src/api/settingsApi.ts
packages/shared/src/db/migrations/0000_shocking_hulk.sql
packages/shared/src/db/migrations/meta/0000_snapshot.json
packages/shared/src/db/migrations/meta/_journal.json
packages/shared/src/db/migrations/migrations.js
packages/shared/src/db/schema.ts
packages/shared/src/store/dbHooks.ts
packages/shared/src/store/metagrabActions.ts
packages/shared/src/store/settingsActions.ts
packages/shared/src/urbit/settings.ts

Adds the option to fallback to our cloud infra for link previews that are hard to get. The fallback serverless function is already deployed.
Adds a privacy option to disable the fallback option and rely only on `%metagrab` itself.
To test, try any of the links that we were having trouble with.
Fixes TLON-4308

links: use rich preview fallback

---

packages/app/ui/components/BareChatInput/index.tsx
packages/app/ui/components/ChatMessage/ChatMessage.tsx
packages/app/ui/components/GalleryPost/GalleryPost.tsx
packages/app/ui/components/PostContent/BlockRenderer.tsx
packages/app/ui/components/draftInputs/LinkInput.tsx

Updates our handling for embeddable links. Previously we were storing them as inline links without metadata. Now, we'll fetch nice previews for them and have this data available in contexts where we don't want to render an embed.
Updates the Link block renderer to optionally display as an embed if one is available.
Notably, this means we'll get nice rich previews in galleries instead of the embed falling back to a raw URL string.
Fixes TLON-4309

embeds: store as rich link blocks

---

apps/tlon-mobile/android/app/src/main/java/io/tlon/landscape/notifications/NotificationManager.kt

fixes TLON-4235
Changes the flags passed to the tap intent on the notification so that tapping a notification no longer restarts the main activity, causing a React remount.
My hypothesis for this bug's cause is:
1. User launches app
2. App starts spinning on _lots_ of DB queries. (Try logging every query that gets run in `createQuery`!) These take a long time to resolve – this is bad but not the main cause of this bug.
3. Close (i.e. background) the app.
4. Receive a notification
5. Tap on the notification – this triggers our "tap intent" that causes the `MainActivity` to (re)launch
6. Because we configured the tap intent with the flags `Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK`... https://github.com/tloncorp/tlon-apps/blob/af5459041ee09b8ed82733c910c3961e355feff6/a …

avoid blank screen on Android notification tap

---

packages/app/ui/components/Channel/useAnchorScrollLock.ts

This PR fixes an intermittent failure to display channel contents. Previously, if the scroller entered a state where it had more loaded posts than the FlatList would render before user interaction, we'd never toggle the opacity of the channel contents. To remedy that, we've added additional fallbacks to ensure the opacity always gets set if posts are available.
- Toggle opacity after anchor post is rendered + scrolled to
- Toggle opacity two seconds after any posts are available, no matter what.
Tested in channels with and without unreads on both mobile and desktop.
`git revert`

fix channel failure to display

---

packages/shared/src/api/channelsApi.ts
packages/shared/src/db/migrations/0000_massive_wrecking_crew.sql
packages/shared/src/db/migrations/meta/0000_snapshot.json
packages/shared/src/db/migrations/meta/_journal.json
packages/shared/src/db/migrations/migrations.js
packages/shared/src/db/modelBuilders.ts
packages/shared/src/db/queries.ts
packages/shared/src/db/schema.ts
packages/shared/src/store/dbHooks.ts
packages/shared/src/store/sync.ts

part of TLON-4215
Adds plumbing to support pinned posts using existing "ordered posts" API feature.
- Sync changes to a channel's `order` from backend to client DB (under `postOrder` – `order` is reserved by Drizzle for the SQL feature).[^0]
- Add `setOrder` API method to directly set a channel's `order` on backend
- [extra] [Disable usePostWithRelations by passing null options](https://github.com/tloncorp/tlon-apps/commit/886417ee7494557ed750f5aa2cb799463b0420c4) – I added this when adding UI code to test pins; slipping it in here because I think it's a good change (i.e. if a component doesn't yet have a post ID, it can now pass `null` instead of an empty string to the hook until it gets an ID)
[`dil/pinned-posts`](../tree/dil/pinned-posts)[^1] has changes to UI to allow pinning a single …

track ordered posts from backend; add API binding to set ordered posts

---

desk/lib/discipline.hoon

Implements a wrapper agent style library that checks mark sanity on the inner agent.
This means the developer must give the library:
1. a list of marks and their types,
2. a list of subscription paths (path prefixes) and their marks,
3. and a list of scry paths (path prefixes) and their marks.
The library will then:
1. on reload, enforce that mark types haven't changed,
2. for each fact, check if the mark is expected, and type-check the data against it,
3. and for each scry, check if the mark is expected, and type-check the data against it.
Subscription and scry paths support empty string for wildcards. As written, they will simply use the first found matching path. Mismatches are printed to the terminal as priority debug prints and logged to posthog as criticals where possible.
Draft …

discipline: enforce mark sanity

---

packages/app/ui/components/ImageViewerScreenView.tsx

Our newly upgraded Tamagui pulls in a newer `react-native-web` runtime. The required version prevents `findNodeHandle` calls, which have been deprecated in React itself. Our web implementation of the `ImageViewer` lightbox has a gesture detector + touch enabled zoom that calls out to this now invalid `findNodeHandle` api, causing a crash.
I'm not totally clear on where the call is happening. Removing `GestureDetector` or `Zoomable` independently doesn't solve the issue, but ripping out both does. There's [some old discussion](https://github.com/software-mansion/react-native-gesture-handler/issues/1036#event-6342907979) in `react-native-gesture-handler` about avoiding these calls.
- Only wrap in a `GestureDetector` on mobile
- Display a standard image in the lightbox instead of one from …

web: fix imageviewer crash

---

packages/app/ui/components/BareChatInput/index.tsx

Prevent messages from getting sent on Web via _Enter_ press if sending is disabled
- in the _Enter_ handling, prevent `handleSend` call if `disableSend` is set.

web: respect disable send state on "enter" press

---

desk/app/chat.hoon
packages/shared/src/api/apiUtils.ts
packages/shared/src/api/chatApi.ts
packages/shared/src/api/postsApi.ts
packages/shared/src/urbit/channel.ts
packages/shared/src/urbit/dms.ts
packages/shared/src/urbit/utils.ts

We somehow did not catch that we weren't using the new marks and subscriptions from the upgrade. Additionally after using those, we discovered an issue with the way that %chat was trying to give responses. This fixes both of those so that DMs now are able to send the new link blocks.
- adjusted the way we were giving `writ-response-1` and `writ-response` so that the types were correct and checked
- swapped our %chat subscription to v1
- swapped our chat types to match new backend types
- swapped poke marks to match
Manually live on screenshare
- Safe to rollback without consulting PR author? No
Consult the author
n/a

chat: fix dm responses

---

packages/shared/src/api/postsApi.ts

Uses the new path for scries so that we get actual rich link blocks.
as above
manually

chat: fix dm scries

---

packages/app/ui/components/BareChatInput/index.tsx
packages/ui/src/components/Image.tsx

We broke image paste on the protocol release branch. This restores that functionality (while still handling image link pastes as well)
- use the existing `usePasteHandler` in `BareChatInput`
- permit `blob` source paths for images in our base `Image` component
Pasted images on web. ~Waiting for mobile to finish building, will try there as well~ it appears we don't support pasting images on mobile, its absence there isn't a regression
- Safe to rollback without consulting PR author? yes
Revert and push alternative fix.
Fixes TLON-4378

chat input: fix image paste

---

packages/shared/src/api/channelsApi.ts
packages/shared/src/db/queries.ts
packages/shared/src/store/sync.ts

This was causing channels to not load and was a late addition to my role change PR so that's why it didn't get caught. I wasn't sure how to keep `insertChannelPerms` with order insertion.
- this splits inserting channel perms and order insertion since they aren't really required to be together
- adds new order insertion to sync
Manually attempting to load channels and ran `pnpm test`

queries: split perms and order to avoid transaction issues

---

packages/app/ui/components/ChatMessage/ReactionsDisplay.tsx
packages/ui/src/components/Emoji/data.ts

More lingering emoji parse issues. Saw some missing from the map when attempting to parse as short code.
- in `getNativeEmoji`, account for input that's already a raw emoji when passed in
- found a missing callback dep in the ReactionDisplay
Checked a reaction that was missing (🫡) before and after
- Affects important code area:  Channel display
Revert and re-open the issue
Fixes TLON-4388

mobile: fix missing reaction emojis

---

desk/app/channels.hoon

When we merged develop into release-channels-updates at some point, we messed up the path of this scry
- corrected scry path
I did not

channels: fix erroneous merge

---

packages/shared/src/store/useChannelContext.ts

Fixes TLON-4413, we were looking at the wrong app/agent for negotiations
- made sure that app and agent are correct in cases of group dms
Manual

use-negotiate: correctly account for group dms

---

desk/app/groups.hoon

Use the type that matches the mark, and actually check the mark when we receive facts.
For the issue described in TLON-4431, though this may not close that ticket entirely.
Groups agent subscribes to channels on /v1, which is going to give %toggle-post and %channel-response-2 facts. In addition to only handling responses, we want to make sure we use the now-older type when unpacking the vase.
It compiles even with the changed type. ~~No deeper testing (yet).~~ Hit the codepath, it no longer crashes.
- Safe to rollback without consulting PR author, yes.
Code-only change.
Maybe one day.
We might be dropping changes in between kicks and resubscribes on the floor entirely. The subscription doesn't give an initial fact, we never scry out current state from …

groups: handle appropriate mark/type for /v1 sub

---

packages/shared/src/db/queries.ts
packages/shared/src/db/query.ts

The issue here was a transaction being initiated via Drizzle's built in transaction helper rather than via our queue implementation. If they happened to collide poorly, we'd get one of the following errors:
```
[op-sqlite] statement execution error: cannot commit - no transaction is active
[op-sqlite] statement execution error: cannot rollback - no transaction is active
[op-sqlite] statement execution error: cannot start a transaction within a transaction
```
Removing the Drizzle reference prevents these from occurring. We also weren't handling nested transactions, so this adds logic to detect if we're already in one without locking up. 
- remove the offending Drizzle transaction in `insertChannelOrder`
- adds a `meta` field to `QueryCtx` for tracking whether we're already within a …

db: avoid nesting transactions

---

apps/tlon-web/e2e/helpers.ts
packages/app/ui/components/ChatMessage/ChatMessageActions/MessageActions.tsx

Renames "Start thread" in Chat channels to "Reply," then renames "Reply" to the more-accurate "Quote." "Quote" appears both in the root of the channel and in threads; "Reply" does not appear in threads (since we only allow one level of nesting).
- Changes the text labels in MessageActions
- Changes the e2e tests (helpers.tsx) to accommodate the language change
I ran the e2e tests locally to ensure no breakages.
- Safe to rollback without consulting PR author? (Yes)
Simply revert as needed.

MessageActions: rename select message actions

---

packages/app/fixtures/PostReference.fixture.tsx
packages/app/ui/components/BigInput.tsx

There were two more places where we were accidentally importing components from `react-native-gesture-handler` where we should have been importing from `react-native`. This fixes those imports.
We can't import anything from `react-native-gesture-handler` on components that need to be rendered on web, because of the `Error: findNodeHandle is not supported on web. Use the ref property on the component instead.` issue.
As far as I can tell, after this PR, there will be no places on web where a use could run into a gesture handler component (and I don't think we plan on allowing web users to use gestures at all, for now).
Changed some import statements.
Ran locally and made sure the app didn't crash/show white screen.
- Safe to rollback without consulting PR author? No, the notebook input …

web: remove some erroneous react-native-gesture-handler imports

---

packages/app/ui/components/ActionSheet.tsx

Fixes TLON-4400 by replacing `Sheet.ScrollView` with `ScrollView` on Android.
Tested on Android device.

fix sheet tap on android

---

packages/app/fixtures/cosmos.decorator.tsx

Previously, Android fixtures that rendered `Toast` would crash due to missing safe area context.
- Stop using default providers, so that:
- Toast's `Portal` accesses an explicit `PortalProvider`
- `PortalProvider`'s mount point can access the `SafeAreaProvider`'s context
Opened the `Channel.notebook` and `Toast` fixtures – before change, these crashed on Android; after, they ran on Android (and toasts showed as expected). Fixtures showed as expected on iOS and web as well.
git revert

fix toast crash on Android fixtures due to missing safe area context

---

packages/app/fixtures/FixtureWrapper.tsx
packages/app/fixtures/NotebookPost.fixture.tsx
packages/app/fixtures/contentHelpers.tsx
packages/app/ui/components/NotebookPost/NotebookPost.tsx
packages/app/ui/components/PostContent/BlockRenderer.tsx
packages/ui/tamagui.config.ts

fixes TLON-4027
Fixes italics and headers, which were both rendering as plaintext on iOS/Android for different reasons.
- Headers were using a custom Tamagui `tag` variant on the `HeaderText` component. There's also a `tag` prop on the underlying Tamagui `Text` component, which instructs Tamagui Web to use a specific HTML tag. I think overloading this prop as a variant was not (stopped?) working; changing the variant name to something else brought back formatting on `HeaderText`.
- With this change, headings on web became a little smaller on my browser, since we're using our own font sizes instead of the default `h1` etc font sizes.
- We were previously using a "font stack" when defining the Tamagui `body` font's `family`: https://github.com/tloncorp/tlon-apps/blob/0885e43346a599c917eb1cc2 …

fix italic, header notebook content rendering

---

apps/tlon-web/e2e/README.md
apps/tlon-web/e2e/gallery-functionality.spec.ts
apps/tlon-web/e2e/helpers.ts
apps/tlon-web/e2e/notebook-functionality.spec.ts
apps/tlon-web/package.json
apps/tlon-web/playwright.config.ts
apps/tlon-web/rube/index.ts
apps/tlon-web/rube/run-single-test.ts
packages/app/ui/components/ActionSheet.tsx
packages/app/ui/components/AddGalleryPost.tsx
packages/app/ui/components/Channel/ChannelHeader.tsx
packages/app/ui/components/GalleryPost/GalleryPost.tsx
packages/app/ui/components/NotebookPost/NotebookPost.tsx
packages/app/ui/components/draftInputs/GalleryInput.tsx
packages/app/ui/components/draftInputs/NotebookInput.tsx

Adds notebook and gallery end to end tests.
Adds documentation for end to end tests.
Adds a new npm script, `e2e:test`, that allows for devs to run single test files with ship management (starts all three ships for you, runs playwright tests, shuts everything down).
fixes tlon-4393
fixes tlon-4392
fixes tlon-4478
Adds new test files, makes some changes to relevant components to make the tests run reliably.
These are tests.
just revert the merge commit

e2e: notebooks, galleries, and documentation

---

packages/shared/src/store/sync.ts

Stop doing an unnecessary reel subscription during reconnect.
This workaround was added to deal with the fact that eyre didn't send initial bytes down the SSE pipe, which caused clients to not consider the connection established until it did.
urbit/urbit#7080 fixed that and went out with 410. We should no longer need this workaround.
It worked without this workaround before the eyre change.
- Yes, safe to rollback without consulting PR author?
Safe and trivial to rollback.
No.

sync: don't subscribe to reel on-reconnect

---

packages/app/ui/components/PostScreenView.tsx

fixes tlon-4282
There was an issue with the reply input's send button not being pressable/interactable on mobile when the keyboard was open. The user could type some text with their keyboard, then press the send/arrowup button, the keyboard would then dismiss, and the user's message wouldn't be sent. If the user then pressed the send button *again* after the keyboard was dismissed, the message would send. This only happened in the Gallery detail view, not Notebook or the chat-like channels.
The Gallery detail view was the only one rendered within a Carousel, which is what led me to look at Carousel.
It turns out that this was happening because touch events were getting captured by the FlatList in Carousel while the keyboard was open. Apparently, we need to pass `"handled"` to the …

gallery detail view: fix issue with the send button not working on the reply input

---

desk/app/bait.hoon

Make bait agent serve appropriate CORS-related headers when responding to GET requests.
Since we want to pull lure link metadata from browser contexts, and theres no problem with the bait/lure service allowing this kind of access, we must include an Access-Control-Allow-Origin header to appease browser security mechanism.
Here, we do so for every GET request handled by the bait agent.
I'm assuming we only care about [the simple requests case](https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CORS#simple_requests), where we _never_ send credentials. We shouldn't need to, so we shouldn't.
It's on loshut-lonreg right now! You can see the header being returned correctly. @latter-bolden take her for a spin, see how she drives.
- …

bait: allow GET requests from any cross-origin

---

packages/shared/src/logic/content-helpers.test.ts
packages/shared/src/logic/content-helpers.ts

Fix indents in codeblocks. Fixes TLON-4403
Move removal of leading / trailing text to `processLine`, which is not used on codeblock lines. There may be an argument for removing leading trimming altogether (there are some non-codeblock cases where this is desirable), but I've kept that behavior for now to keep the change to behavior small.
Tested on web, modified `content-helpers` test code to cover indent in code block.

fix text indents in messages

---

apps/tlon-web/src/app.tsx
packages/shared/src/db/queries.ts
packages/shared/src/store/sync.ts

fixes tlon-4510
I noticed that on Chrome (but not the Safari PWA that I use daily on desktop), the web app was (only recently, and only on ~finned-palmer):
1) pegging the CPU
2) not showing any contacts data.
I first did a trace to find out what was causing the app to use so much CPU, saw that it was caused by timers.
I then used this snippet from Claude to find where the timer calls are coming from by placing it in main.tsx:
```
const originalSetTimeout = window.setTimeout;
const originalSetInterval = window.setInterval;
let timerCount = 0;
window.setTimeout = function(callback, delay, ...args) {
timerCount++;
console.trace(`setTimeout #${timerCount} created with delay ${delay}ms`);
return originalSetTimeout.call(this, callback, delay, ...args);
};
window.setInterval = function(callback, …
```

perf: batch contact inserts into db

---

packages/app/ui/components/AuthorRow.tsx
packages/app/ui/components/GalleryPost/GalleryPost.tsx

fixes tlon-4353
`DetailViewAuthorRow` has an optional `sent` (for the post's sent time) prop and a `showSentAt` prop. If `showSentAt` was `true`, then we tried to show the pretty sent time for the post. *But*, if you passed `showSentAt` but didn't also pass a `sent` prop, we would try to make a pretty time from `new Date(0)`. So, all gallery posts were just showing the pretty time for `new Date(0)` since we were passing just `showSentAt` and not `sent`.
This PR fixes the issue by:
- actually passing the sent time
- not showing the timeDisplay at all if we don't have `sent`.
It also updates `timeDisplay` to show either the prettyTime (if the post was made today) or the prettyDayAndDateAndTime (if it wasn't made today).
Tested on web.
None afaict.
Revert the merge commit.

gallery: fix missing sent time issue

---

packages/app/fixtures/InviteUsersSheet.fixture.tsx
packages/app/ui/components/InviteUsersSheet.tsx
packages/app/ui/components/InviteUsersWidget.tsx
packages/shared/src/store/groupActions.ts

fixes tlon-4409
We weren't:
- indicating that anything was happening while attempting the invite
- disabling the button during the attempt
- logging any errors if the attempt failed
This fixes those things, and also updates the component to use the new `useStore` hook and fixes the broken cosmos fixture.
Tested on web.
- Safe to rollback without consulting PR author? Yes, but we'll lose these things.
N/A
Revert the merge commit.

invite sheet: add loading indicator, error tracking. fix cosmos fixture

---

packages/app/ui/components/ContactBook.tsx

Fixes broken scrolling in the `ContactBook` within `CreateChatSheet`. This will break closing the sheet by scrolling past the top of the contact list, but swiping down from the top of the sheet or dragging the handle still work. Fixes TLON-4514.
Modified `scrollChange` event in `ContactBook` (used to disable drag in the parent sheet, allowing the child `ScrollView` to be scrolled) to always fire on touch start instead of only when scroll offset is greater than 0.
Tested in iOS simulator. 

fix scrolling in create chat sheet

---

apps/tlon-web/src/logic/utils.ts
packages/ui/src/components/Emoji/SizableEmoji.tsx
packages/ui/src/components/Emoji/data.ts
packages/ui/src/components/Emoji/utils.ts

Our regex for detecting native emojis wasn't comprehensive enough to cover all cases of mobile input. The result was displaying our fallback _stop sign_ emoji instead of the desired one.
We've tried custom regex's (including `\p{Emoji_Presentation}`) as well as libraries without finding a solution that covers all cases. The change in this PR is to instead default to displaying whatever's passed in, so long as it's under a character count threshold.
Since this biases towards showing whatever is received,  we may end up displaying non-emoji short strings if users manually insert them. However the UI will only ever permit actual emojis to be sent, so you'd have to issue pokes manually to abuse this.
- tested with the violating emoji before and after
- Safe to rollback without consulting PR …

mobile: fix certain emojis

---

packages/app/ui/components/BigInput.tsx

fixes tlon-4532
We were taking the `uri` value given to us by Expo's ImagePicker and setting `metadata.image` to that value. The value from ImagePicker is just the local URI for the image, not the URI for the uploaded file.
We also weren't disabling the `Post` button while we were in the middle of a send, and send waits for image attachments to upload, so you could get into a state where:
1) you press the Post button
2) you see no visual response (but actually we're waiting on an upload)
3) you press the button again
4) nothing happens
5) you press again and finally something happens
6) now you see three posts in the index.
It would be great if we could just have the user press send and immediately see their post, I assume the upcoming queueing work will achieve that for notebook posts as …

BigInput: use actual uploaded image url for header image on send, disable post button while sending

---

packages/app/ui/components/BareChatInput/index.tsx

fixes tlon-4507
Shows a box with a loading spinner while we're loading the link preview, allows the user to send the message before the preview is loaded, also cancels loading link previews if the message is sent before the preview is loaded.
Tested on web and iOS simulator.
Revert the merge commit.
(web)
(iOS)

input: show link preview loading, don't block send

---

desk/app/channels-server.hoon
desk/app/channels.hoon
desk/app/chat.hoon
desk/mar/chat/blocked-by.hoon
desk/mar/chat/unblocked-by.hoon

Apply /lib/discipline to chat, channels and channels-server agents.
We do a best-effort manual search through the codebase for facts and
scries as they're currently implemented, and explicate their behavior as
arguments to /lib/discipline. This will help us maintain consistent
types and apis going forward.
We also patch up some marks which were found to be broken during this.
Ran on a local fakezod, used the web client, checked to see if there were any prints from the discipline library. There are not. Note that I did not hit every conceivable codepath, or every old version of the api.
`gh revert #4902`

various: /lib/discipline integration

---

apps/tlon-mobile/android/app/src/main/java/io/tlon/landscape/MainActivity.java

fixes tlon-4543.
Apparently:
> Before targeting SDK 35, using android:windowSoftInputMode=”adjustResize” was all you needed to maintain focus on — for example — an EditText in a RecyclerView when opening an IME. With “adjustResize”, the framework treated the IME as the system window, and the window’s root views were padded so content avoids the system window.
> After targeting SDK 35, you must also account for the IME using ViewCompat.setOnApplyWindowInsetsListener and WindowInsetsCompat.Type.ime() because the framework will not pad the window’s root views.
see: https://stackoverflow.com/questions/79177674/windowsoftinputmode-adjustresize-doesnt-work-in-target-sdk-35/79364446#79364446
https://github.com/facebook/react-native/issues/49759#issuecomment-3048056660
Tested on physical android …

android: fix issue with KeyboardAvoidingView

---

packages/app/ui/components/draftInputs/GalleryInput.tsx

fixes tlon-4443
We had an issue where if a user posted a link block in a gallery and went back to edit it the link would disappear after their edit. We have a `useEffect` in the `GalleryInput` component where we try to determine what the post type is and route the user to the correct input. We weren't accounting for links there.
Updates that `useEffect` to account for link blocks, adds a `mockAttachment` so we can re-attach the link.
Tested on web.
Revert
https://github.com/user-attachments/assets/d4ac8773-3110-465d-b77e-a9ec78b8f569

gallery: fix issue with editing gallery link blocks

---

packages/shared/src/store/activityActions.ts

fixes tlon-4472
Fixes an issue where the "mute thread" action on a message never worked.
We had been passing the child post as the `source` for the volume setting adjustment, rather than the parent. The fix is just grabbing the parent post and using that as the `source` instead. If we don't have a parent post ID, then we are the parent, and we pass the post itself instead (we currently don't allow muting the root/parent post in the UI, but this enables us to allow that in the future if we want).
Tested on web.
Revert

threads: fix thread mute issue

---

packages/app/ui/components/ChatMessage/ReactionsDisplay.tsx
packages/app/ui/utils/postUtils.test.ts
packages/app/ui/utils/postUtils.tsx
packages/shared/src/db/queries.ts

Fixes TLON-4536 where we weren't querying for contact details along with reactions to posts, which caused an issue where nicknames occasionally would fail to display in the reaction tooltip on desktop. Furthermore, this adds an additional step to the nickname computation to show overridden nicknames.
- Modifies the getThreadPosts, getChannelPostsAround (beforePosts, afterPosts), getChannelSearchResults, and getPostWithRelations queries to also include contact details (root cause)
- Moves the more complex logic for useReactionDetails inside its own function, which is still memoized and returned in the parent hook
- Computes the "correct" nickname to show in the reaction details following the override/user-set/bare-patp priority chain
- Defensively trims the list to 3 reactors as before
- …

queries, postUtils, ChatMessage: consistent nickname display in reaction tooltip

---

desk/app/groups-ui.hoon

The groups-ui `/v2/heads` scry was crashing due to a type mismatch on one its internal scry into chat agent. We make that scry a newer endpoint to resolve this.
This got missed during the sequence number addition in #4867. The scry into chat was using the new (updated) type for the old endpoint.
Ideally, you'd bump the entire groups-ui endpoint here, since part of its type changes. However, /v2/heads was never integrated into the client. We can get away with just updating the scry to retrieve data with the new (updated) types from chat and call it a day.
(Perhaps in a fully discipline'd world these kinds of shenanigans wouldn't fly, but we don't live there yet...)
Saw the scry (via http) fail before my change. Got a json response back after my change. The response includes sequence …

groups-ui: complete /v2/heads transition wrt chat

---

desk/app/grouper.hoon

This fixes an issue found where newly joining ships were not getting a DM invite from their inviter. This was caused by a mark/type mismatch. Additionally logging was lacking here so I fixed that too.
- change `chat-dm-action` to `chat-dm-action-1` to match the type we were sending
- move 'DM Invite Sent' event to only send on successful poke to ourselves
- add 'DM Invite Fail' event when we get a poke-nack
Ran changes locally, used personal invite lure and sent an HTTP request to simulate a bite.

grouper: make sure we use the right mark and handle logging correctly

---

apps/tlon-web/e2e/README.md
apps/tlon-web/e2e/app-settings.spec.ts
apps/tlon-web/e2e/chat-functionality.spec.ts
apps/tlon-web/e2e/direct-message-mismatch.spec.ts
apps/tlon-web/e2e/direct-message.spec.ts
apps/tlon-web/e2e/gallery-functionality.spec.ts
apps/tlon-web/e2e/group-cross-ship-visibility.spec.ts
apps/tlon-web/e2e/group-customization.spec.ts
apps/tlon-web/e2e/group-info-settings.spec.ts
apps/tlon-web/e2e/group-lifecycle.spec.ts
apps/tlon-web/e2e/group-protocol-mismatch.spec.ts
apps/tlon-web/e2e/helpers.ts
apps/tlon-web/e2e/invite-service.spec.ts
apps/tlon-web/e2e/notebook-functionality.spec.ts
apps/tlon-web/e2e/profile-functionality.spec.ts
apps/tlon-web/e2e/roles-management.spec.ts
apps/tlon-web/e2e/test-fixtures.ts
apps/tlon-web/e2e/thread-functionality.spec.ts
apps/tlon-web/playwright.config.ts
apps/tlon-web/rube/run-single-test.ts
apps/tlon-web/src/env.d.ts
packages/app/lib/envVars.ts
packages/app/ui/components/ChatMessage/ChatMessage.tsx
packages/app/ui/components/ChatMessage/ChatMessageActions/MessageActions.test.tsx
packages/app/ui/components/ChatMessage/ChatMessageActions/MessageActions.tsx
packages/app/ui/components/GalleryPost/GalleryPost.tsx
packages/app/ui/components/NotebookPost/NotebookPost.tsx
packages/app/ui/components/ScreenHeader.tsx
packages/shared/src/domain/constants.ts
packages/shared/src/store/dbHooks.ts

Fixes TLON-4554 where one could "hide" their own message without being able to unhide, resulting in an unrecoverable state.
- Adds a conditional to our "which message actions to show when" chain to cover this
- Adds a unit test to ensure one can't hide their own posts
- Changes the chat functionality e2e tests to use ~zod and ~ten (no version mismatch)
- Introduces a new step to the e2e tests in which ~zod authors a message, switches contexts to ~ten, and hides the message on ~ten
- Fixes a race condition in the e2e tests where hovering over a chat message would fail because it would incorrectly target the sidebar preview text rather than the message itself in the channel
- Adds a navigateToChannel helper for e2e tests
- Fixes the single-test running issue for e2e
1. Author a post
2. …

MessageActions: prevent users from hiding their own posts

---

desk/app/groups.hoon

OTT, we've had the wrong type since at least https://github.com/tloncorp/tlon-apps/commit/090064947280d4d2e342227783e63598c4356b8c 
- changed update-0 to news-0
Manually changing profile from one ship and watching terminal from listening ship

groups: change to correct type for take-contact

---

desk/app/groups.hoon

Found a few issues while I was testing changes, mostly around path specificity and core referencing. This addresses all that I've found so far.
- Fixed index previews not initializing `se-core` with group
- Fixed index preview crashing because of check in se-abet, since we aren't modifying we didn't need to call `se-abet`
- Fixed path matching order so we actually hit the cases for `%index`
Manually using two ships across the network.

groups: fix refactor issues with index previews

---

desk/app/chat.hoon

We missed a wire when adding sequence numbers to %chat. This adds that in.
- Adds support for v2 wires
Compiled and manually added slog to on-fail to make sure we aren't seeing crashes (removed before committing)

chat: add missing wire

---

packages/app/ui/components/PostContent/BlockRenderer.tsx
packages/shared/src/logic/utils.ts

fixes tlon-4550.
Our `URL_REGEX` only checked if a string contained a valid URL *anywhere* in the string, not whether the string is *only* a valid URL. So a user could input any string into the URL input on gallery's LinkInput and it would be considered valid so long as that string had a URL within it. Adding the `^` and `$` anchors to the regex pattern fixes this.
The crash that Eleanor was seeing was caused by BlockRenderer attempting to render a link block where the URL was one of these invalid strings that contained URLs but weren't *just* URLs. We shouldn't crash in this case, we should just show a URL preview that tells the user the URL is invalid (and going forward, there shouldn't be anymore invalid URLs that we attempt to render in BlockRenderer).
Tested on web.
- Safe to …

link input: fix URL validation issue

---

desk/app/groups.hoon
packages/shared/src/db/queries.ts

fixes tlon-4468
Users were seeing an issue where channel permissions made on web were not reflected on the mobile client unless they killed the app and re-opened. It turns out this was caused by `updateChannel` being constructed in such a way that we didn't attempt to update channel permissions if we didn't receive both `writerRoles` and `readerRoles` in the update. For instance, we would receive an event on the channels subscription indicating we needed to add writers, but that event only contained `writerRoles`; we would pass that to `updateChannel`, and that query would complete without updating the `writers` property because we didn't have both roles arrays. The fix here was just to account for the fact that we could receive updates that are only about readers or writers.
My original …

fix channels perms persistance issue

---

packages/app/ui/components/ChatMessage/ChatMessageActions/MessageActions.tsx

Fixes TLON-4371 by only showing the edit button for admins of a group containing a Notebook channel for the Notebook posts themselves, not the comments beneath.
Adds a condition to the show/hide logic for the edit action in MessageActions. If the post does not have a parent, we can assume it's at the root level of the channel.
- Navigate to a group where you are the admin and others have commented on notebook posts
- Click the ... message actions on anothers' comment
- Observe that you are now no longer able to edit the comment (which didn't work anyway, hence TLON-4371)
git revert

MessageActions: only show admin edit for notebook posts themselves

---

packages/app/ui/components/Activity/ActivitySummaryMessage.tsx

Fixes TLON-4488 by using the correct grammar for single or multiple ships asking for permission to join a group.
In ActivitySummaryMessage, plurality for the rest of the relevancy types is determined by summary.all.length > 1, but for this case it should be determined by authors.length > 1.
The summary.all array contains all the activity events, which could include multiple events from the same user, while authors contains the unique list of users. So even if there's only one user requesting to join, if they have multiple events in summary.all, it would incorrectly show "are" instead of "is".
Therefore, we should see the following notifications for...
```
1 ship: "~zod is requesting to join the group"
2 ships: "~zod and ~bus are requesting to join the group"
3 ships: "~zod, ~bus, and ~web …
```

ActivitySummaryMessage: fix plurality for group join requests

---

packages/app/ui/components/Channel/ReadOnlyNotice.tsx

This was annoying me. At one point in the past we used to just return a string instead of a React fragment. I assume we simply missed this.

ReadOnlyNotice: remove single-quotes around message

---

packages/app/ui/components/ChatOptionsSheet.tsx

fixes tlon-4366
We added this fix at some point to ChannelOptionsSheetLoader but didn't make the same change to GroupOptionsSheetLoader. We just need to call `resetPane()` when we hear that the sheet is not open so we can avoid having the last pane appear when the sheet is opened again.
Web
Revert

ChatOptionsSheet: make sure pane state is reset when the sheet/popover is closed.

---

packages/app/ui/components/ActionSheet.tsx
packages/app/ui/components/ChatOptionsSheet.tsx

Fixes tlon-4602.
~Fix intermittent button press issues in ActionSheet on iOS where buttons required multiple taps to trigger actions (or, in some cases, the buttons would never trigger the actions at all). Replaced unreliable onPress callbacks with onPressIn/onPressOut events and manual state tracking to ensure reliable touch handling in modal contexts.~
~I assume there is something happening here that is causing normal onPress to fail because we're in a modal context. When we were using onPress you could still see the press register visually (the press style would be applied), but the handler would never fire.~
Update: the issue was resolved by switching from `ActionSheet.ScrollableContent` to `ActionSheet.Content` in `ChatOptionsSheet`. The `onPressIn`/`onPressOut` solution was …

ActionSheet: fix issue with unreliable button presses

---

packages/app/ui/components/InviteUsersWidget.tsx

Fixes TLON-4622 by preventing the user from inviting contacts and other ships who are already members to the group again.
When users access the "Invite people" menu, the InviteUsersWidget now extracts all existing group member IDs. These member IDs are passed to the ContactBook component as the immutableIds prop.
The ContactBook component then uses these IDs to mark contacts as immutable, which shows a blue checkmark next to their names, prevents them from being selected for invitation, and provides clear visual feedback that they're already group members.
- Select the "Invite people" group option for a group you have invite rights for (admin/host of a private/secret group or member of a public group)
- Note that if some of your contacts are in the group, they are unselectable
- Enter a …

InviteUsersWidget: disable users who are already members to prevent double-inviting

---

apps/tlon-mobile/android/app/build.gradle
apps/tlon-mobile/ios/Landscape.xcodeproj/project.pbxproj

v6.2.0 for native, v7.3.0 for web

ops: bump client versions

---

apps/tlon-web/e2e/chat-functionality.spec.ts
apps/tlon-web/e2e/forwarding-functionality.spec.ts
apps/tlon-web/e2e/gallery-functionality.spec.ts
apps/tlon-web/e2e/group-customization.spec.ts
apps/tlon-web/e2e/group-info-settings.spec.ts
apps/tlon-web/e2e/group-lifecycle.spec.ts
apps/tlon-web/e2e/group-protocol-mismatch.spec.ts
apps/tlon-web/e2e/helpers.ts
apps/tlon-web/e2e/notebook-functionality.spec.ts
apps/tlon-web/e2e/roles-management.spec.ts
apps/tlon-web/e2e/test-fixtures.ts
apps/tlon-web/e2e/thread-functionality.spec.ts
packages/app/ui/components/ListItem/GroupListItem.tsx
packages/app/ui/components/ListItem/ListItem.tsx

This adds a new test for unreads and removes some lingering cleanup steps in individual tests that we no longer need (covered by our test fixtures).
These are tests.
Revert

e2e: add test for unreads, remove some unnecessary lingering cleanup steps in other tests 

---

packages/app/ui/components/ActionSheet.tsx

fixes tlon-4023 by ensuring our popovers on desktop can only be so tall and can be scrolled if the content is long enough.
- Added `maxHeight` constraint to popover mode in ActionSheet component (50% of viewport height)
- Wrapped popover content in `ScrollView` with vertical scroll indicators when content overflows
- Added `overflow: hidden` to prevent content bleeding outside popover bounds
- Set `strategy="fixed"` for better viewport positioning on desktop
- Maintained existing `allowFlip` behavior for automatic placement adjustment
Tested on web. Doesn't effect mobile.
Revert
https://github.com/user-attachments/assets/f7b34110-5e2b-4b67-b021-1ed35e79bbee

desktop: handle tall popovers

---

packages/app/ui/components/ChatMessage/ChatMessage.tsx
packages/app/ui/components/ChatMessage/ChatMessageActions/Component.tsx
packages/app/ui/components/ChatMessage/ChatMessageActions/MessageActions.tsx
packages/app/ui/components/ChatMessage/ReactionsDisplay.tsx
packages/app/ui/components/GalleryPost/GalleryPost.tsx
packages/app/ui/components/NotebookPost/NotebookPost.tsx
packages/shared/src/types/ChannelActions.ts

Fixes TLON-4628 by removing the ability to...
- add emoji reactions (edit)
- quote
- comment / reply
... for posts in channels you do not have write access to.
Imports the channel context into Chat messages, Gallery blocks, and Notebook posts so we have the user's canRead / canWrite status. Passes this down to the message actions component, which then uses a filter in the channelActionIdsFor function to only allow those we deem OK for writers. Also uses canWrite to hide the emoji quick-reaction block.
Also restores the "Reply" or "Comment" option for posts that already have a thread under them.
- Go to Gallery, Notebook, and Chat channels you have read-only access to
- Access the message actions menu for each
- You should be able to:
- Copy a reference link
- Forward
- Report
- Hide …

ChatMessageActions: hide certain actions for !canWrite

---

packages/app/fixtures/ChatMessage.fixture.tsx
packages/app/ui/components/ChannelSearch/SearchResults.tsx
packages/app/ui/components/ChatMessage/ChatMessage.tsx
packages/app/ui/components/PostContent/ContentRenderer.tsx
packages/app/ui/components/PostContent/InlineRenderer.tsx
packages/app/ui/components/PostContent/contentUtils.tsx

fixes tlon-4320
Adds highlighting for search query text in search results.
- Added optional `searchQuery` parameter to pass search terms through the content rendering system
- Created `highlightSearchTerm` utility function with case-insensitive regex matching and proper escaping of special characters
- Added styled component using `$yellowSoft` background color for highlighted search terms
- Modified to apply highlighting when search query is present in context
- Updated component chain (`SearchResults` → `SearchResultComponent` → `ChatMessage` → `ContentRenderer`) to pass search query from search screen to text rendering
Tested on web and iOS.
Revert
Desktop web:
iOS:

chat: highlight search text in search results

---

.gitignore
CLAUDE.md
apps/tlon-web/e2e/README.md
apps/tlon-web/e2e/dm-thread-functionality.spec.ts
apps/tlon-web/e2e/helpers.ts
apps/tlon-web/e2e/thread-functionality.spec.ts
apps/tlon-web/package.json
apps/tlon-web/rube/playwright-dev.ts
apps/tlon-web/rube/run-single-test.ts
start-playwright-dev.sh
stop-playwright-dev.sh

Enhances our e2e test environment for use with Claude Code, particularly with the Playwright MCP server. Adds new/more comprehensive thread testing that would have caught the issues we found last Friday.
- Updates CLAUDE.md with lots of instructions about our e2e tests.
- Adds new `e2e:playwright-dev` script for setting up an environment that mimics the one that is used by playwright (uses rube to setup/start ships, then starts vite servers for each).
- Adds start-playwright.sh and stop-playwright.sh so that claude code can reliably start `e2e:playwright-dev` and leave it running in the background while it uses the Playwright MCP server to debug test failures, then kill the script cleanly.
- Updates `e2e:test` so that it just prints which tests passed/failed and then quits, allowing …

e2e: add new claude tooling, add thread tests

---

desk/app/channels-server.hoon
desk/app/channels.hoon
desk/tests/app/channels-server.hoon
desk/tests/app/channels.hoon

In real-world conditions, the vases coming in to agents will have the types on them that match the marks on their cages. The tests were failing to account for this, and so didn't catch that this code was subtly broken. We patch both the tests and the code here.
First we patch up the existing tests to account for the new discipline wrapper properly. Then we add a new test for the channels-server side of the poke-based sequence nr negotiation flow.
With that setup done, we patch the tests to more accurately simulate real-world invocations, and finally make one-line changes to the agent code to handle these invocations correctly.
Updated the tests to be more accurate, which made them fail. Updated the code to make the new tests pass.
`;;` is notorious for being slow in some select cases. ~~I …

channels/server: ;; instead of !< for sequence nr pokes

---

desk/app/groups.hoon

The groups agent did not issue a leave for the upgraded group updates subscription path. This caused lib-negotiate to automatically try to re-establish subscription on the old path, resulting in a watch-nack which the agent did not expect, and silently ignored, as it wasn't in the "group join in progress" state. We fix this by issuing leaves, properly handling watch-nacks and re-establishing subscriptions post migration.
The fix consists of three parts:
1. We issue leaves for deprecated subscriptions during migration, which is going to prevent reception of watch-nack.
2. We nonetheless log any watch-nacks on group updates wire as critical error, as they now should be truly unexpected.
3. We safely re-subscribe to each group post migration. This guarantees that all old subscriptions are …

groups: properly upgrade group subscriptions

---

desk/app/groups.hoon

In some cases full group log replay would fail at the subscriber side – a seat might not always be present when targeted by other updates. While this has been observed already in TLON-4657, in this case a seat could be already deleted, or not yet instantiated while some other update tried to reference it.
In particular, we found and fix two cases here:
1. A group host would incorrectly try to issue notification for a seat that already had been deleted in an +se-core update. We detect a missing seat and do not attempt to send the notification.
2. A subscriber would try to check his own admin permissions for certain events during log replay, forgetting that in fact his own seat might not yet be created.
I repeated the reproduction in TLON-4657 and observed the ship joining without problem, …

Robustly handle log replay at the client side

---

desk/app/groups.hoon

The new groups agent introduced a sync mechanism that is also used from channels. New group members receive the group log and apply it locally. However, each group update caused a response to be emitted to the client, slowing down the group join process. This PR fixes this by preventing responses from being generated until the group log has been fully applied. At the end of the process a synthetic group %create response is sent to the client.
`+go-response` is modified to only send out responses after group initialization has completed.
`+go-apply-log` now sends a single synthetic %create event, but only upon group initialization.
Joined Tlon's group, which before the fix took about 2 minutes join. With this fix the join time is down to about 10 seconds.
- Safe to rollback without …

Fix group join performance

---

desk/app/channels-server.hoon

A poke was added in #4996 that uses this wire, but no handling of the resulting signs was implemented. We don't particularly care what the member does with the "please join" notification, so we just no-op whenever we get a result.
The proof writes itself.
- Sure, safe to rollback without consulting PR author if you really must.
`git revert`

channels-server: handle signs from /request-join wire

---

desk/app/groups.hoon
desk/lib/groups-conv.hoon

We prune bad gangs entries for groups that are already joined and initialized. Without this, a migration running on a ship which contains "join in progress" despite being already joined to the group would trigger a re-join and the ship would have left the group, deleting its local state.
We introduce two changes to make the agent robust against this and similar problems in the future. 
1. Most immediately, we prune the gangs state removing entries for groups that are already joined  and had been initialized. 
2. We handle a watch-nack for a group robustly – if a group is already joined and initialized, we don't leave the group, but only log a critical error. 
By the way, we improve `+se-compat-send-invites` by initiating negotiation before issuing an invite poke. (Also fixing a `+roll` …

Robustly handle inconsistent gangs state during the migration

---

desk/app/channels.hoon

Fixes two small issues with the `/range` endpoint identified by @latter-bolden.
- Give `newest: 0` instead of `newest: 1` if a channel has no posts yet.
- Don't respect messages with `seq=0` while traversing the message list for building the `/range` response.
Tested manually by running queries and observing the changes. 
Could just revert if needed. This endpoint isn't used in production yet.

channels: /range endpoint tweaks

---

desk/app/groups.hoon

Fixes issue found in onboarding testing with non-host admin created invites. 
- moved `?>  from-self` check to be in more idiomatic place

groups: checking from self higher up to avoid fact return src mixup

---

desk/app/channels.hoon

Adds a missing mark `%channel-denied` that can be received on all `/said` endpoints.
Compiled.
PR can be reverted.

channels: add missing mark for /said paths

---

CLAUDE.md
apps/tlon-web/e2e/auth.setup.ts
apps/tlon-web/e2e/chat-functionality.spec.ts
apps/tlon-web/e2e/direct-message-mismatch.spec.ts
apps/tlon-web/e2e/forwarding-functionality.spec.ts
apps/tlon-web/e2e/gallery-functionality.spec.ts
apps/tlon-web/e2e/group-cross-ship-visibility.spec.ts
apps/tlon-web/e2e/group-protocol-mismatch.spec.ts
apps/tlon-web/e2e/helpers.ts
apps/tlon-web/e2e/notebook-functionality.spec.ts
apps/tlon-web/e2e/shipManifest.json
apps/tlon-web/e2e/test-fixtures.ts
apps/tlon-web/e2e/thread-functionality.spec.ts
apps/tlon-web/package.json
packages/app/ui/components/ChatMessage/ChatMessage.tsx
packages/app/ui/components/ChatMessage/ChatMessageActions/Component.tsx

Fix E2E test flakiness by implementing comprehensive stability checks. Tests were failing unpredictably in CI due to React render timing, navigation transitions, loading states, and message delivery confirmation issues. Created a `waitForSessionStability()` function that ensures the application is stable before operations, reducing many test failures (down to a few flakey tests, most tests pass the first time).
Also, I disabled the forward-functionality test. I could not get this one to pass, we'll need to make a ticket for fixing it.
- Add `waitForSessionStability()` function to wait for React renders, navigation completion, loading states to clear, and message delivery
- Apply stability checks to lots of helper functions throughout the test suite
- Add new `acceptGroupInvite()` helper …

e2e: reduce flakiness

---

CLAUDE.md
apps/tlon-web/e2e/shipManifest.json
apps/tlon-web/rube/README-ARCHIVING.md
apps/tlon-web/rube/archive-piers.sh
apps/tlon-web/rube/verify-archives.sh

Automates the manual e2e pier archiving process with scripts that handle archive creation, GCP upload, and validation, replacing the previous error-prone manual workflow.
- Added `archive-piers.sh` script that fully automates the pier archiving workflow:
- Starts playwright-dev environment and applies desk updates
- Archives zod, ten, and mug piers (excludes bus for protocol testing)
- Validates archives locally before upload to catch corruption early
- Uploads to GCS with proper permissions and updates shipManifest.json
- Supports dry-run, verification, and cleanup options
- Added `verify-archives.sh` script for comprehensive validation:
- Downloads archives from manifest URLs
- Tests pier extraction and essential file presence
- Verifies each pier can boot successfully
- Added …

e2e: automate pier archiving and gcp upload

---

desk/app/chat.hoon

Fixes TLON-4703. We found this when testing the tombstones migration. Because chats were sequenced before the tombstone work, any deletes that have happened since will create gaps in the sequence. This runs the same sequencing logic as the previous update, but now that we have tombstones we should never drop a number.

chat: resequence chats to restore missing numbers

---

desk/app/channels.hoon
desk/tests/app/channels.hoon

Ensure we fetch sequence numbers and tombstones, even if the channel host doesn't update as fast as we do.
In #4889, we had made channels explicitly fetch sequence numbers from the host, to make sure we were in sync. In #4963, we made it do the same for tombstone data.
The logic for those two flows was/is identical, but had a serious flaw: when sending out the poke, we don't check whether lib negotiate thinks we match.  
This isn't a problem for the logic itself, it's robust against poke-nacks. But negotiate will crash the event, because sending a poke to a mismatching peer is considered an implementation error.  
That crash would kill the timer event and call `+on-fail`, which contains no recovery logic for this scenario (and couldn't even if it wanted to). As a result, some channels …

channels: content negotiation fixes

---

desk/app/channels.hoon
desk/tests/app/channels.hoon

Detects duplicate message sends and prevents them from being processed.
The client does not always have enough information to know whether its message send made it into the backend, so it retries rather aggressively. This may result in messages being sent multiple times.
Here, we make the backend track the sent-at timestamps for messages. The client guarantees that each has a unique sent-at timestamp, so we can use those to detect and prevent duplicate messages from being sent.
Even though it's ephemeral state, we must unfortunately add it into the $state type proper. The alternative is threading is all the way through into and out of the helper core, which would be less than pretty.
Wrote and ran the tests. Also tested by manually poking with the same poke repeatedly.
- Safe to rollback …

channels: prevent duplicate post sending

---

desk/app/chat.hoon
desk/app/groups-ui.hoon
desk/mar/chat/changed-writs.hoon

Make chat's /changes mirror channel's by omitting `null`s (a la 0ec40d1), and include it in the groups-ui global /changes scry.
That's it, those are the changes. Note that this changes the type of the `%chat-changed-writs` mark, which test ships that had the integration branch already might get upset about.
Manually invoking the scry endpoints.
- Safe to rollback without consulting PR author, sure.
Can just revert, though again beware of the mark type change.

chat: /changes tweaks

---

desk/app/groups.hoon

In new groups there are three kinds of updates that are restricted to admin members. These are: token, pending ships, and entry requests. A non-admin ship should never hear about such updates. However, we presently don't correctly handle a case of a previously non-admin member that acquired admin rights and heard about token deletion.
The chance of this happening is minimal, because for now we neither delete tokens, nor expose this functionality to the user, but we should deploy this change as a safeguard before a proper fix to this problem, in connection with robust group resubcriptions is implemented.
Removes assertion and prevents crashing on non-existent token deletion.
Compiled.
- Safe to rollback without consulting PR author? No, because could trigger a group desync.
- Affects …

groups: delete tokens without crashing

---

desk/app/groups.hoon

Some third-party developers (notably %quorum) seem to be using groups to host their custom content unsupported by channels. They do this by modifying the group-side nest kind. This causes crashes on ships hosting such content.
We normalize the nest kind and cast it to the channels $kind type, ensuring the scry
is going to succeed.
I have setup two ships and created a group with multiple channels. I have confirmed that the `active-channels` set is correctly updated. I have then setup a new channel, which was correctly reflected in `active-channels` on the subscriber.
Revert.

groups: normalize channel kind in active-channels sync

---

desk/lib/channel-utils.hoon

We might receive all kinds of `kind=path` values for message previews/reference resolution. We generally shouldn't crash on these, especially not in logic that's just there to give old-style data on old subscription paths. We remove the crash and fall back to `[%chat ~]` in unrecognized cases.
First, we must respect /[kind]/unknown paths and similar, since those will be produced for missing or deleted posts.
Kinds we don't recognize at all will now simply fall back to pretending to be %chat messages, instead of crashing the whole event when they get processed.
Smoke-tested for message handling in general.
Revert.

channel-utils: best-effort kind-data downconvert

---

apps/tlon-mobile/src/App.main.tsx

We were seeing crashes related to Tamagui tamagui theme. In the warning it says "99% of the time this is due to mismatched @tamagui packages" but all of ours are on the same version.
Inspecting the trace, the error gets emitted from the app's top level `ErrorBoundary` component. We mount it above the Tamagui provider, so it blows up when rendering since it uses Tamagui components for the error screen visual. Since the error boundary component itself crashes, the underlying issue gets swallowed.
- Move the root `ErrorBoundary` below the `BaseProviderStack` (the component that mounts Tamagui theme)
in `<App />`, I threw an error. Confirmed before the change all that shows up is the Tamagui theme. After the change, the error screen is shown and the actual thrown error is logged.
- Safe to …

mobile: move ErrorBoundary below BaseProviderStack

---

packages/app/ui/components/InviteUsersWidget.tsx
packages/app/ui/contexts/chatOptions.tsx

Addresses a few things we found during QA. Fixes TLON-4725
- Reverts the change where we prevented the user from inviting other users who are already in the group. Unfortunately you do need to re-invite someone, sometimes.
- Adds a timeout between the group long-press menu and the "Invite people" sheet popping. Similar to the problem we found before, Expo 52 is much more strict about unmounting and remounting.
Tested in iOS simulator.
Revert

misc: v6.2.2 fixes

---

packages/app/lib/nativeDb.ts

After subsequent logins on the same app install, migrations were failing to run causing a cascade of errors and an empty ChatList.
We added a `didMigrate` flag to `NativeDB` in https://github.com/tloncorp/tlon-apps/pull/4988. During logout, we call `resetDb` which in turn runs `purgeDb` followed by `runMigrations`. The former was fully resetting the database, but leaving the `didMigrate` flag set. This meant the follow on migrations call was a no-op.
To resolve, we can just reset the flag when we reset all the other class instance properties in `purgeDb`.
Note, we attempted a previous spot fix [here](https://github.com/tloncorp/tlon-apps/pull/5035), but didn't find this.
Fixes TLON-4727
Log in, log out, log back in. 
Before the change: empty ChatList stuck in _Loading..._ 
After the …

db: fix bug in NativeDB after reset

---

.github/workflows/ci.yml

Fixes CI incorrectly showing as passing when e2e test script execution fails in containers on our self-hosted Fedora runners.
When `pnpm e2e:force` failed inside the container (without running the tests yet), the bash script continued to the next command (`chmod -R 777 /workspace || true`) which succeeded. This success exit code masked the test failure, making the CI step appear green.
This PR adds `set -euo pipefail` to container bash scripts so they exit immediately on any command failure, preventing subsequent commands from masking the failure.
- Testing by putting this PR up and letting it CI run a few times.
Revert.
N/A

e2e: fix issue with failures not being reported in ci workflow

---

desk/app/groups.hoon

There are group hosts of the network with the group log containing inconsistent updates, when replayed from the beginning. This is an inheritance from old groups, and little can be done about it, short of attempting to sanitize logs to make sure they apply cleanly. For now, however, we simply restore the robust behavior of old groups which does not result in a crash prevent group join on some hosts.
Fixes TLON-4739.
1. Prevent crashes in`+go-u-seat` by defaulting to no-op when a seat is not found.
Run on a test moon. Verified that a group join fails prior to this fix with the same cause. After the fix was deployed, the group was successfully joined.
- Safe to rollback without consulting PR author? No.
Revert, at the risk of breaking some group joins.

groups: robustly handle invalid seat updates

---

apps/tlon-mobile/src/App.main.tsx

`expo-splash-screen` has a bug in the native implementation for `SplashScreen.hideAsync`. To actually close it, it needs to target the splash view and uses a heuristic to find it. If a modal view is popped before the splash is hidden, it finds that modal instead and fails to remove the actual splash view.
This happened when you hit `GettingNodeReady` on a fresh install because it immediately pops a notification permission prompt for letting you know when your ship is booted. There are probably other circumstances where this can get hit that we didn't know about. For example, deeplink click while authenticated will immediately pop a group preview sheet.
To avoid this condition, we gate rendering `<App />` until the splash has been successfully hidden. We shouldn't be popping modals any …

mobile: prevent locking on splash screen

---

packages/app/ui/components/ManageChannels/EditChannelScreenView.tsx

Fixes tlon-4444 by ensuring we wrap appropriately in ChannelRoleSelector when we reach the end of the container with role names.
Tested on web and iOS.
Revert

roles: make sure all roles are visible in ChannelRoleSelector

---

packages/app/lib/splashscreen.ts

Fixes empty chat list issue in web app where users would see "Welcome to Tlon" message immediately after loading before data had synced from the backend.
The `splashScreenProgress` system was added about a month ago to manage loading states across platforms. A few days after it was added, a 5-second timeout was added to all splash screen tasks. This timeout forced the UI to display after 5 seconds even if data hadn't synced yet. Since the web app creates a fresh database on every page load (unlike mobile which persists it), the timeout would expire before initial sync completed, resulting in users seeing an empty chat list until data arrived moments later. Prior to the `splashScreenProgress` system, the web app used a simple `dbIsLoaded` check with no timeout system.
- Modified splash …

web: remove 5s timeout for database loading to prevent empty chat list

---

desk/app/groups.hoon

While testing the _other_ group channel init problem, it was discovered that the special case logic introduced in  `+go-u-create` to optimize group joins does not apply when running on the group host, which can't track its own group initialization status (group is always considered initialized, even though we might not be joined). This caused a `%create` response not to be emitted when self-joining a group. 
Note that this should not cause any visible issues, since the client eagerly populates a newly created group and does not rely on the `%create` event.
1. Restore the original logic in `+go-u-create`. When a group is not initialized, a check in `+go-response` is going to prevent it from being sent out, so for a subscriber joining a group this change amounts to nothing. For a group …

groups: restore create response in +go-u-create for group self-joins

---

desk/app/channels.hoon

Due to internal pre-release version churn, we got into another unique one-off bad spot: some clients got the latest patch before the publishers they care about. Unlike on livenet, there was no protocol mismatch to prevent them from asking for a sync. So they got a seq/tomb sync from their host, who hadn't yet cleaned up their data. End result: bad data on the client, even after the host finally cleaned up.
Here, we bump the channels agent version _again_, cleaning up bad tombstones _again_, and asking the hosts for their seqs and tombs _again_. Assumption here is that all hosts on pre-release have now gotten the latest patch, so should have good data, and we can do a sync from them again right away.
That's it, that's the change. We move it out of the previous state migration and into the …

channels: re-do the seq/tomb sync migration/kickoff

---

packages/shared/src/store/postActions.ts
packages/shared/src/store/useChannelPosts.ts

fixes tlon-4705
Two thread-related bugs:
1. Thread replies were being delivered to main channels when messages failed and you hit retry
2. Thread replies would briefly appear in main channel view (if you quickly navigated out of the thread) due to missing filtering in useChannelPosts
The retry problem was that `retrySendPost()` always called the regular post API without checking if it was originally a thread message. The UI problem was that subscriptions weren't filtering out reply posts like database queries do, thread replies would appear briefly in the main chat channel until the next database query update removed them via deduplication logic.
1. Updated `retrySendPost()` to check if a failed message has a `parentId` (indicating it was originally a thread reply). If it does, it fetches …

threads: fix issue with reply messages delivered to main chat

---

apps/tlon-web/e2e/group-customization.spec.ts
packages/app/ui/components/Form/inputs.tsx

1) show error messages from uploads in ImageInput as a toast to the user
2) don't allow users who can't upload to even attempt to upload
Tested on web and iOS sim, with ships that do and do not have a storage config.
Revert

ImageInput: show errors on upload, don't let users without configs attempt to upload

---

packages/app/ui/components/Channel/PostList/PostList.web.tsx

fixes TLON-4668
Fixes bug where new web scroller would not scroll to bottom after sending a post while channel was still loading newer posts ("catching up") by sticking to scroll bottom after sending a message even if channel is still catching up (and maintaining rules about user already viewing bottom of scroll in order to stick to bottom of scroll).
We pause this "stick to scroll start" functionality whenever we believe the channel may have newer posts that are not yet loaded (`hasNewerPosts`) https://github.com/tloncorp/tlon-apps/blob/44c6211621fce584c4a90f43a002f7a2551c3559/packages/app/ui/components/Channel/PostList/PostList.web.tsx#L155-L160 – the thought here is that, if we load new messages in, we want to scroll to those once instead of "stuttering" two scroll-to-bottoms
We always …

stick to scroll bottom before caught up if user sends a post

---

packages/app/ui/components/ChatMessage/ChatMessageActions/MessageActions.tsx

When users tapped "Forward post" on iOS, the app would completely freeze up. Turns out we had a a race condition with the modal, we were trying to open the forward sheet while simultaneously closing the message actions sheet, and iOS in particular didn't like that.
- For iOS devices: we now dismiss the action sheet first, wait a bit (300ms), then open the forward sheet
- For Android/web: kept the original flow since they handle simultaneous modals just fine
- Added an early return to avoid calling dismiss twice and keep the haptic feedback working
Tested on web and the sim.
Revert
N/A

forwarding: fix issue with message forward hang on iOS

---

desk/app/groups.hoon

Various bugs might lead to big data being injected into a group's metadata fields. Certainly, we don't do any data validation/sanitization right now. In practice, this means some groups have huge image metadata fields containing the raw image data.
Fixes TLON-4753
Here, we modify agent load logic, so that we always do a quick pass over the groups we have in state. If a group we host is affected, run a command that clears it, ensuring updates get sent to subscribers informing them of the change. If it's a foreign group, just clear the data locally, but don't send any subscription updates.
Tested on my fakezod with contrived group metadata setup.
Maybe the threshold is too low? I've seen links (in posts) as big as 2.7kb. That's kinda nuts honestly, imo if your groups image url is >3kb you …

groups: clear out >3kb image metadata

---

desk/app/groups.hoon
packages/app/hooks/useGroupContext.ts
packages/app/ui/components/ActionSheet.tsx
packages/app/ui/components/GroupChannelsScreenView.tsx
packages/app/ui/components/GroupPreviewSheet.tsx
packages/app/ui/components/ListItem/listItemUtils.tsx
packages/shared/src/api/groupsApi.ts

Fixes issue where "You don't have access to any channels in this group" incorrectly appears after joining a group. The issue occurred when group metadata synced before channels, causing the UI to show an access error instead of a loading state during the join process.
Users were seeing "You don't have access to any channels" immediately after joining groups, even when they had full access. This was caused by:
1. Backend subscription crashes when processing section updates for non-existent channels
2. Frontend incorrectly detecting sync completion when channels hadn't loaded yet  
3. UI showing wrong states based on incomplete data
The subscription was crashing because section update operations were attempting to access channels that didn't exist in the local state. Without the defensive …

group joins: fix issue where we falsely report that users don't have access to any channels

---

packages/app/ui/components/Channel/PostList/PostList.web.tsx

towards TLON-4706
`useStickToScrollStart` uses the opaque `scrollerContentsKey` param to trigger a "scroll-to-bottom if needed" action. This was previously only triggered when the post list data changed.
This PR changes `scrollerContentsKey` to also key off the viewport / window height into the post list – i.e. when the scroll view resizes (due to getting squeezed by the draft input growing), `useStickToScrollStart` triggers and sticks the scroll to bottom if needed.
This still doesn't work great on Firefox – I took some time but couldn't figure out why. See video below – there's a mysterious scroll that happens on the first input _after_ growing the draft input. My best guess is that it's a bug in the browser's native scroll anchoring implementation (although enabling the …

trigger stick-to-scroll-start when viewport height changes

---

packages/app/ui/components/AttachmentSheet.tsx
packages/app/ui/utils/clipboardUtils.ts
packages/app/ui/utils/index.ts
packages/ui/package.json
pnpm-lock.yaml

Adds uploading an image to all attachment fields using the image data the user has on their clipboard. This is a nice-to-have users have been asking about for some time.
- Upgrades the `@react-native-clipboard/clipboard` dep, since support in iOS for image data on the clipboard was recently added.
- Adds a `getClipboardImageData` callback to `AttachmentSheet`, which checks if there's an image in the phone's clipboard when the attachment menu opens. It then tries different ways to grab the image data (PNG, then JPEG, then a generic method).
- Adds a "Paste from Clipboard" option to the sheet if there's compatible image data on the user's clipboard.
- Handles uploading into a generic 300x300 image, then resizes as the image upload completes.
React Native's generic `TextInput` only supports …

AttachmentSheet: allow pasting image data from clipboard

---

packages/app/ui/components/Channel/index.tsx

fixes tlon-4804
Fixes unread count flickering that occurs when viewing channels with *only* thread unreads.
A feedback loop was causing unread indicators to flicker continuously when:
1. A channel had unread thread messages but no main channel unreads
2. The Channel component would see `unread.count > 0` (which includes thread unreads) and mark the channel as read
3. The server would continue sending updates because thread unreads still existed
4. This created an infinite loop of marking read → receiving updates → marking read
I'm not totally certain why this bubbled up now, the Channel component has worked this way since March. This issue emerged around September 5th when we made some backend changes to how thread unreads are filtered, I'm assuming that's related.
- Updated the channel …

unreads: fix flickering unread badge on channels

---

packages/app/fixtures/Channel.fixture.tsx
packages/app/lib/featureFlags.ts
packages/app/ui/components/Channel/PostList/PostList.web.tsx

fixes TLON-4664
Everyone gets the native web scroller introduced in https://github.com/tloncorp/tlon-apps/pull/4868
Removes the `webScroller` feature flag, and changes the access to code equivalent to `webScroller = true`.
Opened web app (Firefox) – flag doesn't show up in flags setting screen, and channel appears to be using web scroller (e.g. highlighting text works well).
git revert

remove webScroller feature flag, defaulting to enabled

---

desk/app/channels.hoon
desk/app/groups-ui.hoon
desk/app/groups.hoon
desk/lib/test-agent.hoon
desk/mar/ui/init-1.hoon
desk/mar/ui/init-2.hoon
desk/mar/ui/init-3.hoon
desk/mar/ui/init-5.hoon
desk/mar/ui/init.hoon
desk/sur/ui.hoon
desk/tests/app/activity.hoon
desk/tests/app/channels-server.hoon
desk/tests/app/channels.hoon
desk/tests/app/chat.hoon
desk/tests/app/groups.hoon
desk/tests/app/logs.hoon
desk/tests/app/verifier.hoon
desk/tests/lib/negotiate.hoon

Wrong scry types were introduced by mistake to old unused endpoints during channels custom type changes, which involved changes to conversion functions, introduced last year. We fix both the types expected by the groups-ui agent and the types returned from some channels scries that were wrongly modified at the time.
Additionally, we also fix the most recent scry endpoint `v5`, which was failing due to an unnoticed change in the JSON conversion function.
**Note: you should only look at the last commit when reviewing. Github needlessly repeats the changes that are already in `mp/backend-unit-tests` branch.**
1. Adjust the expected scry types, and init types in the groups-ui agent.
2. Fix a channels scry endpoint to return the correct type.
Queried all modified endpoints.
- Safe to rollback …

Fix failing groups-ui scries

---

desk/app/groups.hoon

Old %group-join poke was implemented in a way that required
an entry in foreigns to work. This was never a problem at the client,
because it would always preview groups before joining. However,
it caused crashes at hosting, who were issuing group join pokes to
public groups without previewing first.
We improve this by defaulting to a join without token when a foreign
group entry is not found.
1. Fix the handling of the %group-join poke to never crash, but rather use an empty join token when none is available.
1. Unit tests pass.
2. Group join works from the client.
Can be reverted.

groups: better %group-join poke compatibility

---

desk/app/logs.hoon
desk/sur/logs.hoon

By default, only send logs with volume %info and higher into posthog, dropping the remainder on the floor.
This is a partial revert of #5052's 89761bd. In that PR we introduced additional %dbug logs but ended up not including log submission control. The result is excessive log submission to posthog.
Here we reintroduce that log submission control.
My beef with #5052's terminal logging remains and as such I have excluded it from scope here.
If it compiles, it works, right? (:
- Affects important code area: none
Can revert, old code's `+on-load` Just Works with any previous state.

logs: filter posthog logs

---

packages/app/ui/components/GroupMembersScreenView.tsx

I ran into TLON-4639 while attempting to give ~wittyr-witbes admin control of Tlon Studio, which has some 6K members. Scrolling through the entire list was not fun. Therefore, this fixes TLON-4639 by adding a filter input to the group members screen view. 
- Creates Fuse.js objects for members, banned users, invited users, and users asking for entry
- Adds an input box to the top of the members list screen to allow for filtering by name or @p
- Allows the user to clear the input and reset the filter
- Open a group with lots of members (Tlon Studio)
- Search for a known @p far down in the alphabet (I used ~wittyr-witbes)
- Verify that the exact match shows at the top of the list
- Enter a known nickname
- Verify that the exact match(es) show at the the top of the list
- Enter a partial @p …

GroupMembersScreenView: add filter input

---

desk/app/groups.hoon
desk/app/logs.hoon
desk/tests/app/logs.hoon

Some group subscribers have a corrupted state where a channel is placed in a non-existent section. This prevent a channel section update from going through. We fix this by robustly handling a current missing channel section.
Another instance of invalid channel nests inserted by third-party developers was caught and fixed.
We also drive-by-fix the logs agent to pass the unit tests broken by recently merged changes: the default volume was not initialized.
1. We avoid a `+jab` crash and replace it with a two step get, put to update a channel section.
2. Ignore channels with invalid nest kinds during active-channels loading.
3. Fix the logs agent to initialize its logging volume to `%info` by default.
Compiled and run the unit tests.
- Safe to rollback without consulting PR author? No
- …

groups: robustly handle a missing channel section & other fixes

---

packages/app/ui/components/Channel/PostList/PostList.web.tsx

fixes TLON-4832
Without this fix, the deleted `justifyContent` would always have the content justified to flex-end, even in non-inverted contexts (e.g. notebooks).
Switches `justifyContent` based on `inverted` when justifying the content container (which hugs the contents of the channel) instead of when justifying the content inside the container (which would do nothing, since the container hugs the content – so flex-start would look the same as flex-end). This bug was probably introduced when adding this container around the content.
See screen recording – tested only on Firefox.
git revert
https://github.com/user-attachments/assets/48559532-b641-4076-98a6-a77517b0497d

web scroller: fix content justification for notebooks

---

packages/app/ui/components/PersonalInviteSheet.tsx

OTT, fixes tlon-4638. Looks like this:
Revert

personal invite modal: fix padding/space issues

---

desk/lib/negotiate.hoon
desk/lib/test-agent.hoon
desk/lib/test-negotiate-agent.hoon
desk/tests/app/groups-server.hoon
desk/tests/app/groups.hoon

Introduces /lib/test-negotiate-agent, which wraps around /lib/test-agent to augment it with transparent handling and hiding of /lib/negotiate behavior.
Simplifies the groups agent tests by making them use this as a drop-in replacement of /lib/test-agent.
/lib/test-negotiate-agent overloads the original test-agent library, changing the behavior of `+do` to process negotiate cards appropriately, and re-defining every arm that calls `+do` to make sure that gets used.
When we see a version negotiation subscription we out, we simulate an instant watch-ack and matching version fact. This will "release" the underlying subscriptions, if any, and from the test writer's perspective they happen as if the negotiate wrapper wasn't even there.
I, uh, ran the tests.
I'm not very happy with the amount of …

tests: easier testing of negotiate-wrapped agents

---

packages/app/ui/components/Embed/EmbedContent.tsx
packages/app/ui/components/Embed/EmbedWebView.tsx
packages/app/ui/components/Embed/EmbedWebView.web.tsx
packages/app/ui/components/Embed/providers.ts
packages/app/ui/components/GalleryPost/GalleryPost.tsx
packages/app/ui/components/PostContent/BlockRenderer.tsx
packages/shared/src/store/metagrabActions.ts

Fixes tlon-4644, missing link metadata in link previews for youtube links, by special casing youtube links in `getLinkMetaWithFallback` using the `fetchEmbed` function we already have, which fetches oembed data. Youtube doesn't provide title/description via opengraph, only via oembed.
Fixes tlon-4645, youtube (and other) embeds not filling the full width in gallery detail view, by removing the constraint that limited embeds to `provider.defaultWidth` (320px). Embeds now always use 100% width while maintaining aspect ratio. Also fixed some aspect ratio issues on web by removing conflicting height calculations and using CSS aspect-ratio format (`16/9` instead of decimal). Added `aspectRatio` property to provider configs to maintain correct proportions while filling the available width. …

embeds/links: better youtube link descriptions, allow embeds to fill full width

---

packages/app/hooks/nagLogic.test.ts
packages/app/hooks/nagLogic.ts
packages/app/hooks/useNag.ts
packages/app/ui/components/SystemNotices.tsx
packages/shared/src/db/keyValue.ts
packages/shared/src/domain/analytics.ts
packages/shared/src/domain/system.ts

Fixes TLON-4896 by not slamming the user with a notification permissions nag beneath the dialog already asking for the same thing. Also introduces a grace period of 3 days until we show the nag.
- Only shows the notification permissions nag if explicitly denied, not just undetermined
- Adds an `initialDelay` prop to the `useNag` hook in ms
- Calculates the "first eligible time" for the nag to show
- Checks `Date.now()` on system notice mount to see if we are past the "first eligible time"
- Shows the nag if we are past it, does not if we are before it
- Logs events for people opening the system preferences from the nag and for enabling, then returning to the app
- Set the notification perm nag grace period to 1 minute
- Launch the simulator w/ fresh install
- Deny notification permissions …

onboarding: dont nag for notif permission until we need to

---

apps/tlon-mobile/src/components/AuthenticatedApp.tsx
apps/tlon-web/src/app.tsx
packages/shared/src/api/postsApi.ts
packages/shared/src/db/keyValue.ts
packages/shared/src/db/queries.ts
packages/shared/src/store/sync.ts
packages/shared/src/urbit/ui.ts

Implements the client portion of our new `init-posts` endpoint for fetching initial message data after mobile login or web tab open. Previously on mobile we were not preloading messages and on web we were using a multi request "predictive sync" operation. This gives us a configurable single endpoint to fetch starting messages.
Uses adaptive loading on mobile where we first check the network characteristics before deciding how much data to sync. If you're on WiFi, it'll behave differently than if you're on 3G.
It's easy to switch the constants for num channels and num messages. We probably want to do a bit more perf testing to select the right constants there, but right now the base64 bug is complicating getting representative test data. I don't think that needs to block merge, but it …

sync: message preload client integration
