tloncorp/tlon-apps

ui/.eslintrc.js, ui/package-lock.json, ui/package.json, ui/src/chat/ChatScroller/ChatScroller.tsx, ui/src/chat/ChatThread/ChatThread.tsx, ui/src/state/chat/writs.ts
This replaces our virtual scroller with react-virtuoso. Seems to have less issues with getting stuck. Addresses #942
=> vscroll: switching to virtuoso

ui/src/pages/NewDm.tsx
=> club: erroneous presig for multidm

desk/desk.docket-0, talk/desk.docket-0
=> meta: version bump for release

ui/src/components/ButterBar.tsx, ui/src/groups/GroupSidebar/GroupSidebar.tsx
=> groups: if group title text is white, use drop shadow

ui/src/components/Sidebar/SidebarSorter.tsx, ui/src/dms/MessagesSidebar.tsx, ui/src/groups/GroupSidebar/ChannelSortOptions.tsx
see #964.
for these we do need to be setting a specific width and not using w-full, i think because of the way radix portalling works.
=> sidebar: set specific width for filtering dropdowns

ui/src/profiles/EditProfile/EditProfile.tsx, ui/src/profiles/EditProfile/ProfileFields.tsx
ref: #921 
I'd like someone to pull this and test it, because i seem to be encountering some different issue with contact-store that prevents me from loading profiles no matter what their privacy setting is on other ships.
=> contacts: flipped public/private logic on editing field

ui/package-lock.json, ui/package.json, ui/src/chat/ChatChannel.tsx, ui/src/chat/ChatMessage/ChatMessage.tsx, ui/src/chat/ChatMessage/DateDivider.tsx
=> chat: mark chat channel read when unread divider is visible on screen

ui/src/chat/ChatInput/ChatInput.test.tsx, ui/src/chat/ChatMessage/ChatMessage.test.tsx, ui/src/components/References/AppReference.tsx, ui/src/components/References/ContentReference.tsx, ui/src/logic/utils.ts, ui/src/state/docket.ts, ui/src/types/chat.ts, ui/src/types/diary.ts, ui/test/setup.ts
- Ports over docket state from garden
- Adds an AppReference component
- Changes the types to reflect changes to desk cites
fixes tloncorp/homestead#612
=> refs: adds desk refs

ui/src/chat/ChatScroller/ChatScroller.tsx
this & an actual production build would do wonders for the virtual scroller
=> ui: make virtuoso set keys on components properly

ui/src/chat/ChatReactions/ChatReaction.tsx
Reactions are useless if you don't know who reacted!
=> feel: adds ships to chat reactions

ui/src/components/Sidebar/Sidebar.tsx, ui/src/components/Sidebar/__snapshots__/Sidebar.test.tsx.snap, ui/src/components/icons/ArrowNWIcon.tsx
fixes tloncorp/landscape-apps#986
=> groups: adds feedback button and hover-menu to app title

desk/app/chat.hoon, desk/sur/chat-0.hoon
Turns out we weren't finished yet haha.
=> chat: saga migration

ui/src/components/Nav/Nav.tsx
=> nav: enabled sticky scrolling

ui/src/channels/ChannelTypeSelector.tsx, ui/src/channels/NewChannel/NewChannelForm.tsx, ui/src/groups/GroupAdmin/AdminChannels/ChannelJoinSelector.tsx, ui/src/groups/GroupAdmin/AdminChannels/ChannelPermsSelector.tsx
=> added required value to name field, added required: false to all others

ui/src/groups/NewGroup/NewGroupInvite.tsx
fixes #599 
@urcades @jyng 
thoughts on how this looks/works?
https://user-images.githubusercontent.com/1221094/197270463-6231382d-4dca-425d-8513-949afe6c05de.mov
=> groups: add ability to remove potential invite from invite list on new group creation

ui/src/components/Sidebar/Sidebar.tsx, ui/src/components/Sidebar/SidebarItem.tsx, ui/src/components/Sidebar/__snapshots__/Sidebar.test.tsx.snap, ui/src/state/settings.ts
=> groups: set notifications sidebar item as active in default route

ui/src/chat/ChatScroller/ChatScroller.tsx, ui/src/groups/Groups.tsx
OTT, bah can't believe I didn't catch this before. Fixes issues @patosullivan and I were seeing trying to access the forge.
=> vscroll: useMemo on objects generated on render that are deps

ui/src/chat/ChatInput/ChatInput.tsx
=> chat: fix issue where S3 urls would seem to persist as drafts

desk/app/chat.hoon
Stops state from getting corrupted with wrong type
=> chat: reverting problematic save

desk/app/chat.hoon
this *should* work, testing on a ~marnec install now.
=> chat: fix state migration

desk/app/chat.hoon
be sober, be vigilant, because your adversary the devil, as a roaring lion, walketh about, seeking whom he may devour
=> chat: atone

ui/src/api.ts, ui/src/app.tsx, ui/src/components/DisconnectNotice.tsx, ui/src/groups/GroupSidebar/GroupSidebar.tsx, ui/src/state/local.ts
fixes #1039 
https://user-images.githubusercontent.com/1221094/199313876-c5deb66f-df4e-4a11-b6af-c13e69550c1c.mov
Also, yes, resizing the viewport triggers a call to `http://localhost:3000/~/scry/hark/group/{flag}/latest.json` which results in a 404, which, while it provided a nice way to test this feature, is pretty weird.
=> handle frontend disconnects

ui/src/heap/HeapTextInput.tsx
=> heap: set field focus target on heap text input to entire input

ui/src/components/ShipSelector.tsx
=> groups: fix for double listing of matched value in join ship selector

ui/src/groups/FindGroups.tsx, ui/src/groups/useGroupJoin.ts, ui/src/state/groups/groups.ts, ui/src/state/hark.ts
OTT
fixes #1043 (I think)
tested by posting a ref to non-existent group.
@arthyn would this cover the case you mentioned in your issue? The ref you mentioned itself is no longer available.
=> Chat: fallback to 'find groups' if join fails on group ref

ui/src/app.tsx, ui/src/chat/ChatThread/ChatThread.tsx
OTT, I don't think this had a ticket
=> chat: fixing thread layout regression

ui/src/diary/DiaryImageNode.tsx, ui/src/diary/DiaryInlineEditor.tsx
see: #991.
also includes the previously non-existent ability to click on a notebook data type from the list to insert it
=> diary/edit: up/down to exit image URL paste section

desk/app/chat.hoon, desk/app/diary.hoon, desk/app/groups.hoon, desk/app/heap.hoon, desk/lib/etch.hoon, desk/lib/plume.hoon, desk/lib/pprint.hoon, desk/lib/xray.hoon, desk/sur/chat.hoon, desk/sur/plum.hoon, desk/sur/xray.hoon, desk/ted/keep.hoon
if we can't devase the old state in +load, save it as a noun to /put.
also prints the a json representation of it (should remove before merging)
=> all: save bad state to /put

ui/src/chat/ChatContent/ChatContent.tsx, ui/src/heap/HeapRow.tsx, ui/src/notifications/Notification.tsx
=> groups: various mobile overflow fixes

ui/src/chat/ChatScroller/ChatScroller.tsx
=> chat: fix missing today marker

ui/src/api.ts, ui/src/app.tsx, ui/src/logic/useMedia.ts, ui/src/state/local.ts
This addresses #1083. Bug was introduced when I changed the useMedia hook to prevent multiple listeners, initialized was getting overwritten from true to false. I think this also addresses #1092?
=> talk: fixing looping chatinput focus

ui/src/diary/DiaryAddNote.tsx, ui/src/logic/tiptap.ts
see: #981.
tests currently won't pass due to an ESlint rule, if someone can help me rewrite that check i'd appreciate it.
=> notebooks: prevented insertion of extraneous newlines into notebook posts

ui/src/diary/DiaryAddNote.tsx, ui/src/logic/tiptap.ts
=> lint: fixing type issue from in PR commit

ui/src/components/References/GroupReference.tsx, ui/src/groups/useGroupJoin.ts
=> Groups: show private group join requested in group reference

ui/src/chat/ChatScroller/ChatScroller.tsx
Fixes issue posted by @alecananian  showing constant jumping in thread.
=> chat-scroller: more stable layout

ui/index.html
=> groups: added apple-touch-icon to header

ui/src/channels/ChannelHeader.tsx
=> Talk: changed back button behavior on mobile

ui/src/dms/MessagesSidebar.tsx
=> talk: added feedback menu to sidebar

desk/app/chat.hoon, desk/app/diary.hoon, desk/app/heap.hoon
=> fix for checking group before creating diary, chat

desk/app/chat.hoon, desk/app/diary.hoon, desk/app/heap.hoon
=> groups: remove comments

ui/src/dms/MessagesSidebar.tsx
=> talk: changed header title

ui/src/components/ShipSelector.tsx
I think this gets us where we want to be. See video, but please test for yourselves.
Fixes #1117 
Closes #1141 
https://user-images.githubusercontent.com/1221094/201757947-a5202f28-9373-4e2e-9b60-47cbe53b69d5.mov
=> Fix for ship selector with exact patps

ui/src/chat/ChatChannel.tsx, ui/src/chat/ChatInput/ChatInput.tsx, ui/src/components/CoverImageInput.tsx
=> notebooks: added placeholder to URL field in cover

ui/src/components/CoverImageInput.tsx, ui/src/components/ImageOrColorField.tsx, ui/src/components/ImageURLUploadField.tsx, ui/src/diary/DiaryImageNode.tsx, ui/src/heap/NewCurioForm.tsx, ui/src/profiles/EditProfile/ProfileFields.tsx
I think i caught all the places where you're supposed to paste an image url with these, let me know if i'm missing any. (notebook cover image is covered by #1142)
=> groups: s3 image upload buttons

ui/src/dms/MultiDMEditModal.tsx
=> multi-dm: fix modal dismiss

ui/src/chat/ChatInput/ChatInput.tsx
=> chat/input: disabled autofocus on mobile

ui/src/chat/ChatContent/ChatContent.tsx, ui/src/chat/ChatInput/ChatInput.tsx, ui/src/chat/ChatInput/__snapshots__/ChatInput.test.tsx.snap, ui/src/chat/ChatMessage/ChatMessage.tsx, ui/src/chat/ChatMessage/__snapshots__/ChatMessage.test.tsx.snap, ui/src/styles/components.css, ui/src/styles/utilities.css
I am yet again optimizing word breaks. Also fixed the issue where a small amount of messages would get hidden by the scrollbar.
=> chat: fix word breaking

desk/app/chat.hoon, desk/app/diary.hoon, desk/app/groups.hoon, desk/app/heap.hoon, ui/src/channels/NewChannel/NewChannelForm.tsx, ui/src/groups/NewGroup/NewGroup.tsx
This adds some better normalization to the frontend as well as adds `(sane %tas)` checking in places where we're creating flags addressing #1024
=> apps: handle flag creation safer

ui/src/components/ImageOrColorField.tsx, ui/src/components/ImageURLUploadField.tsx, ui/src/heap/NewCurioForm.tsx, ui/src/profiles/EditProfile/EditProfile.tsx, ui/src/profiles/ProfileCoverImage.tsx, ui/src/profiles/ProfileModal.tsx
=> groups: s3 css fixes

ui/src/components/ImageOrColorField.tsx, ui/src/dms/MultiDMInfoForm.tsx, ui/src/groups/GroupAdmin/GroupInfoEditor.tsx
it's about #1178. basically just had to force this thing to actually use the right "mode" when given a certain initial value.
=> groups/talk: updated color/image input field to account for empty default values

ui/src/chat/ChatInput/ChatInput.tsx
OTT, until we have time to experiment with poor connections and refine this we shouldn't use.
=> chat-input: remove chat draft machinery until we have time

ui/src/groups/useGroupJoin.ts
=> group-join: don't fail if there's no notification

ui/src/styles/components.css
=> Add z-index:10 for dropdown class in components.css

ui/src/heap/NewCurioForm.tsx
=> heap: input scroll enabled

ui/src/components/EmojiPicker.tsx, ui/src/groups/GroupInviteDialog.tsx
We weren't presigging ships that users were typing into the invite modal ship selector.
=> groups: Add presig to invite modal

ui/src/groups/Groups.tsx
=> groups: Route to channel index by default if no channels joined

desk/app/groups.hoon
OTT, fixes #1225 and #1224 sorry didn't mean to include both
=> groups: don't invite someone who's joining and make sure gangs get cleaned up

ops/bounce.yml, ops/sync.sh, ops/sync.yml, ui/src/dms/NewDm.tsx
This resolves #1229.
It also updates the bouncer scripts to sync the talk desk as well.
=> multi-dm: pre-sig ship names

desk/app/chat.hoon, desk/app/groups.hoon
#1195 
This doesn't prevent seeing that secret channels exist yet, but you can't join them.
=> Enforce reader permissions

desk/app/groups.hoon, ui/src/groups/useGroupJoin.ts
OTT, not sure if this is the issue but can't repro with the fix on. Also fixes erroneous logic for group joins now that we have secret groups.
=> groups: fix secret join and protect vs missing xeno

ui/src/diary/DiaryImageNode.tsx, ui/src/diary/useDiaryNode.tsx
added a new function that lets you manipulate diary node values directly. lets you actually use the s3 uploader now
=> diary/Image: use UpdateValues

ui/src/chat/ChatNotice.tsx, ui/src/chat/ChatScroller/ChatScroller.tsx
=> chat: show date divider on new day even on notice

desk/app/diary.hoon, desk/lib/notes.hoon, desk/lib/quips.hoon, ui/src/state/diary/notes.ts
Fixes #1213, also adds notifications for the OP if someone comments.
=> diary: correcting time linkages

ui/src/components/Sidebar/GroupList.tsx, ui/src/components/Sidebar/Sidebar.tsx, ui/src/components/Sidebar/__snapshots__/Sidebar.test.tsx.snap, ui/src/dms/MessagesList.tsx, ui/src/dms/MessagesSidebar.tsx, ui/src/dms/MobileMessagesSidebar.tsx, ui/src/nav/GroupsNav.tsx, ui/src/nav/MobileRoot.tsx, ui/src/styles/utilities.css
see: #1185.
also see: #1202
we needed to also see if the background location was a match for being "in a group" to prevent modals that weren't underneath a group-specific route from launching the sidebar over to the main view.
=> sidebar: scroll changed, background location match added

ui/src/groups/GroupSidebar/GroupSidebar.tsx
=> groups: Show default cover import (0x0) as default cover color

desk/app/chat.hoon, ui/src/state/chat/chat.ts
=> clubs: prevent double 'join' and represent pending correctly

ui/src/channels/ChannelHeader.tsx, ui/src/chat/ChatInput/ChatInput.tsx, ui/src/chat/ChatInputMenu/ChatInputMenu.tsx, ui/src/chat/ChatMessage/Author.tsx, ui/src/chat/ChatMessage/__snapshots__/ChatMessage.test.tsx.snap, ui/src/components/NavTab.tsx, ui/src/components/Sidebar/SidebarItem.tsx, ui/src/components/Sidebar/__snapshots__/Sidebar.test.tsx.snap, ui/src/diary/DiaryChannel.tsx, ui/src/groups/GroupAdmin/AdminChannels/AdminChannelListItem.tsx, ui/src/nav/MobileGroupRoot.tsx
solving some overflow issues w/ long channel/user names (lots of setting the correct grow/shrink values) and makes the formatting toolbar's "link" feature actually work on phones
=> groups: usability fixes

desk/desk.docket-0, talk/desk.docket-0
=> meta: version bump

ui/src/heap/HeapDetail/HeapDetailHeader.tsx
=> heap: fix titles for links in detail view

ui/src/logic/useMigrationInfo.ts
OTT, this was in last redux but it was showing weird merge conflicts
=> migration: handle empty groups

ui/src/chat/ChatInputMenu/ChatInputMenuButton.tsx, ui/src/chat/ChatInputMenu/ChatInputMenuToolbar.tsx
=> chat: clean up chat input toolbar based on urcades feedback

desk/mar/migrate-map.hoon
=> migrate-map: actually give the value, not just a gate

desk/app/diary.hoon
OTT, not sure what else could be wrong with our imp subscriptions. seems like we're giving facts in the right places and the frontend has a sub for each app to set state.
=> diary: add imp subscription

ui/src/components/References/CurioReference.tsx, ui/src/components/References/GroupReference.tsx, ui/src/components/References/NoteReference.tsx, ui/src/components/References/WritBaseReference.tsx, ui/src/state/groups/groups.ts
=> groups/diary: added not-prose to writ ref

ui/src/heap/HeapTextInput.tsx
After release, implement a title input
=> heap: submit curio with empty title to pass validation

desk/app/groups.hoon
Fixes "unable to create channel after creating group"
=> groups: finish initialising group before giving fact

.github/actions/release/Dockerfile, .github/actions/release/action.yml, .github/actions/release/entrypoint.sh, .github/workflows/deploy-canary-groups.yml, .github/workflows/deploy-canary-talk.yml, .github/workflows/deploy-internal-groups.yml, .github/workflows/deploy-internal-talk.yml
=> ops: changing so subsequent deploys don't glob

desk/app/chat.hoon, desk/app/diary.hoon, desk/app/groups.hoon, desk/app/heap.hoon
Fix role import, cause of Galens mystery channels
=> migration: fix role import

ui/src/api.ts, ui/src/components/References/AppReference.tsx
OTT, this should fix remaining issues with app references
=> app-ref: fix id and add subscribeOnce to api

ui/src/chat/ChatMessage/ChatMessageOptions.tsx, ui/src/chat/ChatMessage/__snapshots__/ChatMessage.test.tsx.snap, ui/src/chat/ChatReactions/ChatReactions.tsx, ui/src/components/EmojiPicker.tsx
=> chat: fixed emoji picker screen collision issues

ui/src/diary/DiaryAddNote.tsx, ui/src/diary/DiaryInlineEditor.tsx, ui/src/logic/tiptap.test.ts, ui/src/logic/tiptap.ts
Fixes issues with editing migrated notes, also handles more cases for content within notes to display correctly in the editor.
=> Diary: fix issues with editing notes

ui/src/logic/useMigrationInfo.ts
This significantly reduces the subscription load since these will retry constantly if you're getting briefs.
=> migration: only retry unjoined checking after 10 mins

ui/src/groups/GroupAdmin/GroupInfo.tsx
=> groups: showing group privacy correctly in the member list

ui/src/components/Mention/MentionPopup.tsx
=> chat: fix double sig on mentions

ui/src/logic/useMigrationInfo.ts
=> migration: use wait checking for valid behavior

ui/src/logic/useMigrationInfo.ts
=> migrate: only sub wait once

ui/src/profiles/ProfileModal.tsx
=> Fix message button navigation in profile modal

ui/src/components/References/NoteReference.tsx, ui/src/components/References/ReferenceBar.tsx
see: #1446. also fixes a similar issue in `ReferenceBar`.
=> fixed talk > gallery/notebook ref linking

ui/src/groups/ChannelIndex/ChannelIndex.tsx
=> groups: added channel edit modal to ChannelIndex

ui/src/groups/GroupAdmin/GroupAdmin.tsx, ui/src/groups/GroupAdmin/GroupMemberItem.tsx, ui/src/groups/GroupAdmin/GroupMemberManager.tsx, ui/src/groups/GroupAdmin/GroupMembers.tsx, ui/src/groups/GroupAdmin/MemberScroller.tsx, ui/src/state/groups/groups.ts
Previously viewing the member list in a large group would cause severe perf issues. This change virtualizes the member list to allow one to view a large group such as Urbit Community.
This resolves #1483
https://user-images.githubusercontent.com/16504501/207625973-0ae6584c-20c0-470e-8e21-d6d103cb3630.mp4
=> groups: virtualized Member list

desk/app/groups.hoon, desk/mar/group.hoon, ui/src/app.tsx, ui/src/channels/ChannelHeader.tsx, ui/src/components/DisconnectNotice.tsx, ui/src/logic/utils.ts, ui/src/state/bootstrap.ts, ui/src/state/chat/chat.ts, ui/src/state/groups/groups.ts, ui/src/state/groups/type.ts
Optimize bootstrap sequence based on app and reduce group initial scry significantly until we need the full fleet.
=> perf: part 2

desk/app/groups.hoon
=> groups: check that they're in the group so we don't crash

ui/src/state/chat/chat.ts
Fixes #1473 
Still working  on #1468, it's a bit trickier. Will be a different PR.
=> chat: optimistically poke for reaction adds/deletes

ui/package-lock.json, ui/package.json, ui/src/chat/ChatContent/ChatContent.tsx, ui/src/components/MessageEditor.tsx, ui/src/diary/DiaryInlineEditor.tsx
see: #1408, and part of #1444
I've taken a somewhat aggressive method of exiting out of bold/italic/etc that some people may find personally a little annoying, but IMO it's less annoying than the alternative (continuing to keep stuff immediately after the written text formatted)
=> groups: inline formatting fixes, code contrast in editor

ui/src/chat/ChatThread/ChatThread.tsx
I have been reflexively hitting ESC to close threads, and so has ~simfur-ritwed
This adds a keydown handler to open threads. On hitting ESC, the thread is closed.
https://user-images.githubusercontent.com/16504501/207866644-20dfb92d-1797-49b2-81f4-f69716071521.mp4
=> ux: ESC to close an open thread

ui/src/chat/ChatScroller/ChatScroller.tsx
Fixes #1468
This fixes the issue for both emoji reactions and the addition of chat threads. Scrolls the scroller by the change in height.
=> chat: fix issue with scroll position on height resize issue

.github/workflows/bump.yml
=> ops: add bump action

desk/app/groups.hoon
=> Check that channel is in group before deleting

ui/src/heap/HeapBlock.tsx
fixes tloncorp/landscape-apps#1459
Not permissioned:
Permissioned:
=> gallery: wrap actions in canEdit check

ui/src/profiles/EditProfile/EditProfile.tsx, ui/src/profiles/EditProfile/ProfileGroup.tsx
=> profile: reliable spacing for favorite group tags

ui/src/chat/ChatContent/ChatContent.tsx
fixes tloncorp/landscape-apps#1520
=> chat: adds scrolling overflow to chat blocks

ui/src/chat/ChatThread/ChatThread.tsx
=> chat: check channel write perms on chat threads

ui/src/dms/MultiDm.tsx
=> chat: fix input clearing on new messages in DMs

desk/app/chat.hoon
Actual change is on lines 1511-1513
Fixes #1387
=> chat: fix notification message for DM invites

desk/app/chat.hoon, desk/app/diary.hoon, desk/app/groups.hoon, desk/app/heap.hoon, desk/desk.docket-0, desk/mar/reset-group-perms.hoon, ui/src/chat/ChatChannel.tsx, ui/src/diary/DiaryChannel.tsx, ui/src/diary/DiaryNote.tsx, ui/src/dms/MessagesList.tsx, ui/src/groups/ChannelIndex/ChannelIndex.tsx, ui/src/groups/GroupSidebar/ChannelList.tsx, ui/src/heap/HeapChannel.tsx, ui/src/heap/HeapDetail/HeapDetailSidebar/HeapDetailComments.tsx, ui/src/heap/NewCurioForm.tsx, ui/src/logic/useFilteredSections.ts, ui/src/logic/utils.ts, ui/src/state/heap/heap.ts
This makes sure that sects contained in bloc actually act as superusers allowing them full permissions specifically around channel reading/writing. Also adds a poke to reset all channel permissions
Should fix #1502 and gives avenue to fix #1556
=> groups: make bloc actually "sudo"

ui/src/chat/ChatInput/ChatInput.tsx
=> chat: mark the channel read when submitting a message

ui/src/chat/ChatMessage/ChatMessageOptions.tsx
=> chat: allow group admins to delete other people's messages

ui/src/chat/ChatMessage/ChatMessage.tsx
=> chat: show correct last reply time for threads

desk/app/chat.hoon
=> chat: update addressing to match new type

ui/src/diary/DiaryInlineEditor.tsx
For some reason `JSONToListing` still seems to be generating extra newlines even though `limitNewlines` is set/defaulted to true in `tiptap.ts`.
To get around this, I'm filtering out extraneous "paragraph" blocks on the JSON content before passing it to the editor.
For #1357
=> notes: filter out extraneous paragraphs in note editor

ui/src/groups/GroupAdmin/GroupAdmin.tsx
=> groups: ensure full-height member list

ui/src/heap/HeapDetail/HeapDetailSidebar/HeapDetailSidebarInfo.tsx
=> heap: prefer css truncation for detail title

ui/src/diary/DiaryInlineEditor.tsx, ui/src/logic/tiptap.test.ts, ui/src/logic/tiptap.ts
Better fix for #1357, the extraneous newlines bug.
=> diary: fix wrap paragraphs bug

desk/lib/diary-json.hoon, desk/sur/diary.hoon, ui/package-lock.json, ui/package.json, ui/src/diary/DiaryAddNote.tsx, ui/src/diary/DiaryContent/DiaryContent.tsx, ui/src/logic/tiptap.test.ts, ui/src/logic/tiptap.ts, ui/src/types/diary.ts
Still working on the wrapParagraphs issue, so I branched off of there (codeblock formatting would get messed up otherwise).
This should fix #1616 
I imagine we need to do some kind of state transition to account for the new key? cc: @arthyn
=> notes: add proper storage and rendering for codeblocks

ui/src/diary/DiaryAddNote.tsx, ui/src/logic/tiptap.test.ts, ui/src/logic/tiptap.ts
=> tiptap: fixing code blocks for chat

.github/workflows/deploy-external-groups.yml, .github/workflows/deploy-external-talk.yml, .github/workflows/deploy-livenet-groups.yml, .github/workflows/deploy-livenet-talk.yml
Adds doznec and sogryp to github actions
=> ops: adding release targets

ui/src/logic/tiptap.ts
=> notes: fix recursive lists

ui/src/notifications/useNotifications.tsx
Possible partial fix for #1703
=> channels: constant rerender from hook

ui/src/logic/useIsChannelUnread.ts
=> talk: be more careful about dereferencing group

ui/src/chat/ChatInput/ChatInput.tsx
=> chat: revert fix for pasting regular links on mobile android

ui/src/chat/ChatMessage/DateDivider.tsx
=> chat: fix typo

ui/src/components/Sidebar/MobileSidebar.tsx, ui/src/nav/MobileRoot.tsx
This resolves #1744
https://user-images.githubusercontent.com/16504501/213578364-297dddca-4ab4-49aa-85b3-97e95ea614c4.mp4
=> style: mobile sidebar virtual group list

ui/src/chat/ChatInput/ChatInput.tsx, ui/src/components/MessageEditor.tsx, ui/src/diary/DiaryCommentField.tsx, ui/src/heap/HeapTextInput.tsx, ui/src/mocks/heaps.ts, ui/src/state/storage/type.ts, ui/src/state/storage/upload.ts
OTT this should solve the most recent case of #1729
=> chat: avoid giving useMessageEditor any deps that change on submit

ui/src/chat/ChatInput/ChatInput.tsx, ui/src/chat/ChatInput/__snapshots__/ChatInput.test.tsx.snap
=> chat: fix sigil alignment

ui/src/channels/ChannelHeader.tsx
This resolves #1752.
https://user-images.githubusercontent.com/16504501/213740940-1fe4e258-6342-4e73-b41b-883d5599142c.mp4
https://user-images.githubusercontent.com/16504501/213742172-d150bf82-107f-40f7-a5a1-b34f98ce1630.mp4
=> nav: fix channel header back link

ui/src/state/chat/chat.ts
Little drive-by PR. Not sure how we missed this, but it was an easy fix. Thought we had an issue for this, but this is the issue reported by Jack in Tlon Public
=> chat: fix loading for multidms

ui/src/chat/ChatInput/ChatInput.tsx
=> chat: prevent ref paste in wrong input

desk/desk.ship, talk/desk.ship
These are required for a desk that's in the pill to have a sync source.
Fixes #1771
=> groups, talk: add desk.ship

ui/src/chat/ChatInput/ChatInput.tsx
=> threads: use correct blocks

ui/src/chat/ChatChannel.tsx, ui/src/chat/ChatInputMenu/ChatInputMenu.tsx, ui/src/chat/ChatInputMenu/ChatInputMenuToolbar.tsx, ui/src/components/Mention/MentionPopup.tsx, ui/src/components/MessageEditor.tsx, ui/src/components/ShipName.tsx, ui/src/diary/DiaryInlineEditor.tsx
A bunch of really small things, mostly involving mentions and chat:
- #1500 
- #1563 
- #1600 
- #1405 
- #1609
- #1754
=> chat: omnibus #1

ui/src/channels/NewChannel/__snapshots__/NewChannel.test.tsx.snap, ui/src/groups/GroupAdmin/AdminChannels/ChannelPermsSelector.tsx
Copy edits as per @e-shee.
fixes #1762
=> groups: channel permissions copy edits

ui/src/chat/ChatMessage/ChatMessageOptions.tsx
for #1523 
Threads already respect channel perms, just making emojis do the same.
=> chat: prevent emoji reactions in channels you can't write to

ui/src/components/ShipSelector.tsx, ui/src/groups/FindGroups.tsx
for #1621 
autofocus was too grabby for mobile.
=> groups: disable autofocus for find groups on mobile

ui/src/diary/DiaryContent/DiaryContent.tsx, ui/src/logic/tiptap.ts
Fixes #1788 also fixes code blocks so that they're editable.
=> note: make sure we register hoon lang

ui/src/notifications/Notifications.tsx
This resolves #1731
https://user-images.githubusercontent.com/16504501/214877005-b4550d96-5258-4f99-91c3-464cdd32fe0c.mp4
=> ux: mark as read loading spinner

ui/src/dms/DMOptions.tsx, ui/src/dms/MessageSelector.tsx
=> talk: fix nav issues

ui/src/state/chat/writs.ts
=> chat: correctly rectify threads when deleting messages

ui/src/components/ShipSelector.tsx
=> Make copy clearer on 'not found' in ship selector

ui/src/state/chat/writs.ts
OTT this should be the final fix for #1430 our white whale
=> chat: dont add messages already indexed

ui/src/chat/ChatMessage/ChatMessage.tsx
=> chat: do not hide date dividers while chat is unread

ui/src/dms/Dm.tsx, ui/src/dms/MultiDm.tsx, ui/src/logic/useMessageSelector.ts
=> talk: fix issue where useMessageSelector would always search for multiDM with our ship

desk/app/notify.hoon
=> notify: uid coming in should be uv

ui/src/components/ShipSelector.tsx, ui/src/groups/NewGroup/NewGroupInvite.tsx
This fixes #1867 and also adds support for pasting in a list of patps, little treat for @marisarow 
Fixes #1845
=> new-group-invites: only hit enter once and actually support copy paste

ui/src/state/chat/writs.ts
=> chat: dms should be optimistic too

ui/src/state/hark.ts
OTT fixes similar issue to tloncorp/landscape#74 with no notifications
=> hark: expects ud in quilt scry

ui/src/app.tsx, ui/src/components/LandscapeWayfinding.tsx, ui/src/components/References/GroupReference.tsx, ui/src/diary/DiaryChannel.tsx, ui/src/diary/DiaryNote.tsx, ui/src/groups/GroupSummary.tsx, ui/src/heap/HeapChannel.tsx, ui/src/state/settings.ts
Fixes #1856 for groups and talk. Separate PR incoming for Landscape.
Note that the "reject" buttons on the Group Reference components are a bug, unrelated to this work.
=> Landscape Wayfinding

ui/src/notifications/Notification.tsx
Conditionally applies spacing rules to the last element in the content series.
=> notifications: spacing tweaks

ops/sync.yml
=> ops: update sync script

ui/src/diary/DiaryContent/DiaryContent.tsx
=> notebook: don't allow text content to overflow

ui/src/groups/FindGroups.tsx
On the tin.
@emceetee @marisarow @e-shee
=> groups: try again link in find timeout message

ui/src/app.tsx, ui/src/groups/GroupAdmin/MemberScroller.tsx
=> auth: fix to work with new cookie scheme

ui/src/notifications/Notification.tsx
=> notifications: break long lines

ui/src/chat/ChatScroller/ChatScroller.tsx
Suppresses an extraneous log statement
=> devex: remove updateScroll log

ui/src/chat/ChatInput/ChatInput.tsx, ui/src/chat/ChatMessage/ChatMessageOptions.tsx
Fixes #1945 
Also did some cleanup.
=> chat: do not insert replies into browser history

ui/src/chat/ChatMessage/ChatMessage.tsx
=> chat: fix message options not appearing on mobile

ui/src/groups/Groups.tsx, ui/src/nav/MobileGroupRoot.tsx, ui/src/notifications/Notifications.tsx
OTT we just forgot to initialize the group notifications, fixes #1961 also includes some tweaks so that the container stays the right size
=> notifications: make sure we load on mobile and tweak layout

ui/src/diary/DiaryImageNode.tsx
OTT this addresses #1894 and some styling issues I found.
=> diary-image: fix uploader uniqueness and styling

ui/src/notifications/Notifications.tsx, ui/src/notifications/useNotifications.tsx, ui/src/state/hark.ts
OTT, this makes the loading indicator actually follow the progress of updating. This does change a bit how we update notifications upon a "saw" because now they update once success is tracked. Also cleaned up the notifications page so there's less duplication.
=> groups: add real progress to mark read

ui/src/logic/useIsGroupUnread.ts
OTT this fixes hopefully the last of the "ghost" unreads being seen #1888 and clears up some other user feedback we saw.
Fixes #1888
=> sidebar: stop notifications from triggering blue dot

ui/src/notifications/Notifications.tsx, ui/src/notifications/useNotifications.tsx, ui/src/state/hark.ts
Fixes #1941 
Ended up just adding a flag to hark state for this. Also renamed the markRead request state stuff to avoid any future confusion.
https://user-images.githubusercontent.com/1221094/220432310-0e25a0e0-fe28-4bd1-85bb-9e5c18c4cd9e.mov
=> groups: Add loading state for notifications view

desk/lib/groups-json.hoon, ui/src/state/groups/groups.ts, ui/src/state/groups/groupsReducer.ts, ui/src/types/groups.ts
Fixes the issue where drag/drop in the admin channel manager didn't work as expected.
Will attach an issue to this if I can find it.
=> channelmanager: fix reorder rerender issue

ui/src/assets/chatmanifest.json
=> pwa: use correct icon in talk manifest

ui/src/chat/ChatInput/ChatInput.tsx, ui/src/state/storage/upload.ts
Fixes #1921 
Also: make the remove button work for image blocks.
=> Upload: don't allow send without a url for image.

ui/src/heap/HeapDetail/HeapDetailSidebar/HeapComment.tsx
=> heap: break words on heap comments

ui/src/groups/useGroupJoin.ts
=> groups: route joiners to channel list on mobile

ui/src/diary/DiaryNote.tsx, ui/src/diary/DiaryNoteHeader.tsx
=> notes: remove kebab menu + share button

ui/src/logic/useSidebarSort.ts
=> groups: set default group sort to 'Arranged'

ui/src/heap/HeapBlock.tsx, ui/src/heap/HeapRow.tsx
fixes #2057 
makes galleries load faster.
=> heap: don't check for embed if we know it's not

ui/src/chat/ChatContent/ChatContent.tsx, ui/src/chat/ChatContent/ChatContentImage.tsx, ui/src/chat/ChatEmbedContent/AudioPlayer.tsx, ui/src/chat/ChatEmbedContent/ChatEmbedContent.tsx, ui/src/chat/ChatEmbedContent/SpotifyEmbed.tsx, ui/src/chat/ChatEmbedContent/TwitterEmbed.tsx, ui/src/chat/ChatEmbedContent/YouTubeEmbed.tsx, ui/src/chat/ChatMessage/ChatMessage.tsx, ui/src/chat/ChatMessage/ChatMessageOptions.tsx, ui/src/chat/useChatStore.ts
Fixes #2065 
Unfortunately we need to prop-drill the writIds down into the image content/embeds as well in order to have a persistent ID.
=> chat: add global state for pickers, lightboxes, modals

desk/lib/curios.hoon, desk/lib/dm.hoon, desk/lib/mop-extensions.hoon, desk/lib/notes.hoon, desk/lib/quips.hoon
Makes much better use of the data structures we had in place, the beginning of fixes for #1375. This should significantly speed up all channel loads.
Thanks to @midsum-salrux for his mop work in #2042
=> channels: improve querying across the board

ui/src/groups/MobileGroupActions.tsx
=> groups: fix leave group link on mobile

desk/lib/curios.hoon, desk/lib/dm.hoon, desk/lib/mop-extensions.hoon, desk/lib/notes.hoon, desk/lib/quips.hoon
This restores what we reverted
=> ops: restore mop work post release

ui/src/components/LandscapeWayfinding.tsx, ui/tailwind.config.js
=> Wayfinding: fix mobile layout issues.

ui/src/channels/NewChannel/NewChannelForm.tsx
=> groups: handle numeric channel names

ui/src/chat/ChatEmbedContent/TwitterEmbed.tsx, ui/src/heap/HeapDetail/HeapDetailEmbed.tsx
Fixes #1809 and related issue with twitter embeds in the lightbox in chat.
Also allows for scrolling very tall twitter embeds on mobile.
=> embeds: tweet lightbox rendering issues

ui/src/chat/useChatStore.ts
Saw this upon creating a new group w/ chat was unable to react to anything.
=> usechatstore: prevent bad ref for dialogs, make all consistent

ui/src/chat/ChatContent/ChatContent.tsx, ui/src/chat/ChatContent/ChatContentImage.tsx
=> chat: fix issue #2093, where lightbox opens last image

desk/app/chat.hoon, desk/app/diary.hoon, desk/app/groups-ui.hoon, desk/app/groups.hoon, desk/app/heap.hoon, desk/mar/ui/init.hoon, desk/sur/chat.hoon, desk/sur/ui.hoon, talk/app/talk-ui.hoon, talk/sur/ui.hoon, ui/src/chat/ChatInput/ChatInput.test.tsx, ui/src/state/bootstrap.ts, ui/src/state/chat/chat.ts, ui/src/types/chat.ts
Forgot to include this commit in the original PR, also includes pins fix #2105
=> perf: initial load remainder

ui/src/diary/DiaryChannel.tsx, ui/src/diary/DiaryChannelListPlaceholder.tsx
Specifically for list view (does anyone use grid view?) Fixes #2060
=> Add loading placeholder for notebooks

ui/src/state/bootstrap.ts, ui/src/state/chat/chat.ts, ui/src/state/chat/type.ts, ui/src/state/hark.ts, ui/src/state/scheduler.ts
Some more loading stuff and fix to the erroring call on empty quilts.
Fixes #1913 
Fixes #1375
=> perf: more load tweaks

ui/src/diary/DiaryContent/DiaryContent.tsx
=> diary-content: load correct refractor version

ui/src/heap/HeapDetail/HeapDetailSidebar/HeapDetailComments.tsx
=> Add virtual scroller  for heap comments.

ui/src/components/References/AppReference.tsx
For https://github.com/tloncorp/landscape/issues/108, needs to be deployed with changes in https://github.com/tloncorp/landscape/pull/109
=> references: update app reference link

ui/src/components/Grid/grid.tsx
Missed this before merging earlier.
=> grid: justify grid in the center

ui/src/assets/chatmanifest.json, ui/src/assets/manifest.json, ui/src/components/Sidebar/MobileSidebar.tsx, ui/src/styles/base.css
Fixes an issue where extraneous bottom padding would be displayed on Android. 
Fixes an issue where a bad start_url in the manifest would cause the PWA to show a blank screen on iOS.
=> pwa: fix some issues for both platforms

ui/src/dms/DMOptions.tsx, ui/src/groups/GroupActions.tsx, ui/src/groups/GroupSidebar/ChannelList.tsx
=> groups/talk: the gray dot is simply too calm

ui/src/logic/utils.ts, ui/src/state/bootstrap.ts
OTT prevents issues like #2178
=> talk: offer fallback if talk out of sync

ui/src/chat/ChatInput/ChatInput.tsx
=> chat input: fix ref paste in threads on android

desk/app/groups.hoon, ui/src/groups/GroupActions.tsx, ui/src/groups/GroupAdmin/GroupMemberManager.tsx, ui/src/groups/GroupSidebar/MobileGroupSidebar.tsx
Fixes #2181 by checking if the group update is just a member add in go-proxy. Also updates relevant UI components.
=> groups: Allow non-admins to invite to public groups

ui/src/chat/ChatContent/ChatContentImage.tsx
=> Fix typo in <a> tag on ChatContentImage

ui/src/components/Leap/Leap.tsx, ui/src/styles/components.css
OTT more cleanup from #2191 also adjusts global default styling for dialogs (adjusting from pulling from grid)
=> leap,dialog: fix default styling and adjust leap to account

desk/app/greeting.hoon, desk/app/grouper.hoon, desk/desk.bill, desk/mar/grouper/answer-enabled.hoon, desk/mar/grouper/ask-enabled.hoon, desk/mar/grouper/disable.hoon, desk/mar/grouper/enable.hoon, desk/sur/reel.hoon
For sake of types and colocation of concerns we decided to move %grouper and %greeting to this desk so that landscape can stay clean of groups stuff.
=> lure: grouper agent

ui/src/chat/ChatContent/ChatContentImage.tsx, ui/src/components/LightBox.tsx, ui/src/groups/ChannelsList/EditChannelModal.tsx
Cleans up a few issues seen from dialog changes like fixes #2220
=> dialog: cleanup

desk/mar/webmanifest.hoon, talk/mar/webmanifest.hoon
=> Add webmanifest marks

ui/package-lock.json, ui/package.json, ui/vite.config.ts
Also remove unused package, @radix-ui/react-switch.
=> perf: Use manual chunking to reduce index chunk size

ui/src/state/chat/writs.ts
Fixes #2026
@arthyn found this while we were on a call
=> chat: fix double render on reconnect

ui/src/groups/NewGroup/NewGroupInvite.tsx
=> Fix missing create group button

ui/src/chat/ChatContent/ChatContent.tsx, ui/src/logic/utils.ts
=> Increase text-size of emoji-only messages

ui/src/chat/ChatReactions/ChatReaction.tsx
=> emojis: indicate which were sent by the user

ui/src/heap/HeapBlock.tsx
New wrapper component didn't set w-full/h-full
Fixes #2221
Fixes #2229
=> heap: fix for references not displaying content

ui/src/components/ShipSelector.tsx
=> invites: portal ship selector menu

ui/src/chat/ChatInputMenu/ChatInputMenu.tsx, ui/src/chat/ChatThread/ChatThread.tsx, ui/src/components/Grid/grid.tsx, ui/src/components/Leap/Leap.tsx, ui/src/components/Mention/MentionPopup.tsx, ui/src/diary/DiaryInlineEditor.tsx, ui/src/heap/HeapDetail.tsx, ui/src/keyMap.ts
Could be surfaced up later as a modal.
=> Create keyboard shortcuts map for future use

ui/src/state/bootstrap.ts, ui/src/state/scheduler.ts
OTT, this should make reconnects a little smoother. We have a little more room here we can play with if this isn't enough.
=> reconnect: fan out refetching a little so we don't choke reconnection

ui/package-lock.json, ui/package.json, ui/src/sw.ts, ui/tsconfig.json, ui/vite.config.ts
This allows us to add custom functionality to the SW later (i.e., web push notifications).
Overall functionality should be exactly the same for now.
=> pwa: Switch to injectManifest strategy for sw.

ui/src/groups/GroupSidebar/ChannelList.tsx, ui/src/groups/Groups.tsx, ui/src/state/groups/groups.ts
Fixes #2306
Also tweaked the queryKeys (use 'groups', not 'group' for useGroup) and tweaked the behavior of useGroupLeaveMutation due to some weirdness I saw around group leaves.
=> Add loading state for initial group load

desk/mar/contact.hoon
Fixes https://github.com/tloncorp/landscape-apps/issues/2310
=> Fix /mar/contact.hoon

.github/helpers/deploy.sh, .github/workflows/deploy-groups.yml, .github/workflows/deploy-talk.yml, talk/mar/ui/init.hoon
Same as #2327 just branched off of 2.11 and with the deploy stuff so this can safely go to mainnet.
=> chat: restore missing dms hotfix

desk/app/chat.hoon
=> chat: handle contacts wire correctly

ui/src/state/settings.ts
=> settings: more defaulting safety

ui/src/chat/ChatInput/__snapshots__/ChatInput.test.tsx.snap, ui/src/groups/GangPreview/__snapshots__/GangPreview.test.tsx.snap, ui/src/state/settings.ts
=> settings: ensure deps don't loop

ui/src/groups/ChannelsList/ChannelsList.tsx, ui/src/state/chat/chat.ts, ui/src/state/chat/writs.ts
This should resolve #2313 and #2335
=> chat,channel-list: safer referencing

ui/src/dms/Dm.tsx
=> dm: remove errant padding squishing images

.github/actions/glob/action.yml, .github/helpers/deploy.sh, .github/workflows/bump.yml, .github/workflows/deploy-groups.yml, .github/workflows/deploy-talk.yml, .github/workflows/sync.yml
OTT, master should only be updated once dev goes to livenet
=> ops: sync dev to master

ui/src/groups/NewGroup/NewGroup.tsx, ui/src/groups/NewGroup/NewGroupInvite.tsx
Fixes #2325
A bandaid for now until we refresh the new group flow.
=> groups: remove moderator role from new group flow

.github/workflows/sync.yml
=> ops: properly naming things

ui/src/profiles/EditProfile/EditProfile.tsx, ui/src/types/contact.ts
add-group/del-group expect a flag (string), we were sending an object with the flag parts.
Fixes #2366
=> bugfix: update favorite groups in profile

.github/workflows/sync.yml
=> ops: use the right names for sync trigger

ui/src/heap/HeapBlock.tsx, ui/src/heap/useCurioActions.ts
=> gallery: show delete loading status for gallery items

ui/src/state/groups/groups.ts
Fixes #2431 (at least the second part, maybe the first part too).
=> groups: check for undefined data in useGroups

ui/src/heap/HeapDetail/EmbedFallback.tsx, ui/src/heap/HeapDetail/HeapDetailBody.tsx
=> heap: respect calm settings in detail view

ui/src/chat/ChatInput/ChatInput.tsx, ui/src/groups/ChannelsList/ChannelsList.tsx
=> bugfix: prevent send on enter while uploading images

.github/workflows/add-to-project.yml
Adds opened pull requests to the project board.
=> ops: add PRs to project

ui/src/chat/ChatReactions/ChatReaction.tsx
Fixes #2032
Limits list to first three ships to have reacted, followed by "and X others".
=> chat: truncate emoji reaction ship list

ui/patches/@urbit+http-api+2.4.4-debug.patch, ui/src/api.ts, ui/src/logic/utils.ts, ui/src/state/diary/diary.ts, ui/src/state/diary/notes.ts, ui/src/state/heap/curios.ts, ui/src/state/heap/heap.ts
This enables the Tlon hosting platform to run analytics. Also fixes an issue where newly created heaps/diaries were erroring on actions like adding posts, etc.
=> apps: hosting support

ui/package-lock.json, ui/package.json, ui/src/channels/ChannelHeader.tsx, ui/src/chat/useChatStore.ts, ui/src/logic/useReactQueryScry.ts, ui/src/logic/useReactQuerySubscribeOnce.tsx, ui/src/logic/useReactQuerySubscription.tsx, ui/src/queryClient.ts, ui/src/state/chat/chat.ts, ui/src/state/groups/groups.ts
Stop fetching on focus and reconnect by default, better briefs syncing, new channel reaping handling, stopping channel notifications from being automatically marked read (clogging request queue).
=> reconnect: tweaking pt3

ui/patches/@urbit+http-api+2.4.5-debug.patch
=> http-api: update patch

ui/src/chat/ChatMessage/__snapshots__/ChatMessage.test.tsx.snap, ui/src/components/ShipName.tsx, ui/src/components/Sidebar/__snapshots__/Sidebar.test.tsx.snap
=> shipname: show nickname on hover if calm

pre_playwright.sh, ui/e2e/shipManifest.json
OTT, fixes issues I was having running tests locally because I had other ships running on those ports
=> ops: use more less contentious ports

ui/src/dms/DMHero.tsx
Resolves #2430 
Adds click handler to the DM hero sigil that shows the clicked user's profile modal
=> talk: add click to dm hero to show profile modal

desk/app/chat.hoon
Addresses https://github.com/tloncorp/landscape-apps/issues/1890.
=> chat: fix initialization of 'new' in +di-abed-soft

ui/src/state/lure/lure.ts
=> Add a 'not' to fix backwards error logic

ui/src/state/groups/groups.ts
=> groups: immediately remove group data on leave

desk/app/groups.hoon, ui/src/groups/Groups.tsx, ui/src/state/groups/groups.ts
This breaks playwright for now, I'll make a follow-up PR to fix playwright.
=> groups: add message to connectivity check hi, block scry until hi completes

ui/src/channels/ChannelHeader.tsx, ui/src/chat/ChatInput/ChatInput.tsx, ui/src/chat/ChatInputMenu/ChatInputMenuToolbar.tsx, ui/src/components/InstallPrompt.tsx, ui/src/components/LandscapeWayfinding.tsx, ui/src/components/MigrationTooltip.tsx, ui/src/components/SettingDropdown.tsx, ui/src/components/Sidebar/GangItem.tsx, ui/src/components/Sidebar/Sidebar.tsx, ui/src/components/Sidebar/SidebarSorter.tsx, ui/src/components/VitaMessage.tsx, ui/src/diary/DiaryChannel.tsx, ui/src/diary/DiaryNoteOptionsDropdown.tsx, ui/src/dms/DMOptions.tsx, ui/src/dms/MessagesSidebar.tsx, ui/src/groups/GroupActions.tsx, ui/src/groups/GroupAdmin/GroupMemberItem.tsx, ui/src/groups/GroupSidebar/ChannelSortOptions.tsx, ui/src/styles/components.css, ui/tailwind.config.js
Unifies all system dropdowns. Fixes #2176
=> groups: unify dropdowns

ui/src/app.tsx, ui/src/state/settings.ts
Switch to %settings from %settings-store
Fixes #2548
=> switch to new %settings agent

ui/src/chat/ChatScroller/ChatScroller.tsx
=> chat: initial load should be at bottom on non-scrollto chats

ui/src/chat/ChatScroller/ChatScroller.tsx
This fixes the error seen in LAND-560
Fixes LAND-560
=> chat-scroller: work with virtuoso dev quirks

ui/package-lock.json, ui/package.json, ui/src/chat/ChatScroller/ChatScroller.tsx, ui/src/chat/ChatScroller/IChatScroller.ts, ui/src/chat/ChatSearch/ChatSearchResults.tsx, ui/src/chat/ChatThread/ChatThread.tsx, ui/src/state/chat/chat.ts, ui/src/state/chat/writs.ts, ui/src/types/chat.ts
OTT, this should resolve the last of the perf issues from search hopefully 
Fixes LAND-584
=> chat: switch to btree for perf

ui/src/logic/channel.ts
=> talk: don't count invalid clubs in unreads

ui/src/state/diary/diary.ts
Fixes LAND-597 and another missing quips issue (i.e., the note in the cache was the wrong shape, did not include quips).
Also updates our optimistic update functionality to be in-line with the tanstack query docs on setQueryData: https://tanstack.com/query/v4/docs/react/reference/QueryClient#queryclientsetquerydata
Fixes LAND-589 as well.
=> diary: fix more cache issues

desk/lib/mark-warmer.hoon
=> groups: missing group warmer

ui/src/state/storage/storage.ts
fixes LAND-631
other agent names are fine.
=> update agent name for storage

ui/src/app.tsx, ui/src/diary/DiaryChannel.tsx, ui/src/diary/DiaryNote.tsx, ui/src/diary/diary-add-note.tsx, ui/src/heap/HeapDetail.tsx, ui/src/heap/HeapDetail/HeapDetailHeader.tsx, ui/src/notifications/Notifications.tsx
=> groups: inconsistent browser tab labels

ui/src/diary/DiaryCommentField.tsx
=> notebook: make all the add comment section focusable

ui/src/components/PalIcon.tsx
Fixes https://github.com/tloncorp/landscape-apps/actions/runs/5428572389/jobs/9872886867#step:4:1
=> author: fix tsc error

ui/src/components/PalIcon.tsx
Adds new SVGs and dark mode(s).
=> groups: add new pals icons

ui/src/components/ActivityModal.tsx, ui/src/logic/analytics.ts, ui/src/state/settings.ts
Fixes issue with capturing analytics events when we've opted-in.
=> analytics: capture the data when opted

ui/src/components/AboutDialog.tsx, ui/src/components/ImageURLUploadField.tsx, ui/src/components/SettingsDialog.tsx, ui/src/components/ShipSelector.tsx, ui/src/components/Sidebar/MobileSidebar.tsx, ui/src/groups/GroupAdmin/GroupAdmin.tsx, ui/src/groups/GroupAdmin/GroupInfoFields.tsx, ui/src/groups/GroupInviteDialog.tsx, ui/src/styles/components.css
=> groups: mobile layout issues

ui/src/components/ErrorAlert.tsx, ui/src/state/vere.ts
Fixes LAND-660
Looks like this when submitted to github:
=> Update error boundary issue template

desk/app/diary.hoon, desk/mar/diary/logs-1.hoon, desk/mar/diary/logs-2.hoon, desk/mar/diary/logs.hoon, desk/mar/diary/update-1.hoon, desk/mar/diary/update-2.hoon, desk/mar/diary/update.hoon, desk/sur/diary-0.hoon, ui/src/notifications/useNotifications.tsx, ui/src/state/diary/diary.ts, ui/test/setup.ts
This updates @patosullivan 's branch so that we correctly increment the epic and negotiate versions correctly. Notably this means we need some signalling around version mismatch, will handle in LAND-532.
=> diary: update increment

ui/src/dms/Dm.tsx, ui/src/dms/MultiDm.tsx
fixes LAND-654
On the tin, see Linear for comparison.
=> chat: prevent thread panel shrinkage on long message input

ui/src/components/SettingsDialog.tsx, ui/src/groups/GroupInviteDialog.tsx
=> groups: app info and group modals no longer scrollable; incorrect spacings

ui/src/diary/diary-add-note.tsx
we really need to get CI fixed :(
=> fix ts error in build, blocking deploys

ui/src/groups/GroupAdmin/GroupRoleCreate.tsx, ui/src/groups/GroupAdmin/GroupRoles.tsx
=> groups: support non-@tas characters in role names

ui/src/components/References/GroupReference.tsx, ui/src/components/References/UnavailableReference.tsx
=> groups: add a button mode for unavailable group references

ui/src/groups/FindGroups.tsx
=> find: show all groups if the group is not found

ui/src/components/SettingsDialog.tsx, ui/src/diary/diary-add-note.tsx, ui/src/heap/HeapTextInput.tsx, ui/src/logic/tiptap.ts, ui/src/types/content.ts, ui/src/types/groups.ts
OTT
Fixes LAND-678
https://github.com/tloncorp/landscape-apps/assets/90741358/7f6269d4-6a1d-4457-9533-f6471c83fe18
=> diary: fix styling when note title is long

ui/src/groups/GroupAdmin/GroupAdmin.tsx, ui/src/groups/GroupAdmin/GroupMemberItem.tsx
OTT
Fixes LAND-708
https://github.com/tloncorp/landscape-apps/assets/90741358/db46035a-b4a2-4d1c-9993-a752715c7643
=> groups: fix dropdown visibility when editing member roles in Admin Dialog

ui/src/app.tsx, ui/src/components/Sidebar/MobileSidebar.tsx, ui/src/dms/Dm.tsx, ui/src/dms/MessageSelector.tsx, ui/src/dms/MobileMessagesSidebar.tsx, ui/src/dms/MultiDm.tsx
this does not include adding DMs to desktop, but it could easily be added. this does not include the new icon treatment, but it could if we want it to.
fixes LAND-711
=> mobile: add DMs to groups mobile

ui/src/diary/DiaryChannel.tsx, ui/src/diary/DiaryList/DiaryGridItem.tsx, ui/src/diary/DiaryList/DiaryGridView.tsx, ui/src/diary/DiaryList/DiaryListItem.tsx, ui/src/state/diary/diary.ts, ui/src/types/diary.ts
Reduces ambiguity around working with notebook data.
Fixes LAND-679.
=> notebooks: refactor to remove DiaryLetters and DiaryNotes types

ui/src/diary/DiaryNote.tsx
=> notebooks: hide edit button on cached notes

ui/src/diary/DiaryHeader.tsx, ui/src/diary/DiaryNote.tsx, ui/src/diary/DiaryNoteHeader.tsx, ui/src/diary/DiaryNoteOptionsDropdown.tsx
Enables all edit functionality if you host the channel.
=> notebook: add self-hosting check to diary channels

desk/app/groups.hoon
=> groups: remove channel meta notifications

desk/app/chat.hoon, ui/src/groups/GroupSidebar/__snapshots__/ChannelList.test.tsx.snap
=> chat: don't allow dming self

ui/package-lock.json, ui/package.json, ui/src/heap/HeapDetail/HeapDetailBody.tsx, ui/src/heap/HeapVideoPlayer.tsx, ui/src/heap/HeapVimeoPlayer.tsx, ui/src/heap/HeapYoutubePlayer.tsx
Adds support for displaying video files and fixes positioning in YouTube/Vimeo embeds.
Fixes LAND-618
=> Heap: Fix video positioning in heap detail view

desk/app/groups-ui.hoon, desk/app/groups.hoon, desk/desk.docket-0, desk/lib/groups-json.hoon, desk/lib/mark-warmer.hoon, desk/mar/groups-ui.hoon, desk/mar/ui/init-0.hoon, desk/mar/ui/init.hoon, desk/sur/groups.hoon, desk/sur/ui.hoon, talk/app/talk-ui.hoon, talk/desk.docket-0, talk/mar/ui/init-0.hoon, talk/mar/ui/init.hoon, talk/sur/ui.hoon, ui/src/components/References/ReferenceBar.tsx, ui/src/components/References/WritBaseReference.tsx, ui/src/groups/GroupSidebar/__snapshots__/ChannelList.test.tsx.snap, ui/src/heap/HeapDetail/HeapDetailSidebar/HeapComment.tsx, ui/src/state/bootstrap.ts, ui/src/state/groups/groups.ts, ui/src/state/lure/lure.ts
Brings the bugfixes for the right-hand error in Notebooks, a guard against DMing yourself, and the v0 backcompat changes for 4.2.1 into the `august-growth` branch.
=> 4.2.1 -> august-growth

ui/e2e/005-accept-group-invite.spec.ts, ui/src/groups/Groups.tsx
=> groups: adjust "Wait a sec" copy

ui/src/groups/GroupSidebar/__snapshots__/ChannelList.test.tsx.snap, ui/src/groups/LureInviteBlock.tsx, ui/src/state/lure/lure.ts
This refactors the lure checker so that it uses react query which gives us a little more info into what's going on to present more status to the user, and brings the UI more inline with the rest.
Sidenote we have a lot flags here that combine into one state that should probably be combined somehow.
=> lure: more link checking status

ui/src/channels/ChannelHeader.tsx
=> talk: user can't go back from a group channel on mobile

ui/src/chat/ChatEmbedContent/TwitterEmbed.tsx
fixes LAND-759
looks like this:
=> twitter embeds: handle deleted tweets

ui/src/api.ts, ui/src/app.tsx, ui/src/components/Eyrie.tsx, ui/src/logic/analytics.ts, ui/src/state/local.ts, ui/src/window.ts
Adds the ability to:
- turn on verbose mode
- show eyrie
- show react-query-devtools
- turn on analytics debugging
by running window.toggleDevTools() in the console
fixes LAND-663
=> Add production debug tools

ui/e2e/004-invite-to-group.spec.ts, ui/src/diary/DiaryList/DiaryGridItem.tsx, ui/src/diary/DiaryNoteOptionsDropdown.tsx, ui/src/diary/useDiaryActions.ts, ui/src/heap/HeapBlock.tsx, ui/src/heap/useCurioActions.ts
=> groups: add new action menu to notebook and gallery items

.github/workflows/deploy-kernel-groups.yml, .github/workflows/deploy-kernel-talk.yml
=> ops: allow deploying to kernel moon

ui/package-lock.json, ui/package.json, ui/src/components/ToggleGroup.tsx, ui/src/notifications/GroupNotification.tsx, ui/src/notifications/Notification.tsx, ui/src/notifications/Notifications.tsx, ui/src/notifications/useNotifications.tsx
Fixes LAND-758
Looks like this (note, ignore group meta notifications since we don't emit those anymore):
https://github.com/tloncorp/landscape-apps/assets/1221094/570bdd00-be67-44b2-8529-2a417b2fe478
Dark mode:
Desktop (mostly unchanged):
=> groups: implement new activity view

ui/src/chat/ChatEmbedContent/ChatEmbedContent.tsx, ui/src/state/embed.ts
=> support x.com embeds

ui/src/dms/MobileMessagesSidebar.tsx
=> groups: don't show group channels in DM messages list

ui/src/chat/ChatMessage/ChatMessage.tsx, ui/src/chat/ChatMessage/ChatMessageOptions.tsx, ui/src/components/ActionMenu.tsx, ui/src/logic/useLongPress.ts
=> chat: support long press actions on messages

ui/src/channels/ChannelActions.tsx, ui/src/channels/ChannelHeader.tsx, ui/src/channels/HostConnection.tsx, ui/src/chat/ChatChannel.tsx, ui/src/chat/ChatContent/ChatContent.tsx, ui/src/chat/ChatContent/ChatContentImage.tsx, ui/src/chat/ChatMessage/ChatMessage.tsx, ui/src/chat/ChatThread/ChatThread.tsx, ui/src/components/ActionMenu.tsx, ui/src/components/LightBox.tsx, ui/src/components/MobileHeader.tsx, ui/src/components/NavTab.tsx, ui/src/diary/DiaryMarkdownEditor.tsx, ui/src/dms/Dm.tsx, ui/src/dms/MultiDm.tsx, ui/src/groups/ChannelsList/GroupChannelManager.tsx, ui/src/groups/GroupActions.tsx, ui/src/groups/GroupSidebar/MobileGroupSidebar.tsx, ui/src/groups/MobileGroupChannelList.tsx, ui/src/heap/HeapDetail/HeapDetailBody.tsx, ui/src/heap/HeapDetail/HeapDetailHeader.tsx, ui/src/profiles/Profile.tsx, ui/src/styles/components.css
=> mobile: making headers more clickable

ui/package-lock.json, ui/package.json, ui/src/chat/ChatEmbedContent/ChatEmbedContent.tsx, ui/src/styles/index.css
Fixes LAND-620. Shows a thumbnail, renders/plays-inline. No lightbox.
https://github.com/tloncorp/landscape-apps/assets/1221094/56432d05-defa-48f2-847c-c63b7eaacfea
We might want to limit the height/width? It can actually be customized quite a bit, too, if we want to do that:
https://video-react.js.org/customize/customize-component/
=> Chat: Add video player embed

ui/src/chat/ChatEmbedContent/ChatEmbedContent.tsx, ui/src/chat/ChatInput/ChatInput.tsx, ui/src/components/MobileHeader.tsx, ui/src/components/ShipConnection.tsx, ui/src/dms/DMOptions.tsx, ui/src/dms/Dm.tsx, ui/src/dms/MultiDm.tsx, ui/src/styles/index.css
We were missing the titles for these so I added them in. Was also considering updating the alignment like @urcades latest designs, but figured that might be too much to chew. Did throw in hiding chat formatting bar.
=> mobile: dms header

ui/src/app.tsx, ui/src/components/RoleBadges.tsx, ui/src/groups/GroupSidebar/ChannelList.tsx, ui/src/groups/Members.tsx, ui/src/state/groups/groups.ts
Fixes LAND-792
https://github.com/tloncorp/landscape-apps/assets/1221094/2b47a184-5119-4eb3-bc56-2f30b67f0dea
=> groups: new mobile member list

ui/src/chat/ChatInput/ChatInput.tsx
=> chat: images rendered in code blocks

ui/src/groups/ChannelsList/EditSectionDropdown.tsx
=> groups: fix issue with dropdown/action menu for sections in channel manager

ui/src/components/Sidebar/GangItem.tsx, ui/src/components/Sidebar/GroupsSidebarItem.tsx, ui/src/dms/DMOptions.tsx, ui/src/dms/MessagesSidebarItem.tsx, ui/src/groups/GroupActions.tsx
=> talk/groups: add ActionMenu on long-press for dm/group actions

ui/src/components/Layout/Layout.tsx, ui/src/components/Layout/__snapshots__/Layout.test.tsx.snap, ui/src/heap/AddCurioModal.tsx, ui/src/heap/CurioPreview.tsx, ui/src/heap/HeapChannel.tsx, ui/src/heap/HeapHeader.tsx
=> Gallery: Display error messages for drag/paste and failed file upload

ui/src/chat/ChatMessage/ChatMessage.tsx, ui/src/components/Layout/__snapshots__/Layout.test.tsx.snap, ui/src/groups/GangPreview/__snapshots__/GangPreview.test.tsx.snap, ui/src/groups/GroupSidebar/__snapshots__/ChannelList.test.tsx.snap, ui/src/heap/HeapChannel.tsx
=> chat: default msg to smallest width

desk/lib/diary-json.hoon, desk/lib/notes.hoon, desk/mar/diary/action-2.hoon, desk/mar/diary/action-3.hoon, desk/mar/diary/logs-2.hoon, desk/mar/diary/logs-3.hoon, desk/mar/diary/update-2.hoon, desk/mar/diary/update-3.hoon, desk/sur/diary.hoon, ui/package-lock.json, ui/package.json, ui/src/diary/DiaryContent/DiaryContent.tsx, ui/src/diary/DiaryInlineEditor.tsx, ui/src/diary/DiaryMarkdownEditor.tsx, ui/src/diary/parserRules.ts, ui/src/diary/plugins/actionmenu.tsx, ui/src/diary/schema.ts, ui/src/logic/tiptap.ts, ui/src/types/content.ts, ui/src/types/diary.ts
Fixes LAND-756.
https://github.com/tloncorp/landscape-apps/assets/1221094/18acd3e2-663a-4ff2-be3e-9cc8ef542c41
=> notebooks: add markdown checkboxes

ui/src/channels/ChannelHeader.tsx, ui/src/chat/ChatChannel.tsx, ui/src/components/Mention/MentionPopup.tsx, ui/src/diary/DiaryChannel.tsx, ui/src/diary/DiaryHeader.tsx, ui/src/heap/HeapHeader.tsx, ui/src/logic/useReactQuerySubscription.tsx, ui/src/state/diary/diary.ts
Fixes two bugs we'd been tracking:
- The `cannot read 0 of undefined` issue that was preventing notes from being edited
- The permissions issue causing  the "Add Note" button to not be shown
Also adds some stronger typing and defensive naming to prevent similar issues in the future.
Fixes LAND-870
=> diary: fix edit note crash and missing add note button

ui/src/heap/HeapChannel.tsx
=> heap: fix bad prop reference in latest build

desk/app/chat.hoon, desk/app/heap.hoon, desk/lib/notes.hoon
=> notifications: don't receive from self

ui/src/heap/AddCurioModal.tsx, ui/src/heap/HeapInputPlaceholder.tsx, ui/src/heap/NewCurioInput.tsx
Fixes LAND-912 by adding a custom placeholder component to the heap editor which gives an upload button.
https://github.com/tloncorp/landscape-apps/assets/5466421/7f91c44d-616f-44b5-80e2-5144ec1e43cb
=> heap: adding way to upload from mobile

ui/src/chat/ChatChannel.tsx, ui/src/chat/ChatInput/ChatInput.tsx, ui/src/chat/ChatThread/ChatThread.tsx, ui/src/components/Layout/__snapshots__/Layout.test.tsx.snap, ui/src/logic/SafeAreaContext.tsx, ui/src/logic/native.ts, ui/src/main.tsx, ui/src/nav/GroupsNav.tsx, ui/src/nav/TalkNav.tsx, ui/src/notifications/Notifications.tsx
Improvements for padding and safe areas.
- Fixed mobile header on notifications screen
- Removed bottom insets when keyboard is opened
- Removed extra whitespace under content 
Fixes LAND-908
=> Padding tweaks

ui/src/groups/Members.tsx, ui/src/profiles/ProfileModal.tsx
Correctly pops the profile modal in the new Members view. Also adjusts the "Message" button in the profile modal to route to the correct DM view.
https://github.com/tloncorp/landscape-apps/assets/748181/1194f992-dc36-4af8-ac3a-30ba16eb0d04
Fixes LAND-934
=> members: fix profile nav, profile: route to DM

ui/package-lock.json, ui/package.json, ui/src/components/Sidebar/GroupList.tsx, ui/src/diary/DiaryChannel.tsx, ui/src/dms/MessagesList.tsx, ui/src/groups/GroupSidebar/ChannelList.tsx, ui/src/groups/GroupSidebar/__snapshots__/ChannelList.test.tsx.snap, ui/src/heap/HeapChannel.tsx
=> groups: retain scroll position through nav changes

ui/src/components/About/AboutView.tsx, ui/src/components/Settings/SettingsView.tsx, ui/src/profiles/EditProfile/EditProfile.tsx, ui/src/profiles/Profile.tsx
- Removes animation on the Profile / Settings screens
- Affixes the "Edit Profile" header to the top of the screen when scrolling
- Adjusts the margins of the App Settings and About screens
Fixes LAND-903
Fixes LAND-904
Fixes LAND-905
=> profile, settings: remove animation, fix scrolling, margins

ui/src/chat/ChatChannel.tsx
=> groups: add message when user can't write to channel

ui/src/state/bootstrap.ts
OTT, seeing bad behavior, will investigate
=> bootstrap: revert reconnect changes for now

ui/src/app.tsx, ui/src/chat/ChatChannel.tsx, ui/src/components/Layout/Layout.tsx, ui/src/components/LightBox.tsx, ui/src/components/Sidebar/MobileSidebar.tsx, ui/src/dms/Dm.tsx, ui/src/dms/Dms.tsx, ui/src/dms/MessageSelector.tsx, ui/src/dms/MultiDm.tsx, ui/src/groups/Groups.tsx
Fixes LAND-969, LAND-946, LAND-961, LAND-965.
=> mobile: fix safearea in several places, persist bottom nav throughout the app

ui/src/groups/Groups.tsx
OTT, should fix threads being invsible
=> groups: layout changes broke threads

desk/app/chat.hoon, ui/src/chat/ChatChannel.tsx, ui/src/chat/ChatThread/ChatThread.tsx
https://github.com/tloncorp/landscape-apps/assets/1221094/2ba30604-98b0-4663-a8f5-064b0fd5e83d
Fixes LAND-988
Just missed a spot yesterday when applying the bottomPadding.
=> mobile: fix issue with bottom nav covering chat input on threads

ui/src/profiles/ProfileModal.tsx
=> profile: fix buttons on profile

ui/src/chat/ChatScroller/ChatScroller.tsx, ui/src/logic/useScrollerMessages.ts, ui/src/logic/utils.ts
- Somewhat better optimized processing of incoming chat messages
- Improved anchoring of `scrollTo` message
Fixes LAND-975
Fixes LAND-973
Fixes LAND-976
Fixes LAND-978
Fix for 978 isn't 100%, but it should be much improved, and we can reassess after wider testing.
=> Scroll improvements

ui/src/chat/ChatReactions/ReactionDetails.tsx, ui/src/components/WidgetDrawer.tsx, ui/src/profiles/ProfileCoverImage.tsx, ui/src/profiles/ProfileModal.tsx
See homestead for demo video. Only applies on mobile, desktop left as is. 
Needs some some fine-tuning (for example, dynamic sheet height based on how large your profile is), but that can come later.
=> mobile: move profiles from modal to sheet

ui/src/chat/ChatScroller/ChatScroller.tsx
=> scroller: safer dereferencing

ui/src/chat/ChatScroller/ChatScroller.test.tsx, ui/src/chat/ChatScroller/ChatScroller.tsx
=> scroller: add test for rendering empty list

ui/src/diary/DiaryContent/DiaryContent.tsx
It does what it says on the tin and fixes LAND-1021
=> notebook: adds max-widths to codeblocks

ui/src/app.tsx, ui/src/chat/ChatChannel.tsx, ui/src/chat/ChatInput/ChatInput.tsx, ui/src/chat/ChatThread/ChatThread.tsx, ui/src/components/Sidebar/MobileSidebar.tsx, ui/src/dms/Dm.tsx, ui/src/dms/MultiDm.tsx, ui/src/logic/ChatInputFocusContext.tsx
fixes LAND-1010
https://github.com/tloncorp/landscape-apps/assets/1221094/fd7e226b-c8a3-4dcd-a5e5-96e8a3e6fbe7
=> mobile: hide navbar when using the chat input

ui/src/profiles/Profile.tsx
=> profile: add link to manage account

ui/src/profiles/Profile.tsx
An app-side change which fixes HOST-79. We will need to merge and run the deploy sequence once https://github.com/tloncorp/ylem/pull/1793 is deployed to production (@waiyaki will inform when this is complete).
=> profile: change "Manage Account" target

ui/src/heap/HeapDetail.tsx
to account for persistent nav bar.
Fixes LAND-1034.
=> mobile: Add bottom padding for gallery item view

ui/src/chat/ChatScroller/ChatScroller.tsx
=> scroller: ensure message options stay on top

ui/src/chat/ChatChannel.tsx, ui/src/chat/ChatThread/ChatThread.tsx, ui/src/components/Sidebar/MobileSidebar.tsx, ui/src/dms/Dm.tsx, ui/src/dms/MultiDm.tsx, ui/src/heap/HeapDetail.tsx, ui/src/styles/components.css
Fixes LAND-930
https://github.com/tloncorp/landscape-apps/assets/22919953/c5677a9d-a4f9-497d-a990-6ec6c980fca7
=> mobile: fix animation of the chat input during keyboard appearance

ui/src/chat/ChatScroller/ChatScroller.tsx, ui/src/logic/scroll.ts
Working pr for fixing LAND-1040 and LAND-1041. The initial commit should fix most issues, but I'm still testing, and want to dig into the `hasLoadedNewest` flag, since that should probably have prevented these issues.
=> scroller: initial fix for short scrollers

ui/src/app.tsx, ui/src/logic/native.ts
Enables RN to better handle loading states
LAND-1007
=> Post Message to RN when App.tsx initialy runs

ui/src/diary/DiaryComment.tsx, ui/src/diary/DiaryNote.tsx
should fix LAND-944, though I wasn't able to repro the issue.
=> notebook: don't attempt to get a time from an empty string, use sent value where possible

ui/src/app.tsx, ui/src/chat/ChatChannel.tsx, ui/src/chat/ChatThread/ChatThread.tsx, ui/src/dms/Dm.tsx, ui/src/dms/MultiDm.tsx
=> talk: search and message input regressions

ui/src/diary/DiaryContent/DiaryContent.tsx
=> diary: fix long link wrapping

ui/src/components/Mention/MentionPopup.tsx, ui/src/components/MessageEditor.tsx, ui/src/diary/DiaryInlineEditor.tsx
=> chat/diary: support @ mentions (in addition to ~)

ui/src/chat/ChatWindow.tsx, ui/src/dms/DMOptions.tsx, ui/src/dms/Dm.tsx, ui/src/dms/MessageSelector.tsx, ui/src/dms/MultiDm.tsx, ui/src/dms/NewDm.tsx, ui/src/logic/utils.ts, ui/src/state/chat/chat.ts
- Fixes issue where creating a new dm would appear to get stuck loading indefinitely
- Fixes an issue that caused leaving a dm to redirect to the groups home tab
- Modifies new DM interface -- removes "Connect" action, making actually sending the message the primary action, and removes "Cancel" on mobile, as the back arrow in the header makes it redundant. 
Fixes LAND-1070
Fixes LAND-1071
=> New DM flow fixes

ui/src/components/Sidebar/MobileSidebar.tsx
OTT
I know this is a very small change, but can whoever reviews this please try locally before merging?
Fixes LAND-1097
=> mobile nav: fix wonky profile icon

ui/src/logic/utils.ts
=> utils: dont require dev for hosted

ui/src/logic/utils.ts
=> utils: dont bail if env not loaded

ui/src/profiles/Profile.tsx
=> profile: fix accidental QR hardcode

ui/src/components/QRWidget.tsx
=> qr: colors cant be inverted

ui/src/components/QRWidget.tsx, ui/src/groups/LureInviteBlock.tsx, ui/src/profiles/Profile.tsx
=> QR codes: handle non success states

ui/src/components/QRWidget.tsx
=> QR loading state lowercase message

ui/src/components/QRWidget.tsx, ui/src/state/lure/lure.ts
- we don't check if lure isn't enabled
- we shouldn't report error unless we did actually check
=> lure: fix status conditions once more

ui/E2E.md
@patosullivan feel free to suggest any edits
=> Add e2e.md with notes on automated tests

ui/src/chat/ChatInput/ChatInput.tsx, ui/src/chat/ChatMessage/ChatMessage.tsx, ui/src/chat/ChatThread/ChatThread.tsx, ui/src/components/References/ContentReference.tsx, ui/src/diary/DiaryCommentField.tsx, ui/src/diary/diary-add-note.tsx, ui/src/heap/HeapDetail/HeapDetailSidebar/HeapDetailCommentField.tsx, ui/src/heap/HeapDetail/HeapDetailSidebar/HeapDetailComments.tsx, ui/src/heap/HeapTextInput.tsx, ui/src/logic/messageSender.ts, ui/src/replies/ReplyMessage.tsx, ui/src/state/channel/channel.ts, ui/src/types/channel.ts
Fixes LAND-1167
Fixes LAND-1185
Fixes LAND-1184
Fixes LAND-1183
Also fixes a misnamed type for reply responses.
Edit: Now fixes LAND-1176 as well. I also decided to reuse the DiaryCommentField component for Heap comments since the use case is nearly identical (and we were abusing HeapTextInput for that purpose before).
=> chat: fix issues with sent indicators, various issues with replies

ui/src/chat/ChatWindow.tsx, ui/src/diary/DiaryChannel.tsx, ui/src/heap/HeapChannel.tsx
Fixes LAND-1155, looks like this:
=> hackweek: show incompatibility message on newly joined, pre-migrated channels

ui/src/chat/ChatWindow.tsx, ui/src/state/channel/channel.ts
Fixes LAND-1171
We'll need the same thing on #2996 for DMs/Clubs
=> hackweek: only show 'go to latest' button when we're not already at the latest

ui/src/components/Sidebar/Sidebar.tsx
=> fix discover typo in sidebar

ui/src/channels/HostConnection.tsx, ui/src/components/ShipConnection.tsx, ui/src/dms/Dm.tsx, ui/src/dms/MultiDm.tsx, ui/src/groups/FindGroups.tsx, ui/src/groups/GroupSummary.tsx, ui/src/groups/Join/JoinGroupModal.tsx, ui/src/logic/channel.ts, ui/src/state/negotiation.ts, ui/src/types/negotiation.ts
Also make useNegotiation generic, used only in useNegotiate and useNegotiateMulti, fix issue with incompatibility shown on group join, fix css issue on incompatible message in DMs/MultiDMs.
Fixes LAND-1216.
Fixes LAND-1227.
Fixes LAND-1228
=> negotiation: insert facts into cache as we hear them

.github/workflows/glob-and-deploy-hackweek-talk.yml, .github/workflows/glob-and-deploy-hackweek.yml
=> ops: make deploys for hackweek automatic

ui/src/components/WelcomeCard.tsx
=> groups: typographic + color tweaks to welcome message

ui/src/state/chat/chat.ts
=> dms: fix delivery tracking when a dm is first created

ui/src/logic/messageSender.ts
=> dms: fix image link detection when sending messages

ui/src/channels/HostConnection.tsx, ui/src/components/ShipConnection.tsx, ui/src/dms/Dm.tsx, ui/src/logic/channel.ts, ui/src/state/negotiation.ts, ui/src/types/negotiation.ts
And assume we're waiting and everything is fine until we know otherwise
=> negotiation: switch to using status from negotiation rather than boolean

ui/src/dms/NewDm.tsx, ui/src/logic/useMessageSelector.ts
=> dms: block new club creation if some of the ships have version mismatch

ui/src/chat/ChatUnreadAlerts.tsx
fixes LAND-1237
I think this got taken out by mistake earlier on in the hackweek branch.
=> unreads: fix issue with closing unread banner

ui/src/logic/channel.ts
=> negotiation: fix bad status in useChannelCompatibility

ui/src/app.tsx, ui/src/components/EmojiPicker.tsx, ui/src/logic/utils.ts
Fixes the reacts popup / emoji picker not showing on mobile
https://github.com/tloncorp/landscape-apps/assets/1013230/dd5633c6-38f7-41d6-9fbd-fefb1ecc8b76
=> fix reacts popup not showing on mobile

ui/src/chat/ChatWindow.tsx, ui/src/diary/DiaryChannel.tsx, ui/src/dms/DmWindow.tsx, ui/src/heap/AddCurioModal.tsx, ui/src/heap/HeapChannel.tsx, ui/src/state/channel/channel.ts, ui/src/state/chat/chat.ts
fixes LAND-1250
fixes LAND-1255
=> fix paging issues on infinite scroll for channels and DMs

ui/src/state/groups/groups.ts
=> groups: properly invalidate queries when leaving

ui/src/chat/ChatScroller/ChatScroller.tsx, ui/src/chat/ChatScroller/ChatScrollerDebugOverlay.tsx
Remove merge artifact which caused some issues with scroller.
Also adds optional debug overlay for scroller.
=> Fix some scroller issues

ui/src/state/channel/channel.ts
fixes LAND-1270 by updating the post within the pagemap in the cache. Previously we were just updating the cache if it existed (via the usePost query).
Follows the pattern of doing cache updates directly in the onMutate of the mutation.
=> emojis: update posts in cache within onMutate, show emoji reactions optimistically

ui/src/chat/ChatScroller/ChatScroller.tsx
Fixes LAND-1283 by ignoring negative adjustments (always seems to be -1) from the virtualizer in certain cases (such as a message with replies being pushed into view as new messages are received), which would cause a visually imperceptible scroll that would then trigger the chat input to lose focus.
Also: adds some changes for showing chat scroller debug overlay by default when in dev mode by using useShowDevTools().
=> scroller: fix issue that would cause chat input to lose focus after sending while in the scrollback

ui/src/constants.ts, ui/src/groups/GroupSidebar/ChannelList.tsx, ui/src/logic/channel.ts, ui/src/logic/useGroupSort.ts, ui/src/logic/useMessageSort.ts, ui/src/logic/useSidebarSort.ts, ui/src/state/settings.ts
Fixes LAND-1251 by improving defaulting behavior here and makes constants more clear.
=> sidebars: better defaulting, moving constants around

ui/src/state/chat/chat.ts
Setting up the subscription was failing if you were in a chat that you'd just initiated. This updates the logic to wait until we're sure the agent is ready to accept the sub.
Fixes LAND-1306
=> dms: fix missing messages after getting an unread banner

talk/app/talk-cli.hoon
Reverts tloncorp/landscape-apps#3075
Not yet!
=> Revert "talk-cli: import chat structures v2 always"

desk/app/chat.hoon
=> chat: need to handle old wires

ui/src/state/chat/chat.ts
=> dms: update DM query data in place when we hear facts

desk/app/channels.hoon
=> channels: dont include self in unreads

ui/src/chat/ChatThread/ChatThread.tsx, ui/src/dms/DMThread.tsx, ui/src/dms/DmWindow.tsx, ui/src/replies/ReplyMessage.tsx
We weren't calling markRead anywhere in threads.
=> unreads: add markreads back to threads

ui/src/chat/ChatMessage/ChatMessageOptions.tsx
=> chat/dms: update delete modal to spin while loading and close when complete

desk/app/groups.hoon, ui/src/app.tsx, ui/src/groups/GroupAdmin/GroupAdmin.tsx
OTT
Fixes LAND-1370
To reproduce, create a private group and from another ship, request to join it. You'll get a notification in your activity feed that doesn't work without this PR. You'll have to install this branch's `%groups` desk to test.
=> groups: fix broken "requested to join" notifications

ui/src/heap/AddCurioModal.tsx
=> gallery: clear uploader state after attempting to add a gallery block

.github/workflows/bump.yml, .github/workflows/deploy-groups.yml, .github/workflows/deploy-kernel-groups.yml, .github/workflows/deploy-kernel-talk.yml, .github/workflows/deploy-talk.yml, .github/workflows/glob-and-deploy-hackweek-talk.yml, .github/workflows/glob-and-deploy-hackweek.yml, .github/workflows/glob-and-deploy-kernel-groups.yml, .github/workflows/glob-and-deploy-kernel-talk.yml, .github/workflows/sync.yml
This token is not needed and causing and error
https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token
Fixes LAND-1424
=> Remove repo token from groups workflow LAND-1424

ui/src/replies/ReplyMessage.tsx
=> dm: in dm threads, make sure we don't display normal date divider if unread divider is shown

ui/src/chat/useChatStore.ts
=> unread: correctly clear unreads across clients

ui/index.html
fixes HOST-232 safari image upload
=> Remove data: blob: from meta in index

ui/index.html, ui/src/logic/native.ts, ui/src/state/storage/upload.ts
=> csp: remove csp policy without breaking upload in safari

ui/src/logic/tiptap.ts
Fixes `@` mentions not showing in sent messages
=> fix @ mentions not showing in messages

ui/src/groups/GroupAdmin/GroupInfoEditor.tsx, ui/src/groups/GroupAdmin/GroupInfoFields.tsx
Adds a character counter and error state to the group description editor
https://github.com/tloncorp/landscape-apps/assets/1013230/ce3333ee-95f4-472c-9bfc-09501dde6ad8
=> add character counter to group description editor

ui/src/groups/GroupAdmin/GroupRoleCreate.tsx, ui/src/groups/GroupAdmin/GroupRoles.tsx, ui/src/state/groups/groups.ts
- Updates the delete group role flow to wait for success, optimistically update group cache, and invalidate group query when complete
- Updates create group role flow to go back to roles list on create success
- Fixes styling on various button loading states
=> optimistically remove deleted roles from group cache

desk/app/channels.hoon
https://linear.app/tlon/issue/LAND-1057/contacts-on-group-join-grab-latest-set-of-authors
=> LAND-1057: Fetch contacts for authors on receiving checkpoint

DEVELOPMENT.md
@arthyn does it also have to go from the other places?
https://github.com/tloncorp/landscape-apps/blob/5535cfc56f8b6672e2394f9cd1358bcd49a8d279/DEVELOPMENT.md?plain=1#L53
https://github.com/tloncorp/landscape-apps/blob/5535cfc56f8b6672e2394f9cd1358bcd49a8d279/DEVELOPMENT.md?plain=1#L54
https://github.com/tloncorp/landscape-apps/blob/5535cfc56f8b6672e2394f9cd1358bcd49a8d279/DEVELOPMENT.md?plain=1#L76
=> Remove --delete from rsync example in DEVELOPMENT.md

ui/src/logic/tiptap.test.ts, ui/src/logic/tiptap.ts
Fixes recursion crash when pasting pre-formatted text with bold/italics into the New Block modal for galleries
=> fix crash when pasting bold/italics into new gallery block

.github/pull_request_template.md
OTT, adds the checklist oriented PR template we workshopped internally.
Fixes LAND-1457
=> workflow: add PR template

desk/app/chat.hoon
https://linear.app/tlon/issue/LAND-1059/contacts-add-percentheeds-to-multi-dms-by-default
=> LAND-1059: Add contact on multi-DM join

ui/package-lock.json, ui/package.json
PR Checklist
This fixes color regression seen from tloncorp/landscape-apps#3187. Tested by opening a thread and closing it to trigger blue-softer usage.
=> deps: better handling of alpha values

ui/src/app.tsx
PR Checklist
Tested by opening Talk locally and was able to see the report dialog, which does not currently show up on livenet.
=> flagging: forgot to include modal on talk

desk/app/groups.hoon
=> LAND-1063: Preview contacts' favorite groups

ui/.eslintrc.js
=> lint: require key prop in jsx component iterations

desk/sur/activity.hoon
PR Checklist
`desk/sur/activity.hoon`
N/A
N/A
=> LAND-1514: Types for activity agent

.github/workflows/deploy-external-talk.yml, .github/workflows/deploy-internal-talk.yml, .github/workflows/deploy-livenet-talk.yml, .github/workflows/deploy-talk.yml
=> ops: temporarily restore talk actions since github needs in main branch

.github/workflows/deploy-canary-groups.yml
OTT, wonder if this was why the frontend is being weird
=> ops: need to reglob on staging

.github/workflows/deploy-canary-groups.yml
Needed proper dependency chain
=> ops: fix canary deploy

.github/helpers/deploy.sh
=> ops: add log to deploy

.github/workflows/deploy-canary-groups.yml, .github/workflows/deploy-groups.yml
=> ops: fix deploy yml

ui/src/logic/useMessagesUnreadCount.ts
PR Checklist
Tested locally with varied unreads and checked the counts when changing filters
=> messages: fix dm filter count

ui/src/components/Sidebar/SidebarHeader.tsx
OTT
Tested locally against a self hosted moon.
Fixes LAND-1548
PR Checklist
=> desktop sidebar: fix dropdown links for Leap and Landscape

desk/desk.docket-0
fixes land-1549
tested locally on a livenet moon
PR Checklist
=> icons: fix landscape tile

ui/src/profiles/EditPublicProfile.tsx, ui/src/state/profile/profile.ts
OTT
Tested against a local ship.
Fixes LAND-1558
PR Checklist
=> profile: keep edit widget checklist UI in sync with backend updates

DEVELOPMENT.md, apps/tlon-web/README.md
=> web: update readme and development docs

apps/tlon-web/src/chat/ChatThread/ChatThread.tsx
Fixes LAND-1450
Not clear where the bad link was generated, but this is where the error was occurring.
Tested on local livenet moons.
PR Checklist
=> channels: redirect on bad id in thread URL

apps/tlon-mobile/android/app/proguard-rules.pro, apps/tlon-mobile/ios/Landscape.xcodeproj/project.pbxproj, apps/tlon-mobile/ios/Podfile.lock, apps/tlon-mobile/package.json, apps/tlon-mobile/src/App.tsx, apps/tlon-mobile/src/db/index.ts, apps/tlon-mobile/src/db/realm.tsx, apps/tlon-mobile/src/db/schemas.ts, apps/tlon-mobile/src/lib/api.ts, apps/tlon-mobile/src/lib/contactsApi.test.ts, apps/tlon-mobile/src/lib/contactsApi.ts, apps/tlon-mobile/src/lib/sync.ts, package-lock.json
PR Checklist
Tested by running sync and observing logs.
This PR adds Realm, and in order to test it also adds basic Urbit contact syncing. When the app enters an authenticated state, the app will fetch contacts + store them in the database. This PR does not yet include any examples of retrieving the stored contacts.
=> Add Realm + Contact sync

apps/tlon-web/src/state/bootstrap.ts
fixes the perf issue on develop/wannec right now.
We need to figure out a way to prefetch that actually works and doesn't have massive overhead.
Will find the original linear issue and pull it back into todo.
This means LAND-1556 moves back to todo.
=> state: rip out prefetching on unread in bootstrap

apps/tlon-mobile/android/app/build.gradle, apps/tlon-mobile/app.config.ts, apps/tlon-mobile/ios/Landscape.xcodeproj/project.pbxproj
=> ops: bump mobile version to 47

apps/tlon-web/src/components/Avatar.tsx, apps/tlon-web/src/dms/MultiDmAvatar.tsx, apps/tlon-web/src/groups/GroupAvatar.tsx, apps/tlon-web/src/state/avatar.ts
Reverts the change that technically fixed LAND-1691 but introduced a great many regression. Since we plan on releasing tomorrow, I want to unblock the release and work on it a bit more before pushing out.
We all make mistakes.
This PR targets staging.
=> groups: revert avatar src-checking

apps/tlon-web/package.json, apps/tlon-web/src/components/Avatar.tsx, apps/tlon-web/src/dms/MultiDmAvatar.tsx, apps/tlon-web/src/groups/GroupAvatar.tsx, apps/tlon-web/src/state/avatar.ts, desk/desk.docket-0
Undoes those avatar changes that were pulled in from staging yesterday.
=> ops: revert staging merge

patches/react-native-reanimated+3.6.2.patch
Applied the patch to the relevant js file rather than the ts file. Ran the prod build and served it locally and it works.
=> fix react native reanimated on web issue

apps/tlon-web/src/channels/NewChannel/NewChannelForm.tsx, package-lock.json, package.json
=> new-channel: remove errant space preventing check from working

apps/tlon-web/src/replies/ReplyMessage.tsx, desk/app/channels.hoon, desk/app/groups.hoon
We still had a few things hanging out in staging/master which hadn't made their way back into develop
=> staging to develop

apps/tlon-web/src/state/storage/upload.ts
=> s3: fix a regression that caused uploads to fail for cloudflare R2 users

packages/shared/src/api/chatApi.ts, packages/shared/src/api/index.ts, packages/shared/src/api/initApi.ts, packages/shared/src/db/queries.ts, packages/shared/src/sync.ts
Implements loading of aggregated data from the groups init endpoint.
=> Implement native init data endpoint

packages/ui/src/components/Channel/ChatScroll.tsx
Updates the MotiView to only be rendered once the message is active vs always on every chat message.
=> mobile: fix chat message lag

apps/tlon-mobile/src/fixtures/ChannelHeader.fixture.tsx, apps/tlon-mobile/src/fixtures/FixtureWrapper.tsx, apps/tlon-mobile/src/fixtures/ScreenHeader.fixture.tsx, apps/tlon-mobile/src/hooks/useRefetchQueryOnFocus.ts, apps/tlon-mobile/src/hooks/useScreenOptions.ts, apps/tlon-mobile/src/screens/ChannelScreen.tsx, apps/tlon-mobile/src/screens/ChatListScreen.tsx, packages/shared/src/api/urbit.ts, packages/shared/src/db/queries.ts, packages/shared/src/db/query.ts, packages/shared/src/debug.ts, packages/shared/src/store/index.ts, packages/shared/src/store/sync.ts, packages/shared/src/store/syncQueue.ts, packages/shared/src/store/useChannelPosts.ts, packages/shared/src/store/useInitialSync.ts, packages/ui/src/components/Channel/ChatScroll.tsx, packages/ui/src/components/ChatMessage/index.tsx, packages/ui/src/components/IconButton.tsx, packages/ui/src/components/ScreenHeader.tsx, packages/ui/src/index.ts
- add sync queue for more control over loading
- enable gesture nav
- optimize initial load sequence
- fix channel switcher
- remove some extraneous queries
- add home screen header and load state
=> Demo polish

packages/ui/src/components/ActionList.tsx, packages/ui/src/core/Modal.tsx
=> message actions: action list style tweaks

apps/tlon-mobile/src/navigation/HomeStack.tsx, apps/tlon-mobile/src/screens/ChatListScreen.tsx
Fix plus button size on native.
=> native: fix add icon size

apps/tlon-mobile/src/hooks/useCurrentUser.ts, apps/tlon-mobile/src/navigation/TabStack.tsx, apps/tlon-mobile/src/screens/ChannelScreen.tsx, apps/tlon-mobile/src/screens/ChannelSearchScreen.tsx
OTT
Tried this in my already authenticated state and from scratch with a fresh install. No cast fails in sight
=> mobile: ensure we always pass along correct user id

apps/tlon-mobile/src/fixtures/Channel.fixture.tsx, apps/tlon-mobile/src/fixtures/PostScreen.fixture.tsx, apps/tlon-mobile/src/hooks/useImageUpload.ts, apps/tlon-mobile/src/screens/ChannelScreen.tsx, apps/tlon-mobile/src/screens/PostScreen.tsx, packages/shared/src/api/postsApi.ts, packages/shared/src/api/upload.ts, packages/shared/src/db/queries.ts, packages/shared/src/logic/utils.ts, packages/shared/src/store/postActions.ts, packages/shared/src/store/sync.ts, packages/ui/src/components/Channel/index.tsx, packages/ui/src/components/ChatMessage/ChatMessageReplySummary.tsx, packages/ui/src/components/PostScreenView.tsx, packages/ui/src/contexts/contacts.tsx
- fixes missing nicknames in threads
- extracts upload image logic into reusable hook
- adds support for uploading images to threads
- updates parent post metadata when sending/receiving thread replies (reply count, reply authors, last reply time)
Fixes LAND-1852
Fixes LAND-1850
=> native: thread fixes

apps/tlon-mobile/src/fixtures/Channel.fixture.tsx, apps/tlon-mobile/src/screens/ChannelScreen.tsx, packages/shared/src/api/index.ts, packages/shared/src/api/settingsApi.ts, packages/shared/src/db/migrations/0000_adorable_moira_mactaggert.sql, packages/shared/src/db/migrations/meta/0000_snapshot.json, packages/shared/src/db/migrations/meta/_journal.json, packages/shared/src/db/migrations/migrations.js, packages/shared/src/db/queries.ts, packages/shared/src/db/schema.ts, packages/shared/src/db/types.ts, packages/shared/src/store/dbHooks.ts, packages/shared/src/store/sync.ts, packages/shared/src/store/useInitialSync.ts, packages/shared/src/urbit/index.ts, packages/shared/src/urbit/settings.ts, packages/ui/src/components/Avatar.tsx, packages/ui/src/components/Channel/index.tsx, packages/ui/src/components/PostScreenView.tsx, packages/ui/src/contexts/calm.tsx
Fixes LAND-1838
Also fixes an issue with syncing channel perms, where the db would throw an error if we've previously synced channel perms (added onConflictDoUpdate).
=> native: sync calm state, pass it where appropriate

apps/tlon-mobile/src/fixtures/Channel.fixture.tsx, apps/tlon-mobile/src/fixtures/MessageInput.fixture.tsx, apps/tlon-mobile/src/fixtures/PostScreen.fixture.tsx, apps/tlon-mobile/src/screens/ChannelScreen.tsx, apps/tlon-mobile/src/screens/PostScreen.tsx, packages/ui/src/components/Channel/index.tsx, packages/ui/src/components/MessageInput/MessageInputBase.tsx, packages/ui/src/components/MessageInput/index.native.tsx, packages/ui/src/components/PostScreenView.tsx
=> native: automatically save input drafts

apps/tlon-web/src/diary/DiaryNote.tsx, apps/tlon-web/src/state/channel/channel.ts
This fixes LAND-1816 by correcting the types here.
PR Checklist
=> diary: fix host notes check 

apps/tlon-mobile/src/screens/ChannelScreen.tsx, apps/tlon-mobile/src/screens/PostScreen.tsx, packages/ui/src/components/ChatMessage/ChatMessageActions/Component.android.tsx
=> native: fix "Start a Thread" on Android

apps/tlon-web/src/groups/AddGroup/JoinGroup.tsx
=> join-group: shipselector needed better validation

apps/tlon-web/src/components/Sidebar/useSearchFilter.ts, apps/tlon-web/src/dms/MessagesList.tsx
=> sidebar: use fuzzy instead of startswith

packages/ui/src/components/PostScreenView.tsx
=> native: fix ref attachments in thread view

packages/ui/src/components/ContactName.tsx
=> native: ellipsize long contact display names

apps/tlon-mobile/src/screens/PostScreen.tsx
Also removes unnecessary layout effect for hiding the tab bar (it's already hidden in this view since we hid it in the channel view).
Fixes LAND-1885
=> native: add safe area padding to PostScreen

packages/shared/src/api/channelsApi.ts, packages/shared/src/store/sync.ts
=> native: handle hide/show post subscription events

apps/tlon-web/src/components/Mention/MentionPopup.tsx
=> mentions: dont pop in code blocks

apps/tlon-mobile/src/fixtures/Channel.fixture.tsx, packages/ui/src/components/Channel/index.tsx
Some fixes post-scroller-merge:
- Fixes channel horizontal padding
- Fixes notebook channels failing to load
- Refactors channel fixture a bit
=> native: fix channel layout issues

packages/ui/src/components/AuthorRow.tsx
Missed that @urcades and @jamesacklin requested this in a figma comment.
=> native: remove author names from gallery root view

apps/tlon-mobile/src/fixtures/Channel.fixture.tsx, apps/tlon-mobile/src/hooks/useCurrentUser.ts, apps/tlon-mobile/src/screens/ChannelScreen.tsx, apps/tlon-mobile/src/screens/ChannelSearchScreen.tsx, apps/tlon-mobile/src/screens/PostScreen.tsx, apps/tlon-mobile/src/screens/useChannelContext.ts, packages/shared/src/api/apiUtils.ts, packages/shared/src/api/groupsApi.ts, packages/shared/src/store/postActions.ts, packages/shared/src/store/useChannelPosts.ts, packages/ui/src/components/Channel/index.tsx, packages/ui/src/components/ChannelSwitcherSheet.tsx, packages/ui/src/components/PostScreenView.tsx, packages/ui/src/contexts/calm.tsx
This is an incremental refactor that groups up shared functionality between thread and channel views. Could be cleaned up more but helps start to isolate the reused logic.
=> native: channel screen refactor

apps/tlon-mobile/src/hooks/useFocusNotifyOnChangeProps.ts, apps/tlon-mobile/src/screens/ChatListScreen.tsx, packages/shared/src/store/dbHooks.ts
- Disables re-rendering of chat list query when offscreen
- Disabled refetch of init data every time ChatList is focused
=> native: more perf work

apps/tlon-web/vite.config.mts
=> vite: make sure we don't dupe react query

apps/tlon-web/src/components/Sidebar/MobileSidebar.tsx, pnpm-lock.yaml
Should fix issue seen with recent deploy to develop
PR Checklist
=> release: fix import and lockfile

desk/lib/activity-json.hoon, packages/shared/src/urbit/activity.ts
This should help @latter-bolden
PR Checklist
=> activity: add notified flag to json

packages/shared/src/urbit/activity.ts
This should fix build
PR Checklist
=> activity: re-jigger types to better reflect backend

apps/tlon-mobile/src/screens/ChannelScreen.tsx, apps/tlon-mobile/src/screens/ChannelSearchScreen.tsx, apps/tlon-mobile/src/screens/ChatListScreen.tsx, apps/tlon-mobile/src/screens/useChannelContext.ts, apps/tlon-mobile/src/types.ts, packages/shared/src/store/useChannelPosts.ts, packages/shared/src/store/useInitialSync.ts, packages/ui/src/components/Channel/index.tsx
- Fixes hang when opening a channel with unreads
- Syncs stale channels on return to chat list
=> native: sync tweaks

apps/tlon-web/src/dms/DMOptions.tsx, apps/tlon-web/src/groups/GroupSidebar/ChannelList.tsx, apps/tlon-web/src/logic/channel.ts, apps/tlon-web/src/state/unreads.ts
=> activity: always bubble blue dots

packages/shared/src/api/apiUtils.ts, packages/shared/src/api/chatApi.ts, packages/shared/src/store/sync.ts, packages/shared/src/urbit/dms.ts, packages/ui/src/components/PostScreenView.tsx
Ports over my chat sub work from the main activity PR. Hopefully helps solve some of the weirdness we're seeing in DMs more broadly.
Also fixes the problem where the parent post is missing and the input is all the way at the top when starting a new thread.
Fixes TLON-1926
=> native: wire up chat sub

apps/tlon-web/vite.config.mts
=> vite: fix webmanifest request

packages/ui/src/components/ContentRenderer.tsx
=> native: fix missing serifs in note content

.github/workflows/sync-dev.yml
=> ops: keep dev in sync with staging

.github/workflows/sync-dev.yml, apps/tlon-web/src/chat/ChatThread/ChatThread.tsx, apps/tlon-web/src/components/Leap/useLeap.tsx, apps/tlon-web/src/dms/DMOptions.tsx, apps/tlon-web/src/dms/DMThread.tsx, apps/tlon-web/src/groups/GroupSidebar/ChannelList.tsx, apps/tlon-web/src/logic/channel.ts, apps/tlon-web/src/state/unreads.ts, apps/tlon-web/vite.config.mts, desk/app/activity.hoon, desk/desk.docket-0, desk/lib/activity-json.hoon, desk/lib/mark-warmer.hoon, desk/mar/activity/feed-init.hoon, desk/mar/activity/feed.hoon, desk/sur/activity.hoon, packages/shared/src/urbit/activity.ts
=> ops: fix dev sync and merge staging changes

packages/shared/src/db/queries.ts
Fixes TLON-1965 by excluding replies from lastPosts
=> native: don't show thread replies as lastPosts

packages/shared/src/db/queries.ts
Fixes TLON-2074 by early returning if cursorRow length is zero.
=> native: fix rowNumber undefined issue on opening a dm

desk/app/activity.hoon
Our previous attempt to limit duplicates only made sure we saw new sources from a previous request. This now checks to make sure we haven't added that source yet (with exception for mentions).
Fixes TLON-2082
PR Checklist
=> activity: remove feed duplicates

packages/ui/src/components/ProfileScreenView.tsx
=> native: disable logout for now

apps/tlon-web/src/components/ActionMenu.tsx, apps/tlon-web/src/components/NavTab.tsx, apps/tlon-web/src/components/Sidebar/AppNav.tsx, apps/tlon-web/src/components/Sidebar/GroupsSidebarItem.tsx, apps/tlon-web/src/groups/GroupActions.tsx, apps/tlon-web/src/state/unreads.ts
Fixes TLON-2110 by adding a "mark all read" option in a sheet (or dropdown on desktop) that appears on longpress of the home icon.
=> web: add mark all read button to home button

desk/desk.docket-0
=> ops: staging to dev

apps/tlon-mobile/src/App.main.tsx, apps/tlon-mobile/src/ErrorBoundary.tsx
=> native: add error boundary, explicitly send js errors to crashlytics

.github/workflows/sync-dev.yml
=> ops: dont fail dev sync if there's nothing to commit

apps/tlon-web/src/groups/GroupSidebar/ChannelList.tsx, apps/tlon-web/src/state/unreads.ts, desk/app/chat.hoon
Fixes TLON-2103, TLON-2109, TLON-2117
PR Checklist
=> unreads: fix missing counts, missing group dots, and inability to clear dm threads

desk/app/activity.hoon
=> activity: dont crash on bad data

packages/shared/src/db/modelBuilders.ts, packages/shared/src/store/postActions.ts
This fixes the issue where the post author is incorrectly displayed (missing contact) when a just-sent post is initially rendered.
=> native: fix initial post author

apps/tlon-mobile/src/screens/ChatListScreen.tsx, packages/shared/src/store/sync.ts
Fix race condition that could cause previews to fail to appear.
=> fix previews

packages/ui/src/components/Channel/index.tsx
Micro PR to fix a small regression.
Fixes TLON-2151
=> native: hide input when channel is a DM invite

packages/shared/src/api/chatApi.ts, packages/shared/src/api/postsApi.ts, packages/shared/src/db/queries.ts, packages/shared/src/db/types.ts, packages/shared/src/store/sync.ts
=> native: fix off by 1 DM reply counts

apps/tlon-mobile/src/screens/ChatListScreen.tsx
OTT
Fixes TLON-2190
@patosullivan thinking this will be easiest for you to continue merging into develop in the meantime, but lemme know if there's another solution you'd prefer!
=> native: hide group actions for now

apps/tlon-mobile/package.json, apps/tlon-web/package.json, packages/shared/package.json, packages/ui/package.json, pnpm-lock.yaml
Updates Tamagui packages from 1.93.2 to 1.101.3 (latest). No breaking changes, tested in sim and via Expo build. 
Details here: https://github.com/tamagui/tamagui/releases
=> update tamagui dep

apps/tlon-web/src/mocks/chat.ts, apps/tlon-web/src/mocks/handlers.ts, apps/tlon-web/src/state/bootstrap.ts, apps/tlon-web/src/state/broadcasts.ts, apps/tlon-web/src/state/unreads.ts, desk/app/groups-ui.hoon, desk/mar/ui/init-3.hoon, desk/sur/ui.hoon, packages/shared/src/api/unreads.test.ts, packages/shared/src/urbit/activity.ts
=> groups-ui: fix init types

apps/tlon-mobile/cosmos.imports.ts, apps/tlon-mobile/src/fixtures/GroupMetaScreen.fixture.tsx, apps/tlon-mobile/src/hooks/useImageUpload.ts, apps/tlon-mobile/src/screens/GroupSettings/GroupMetaScreen.tsx, apps/tlon-mobile/src/screens/GroupSettings/useGroupContext.ts, packages/shared/src/api/groupsApi.ts, packages/shared/src/store/groupActions.ts, packages/ui/package.json, packages/ui/src/components/Button.tsx, packages/ui/src/components/Channel/ChannelHeader.tsx, packages/ui/src/components/DeleteSheet.tsx, packages/ui/src/components/FeatureFlagScreenView.tsx, packages/ui/src/components/FormInput.tsx, packages/ui/src/components/GenericHeader.tsx, packages/ui/src/components/GroupChannelsScreenView.tsx, packages/ui/src/components/GroupIcon.tsx, packages/ui/src/components/GroupMetaScreenView.tsx, packages/ui/src/index.ts, pnpm-lock.yaml
=> native: add ability to edit group metadata

apps/tlon-mobile/src/screens/ChannelScreen.tsx, packages/shared/src/logic/utilHooks.ts, packages/shared/src/store/index.ts, packages/shared/src/store/session.ts, packages/shared/src/store/sync.ts, packages/shared/src/store/useChannelPosts.ts, packages/ui/src/components/Channel/Scroller.tsx
Improvements to post loading behavior + performance
- Debounce loader changes so that they don't trigger repeatedly
- Actually load newest page of posts when entering a channel with no unreads.
- Increase page size of posts when loading from the api
=> post loading ux

packages/ui/src/components/Channel/Scroller.tsx, packages/ui/src/components/ChatList.tsx, packages/ui/src/components/SwipableChatListItem.tsx
This PR makes rendering our lists a million times more perfomant lol. Will probably want to keep tuning.
=> native: optimize list rendering

.husky/pre-commit, .husky/pre-push
=> move tests + typecheck to pre-push hook

packages/ui/src/components/ChatList.tsx, packages/ui/src/components/ListItem/SwipableChatListItem.tsx
Fixes fixes chat list swipe interaction, refactor casualty.
=> native: fix chat list item swipe

desk/lib/mark-warmer.hoon
=> add ui-init-3 to mark-warmer

packages/ui/src/components/ContentReference/ChannelReference.tsx, packages/ui/src/components/ContentReference/GalleryReference.tsx, packages/ui/src/components/ContentReference/GalleryReferenceWrapper.tsx, packages/ui/src/components/ContentReference/index.tsx
=> native: implement gallery refs

desk/app/channels.hoon
OTT, let's us suspend activity on hosts
PR Checklist
=> channel: don't unconditionally scry activity, check running

apps/tlon-mobile/eas.json
=> native: set notify provider for production deploys

apps/tlon-mobile/src/App.main.tsx, packages/ui/package.json, packages/ui/src/components/Channel/Scroller.tsx, packages/ui/src/components/Channel/index.tsx, packages/ui/src/components/ChatMessage/ChatMessageActions/EmojiToolbar.tsx, packages/ui/src/components/DetailView/DetailView.tsx, packages/ui/src/components/Emoji/EmojiPickerSheet.tsx, packages/ui/src/components/Emoji/SizableEmoji.tsx, packages/ui/src/components/Emoji/data.ts, packages/ui/src/components/Emoji/index.ts, packages/ui/src/components/PostScreenView.tsx, packages/ui/src/components/SearchBar.tsx, packages/ui/src/index.ts, pnpm-lock.yaml
I think this is at a good stopping place for now.
Fixes the sheet drag catching when you scroll the emojis and adds search. Should also be a step up in performance, but there's certainly more work to be done on that front.
Fixes TLON-2333
=> native: better emoji picker

desk/app/activity.hoon
We potentially have bad data here, so we should be careful.
PR Checklist
=> activity: dont crash feed

apps/tlon-web/src/state/activity.ts
OTT, I forgot to actually do the marking read -.-  working on that now but I don't want it to affect internal deploy will fix as another PR later.
PR Checklist
=> activity: disabling auto-marking until it can be fixed

apps/tlon-web/src/logic/useScrollerMessages.ts, apps/tlon-web/src/notifications/DMNotification.tsx, apps/tlon-web/src/notifications/Notifications.tsx, apps/tlon-web/src/state/chat/chat.ts, desk/app/activity.hoon, desk/app/channels.hoon, desk/app/groups.hoon, desk/desk.docket-0
=> ops: sync dev 7 23

desk/app/activity.hoon
OTT, this was causing crashes when scrolling in the activity feed. Fixes TLON-2436
PR Checklist
=> activity: we shouldn't operate on events we have no indices for

apps/tlon-web/src/app.tsx, apps/tlon-web/src/components/Sidebar/util.tsx, apps/tlon-web/src/groups/GroupSidebar/GroupSidebar.tsx, apps/tlon-web/src/groups/useGroupJoin.ts
includes the commits from https://github.com/tloncorp/tlon-apps/pull/3795
=> ops: copy blank screen fixes over to staging

desk/app/activity.hoon, desk/tests/app/activity.hoon
This uses a more reliable time so that we know for sure it will be marked read. Forgive me again.
PR Checklist
=> activity: fix init again

desk/app/activity.hoon, desk/desk.docket-0, desk/lib/activity.hoon, desk/lib/test-agent.hoon, desk/tests/app/activity.hoon
=> ops: sync dev 7 26

apps/tlon-mobile/ios/Landscape.xcodeproj/project.pbxproj
/1/chan/chat/~bitpyx-dildus/interface/msg/170141184506927627689871266747728789504
=> native: point Landscape-preview scheme to correct extension dependency

packages/shared/src/store/postActions.ts
=> native: fix for retries sent as notices

packages/shared/src/store/storage/storageActions.ts
=> storage: use de-sigged patp since that was previously used

apps/tlon-mobile/src/navigation/RootStack.tsx, packages/shared/src/db/queries.ts
OTT
Chatted with Hunter, sounds like freezing blurred screens isn't critical to his perf changes. We'll need more work to ensure that doesn't break things before adding.
=> native: fix delayed unread clearing

desk/app/activity.hoon
=> activity: set allowed to all since we won't be using it

packages/app/features/top/ChannelScreen.tsx, packages/shared/src/db/queries.ts, packages/ui/src/components/ImageViewerScreenView.tsx
Grab bag of small fixes that came up in feedback with the last build.
Fixes TLON-2586 (channels freeze on white screen)
Fixes TLON-2580 (missing close overlay on image viewer)
Fixes TLON-2589 (reactions not inserted when adding posts)
=> native: hotfixes

desk/mar/channels-2.hoon
OTT, this mark should have changed when we did all our new types
=> channels: bad mark

packages/app/hooks/useHandleLogout.ts, packages/app/utils/hosting.ts
=> native: reset hosting auth tracking on signout

apps/tlon-mobile/src/screens/Onboarding/InventoryCheckScreen.tsx, apps/tlon-web-new/src/lib/migrator.ts
Mistakenly wrapped text with text, which caused problems with updating the color when switching between light/dark display modes.
=> onboarding: fix primary button text color

apps/tlon-mobile/src/controllers/PostScreenController.tsx, apps/tlon-mobile/src/fixtures/DetailView.fixture.tsx, apps/tlon-mobile/src/fixtures/PostScreen.fixture.tsx, apps/tlon-web-new/src/controllers/PostScreenController.tsx, packages/app/features/top/PostScreen.tsx, packages/ui/src/components/PostScreenView.tsx
As it turns out, we had all the click-handling set up in AuthorRow but weren't passing anything down through the view (from the controller) to handle navigating to a profile from a detail view. Fixes TLON-2208.
Video evidence:
https://github.com/user-attachments/assets/bfddcab7-e08c-4138-98dc-2d5a2a427a17
=> detail view: allow navigating to profile

apps/tlon-web-new/src/app.tsx, apps/tlon-web-new/src/lib/triggers.ts, apps/tlon-web-new/src/lib/webDb.ts, packages/shared/src/api/chatApi.ts, packages/shared/src/db/keyValue.ts, packages/shared/src/store/sync.ts
Fixes TLON-2691
Fixes TLON-2692
Fixes TLON-2716
We need to wait to render the AppRoutes until we know that we have data in the db, otherwise the app may appear blank before the user starts interacting with it. To fix this, I added a loop to poll whether the database size is zero. If it's not zero, we consider that "loaded" and we can render the AppRoutes.
This issue also effected loading in contact/calm settings data via the AppDataContext, and even if that data had loaded in we weren't getting it throughout useContact/useCalmSettings in the app. This was somewhat fixed by moving the context provider into AppRoutes, but it seems like a race condition could cause that data to still not be loaded in, so I also added a useEffect to refetch contacts/calm settings.
This also fixes the …
=> new web: omnibus db-related fixes

apps/tlon-web/src/groups/LureInviteBlock.tsx, apps/tlon-web/src/logic/branch.ts, apps/tlon-web/src/state/lure/lure.ts, desk/desk.docket-0, packages/shared/src/store/lure.ts, packages/ui/src/components/InviteUsersWidget.tsx
=> ops: merge staging into develop

packages/ui/src/components/GroupMembersScreenView.tsx
Adds safe-area padding to the bottom of the Members list.
=> Members: adds padding to the bottom of the list

packages/ui/src/components/ChatOptionsSheet.tsx
=> rectify options sheets for groups/channels/dms/multi-dms

packages/shared/src/store/lure.ts
- fix stale Lure detection
- only consider Lure status _ready_ if we have a deeplink
- more error logging
- shorten timeout for subscribe once fetches
Should resolve TLON-2753, but I was only seeing that present on the actual build. Will cut a new one and confirm resolved before closing.
=> native: more lure fixes

apps/tlon-mobile/src/controllers/CreateGroupScreenController.tsx, apps/tlon-web-new/src/controllers/CreateGroupScreenController.tsx, packages/app/features/top/CreateGroupScreen.tsx, packages/ui/src/components/CreateGroupView.tsx
=> group creation: make sure back button goes back to chat list after successful group creation

packages/ui/src/components/PostContent/contentUtils.tsx
Prevents crash which could occur when activity post content is null.
=> fix activity crash

desk/app/grouper.hoon
=> grouper: should only send DM if inviter

packages/shared/src/store/useChannelPosts.ts
fixes TLON-2729 (or at least one cause of it!)
| Before | After |
| --- | --- |
| <video src="https://github.com/user-attachments/assets/1f330280-1e99-4202-b759-64049d67e0b7" /> | <video src="https://github.com/user-attachments/assets/d85e97ba-851c-41a9-ac27-199e2d9b7acd" /> |
<details>
<summary>Those videos use the following patch to make the bug reproducible by simulating a slow call to sync endpoint:</summary>
```diff
diff --git a/packages/shared/src/store/sync.ts b/packages/shared/src/store/sync.ts
index 9f403e053..d412a600d 100644
--- a/packages/shared/src/store/sync.ts
+++ b/packages/shared/src/store/sync.ts
@@ -901,6 +901,10 @@ export async function syncPosts(
newer: response.newer,
older: response.older,
});
+  } else {
+    console.log('Simulating slow sync...');
+    await new …
```
=> native: use null pagination token to indicate end of posts list

.github/workflows/ci.yml, .github/workflows/deploy-canary.yml, .github/workflows/deploy-ephemeral.yml, .github/workflows/deploy.yml, .github/workflows/mobile-build.yml, .github/workflows/mobile-update.yml, .husky/pre-commit, .husky/pre-push, package.json, pnpm-lock.yaml
=> remove local git + postinstall hooks

packages/ui/src/components/Channel/EmptyChannelNotice.tsx
=> Only show lure invite button if we're an admin in a new empty group

desk/app/grouper.hoon
Never changed the flag for these after refactoring, fixes TLON-2855
PR Checklist
=> grouper: fix private group invites

desk/app/chat.hoon
OTT, found by @dnbrwstr 
PR Checklist
=> chat: now that we have blocks, dont ignore archived DMs

packages/app/features/top/useConnectionStatus.tsx
Fixes TLON-2813 by avoiding showing "Offline" for your own node status on your profile.
=> useConnectionStatus: always return 'yes' for self

packages/ui/src/components/Channel/ChannelHeader.tsx, packages/ui/src/components/Channel/index.tsx
=> move the 'add' button in notebook/gallery to header

packages/ui/src/components/ChatOptionsSheet.tsx
Breaks group admin actions in the group actions sheet out into a sub-menu, similar to Notifications. Also reformats the "Group with 420 members" string to handle group publicity and single-member counts ("Secret group with 1 member," etc.).
Fixes TLON-2755; the sheet is now _slightly_ shorter.
=> ChatOptionsSheet: break out group admin actions into sub-pane

.github/workflows/deploy-canary.yml
Does same as your other PR but for canary
PR Checklist
=> ops: add package build step for canary

packages/ui/src/components/CreateGroupView.tsx
Fixes TLON-2890 by adding horizontal padding in CreateGroupView.
=> CreateGroupView: better padding in sheet

packages/ui/src/components/ListItem/InteractableChatListItem.tsx
Ensures action callback is updated with list item.
=> fix swipe actions

packages/ui/src/components/Channel/DmInviteOptions.tsx
| Before | After |
|---|---|
| ![Screenshot 2024-10-03 at 6 44 45 PM](https://github.com/user-attachments/assets/ca7bc4bb-42c4-4bb4-a7b5-b5f52fe72d8e) | ![Screenshot 2024-10-03 at 6 39 34 PM](https://github.com/user-attachments/assets/c235f085-ed08-4b88-abb4-85fd6b5df23e) |
=> DmInviteOptions: pad up from bottom

packages/shared/src/store/useChannelPosts.ts
fixes TLON-2848
If we're in bad network conditions or if the ship is under heavy load we could be in a state where if a user sends a post while the channel is still syncing while a user is sending a new post. If that happens, and then the channel sync completes, and then the post is actually sent, the user could see both the pending post and the real post from the backend. It appears to be happening because of some async issue where clearMatchedPendingPosts is called before the new post is added to the query data, so it doesn't find a patching pending post and both posts make it in.
We need to dig deeper to diagnose that async issue, but for now this will fix the apparent issue for users.
=> chat: fix duplicate posts after send

packages/app/hooks/useHandleLogout.native.ts, packages/app/hooks/useHandleLogout.ts, packages/shared/src/api/urbit.ts, packages/ui/src/components/GroupChannelsScreenView.tsx
Fixes TLON-2895 — we'll now show a spinner if we don't yet have any channels for the group to let you know it's still loading
Fixes TLON-2910 — makes sure we fully disconnect the client on logout (subs remaining connected seemed to be the problem, not stale DB data).
=> native: couple tiny fixes

packages/ui/src/components/GroupChannelsScreenView.tsx
| Admin | Non-admin |
|-------|-----------|
| ![Screenshot 2024-10-04 at 2 46 51 PM](https://github.com/user-attachments/assets/dba868fb-c11a-4080-94aa-69e99d9ebaec) | ![Screenshot 2024-10-04 at 2 46 42 PM](https://github.com/user-attachments/assets/aadab892-e1d3-4e10-97b5-97a24d26edd3) |
=> GroupChannelsScreenView: hide + button for non-admins

packages/ui/src/components/ListItem/ChannelListItem.tsx, packages/ui/src/components/ListItem/GroupListItem.tsx, packages/ui/src/components/ListItem/ListItem.tsx
=> ListItem: less-aggressive mute treatment

apps/tlon-mobile/android/app/build.gradle, apps/tlon-mobile/app.config.ts, apps/tlon-mobile/ios/Landscape.xcodeproj/project.pbxproj, apps/tlon-mobile/src/fixtures/Onboarding.fixture.tsx, apps/tlon-mobile/src/screens/Onboarding/WelcomeScreen.tsx, packages/shared/src/db/keyValue.ts, packages/shared/src/store/dbHooks.ts, packages/ui/src/components/Onboarding/OnboardingBenefitsSheet.tsx
- bumps the version to comply with iOS build requirements
- updates Branch env vars to be set conditionally based on preview/prod target
- smuggles in change to only show the welcome sheet on first open (fixes TLON-2851)
Note, after merging if you're working with Branch locally, you'll have to update your env vars:
*BRANCH_KEY* -> *BRANCH_KEY_TEST*
*BRANCH_DOMAIN* -> *BRANCH_DOMAIN_TEST*
=> native: changes for prod

apps/tlon-mobile/src/screens/Onboarding/ShipLoginScreen.tsx, apps/tlon-mobile/src/screens/Onboarding/SignUpPasswordScreen.tsx, apps/tlon-mobile/src/screens/Onboarding/TlonLoginScreen.tsx
Also, just setEulaAgreed on submit.
fixes TLON-2935
=> onboarding: show eula link button on login pages

apps/tlon-mobile/src/screens/Onboarding/InventoryCheckScreen.tsx, packages/ui/src/components/Onboarding/OnboardingBenefitsSheet.tsx, packages/ui/src/components/WelcomeSheet.tsx, packages/ui/src/components/WelcomeSheet.web.tsx
=> WelcomeSheet, OnboardingBenefitsSheet: TM

apps/tlon-mobile/src/screens/Onboarding/PasteInviteLinkScreen.tsx, packages/shared/src/logic/branch.ts
OTT
@dnbrwstr feel free to close
=> native: track branch errors

apps/tlon-mobile/src/screens/Onboarding/PasteInviteLinkScreen.tsx
=> native: fix broken import path

apps/tlon-mobile/src/screens/Onboarding/PasteInviteLinkScreen.tsx
=> native: track onboarding event when invite link clicked/pasted

packages/app/features/groups/GroupMembersScreen.tsx, packages/ui/src/components/GroupMembersScreenView.tsx, packages/ui/src/components/ProfileBlock.tsx, packages/ui/src/components/ProfileSheet.tsx
Makes the "Send message" action work in the user action sheet we have in GroupMembersScreen.
Fixes TLON-2939
https://github.com/user-attachments/assets/af3ad3e1-69e0-4746-8b3a-3537c50fe288
=> GroupMembersScreen, ProfileSheet: wire up navigate to DM

packages/ui/src/components/MessageInput/index.native.tsx
fixes TLON-2787
The issue seems to stem from the user attempting to press "space" while still within the mention node. If we just always add a space immediately after a mention (which is what users want anyway, otherwise they'll just have to press space themselves), the problem goes away.
=> mentions: fix bug with adding space after mentions on android

apps/tlon-mobile/src/fixtures/ActionSheet/GenericActionSheet.fixture.tsx, packages/ui/src/components/ActionSheet.tsx, packages/ui/src/components/ChatOptionsSheet.tsx
Fixes ActionSheet close animations by delaying hiding the modal until animation completes.
=> fix sheet close animations

packages/ui/src/components/MessageInput/MessageInputBase.tsx
=> chat: enable send button even if disconnected/reconnecting

packages/app/features/top/ChannelSearchScreen.tsx
=> search: autofocus chat search box

.github/workflows/mobile-build-nightly.yml
Slightly less disruptive during the workday.
0800 UTC means...
0700 CET
0300 EST
0200 CST
0000 PST
=> meta: build apps at midnight PST

packages/ui/src/components/GalleryPost/GalleryPost.tsx
=> gallery: add captions back to gallery detail views

apps/tlon-mobile/android/app/build.gradle, apps/tlon-mobile/ios/Landscape.xcodeproj/project.pbxproj
OTT
Need to look into why we're getting these warnings with prod and not preview.
=> ops: bump others to 4.0.3

packages/ui/src/components/DetailView.tsx, packages/ui/src/components/PostScreenView.tsx
fixes TLON-2907
https://github.com/user-attachments/assets/dfbf3a23-a82f-4530-abef-369a73a8c515
=> notebook/gallery: scroll to bottom of detail view when reply input is focused

apps/tlon-mobile/src/App.main.tsx, apps/tlon-mobile/src/components/AuthenticatedApp.tsx, apps/tlon-mobile/src/hooks/useNotificationListener.ts
We weren't using these. Tested by running on iOS.
=> native: removed unused notification props

packages/app/features/groups/GroupMembersScreen.tsx, packages/ui/src/components/ChatMessage/ChatMessageActions/MessageActions.tsx, packages/ui/src/components/ChatOptionsSheet.tsx, packages/ui/src/components/GroupMembersScreenView.tsx
Fixes TLON-3076
Only allow posts to be deleted by their authors or the group admin.
=> delete: only show when appropriate

packages/shared/src/api/postsApi.ts
fixes TLON-2961
At one point, in the old web app, we allowed users to post image urls that would be rendered as image posts on the frontend (in galleries and chat). The new app doesn't allow this, but we need to make sure we can still render old image posts in galleries that were formatted this way.
Rather than changing the content renderer, we can detect posts like this before we insert them into the DB and insert them as if they were normal image posts.
The only drawback to this method, afaik, is that the user would need to log out and log back in for posts they already know about (that fit this criteria) to be rendered correctly.
=> gallery: insert old image link posts as image posts in local db

packages/shared/src/db/queries.ts
fixes TLON-2831
also fixes TLON-2971, same thing.
=> members: add 'groups' table to deps for removeChatMembers query

apps/tlon-mobile/src/screens/Onboarding/ReserveShipScreen.tsx, packages/app/hooks/useBootSequence.ts, packages/shared/src/api/urbit.ts, packages/shared/src/http-api/Urbit.ts
=> native: fix onboarding after auth changes

packages/app/hooks/useHandleLogout.native.ts, packages/app/hooks/useHandleLogout.ts, packages/app/utils/splash.ts
=> welcome sheet: show again if user logs out and back in

apps/tlon-mobile/cosmos.imports.ts, packages/ui/src/components/ChatMessage/ViewReactionsPane.tsx, packages/ui/src/components/ChatMessage/ViewReactionsSheet.tsx
=> handle scrolling in view reactions sheet

apps/tlon-mobile/android/app/build.gradle, apps/tlon-mobile/ios/Landscape.xcodeproj/project.pbxproj
=> ops: bump 4.1.0

packages/shared/src/types/PostCollectionConfiguration.ts, packages/ui/src/components/Channel/Scroller.tsx, packages/ui/src/components/DetailView.tsx
=> detail views: fix bad layouts for comments

apps/tlon-mobile/android/app/src/main/java/io/tlon/landscape/notifications/TalkNotificationManager.java
fixes TLON-3104
It looks like we already have everything we need to receive notifications while the app has been killed, the issue was that our `isInForeground` check was always returning true while the app was closed. Afaik, we want notifications while the app is in the foreground anyway (according to another issue galen filed), so I think we can safely remove this (or at least comment it out for now).
Also added some logs around the TalkNotificationManager for debugging in the future.
Tested on a physical device by running a build, allowing the app to open and register a push token, killing the app, then sending a DM to the ship that was logged-in to the app.
=> android: fix issue with notifications service

apps/tlon-mobile/ios/Podfile.lock, apps/tlon-mobile/package.json, package.json, packages/editor/package.json, packages/ui/package.json, packages/ui/src/components/BigInput.native.tsx, packages/ui/src/components/PostScreenView.tsx, packages/ui/src/components/draftInputs/ChatInput.tsx, pnpm-lock.yaml
fixes TLON-3106
Upgraded to tentap 0.5.21, somehow fixed the autofocus/backspace issue. Nothing in their release notes indicated they changed anything directly related to this, but it does work now /shrug
=> input: update tentap, fixes backspace on autofocus, re-enable autofocus

packages/shared/src/api/urbit.ts
As discussed in sync, we need to track these better
PR Checklist
=> urbit: adding posthog error tracking to poke and sub failures

apps/tlon-mobile/src/fixtures/Form.fixture.tsx, apps/tlon-mobile/src/fixtures/UserProfileScreen.fixture.tsx, packages/app/features/settings/AppInfoScreen.tsx, packages/app/features/settings/ProfileScreen.tsx, packages/app/features/settings/UserBugReportScreen.tsx, packages/app/features/top/UserProfileScreen.tsx, packages/ui/src/components/AttachmentSheet.tsx, packages/ui/src/components/EditProfileScreenView.tsx, packages/ui/src/components/FavoriteGroupsDisplay.tsx, packages/ui/src/components/Form/Form.tsx, packages/ui/src/components/Form/controlledFields.tsx, packages/ui/src/components/Form/inputs.tsx, packages/ui/src/components/PostScreenView.tsx, packages/ui/src/components/ProfileScreenView.tsx, packages/ui/src/components/UserProfileScreenView.tsx
Ok, this is enough code that I'm going to cut for review. First set of polish tweaks from our QA pass, focusing on settings screens. 
Includes:
- polish profile edit sequence and input (fixes TLON-3035) (fixes TLON-3045)
- move feature flags to settings root (fixes TLON-3039) (fixes TLON-3025)
- simplify and standardize bug report screen (fixes TLON-3040)
- mark logout action as destructive (fixes TLON-3060)
- fix missing title on gallery post detail screen (fixes TLON-3055)
=> design polish #1

apps/tlon-mobile/src/fixtures/UserProfileScreen.fixture.tsx, packages/ui/src/components/UserProfileScreenView.tsx
=> fix profile layout when bio is empty

apps/tlon-mobile/android/app/build.gradle, apps/tlon-mobile/ios/Landscape.xcodeproj/project.pbxproj
=> ops: bump version

apps/tlon-web-new/vite.config.mts
This fixes the build breakage introduced by #4120.
The issue was that `import './MIGRATION_FILE.sql'` in `shared` was not being interpreted correctly by tlon-web-new's Vite setup:
- Without any change to `vite.config`, it was being interpreted as like, JS i guess? and raising syntax errors about SQL code not being valid JS code
- Adding .sql files to `assetsInclude` so that these are treated as assets by Vite, we get the sql file import resolving as a URL (on dev server, this is a weird URL with a path that includes `@fs` and an absolute local path on my computer's filesystem)
Adding a `?raw` suffix (`import mig from './file.sql?raw'`) fixed the issue, but broke the non-Vite builds (i.e. `tlon-mobile`).
I tried the function-based …
=> web-new: bundle *.sql imports as `export default {filecontent}`

packages/app/navigation/desktop/ChatListDrawerContent.tsx, packages/ui/src/components/ActionSheet.tsx, packages/ui/src/components/ChatOptionsSheet.tsx, packages/ui/src/tamagui.config.ts
fixes TLON-3148
Also cleaned up some names in ChatListDrawerContent.
I created a new ActionSheetMainContent component because we want a different rule here for padding than we do in the ListItemMainContent component, I think.
=> desktop: make action sheet adaptive, display a modal on desktop

packages/ui/src/components/BareChatInput/helpers.ts
Does what it says on the tin.
- Swaps our isUrl regex out for the version that comes from `validator/lib/isURL`
- Handles leading and trailing punctuation
- Preserves all query params
=> BareChatInput: replace isUrl regex with isURL from validator

packages/ui/src/components/BareChatInput/index.tsx
=> desktop chat input fixes: enter to send, fix chat input on web

desk/app/chat.hoon
=> chat: allow dming self

packages/app/features/top/ContactHostedGroupsScreen.tsx, packages/app/features/top/CreateGroupScreen.tsx, packages/app/navigation/desktop/HomeNavigator.tsx, packages/app/navigation/types.ts, packages/ui/src/components/AddGroupSheet.tsx, packages/ui/src/components/ContactBook.tsx, packages/ui/src/components/CreateGroupView.tsx, packages/ui/src/components/FindGroupsView.tsx
Fixes TLON-3199, we just reuse the existing, relevant screens and make sure the ContactBook is scrollable on web.
=> desktop: get create group flow working

desk/app/channels-server.hoon, desk/app/channels.hoon, desk/lib/channel-json.hoon, desk/lib/channel-utils.hoon, desk/sur/channels.hoon
I split this off from 3152 since hooks are going to use a different pathway. This one is super quick and will piggy back off of @mikolajpp 's recent channels changes.
PR Checklist
=> channels: adding field for channel custom metadata

apps/tlon-mobile/src/screens/Onboarding/SignupScreen.tsx, apps/tlon-mobile/src/screens/Onboarding/TlonLogin.tsx
=> native: show eula on new signup and login

apps/tlon-mobile/src/hooks/useDeepLinkListener.ts
OTT, uses the new typed nav helper to fix preview sheet popping when you click a lure link.
Fixes TLON-3203
=> native: fix authed invite link click

packages/ui/src/components/EditProfileScreenView.tsx
OTT
Just need to be careful and intentional about handling undefined vs empty assignment here.
Fixes TLON-3217
=> native: fix clearing avatar from profile

packages/ui/src/components/BareChatInput/index.tsx
=> chat input: reset hasSetInitialContent onSend/onEdit

packages/ui/src/components/ManageChannels/CreateChannelSheet.tsx
Made obsolete by [`ChannelConfigurationBar`](https://github.com/tloncorp/tlon-apps/blob/a9a55377baffda5cb8a3a8a02803734c7c46d503/packages/ui/src/components/ManageChannels/CreateChannelSheet.tsx#L248)
=> custom channels: delete unused edit channel sheet

packages/ui/src/components/ListItem/InteractableChatListItem.tsx
Adds swipe-left actions for groups and (group-)DMs on ChatListScreen to mark the selected item as read.
https://github.com/user-attachments/assets/884b1977-269b-4c55-81e4-cb682688179d
=> InteractableChatListItem: swipe left to mark as read

desk/app/activity.hoon, desk/app/channels.hoon, desk/app/chat.hoon, desk/app/groups.hoon, desk/app/profile.hoon, desk/app/profile/widgets.hoon, desk/lib/activity-json.hoon, desk/lib/activity.hoon, desk/lib/contacts.hoon, desk/lib/contacts/json-1.hoon, desk/lib/notify.hoon, desk/mar/channels-2.hoon, desk/mar/channels-3.hoon, desk/sur/activity.hoon, desk/sur/contacts-0.hoon, desk/sur/contacts.hoon
Implements activity source and events for contact book updates.
Fixes TLON-3176.
=> %contacts activity

apps/tlon-mobile/src/fixtures/Carousel.fixture.tsx, packages/shared/src/api/channelContentConfig.ts, packages/ui/src/components/AuthorRow.tsx, packages/ui/src/components/Carousel.tsx, packages/ui/src/components/ColorPost.tsx, packages/ui/src/components/GalleryPost/GalleryPost.tsx, packages/ui/src/components/ManageChannels/CreateChannelSheet.tsx, packages/ui/src/components/postCollectionViews/CarouselPostCollectionView.tsx, packages/ui/src/components/postCollectionViews/shared.tsx, packages/ui/src/contexts/componentsKits.tsx, packages/ui/src/index.tsx
This PR adds the carousel component + an "immersive feed" collection view based on it.
=> Add carousel collection

packages/ui/src/components/ListItem/ChannelListItem.tsx, packages/ui/src/components/ListItem/GroupListItem.tsx
=> desktop: fix issue with ListItem counts getting occluded by the overflow buttons

desk/app/channels-server.hoon
OTT, fixes TLON-3287
PR Checklist
=> hooks: only host can modify

packages/app/features/contacts/AddContactsScreen.tsx, packages/app/features/top/ContactsScreen.tsx, packages/app/navigation/RootStack.tsx, packages/app/navigation/desktop/ProfileScreenNavigator.tsx, packages/app/navigation/types.ts, packages/shared/src/api/contactsApi.ts, packages/shared/src/logic/utils.ts, packages/shared/src/store/contactActions.ts, packages/ui/src/components/AddContactsView.tsx, packages/ui/src/components/ContactBook.tsx, packages/ui/src/components/ContactRow.tsx, packages/ui/src/index.tsx, packages/ui/src/utils/user.ts
=> native: + button on contacts screen for quick/bulk adding

desk/app/channels-server.hoon
Fixes an issue reported by @patosullivan where his channels wouldn't process posts.
PR Checklist
=> hooks: allow no-op'ing if none

.github/workflows/deploy-canary.yml, .github/workflows/sync-dev.yml, .github/workflows/sync.yml
I think we were just missing a few places
PR Checklist
=> ops: use deploy keys in all the places

packages/ui/src/components/BareChatInput/index.tsx
=> web/chat input: reset chat input height on send

packages/ui/src/components/ActionSheet.tsx, packages/ui/src/components/InviteUsersSheet.tsx
Ensures that the modal fits within the height of the viewport, with some padding.
fixes TLON-3321
=> desktop: set a max height on the invite people modal

desk/desk.docket-0, packages/shared/src/store/sync.ts
=> ops: sync dev 12 6

packages/ui/src/components/ActionSheet.tsx
=> desktop: set 50% minWidth for modals

apps/tlon-web-new/package.json, packages/app/features/top/ChannelScreen.tsx, packages/app/features/top/PostScreen.tsx, packages/ui/src/components/Channel/index.tsx, packages/ui/src/components/FileDrop.native.tsx, packages/ui/src/components/FileDrop.tsx, packages/ui/src/components/PostScreenView.tsx, pnpm-lock.yaml
=> implement drag to upload on desktop

packages/ui/package.json, packages/ui/src/components/PersonalInviteSheet.tsx, packages/ui/src/components/ProfileScreenView.tsx, pnpm-lock.yaml
Adds a simple QR code to the personal invite sheet.
=> PersonalInviteSheet: add QR code for DM-centric Lure

packages/shared/src/store/sync.ts
OTT should fix TLON-2954
PR Checklist
=> sync: make sure deleted posts get deleted

desk/app/groups.hoon
OTT, issue reported by Will and Gary from Red Horizon
PR Checklist
=> groups: ignore joins for groups that exist or are currently joining

packages/app/features/top/ChannelScreen.tsx, packages/shared/src/store/channelActions.ts, packages/shared/src/store/groupActions.ts, packages/ui/src/contexts/chatOptions.tsx
This pr improves channel load perf by eliminating a number of extraneous syncs. More to be done here, but this should help a fair amount.
Fixes TLON-3385
=> improve channel load perf

packages/shared/src/api/groupsApi.ts, packages/ui/src/contexts/chatOptions.tsx
OTT, found today in QA. Going from secret to public/private was not working, just had it in the wrong spot on the conditional. And then sheet wasn't closing when clicking privacy option in menu.
PR Checklist
=> privacy: make sure secret value is correct and make sure we close sheet

packages/ui/src/components/BareChatInput/index.tsx
=> chat input: fix issue with attachments not clearing and input not resetting immediately on send

packages/shared/src/logic/analytics.ts, packages/shared/src/store/sync.ts, packages/shared/src/store/useChannelPosts.ts
This PR adds duration tracking via PostHog for two events: initial sync and channel initial page load.
=> load perf analytics

packages/ui/src/components/BareChatInput/index.tsx
just ONE MORE tiny change to chat input bro just ONE MORE ok, I PROMISE ok bro it's the LAST ONE bro ok
=> chat input (again): clear attachments and reset input height before send

packages/shared/src/db/changeListener.ts, packages/shared/src/db/queries.ts, packages/shared/src/store/sync.ts
OTT, more explanation in comments.
=> perf: avoid some unnecessary query invalidations

desk/app/channels-server.hoon, desk/ted/hook/schedule.hoon
=> hooks: fix schedule thread and state saving

apps/tlon-mobile/index.js, apps/tlon-mobile/src/hooks/useNotificationListener.ts, apps/tlon-mobile/src/screens/Onboarding/WelcomeScreen.tsx, packages/app/features/settings/AppInfoScreen.tsx, packages/app/features/settings/FeatureFlagScreen.tsx, packages/app/features/top/ChatListScreen.tsx, packages/app/hooks/useHandleLogout.native.ts, packages/app/hooks/useHandleLogout.ts, packages/app/utils/posthog.ts, packages/shared/src/db/index.ts, packages/shared/src/db/keyValue.ts, packages/shared/src/db/storageItem.ts, packages/shared/src/store/activityActions.ts, packages/shared/src/store/dbHooks.ts, packages/shared/src/store/storage/storageActions.ts, packages/shared/src/store/sync.ts, packages/ui/src/components/Activity/ActivityScreenView.tsx
This PR converts the remaining `keyVal` items and hooks to use the new format. It doesn't change any stored keys, so shouldn't cause any changes to stored state.
Fixes TLON-3122
=> convert remaining keyval items to new format

packages/ui/src/components/ManageChannels/ManageChannelsScreenView.tsx
=> manage channels: fix issue w/updating local state after adding/deleting channels

.github/pull_request_template.md
OTT something @latter-bolden requested a while back
PR Checklist
=> ops: pr template unused so removing

packages/app/navigation/desktop/HomeNavigator.tsx
=> web-new: add borderRightColor to HomeNavigator

apps/tlon-mobile/src/components/OnboardingInputs.tsx, packages/ui/src/components/Form/inputs.tsx
=> fix onboarding OTP input

packages/ui/src/components/MessageInput/AttachmentButton.tsx, packages/ui/src/components/WelcomeSheet.tsx
This reverts commit b8f15dd7006e0e2471ad3e7985503259cbd54179, reversing changes made to ad3aa654c5c347b4d825ad378579ef0501ea9ca9.
=> Revert "Merge pull request #4337 from tloncorp/ja/welcome-modal"

packages/app/features/top/ChannelSearchScreen.tsx, packages/ui/src/components/SearchBar.tsx
fixes tlon-3331
https://github.com/user-attachments/assets/2d5b1eb5-00ea-4c2c-ae2a-de92a72ee258
=> Search: fix layout issues

packages/ui/src/components/ChatOptionsSheet.tsx
=> ChatOptions: allow non-admins to invite from channel options for public groups

packages/app/features/top/CreateChatSheet.tsx
=> group creation: fix issue with collapsed contact book

apps/tlon-mobile/ios/Podfile.lock, packages/app/features/top/ChatListScreen.tsx
=> mobile: hide keyboard when closing search on chat list

packages/ui/src/components/BareChatInput/index.tsx
=> desktop: enter should submit edit

packages/shared/src/db/queries.ts
=> batch post insertion

apps/tlon-mobile/ios/Podfile.lock, packages/shared/src/api/urbit.ts, packages/shared/src/debug.ts, packages/shared/src/domain/analytics.ts, packages/shared/src/store/sync.ts
=> detailed tracking for api calls + init steps

apps/tlon-mobile/ios/Podfile.lock, apps/tlon-mobile/package.json, pnpm-lock.yaml
Fell out of profiling work I'm doing. In my testing makes the network panel much more reliable (although still not 100%), and doesn't have other side effects. Would love to hear if it improves things for others.
=> update expo dev client

apps/tlon-web/src/groups/GroupAdmin/GroupInfoEditor.tsx, apps/tlon-web/src/groups/GroupAdmin/PrivacySelector.tsx, apps/tlon-web/src/groups/LureInviteBlock.tsx, apps/tlon-web/src/state/lure/lure.ts
=> old web: use new lure generation logic + prevent toggling on/off

packages/shared/src/api/urbit.ts
=> redact user, group, and channel ids in scry analytics events

packages/ui/src/components/Activity/ActivityScreenView.tsx
=> activity: make sure flagged post activity items route to the post when pressed

packages/app/features/groups/GroupRolesScreen.tsx
fixes tlon-3624 by using our default "fit" snapPointsMode and always dismissing the keyboard on blur of a form input.
=> roles: fix keyboard avoidance issues in add/edit role sheets

packages/app/features/groups/GroupMembersScreen.tsx, packages/shared/src/api/index.ts, packages/ui/src/components/GroupMembersScreenView.tsx, packages/ui/src/components/ProfileSheet.tsx
fixes tlon-3630
Was just a bad conditional. Whether the current user is the host is irrelevant, we just need to know if the user we're trying to operate on is the host.
=> roles: allow removal of admin role for non-host users

apps/tlon-mobile/src/screens/Onboarding/CheckOTPScreen.tsx, apps/tlon-mobile/src/screens/Onboarding/PasteInviteLinkScreen.tsx, apps/tlon-mobile/src/screens/Onboarding/WelcomeScreen.tsx, packages/app/utils/posthog.ts, packages/ui/src/components/PersonalInviteButton.tsx
OTT, just tacks on extra meta to the PostHog _Account Created_ event.
=> Signup: log invite metadata when account created

packages/shared/src/store/sync.ts
Fixes infinite spinner on new group join. Lots of logic that seems wack around here, let's discuss later.
Fixes TLON-3554
=> fix new group join

.github/workflows/mobile-testing.yml
=> ops: remove on PR trigger

.github/workflows/deploy.yml, apps/tlon-web-new/.env, apps/tlon-web-new/src/app.tsx, apps/tlon-web-new/src/env.d.ts, apps/tlon-web-new/src/logic/analytics.ts, apps/tlon-web-new/src/main.tsx, packages/app/constants.ts, packages/shared/src/store/lure.ts
Reverts the desktop env var changes. These are causing issues with eas builds, let's punt on sorting that out until after we have an RC.
=> Revert desktop env var merge

packages/shared/src/db/keyValue.ts, packages/shared/src/store/sync.ts, packages/shared/src/test/setup.ts
Specify last sync time when fetching latest posts so that we only get new items. 
Fixes TLON-3626
=> optimize latest posts fetch

packages/shared/src/db/keyValue.ts, packages/shared/src/store/sync.ts, packages/shared/src/test/setup.ts
We need to cut another build for the release and we don't want this going out yet. 
Seems like it also may be causing issues on web. @dnbrwstr can you take a look before we pull back into develop?
=> Revert "optimize latest posts fetch (#4404)"

packages/ui/src/components/ScreenHeader.tsx
OTT, this fixes the issue seen from merging first sidebar PR preventing login from advancing.
=> screen-header: revert change to wrap, just add pointer

.github/workflows/deploy-external.yml
fixes tlon-3709
it was already setup for binnec and marnec, this was the straggler.
I added the desk to doznec as well.
=> ops: add external/doznec deploy for tm-alpha

.github/workflows/mobile-testing.yml
OTT, making name clearer and allowing to run manually
=> ops: allow running test on branch

packages/app/navigation/desktop/SettingsNavigator.tsx, packages/ui/src/components/SettingsScreenView.tsx
=> desktop: show focused screen in settings sidebar

apps/tlon-mobile/ios/Podfile.lock, packages/app/package.json, pnpm-lock.yaml
fixes tlon-3712
We just needed to add `expo-blur` to the package.json for the `app` package.
=> fix issue with app crashing on long press of chat messages

packages/app/ui/components/ListItem/ChannelListItem.tsx, packages/app/ui/components/ListItem/GroupListItem.tsx
=> list-item: aligning options with actions at top of sidebar

apps/tlon-mobile/ios/Podfile.lock, packages/app/features/chat-list/ChatListTabs.tsx, packages/app/hooks/useFilteredChats.ts
Fixes TLON-3728. accidentally included sidebar width PR
=> chat-list: fix all tab mobile

packages/app/navigation/desktop/ActivityNavigator.tsx, packages/app/navigation/desktop/HomeNavigator.tsx, packages/app/navigation/desktop/MessagesNavigator.tsx, packages/app/navigation/desktop/ProfileNavigator.tsx, packages/app/navigation/desktop/SettingsNavigator.tsx
=> sidebar: consistent widths

apps/tlon-mobile/src/screens/Onboarding/SignupScreen.tsx
=> onboarding: don't allow keyboard enter key to submit when email is invalid

packages/app/ui/components/ListItem/ChannelListItem.tsx, packages/app/ui/components/ListItem/GroupListItem.tsx
=> chat-list-item: improving badge alignment/placing

packages/app/navigation/utils.ts
Fixes TLON-3734, we weren't correctly accounting for nested depths and we were checking with uppercase for some reason.
=> nav-utils: add logging and make getTab recursive

packages/app/ui/components/ListItem/ChannelListItem.tsx, packages/app/ui/components/ListItem/GroupListItem.tsx, packages/app/ui/components/ListItem/ListItem.tsx
=> list-item: allowing counts to show blue if notified

apps/tlon-web-new/src/app.tsx
=> desktop: remove redundant "Tlon" from document title

desk/app/chat.hoon
=> ops: staging to develop 2 27

desk/app/channels-server.hoon, desk/app/diary.hoon, desk/app/grouper.hoon, desk/app/groups.hoon, desk/app/heap.hoon
This PR adjusts the %groups scry types to correspond to the actual result.
=> Fix %groups scry mismatches 

packages/shared/src/db/queries.ts, packages/shared/src/db/schema.ts, packages/shared/src/store/channelActions.ts, packages/shared/src/store/dmActions.ts, packages/shared/src/store/sync.ts
=> sync: make sure we delete channels that aren't there anymore

packages/app/features/chat-list/ChatList.tsx
=> Chat list: Make Groups Swipeable Again

desk/mar/group/previews-1.hoon
OTT, found while testing some other things
=> groups: adding missing previews mark

packages/app/ui/components/GalleryPost/GalleryPost.tsx
fixes tlon-3793. missed a spot where we needed optional chaining.
=> gallery: fix crash on some previews

.github/workflows/electron-build.yml, apps/tlon-desktop/package.json, apps/tlon-desktop/resources/entitlements.mac.plist
and specify working directories
=> desktop: add apple signing, tweak gh action to only deploy with desktop tags

packages/shared/src/store/sync.ts
OTT, see comment in code. 
Fixes TLON-3807.
=> fix slow reconnect

apps/tlon-desktop/electron-store-wrapper.cjs, apps/tlon-desktop/src/main/index.ts, apps/tlon-desktop/src/main/sqlite-service.ts
- open external URLs in the user's default browser
- use separate dev and prod sqlite files and json files for store
- clean up store related code, add some debugging, fix issue with null cached ship url on app restart.
=> desktop: electron cleanup

apps/tlon-web-new/src/components/DesktopLoginScreen.tsx
=> desktop: allow desktop users to login via the self hosted login screen

apps/tlon-desktop/src/main/notification-service.ts
=> desktop: add dock notification badging

packages/app/ui/components/BareChatInput/index.tsx, packages/app/ui/components/BareChatInput/useMentions.tsx, packages/app/ui/components/ListItem/ContactListItem.tsx, packages/app/ui/components/MentionPopup.tsx, packages/app/ui/components/MessageInput/InputMentionPopup.tsx, packages/app/ui/components/MessageInput/MessageInputBase.tsx
Adds a selected mention index that can be controlled with arrow keys. Handles enter to select and escape to dismiss.
@jamesacklin flagging you for UX review.
Fixes TLON-3783
=> Web: Mention keyboard controls

README.md
The README is very old and hardly reflects the current state of things. In this commit, we plant the seed of a new README that describes the current architecture of TM and removes references to out-of-date or non-existent documentation.
=> README: let's start from scratch

packages/app/ui/components/AuthorRow.tsx
=> desktop: fix issue with edited badge squishing author row

packages/app/navigation/utils.ts
=> desktop: navigate back to chat from notebook/gallery post if linked from chat

packages/app/features/chat-list/ChatList.tsx, packages/app/ui/components/ListItem/ChannelListItem.tsx
the hover states match those in our contacts tab.
fixes tlon-3741
=> desktop: add hover states for desktop group/chat/channel list items

packages/app/navigation/desktop/HomeSidebar.tsx
=> desktop: better "empty" state

packages/app/features/top/ChannelScreen.tsx, packages/app/ui/components/PostScreenView.tsx, packages/shared/src/store/postActions.ts, packages/shared/src/store/useChannelPosts.ts, packages/shared/src/types/PostCollectionConfiguration.ts
=> remove deleted posts in galleries

.github/workflows/deploy-external.yml
OTT, not sure if this auto-formatting is kosher
=> ops: dont deploy kernel moon by default

packages/shared/src/db/migrations/0000_right_marauders.sql, packages/shared/src/db/migrations/meta/0000_snapshot.json, packages/shared/src/db/migrations/meta/_journal.json, packages/shared/src/db/migrations/migrations.js, packages/shared/src/db/queries.ts, packages/shared/src/db/schema.ts
=> db: remove unwanted constraints

desk/app/lanyard.hoon, desk/app/verifier.hoon, desk/sur/verifier.hoon
=> ops: promote 410 jael fix

packages/app/ui/components/AttachmentSheet.tsx
OTT, fixes tlon-3991
Browser doesn't like the fake image trick.
=> desktop: fix desktop image attachment regression

packages/app/ui/components/TwtitterAttestationPane.tsx
=> verifier: update twitter attest copy

packages/app/features/top/ChannelScreen.tsx
cc @arthyn 
This resolves it, but we should find a better fix if possible.
=> channels: fix unread scroller lock

packages/shared/src/db/queries.ts
=> queries: fix columns in deletechannels

package.json, patches/@10play__tentap-editor@0.5.21.patch, pnpm-lock.yaml
Fixes the breaking issue we were seeing in prod, caused by invalid imports in tentap on web. For now, just patched those imports out of the module.
=> Fix editor import error

packages/app/ui/components/MessageInput/InputToolbar.tsx, packages/app/ui/components/MessageInput/index.tsx, packages/app/ui/components/draftInputs/DraftInputConnectedBigInput.tsx
(hopefully) OTT for 
Fixes TLON-3934
Fixes TLON-3933
=> web: notebook bugs

packages/app/ui/components/ChatMessage/ChatMessageActions/Component.tsx
=> desktop: unhide emoji toolbar in message options for gallery and notebook posts

packages/app/features/chat-list/ChatList.tsx
Fixes TLON-3949, just something I noticed recently after changing type sizing.
=> chat-list: use proper sizing in diff contexts

packages/shared/src/api/chatApi.ts, packages/shared/src/api/postsApi.ts, packages/shared/src/store/postActions.ts
Fixes TLON-3961, we just forgot to conditionally check for channel type.
=> dms: fix delete

apps/tlon-mobile/ios/Podfile.lock, packages/app/ui/components/ChatMessage/ReactionsDisplay.tsx, packages/app/ui/components/GalleryPost/GalleryPost.tsx, packages/shared/src/logic/utils.ts, packages/shared/src/types/PostCollectionConfiguration.ts, packages/ui/src/assets/icons/React.svg, packages/ui/src/assets/icons/index.ts
fixes tlon-3865
Edit: now fixes tlon-3909 as well
=> gallery: add meta-row to detail view + new details in grid previews

packages/app/ui/components/BareChatInput/index.tsx, packages/app/ui/components/MessageInput/AttachmentPreviewList.tsx, packages/app/ui/components/MessageInput/MessageInputBase.tsx
fixes tlon-3981
looks like this:
https://github.com/user-attachments/assets/ee9b3827-443e-49ef-9b9d-6e2d392182f2
=> chat: show error state when s3 uploads fail

packages/app/features/chat-list/ChatList.tsx
Got the order wrong in this guy https://github.com/tloncorp/tlon-apps/pull/4635 switching them to be correct.
=> chat-list: swap item dimension values

packages/app/ui/components/InviteFriendsToTlonButton.tsx, packages/app/ui/components/PersonalInviteButton.tsx
=> invite buttons: use copy rather than share on web

packages/ui/src/index.ts
=> desktop: make the sidebar skinnier

packages/app/ui/components/BigInput.tsx
fixes tlon-3962
Allows users to posts refs in gallery text posts (also shows the inline preview for the ref in the big input). Doesn't allow posting refs in notebooks.
=> gallery: handle ref attachments

packages/app/ui/components/Onboarding/OnboardingBenefitsSheet.tsx
Adds a close button and cleans the copy up a bit.
=> OnboardingBenefitsSheet: close button, improved copy

packages/shared/src/store/bufferedSubscription.ts, packages/shared/src/store/sync.ts
This pr improves performance of chatlist + other screens by batching incoming subscription events, reducing the number of invalidations they produce. May fix TLON-4047, but needs testing.
=> batch subscription events

apps/tlon-mobile/src/screens/Onboarding/WelcomeScreen.tsx, packages/shared/src/api/systemContactsApi.native.ts
Remove welcome benefits sheet (Fixes TLON-4089)
No email only contacts (TLON-4060)
=> mobile: release fixes

packages/app/ui/components/PostContent/contentUtils.tsx
OTT, this is super random just something I noticed and was in the neighborhood
=> content: don't count spaces when looking for emoji

cosmos.imports.ts, packages/app/features/contacts/InviteSystemContactsScreen.tsx, packages/app/ui/components/Wayfinding/SplashSequence.tsx
Came up during the design review. Minimal changes.
=> SplashSequence, InviteSystemContactsScreen: button copy

packages/app/ui/components/BareChatInput/useMentions.tsx
Forgot to push this change in my last PR.
=> mentions: fix multiline mentions, show nickname if possible

packages/app/ui/components/Wayfinding/SplashSequence.tsx
More copy changes to the Welcome tour.
=> SplashSequence: new copy

packages/app/features/top/CreateChatSheet.tsx
Does what it says on the tin; changes the CreateChatSheet text items to be more grammatically consistent
=> CreateChatSheet: grammatical consistency

packages/app/ui/components/BareChatInput/useMentions.tsx
Forgot to add this to https://github.com/tloncorp/tlon-apps/pull/4730
=> mentions: restore nickname in input

packages/app/lib/nativeDb.ts
#4746 was reverted in https://github.com/tloncorp/tlon-apps/pull/4757 – 8677ada should fix the bug causing the revert (although as noted in #4746, still not clear on root cause)
Fix is resetting the flag we're using to skip migrations on `purgeDb`, since we're opening a new connection. (The bug was likely caused by the `__changelog_table` trigger setup sharing the same code path as migrations.)
=> android: navigate to notification subject on tap (redo)

apps/tlon-mobile/src/App.main.tsx, packages/app/lib/backgroundSync.ts, packages/app/lib/betterSqlite3Connection.ts, packages/app/lib/nativeDb.ts, packages/app/lib/opsqliteConnection.ts, packages/app/lib/sqliteConnection.ts
OTT
Let's see if this stabilizes things.
=> mobile: revert DB changes & disable background sync

packages/app/ui/components/SystemNotices.tsx, packages/app/ui/components/Wayfinding/SplashSequence.tsx, packages/shared/src/store/sync.ts
=> mobile: show confirmation alert when contact book import is successful

packages/app/ui/components/GalleryPost/GalleryPost.tsx
Root cause here was bad parens in the conditional logic.
=> fix gallery crash

desk/app/metagrab.hoon
No reason to be more lenient than this, right?
=> metagrab: authenticated requests only

.github/workflows/build-and-glob.yml
OTT, doing this manually was more headache than just adding this
=> ops: add build/glob only action for release branches

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Adds a pull request template for new PRs.
=> ops: pull request template

packages/app/ui/components/draftInputs/LinkInput.tsx
=> link-input: allow links with no preview

packages/app/provider/BaseProviderStack.tsx
Separates provider layers to clarify where in the stack providers go + hopefully avoid future Android/portal bugs.
Tested basic functionality in builds for web, iOS, and Android
=> separate provider layers

packages/app/ui/components/ContactName.tsx
Fixes TLON-4439
- escaped matched text regex construction to prevent things like "mismatching groups" etc.
Manually running pnpm dev
n/a
n/a
=> mentions: fix regex crashes

.github/helpers/deploy.sh
=> ops: fix source order in deploy script

apps/tlon-mobile/android/app/build.gradle, apps/tlon-mobile/ios/Landscape.xcodeproj/project.pbxproj
=> ops: bump mobile versions

desk/app/channels-server.hoon, desk/app/groups.hoon
This PR adds some changes necessary to make group subscription restart work correctly. 
In particular, we account for the fact that channel permissions are stored in two separate places: read permissions in the groups agent, while write permissions are stored in the channels-server.
As such, when a group subscription is re-established, we need to make sure that the local channels-server of each group member does a deep permission recheck to account for changes in read permissions (should we kick subscribers from the channel?) and write permissions (should we remove roles no longer present in the group?)
1. Added two more cases in which we restart the subscription.
3. Modified channels-server to do a full permissions recheck when a group create event is received. That this is going to be …
=> groups: properly handle group resubscription

desk/desk.docket-0
=> ops: bump %groups to v8.1.0

packages/shared/src/api/urbit.ts, packages/shared/src/http-api/Urbit.ts
OTT, adds telemetry for response status code and content length for JSON and noun scries.
=> http-api: log scry status and size

desk/lib/negotiate.hoon
=> negotiate: use proper wires and handle them

packages/app/features/top/ChannelScreen.tsx, packages/app/hooks/useGroupNavigation.ts, packages/app/navigation/utils.ts, packages/app/ui/components/Channel/PostList/PostListFlatList.tsx, packages/app/ui/components/Channel/Scroller.tsx, packages/app/ui/components/Channel/index.tsx, packages/app/ui/components/Channel/useAnchorScrollLock.ts, packages/app/ui/components/ChatMessage/ChatMessage.tsx, packages/app/ui/components/GalleryPost/GalleryPost.tsx, packages/app/ui/components/NotebookPost/NotebookPost.tsx, packages/app/ui/contexts/componentsKits.tsx, packages/app/ui/contexts/scroll.tsx
Assorted performance optimizations aimed at improving scroller performance. Still more that could be improved here.
- Memoize assorted inline props
- Convert callbacks that depend on navigation (the identity of which can frequently change) to instead depend on a mutable navigation ref.
- Try tweaking FlatList config to render slightly less offscreen content at a slightly larger batch size
Tested on web + sim
=> scroller performance optimization

apps/tlon-mobile/android/app/build.gradle, apps/tlon-mobile/ios/Landscape.xcodeproj/project.pbxproj, desk/desk.docket-0
%groups v9.0.1, native apps v7.0.1
=> ops: bump desk and app versions

desk/app/notify.hoon
Notify agent had not yet been instrumented with any logging. Here, we add logging to every codepath where we already +slog. We also add info logs for kicks, which will let us get a read on subscription (in)stability if that's ever relevant.
It compiles, it runs. Behavior wasn't otherwise changed.
Simply revert.
=> notify: minimal error case logging
