ui/src/heap/HeapChannel.tsx
fixes #919.
this may be a bit rough as we're using the first content element to sort if an "official" title is unavailable (so many links will start with h as in https) but it does work.
=> galleries: added option to sort by alphabet

ui/src/components/ShipSelector.tsx, ui/src/pages/NewDm.tsx
this one's about #785, it just needed a little bump in padding value to keep it from "filling up", and a corresponding mod to the button.
@urcades this is the simplest fix but it does make the input a tiny bit taller (as tall as it was after it "jumps" in the current version)
=> talk: set ShipSelector padding to avoid size jumping

.gitignore, bin/bounce, bin/start, bin/sync, ops/README.md, ops/bounce.yml, ops/sync.sh, ops/sync.yml
These are optional config files for use with [bouncer](https://github.com/tloncorp/bouncer).
Note that the paths in the yml files and bin scripts will need to be updated for your system.
The change includes an update to the gitignore for these directories. This way, others can tweak the bouncer config without introducing a git diff in their local repo. Eventually we can use ENV vars or similar to customize config for each individual system
=> devex: add scripts and config for use with bouncer

ui/src/chat/ChatContent/ChatContentImage.tsx, ui/src/chat/ChatInput/__snapshots__/ChatInput.test.tsx.snap, ui/src/components/Avatar.tsx, ui/src/components/ButterBar.tsx, ui/src/components/CoverImageInput.tsx, ui/src/components/MessageEditor.tsx, ui/src/components/ShipName.tsx, ui/src/constants.ts, ui/src/diary/DiaryContent/DiaryContentImage.tsx, ui/src/diary/DiaryImageNode.tsx, ui/src/diary/DiaryInlineEditor.tsx, ui/src/diary/DiaryList/DiaryGridItem.tsx, ui/src/diary/DiaryNoteHeadline.tsx, ui/src/groups/GroupAvatar.tsx, ui/src/groups/GroupInfoFields.tsx, ui/src/groups/GroupSidebar/GroupSidebar.tsx, ui/src/heap/HeapBlock.tsx, ui/src/heap/HeapRow.tsx, ui/src/profiles/EditProfile/ProfileFields.tsx, ui/src/profiles/ProfileCoverImage.tsx, ui/src/state/settings.ts
Dependent on urbit/garden#10.
Implements controls from Landscape to disable:
- avatars
- nicknames
- remote image fetching
- spellcheck
Manifests in the following product locations:
- Chat images
- Ship avatars
- Ship names
- Profile headers
- Notebook headers
- Notebook images
- Gallery items
- Notebook, gallery, profile bio, and chat text inputs
- Group icons
- Group headers
Also introduces a constant for the Landscape desk, since we're using `%garden` now and will eventually use `%landscape`.
fixes tloncorp/landscape-apps#936
=> groups: use landscape settings

ui/src/groups/GroupAdmin/GroupMemberManager.tsx, ui/src/groups/GroupAdmin/GroupPendingManager.tsx
ref: #974 
the "concat" logic was off in the pending list leading to the list getting duplicated, and the members list needed a filter added to it, plus some restructuring so typescript wouldn't go off about the `Cordon` type.
=> groups: pending members show up where they should

desk/app/chat.hoon, desk/app/diary.hoon, desk/app/groups.hoon, desk/app/heap.hoon, desk/mar/chat/action.hoon, desk/mar/chat/logs.hoon, desk/mar/chat/update.hoon, desk/mar/diary/action.hoon, desk/mar/diary/logs.hoon, desk/mar/diary/update.hoon, desk/mar/group/action.hoon, desk/mar/group/init.hoon, desk/mar/group/log.hoon, desk/mar/group/update.hoon, desk/mar/heap/action.hoon, desk/mar/heap/logs.hoon, desk/mar/heap/update.hoon
The internal rolling release build is using numbered marks, whilst the public alpha is using unnumbered marks. As the public alpha lacks the mark files for the numbered marks and the rolling release lacks mark files for the unnumbered marks, this causes a kick-resubscribe loop whenever two ships on different builds attempt to communicate over a subscription. Rectifies this issue by returning to sending unnumbered marks over a subscription and adding the ability to receive numbered or unnumbered marks as pokes and %facts. Once this commit has been deployed to public alpha, we can return to giving numbered marks over subscriptions.
=> desk: fix kick resubscribe loop due to public/rolling mismatch

ui/src/chat/ChatMessage/ChatMessage.tsx, ui/src/chat/ChatMessage/__snapshots__/ChatMessage.test.tsx.snap, ui/src/state/base.ts, ui/src/state/chat/chat.ts, ui/src/state/chat/type.ts, ui/src/state/chat/writs.ts
partially covers #711 
**Functionality that is covered:**
- Optimistic posting of sent messages from input field to ChatScroller
- "Sent from Browser, not delivered to host ship" and "Delivered to host shop" now have distinct visual states.
The effect on UX is that messages now feel like they post instantly now instead of having a percieved lag as the message makes its roundtrip from the host ship back to your urbit. (this is still so much faster than g1, it sometimes feels instant! but often it still doesn't!)
**Functionality that needs to be covered:**
- The distinct intermediary state of "sent from browser to user's ship, not yet reached host ship" detailed in issue #711
- design: https://www.figma.com/file/sCFYLlAGjehlYXUkT2rarg/Product-Handoffs-(Locked)?node-id=1292%3A69107
@arthyn …
=> chat: sent/delivered status for messages

ui/src/dms/MessagesList.tsx
see: 988
apparently the "RECENT" flag in sortOptions was changed to sort by date, but in the wrong direction at some point. I'm reversing the sorted array, which is brute-forcey but works great.
=> sort DMs by most recent

desk/app/diary.hoon, desk/lib/diary-json.hoon, desk/lib/notes.hoon, desk/lib/quips.hoon, desk/mar/diary/note.hoon, desk/mar/diary/outline.hoon, desk/mar/diary/outlines.hoon, desk/sur/diary-0.hoon, desk/sur/diary.hoon, ui/src/components/References/NoteReference.tsx, ui/src/diary/DiaryChannel.tsx, ui/src/diary/DiaryComment.tsx, ui/src/diary/DiaryList/DiaryGridItem.tsx, ui/src/diary/DiaryList/DiaryGridView.tsx, ui/src/diary/DiaryList/DiaryListItem.tsx, ui/src/diary/DiaryNote.tsx, ui/src/diary/DiaryNoteHeadline.tsx, ui/src/logic/utils.ts, ui/src/state/diary/diary.ts, ui/src/state/diary/notes.ts, ui/src/state/diary/type.ts, ui/src/types/diary.ts
- Moves quips inside the $seal data structure of a note, instead of existing separately to the noteId -> note mapping
- Changes the datatype of publish quips to be at parity with chat messages
- Reworks the fetching of notes so that we don't have to front load so much data
=> quips: refactor

ui/src/components/Sidebar/Sidebar.tsx, ui/src/components/Sidebar/__snapshots__/Sidebar.test.tsx.snap, ui/src/logic/tiptap.test.ts, ui/src/logic/tiptap.ts
see: #987 
the tests weren't catching this because our previous test for a "styled paragraph" consisted of a single word that was styled, in which case inserting the single linebreak after the word perfectly aligned with expected behavior.
=> chat: stop inserting linebreaks before/after styled text

ui/src/components/Sidebar/GroupList.tsx, ui/src/components/Sidebar/__snapshots__/Sidebar.test.tsx.snap
see: #782.
group joins that have an "error" state (due to nonexistent target group etc) were still appearing, this PR prevents them from appearing. tradeoff: the errored joins still technically persist in the backend, and could potentially build up and affect performance after long periods of use
the ideal fix for this requires backend changes (a separate "possible error/nonexistent group" visual state/tooltip text arrangement, with a cancel button).
unfortunately the only function to cancel a group join currently doesn't seem to work if the join process itself has errored – if we desire this functionality soon, we should create a separate issue for it.
=> groups: hide group joins with "error" states

ui/package-lock.json, ui/package.json, ui/src/components/FileUpload.tsx, ui/src/state/storage/index.tsx, ui/src/state/storage/reducer.ts, ui/src/state/storage/storage.tsx, ui/src/state/storage/upload.tsx, ui/src/types/storage.ts
Adds S3 upload, cribbing a lot of work from https://github.com/arthyn/silo.
Introduces an otherwise unremarkable HTML file input component which accepts a forwarded ref. The thinking here is that we could use this elsewhere in the interface as a hidden element, pass the input an event the ref, and use the provided FileStore however we see fit.
=> s3: generic upload component

ui/src/heap/HeapChannel.tsx, ui/src/heap/NewCurioForm.tsx, ui/src/state/heap/heap.ts, ui/src/state/settings.ts, ui/src/types/heap.ts
Fixes #926 
We should allow the user to set which mode they'd prefer to view a gallery with on a per-user basis. Previously it was set on a per-gallery basis.
=> groups: set heap display mode in settings store

ui/src/chat/ChatInput/ChatInput.tsx, ui/src/logic/tiptap.test.ts, ui/src/logic/tiptap.ts
Fixes the following issues with drafts:
- Adding a new line when returning to a draft (fixes #978)
- Not showing most recent draft if more than one draft has been created
- Unnecessarily updating drafts (when new draft is the same as the old draft)
There may be an issue with the backend code causing these empty paragraphs/breaks to get added to messages. If that's the case, it'll obviate most of the code here.
=> chat: fix several issues with drafts

desk/app/groups.hoon, ui/src/app.tsx, ui/src/components/Sidebar/Sidebar.tsx, ui/src/components/Sidebar/__snapshots__/Sidebar.test.tsx.snap, ui/src/groups/FindGroups.tsx, ui/src/notifications/Notification.tsx, ui/src/notifications/Notifications.tsx
This fixes an issue where doing a search in find groups triggers the wrong nav. Also changes notifications so that the scrollbar doesn't jump when opening the dropdown menu.
=> nav: find groups triggers wrong nav

ui/package-lock.json, ui/package.json, ui/src/components/FileUpload.tsx, ui/src/components/_ExampleFileUpload.tsx, ui/src/state/settings.ts, ui/src/state/storage/upload.tsx, ui/src/types/storage.ts
Embellishes the FileStore a bit by:
- Adding a pre-signed URL for all uploads
- Keying the FileStore, rather than referring to uploads by index
- Adds a 'for' field and a required ID on all image inputs
- Adds an example implementation to show how to produce a (or a list of) URL(s) from a file input
As a result, the component supports multiple inputs on the same page.
=> s3: key FileStore on input ID

.github/actions/deploy/entrypoint.sh
The bash output needed the space in between to work
=> ops: fix ref deploys

talk/desk.docket-0, ui/src/chat/ChatInput/ChatInput.tsx, ui/src/logic/useFileUpload.ts, ui/src/logic/utils.ts, ui/src/state/storage/upload.tsx, ui/src/types/storage.ts
[mostly] closes #160 
Added a new hook called useFileUpload that can be used anywhere we want to dynamically insert a hidden upload input.
Added the ability to upload images to chat.
Added the ability to paste an image URL into the chat input and have it get sent as an Image block type.
Added some loading/error states around chat input.
Note:
Does not include pasting of images directly into chat from the clipboard.
Does not show the image as a preview, just adds the image URL to the chat input.
https://user-images.githubusercontent.com/1221094/198136649-fba0f2f4-4878-461b-a71e-50c1cb008ed5.mov
https://user-images.githubusercontent.com/1221094/198136787-29971834-778b-420e-b35e-284d8949f8cb.mov
=> chat: add image upload (and pasting of image URLs) to chat input

ui/src/app.tsx, ui/src/chat/ChatMessage/ChatMessage.tsx, ui/src/chat/ChatScroller/ChatScroller.tsx, ui/src/chat/ChatWindow.tsx, ui/src/components/Sidebar/MobileSidebar.tsx, ui/src/components/Sidebar/SidebarSorter.tsx, ui/src/components/icons/CaretRight16Icon.tsx, ui/src/groups/ChannelIndex/ChannelIndex.tsx, ui/src/groups/ChannelIndex/__snapshots__/ChannelIndex.test.tsx.snap, ui/src/groups/FindGroups.tsx, ui/src/groups/GroupAdmin/GroupAdmin.tsx, ui/src/groups/GroupSidebar/MobileGroupSidebar.tsx, ui/src/groups/MobileGroupActions.tsx, ui/src/nav/MobileGroupRoot.tsx, ui/src/notifications/Notifications.tsx, ui/src/state/chat/chat.ts, ui/src/state/chat/type.ts, ui/src/state/chat/writs.ts, ui/src/styles/components.css
This addresses #1005 by adding more routes to the bottom nav. I decided it would be difficult to represent the difference between all channels and joined channels so I added that one to the top right header only on the channels page.
This also throws in some mobile styling tweaks to headers that @urcades was working on, and some improvements to how the virtual scroller manages keys/data and loading.
=> nav: improving mobile

DEVELOPMENT.md, bin/bounce, bin/sync, desk/app/groups.hoon
This closes #754 by filtering certain notifications to only be sent to Admin users.
Suppress the following notifications for non-Admin users (ie, those not in the bloc):
- joined channel
- requested to join
- left channel
- member role change (user is now an ...)
*On Admin ship*
*On Member ship*
=> groups: suppress superfluous notifications

ui/src/channels/NewChannel/NewChannelForm.tsx
see: #1034 
had to add in a call to set the channel as default as apparently "CreateChannel" doesn't take a "join" argument
=> groups: set channel as default upon creation

ui/src/logic/utils.ts
Handles the same file extensions in the `IMAGE_URL_REGEX` function as in the `IMAGE_REGEX` function.
Practically speaking, handles jpegs from iOS in the S3 file uploader in chat.
=> groups: update image regex

desk/ted/raze.hoon
`-groups!raze %groups` nukes all agents in the specified desk.
`-groups!raze %groups ~[%hark %heap]` nukes only the specified agents.
=> ops: raze all agents

ui/src/chat/ChatMessage/Author.tsx, ui/src/chat/ChatMessage/__snapshots__/ChatMessage.test.tsx.snap
see: #1037.
There's an `Author` component that consists of an avatar and a shipname that we're using in contexts where authorship is connoted that I'm pretty sure covers all cases where a ShipName is used and there isn't additional interactivity, let me know if i'm missing any instances with this.
=> groups: click to copy ID

desk/app/heap.hoon
Some leftovers from the timestamp pairing, previously this used the whole curio diff but now we only need the delta. 
plz compile before committing uwu
=> heap: use the correct type for reduce

ui/tailwind.config.js
see #1076.
simple as.
tradeoff: some tooltips may no longer be visible on mobile without long-pressing. the only one I can think of that isn't purely instructional is the emoji react hover action that shows who reacted – we likely want to implement an alternative method to see this anyway (to account for cases where more than 5 or so people have reacted to a message with the same emoji, which happens pretty often in group-based chat apps like this)
=> everywhere: disabled CSS hover on touchscreens

desk/app/groups.hoon, desk/mar/group/cancel.hoon, ui/src/components/Sidebar/GroupList.tsx, ui/src/state/groups/groups.ts, ui/src/state/groups/type.ts
This addresses the immediate issues with #1067 by adding an ability remove "errored" joins and also lets new invites show up even if a join was errored. Also adds a new cancel flow for "errored" joins so they can be removed from the sidebar.
This also removes the "Cancel Join" button from the join in progress popover because it's currently not possible to remove a join in progress (only maybe hide it and it would still have the potential to go through). We may be able to come up with something later that gives us the ability to completely cancel, but we need quite a bit to do it.
=> groups: adding better handling for errored group joins

ui/src/channels/NewChannel/__snapshots__/NewChannel.test.tsx.snap, ui/src/components/Dialog.tsx, ui/src/groups/GroupInfoFields.tsx, ui/src/groups/NewGroup/NewGroup.tsx, ui/src/styles/components.css
This resolves #1112 by tweaking some of the mobile-specific styling for the Create Group dialog. With this change, the color inputs do not overflow, and the preview image is now centered in the dialog.
=> ui: mobile styling for New Groups modal

ui/src/groups/GroupSidebar/GroupSidebar.tsx
Brings consistency with group items in the All Groups view; indicates that the group name is navigable.
=> groups: adds ellipsis to name-hover in group sidebar

ui/src/api.ts, ui/src/groups/NewGroup/NewGroup.tsx, ui/src/groups/NewGroup/NewGroupInvite.tsx, ui/src/logic/status.ts, ui/src/state/groups/groups.ts, ui/src/state/subscription.ts
This adds a pathway for tracking poke responses that come down subscriptions so that we can start culling the missing loading states in #566 (and not just track the poke's request itself which is only half of the loading). 
This adds a loading state to group creation as an example. Essentially, when doing a poke that will eventually produce a fact down a subscription, you call and await `useSubscriptionState.getState.track(...)`. The function you pass must be able to read the facts on a subscription and determine the correct fact has come down. When this promise is finished you can assume that the function you passed returned true and it's safe to show success/proceed.
=> groups: adding new harness for tracking poke results

ui/src/app.tsx, ui/src/channels/ChannelHeader.tsx, ui/src/channels/NewChannel/NewChannelForm.tsx, ui/src/components/ShipSelector.tsx, ui/src/components/Sidebar/MobileSidebar.tsx, ui/src/components/Sidebar/SidebarSorter.tsx, ui/src/components/icons/BellIcon.tsx, ui/src/groups/ChannelIndex/ChannelIndex.tsx, ui/src/groups/ChannelIndex/__snapshots__/ChannelIndex.test.tsx.snap, ui/src/groups/FindGroups.tsx, ui/src/groups/GroupAdmin/GroupAdmin.tsx, ui/src/groups/GroupJoinList.tsx, ui/src/groups/GroupSidebar/ChannelList.tsx, ui/src/groups/GroupSidebar/MobileGroupSidebar.tsx, ui/src/groups/MobileGroupActions.tsx, ui/src/groups/MobileGroupsActions.tsx, ui/src/nav/MobileGroupRoot.tsx, ui/src/nav/MobileRoot.tsx, ui/src/notifications/Notifications.tsx, ui/src/profiles/EditProfile/EditProfile.tsx, ui/src/profiles/ProfileModal.tsx
A wholesale redesign of the mobile navigation. Unless otherwise noted, these changes only affect the mobile view and should have no effect on the desktop view.
**Groups app home**
- Add labels to all icons
- Replaces Groups icon
- Switches notification counter to activity bell
- Places Find Groups in the nav
- Adds grayscale/opacity effects to the ship avatar in the inactive Profile tab
- Adds an overflow menu containing the Submit Feedback link
- Adds a Add Group button in the header of the screen
- Relocates the group sorting control to the header
**Find Groups, Notifications**
- Unifies page headers with Groups app home
- Removes gray background and card section treatments
**Group home**
- Adds labels to all icons
- Relocates the Group Info item
- Adds grayscale/opacity effects to the …
=> groups: mobile nav redesign

ui/src/state/groups/groups.ts, ui/src/state/groups/type.ts
Fixes #1035 by reloading group state (await useGroupState.getState().start()) when moving a channel. Incorrect list will flash briefly (a few milliseconds) before correct one is shown.
=> groups: fix for jumping/mis-ordered admin channel list

ui/src/chat/ChatMessage/ChatMessage.tsx, ui/src/chat/ChatMessage/__snapshots__/ChatMessage.test.tsx.snap, ui/src/chat/ChatScroller/ChatScroller.tsx
Fixes #1096 and #1102 
Note that this doesn't account for scrolling directly to a message, as it appears that for now we don't actually use the `scrollTo` prop. Should it?
=> Always open chat at bottom

ui/src/chat/ChatChannel.tsx, ui/src/components/Sidebar/Sidebar.test.tsx, ui/src/groups/GroupSidebar/ChannelList.tsx, ui/src/lib.ts, ui/src/logic/useChannelSort.ts, ui/src/logic/usePrefetchGroupMessages.ts, ui/src/state/chat/chat.ts, ui/src/state/chat/writs.ts
This resolves #1073 by refactoring the channel list sort behavior and adding an effect hook to prefetch messages. When selecting a group, the messages for each channel will be fetched, then the last message timestamp will be compared to determine the sort order.
For now this is done somewhat ineffciently. In discussion with @arthyn, we came up with a more scalable approach that can be implemented after the initial release. In short, implement a new backend endpoint that publishes the latest message for each channel.
https://user-images.githubusercontent.com/16504501/201065746-db26cb48-d881-495b-9d9e-e955f96bc767.mp4
=> channels: fix recent sort in sidebar

ui/src/chat/ChatScroller/ChatScroller.tsx, ui/src/chat/ChatThread/ChatThread.tsx
Fixes #1105 
We can now scroll to a message using the URL param `msg` (such as when clicking a chat reference).
Also, when closing a thread we'll return to the message attached to that thread in the scroller (important for mobile).
=> chat: use scrollTo to scroll to messages, fix thread exits

ui/src/components/Sidebar/Sidebar.test.tsx, ui/src/groups/GroupSidebar/ChannelList.tsx, ui/src/logic/useChannelSort.ts, ui/src/logic/usePrefetchChannels.ts, ui/src/state/chat/chat.ts, ui/src/state/diary/diary.ts, ui/src/state/heap/heap.ts
The previous PR (#1114) only supported chat channels; this adds support diary and heap channels too.
https://user-images.githubusercontent.com/16504501/201310743-70d962c5-6be4-4727-abdf-218f25d55a35.mp4
=> channels: recent sort applies to all channel types

ui/src/channels/ChannelHeader.tsx
Adds admin-specific actions to the context menu in the channel header. You may now edit and remove channels from within the channel itself.
Administrator (channel host) view:
https://user-images.githubusercontent.com/748181/201430842-fe9d70ce-0046-4532-a675-4a9a42f38ca3.mov
Administrator (non-host) view:
Member (non-host) view:
https://user-images.githubusercontent.com/748181/201430870-c5b5804e-a31e-4fc6-933a-d4a0e6102a4a.mov
Fixes #1127
=> groups: add admin channel actions to channel header

ui/src/chat/ChatContent/ChatContent.tsx, ui/src/chat/ChatInput/ChatInput.tsx, ui/src/chat/ChatInput/__snapshots__/ChatInput.test.tsx.snap, ui/src/chat/ChatScroller/ChatScroller.tsx
This fixes #1143 and throws in some extra word breaking for inline code and chat input.
Side note, we don't handle block code right now. We should add handling for that with the potential for overflow scrolling.
Btw when doing this I couldn't find our old message row/type spec in figma @urcades so that I could match what inline code was supposed to be.
=> chat: fix backscroll loading

ui/src/components/Avatar.tsx
Accounts for non-square source images.
Before: 
After:
=> groups: prevent avatar squishing

ui/src/components/icons/LockOpen16Icon.tsx, ui/src/groups/GroupSummary.tsx
turns out, we weren't even using the right icon
https://www.figma.com/file/sCFYLlAGjehlYXUkT2rarg/Product-Handoffs-(Locked)?node-id=1593%3A70558&t=Et5CNuy7uGmrCNXY-0
=> groups/search: replaced globe icon with open lock icon

ui/src/api.ts, ui/src/app.tsx, ui/src/components/DisconnectNotice.tsx, ui/src/state/local.ts
Closes #1086 
It seems we were already showing the disconnect bar on ship shutdown, but we weren't catching errors with subscriptions themselves. This *should* solve that.
=> Catch disconnects caused by subscription errors, use errorCount

ui/src/app.tsx, ui/src/groups/GroupAvatar.tsx, ui/src/groups/GroupSidebar/GroupSidebar.tsx, ui/src/logic/useMedia.ts
This showed up as an issue because I noticed our media query not picking up theme changes. Essentially on first render before the setQuery call can update the initialized flag, each invocation was creating a query listener. I moved the tracking outside of react state so that it's updated immediately.
=> app: fix media query deduplication

desk/app/chat.hoon, desk/app/diary.hoon, desk/app/heap.hoon, ui/src/chat/ChatUnreadAlerts.tsx, ui/src/groups/GroupSidebar/ChannelList.tsx, ui/src/groups/GroupSidebar/__snapshots__/ChannelList.test.tsx.snap, ui/src/logic/useChannelSort.ts, ui/src/logic/useGroupSort.ts, ui/src/logic/useSidebarSort.ts, ui/src/state/settings.ts
Unfortunately I think I sent @tomholford down the wrong path for #1114 my apologies! The `brief.last` is the correct thing to use for the last message we just had a few issues. We weren't using nests, looking at all channel types, updating briefs for posts in all channel types, and our chat brief was going off out of order so it was always one behind. This corrects all of that and also changes the default sort for channels to arranged and default heap view to grid.
This does rip out the channel prefetching which I think we need to revisit after launch. The prefetching was incurring too many requests + subscriptions holding up loading anything else for like 10s+ which I think is not a decent enough trade off yet. Also we don't really want to be subscribed to all channel updates because …
=> sidebar: recent sorting

ui/src/channels/ChannelHeader.tsx, ui/src/styles/components.css
see: #1181.
This did actually require some structural changes – there was a needlessly complicated hack laid on top of radix's `Popover` element to simulate the functionality of its `Dropdown` element that led to it behaving jankily – some components have been replaced with a CSS class (dropdown-item-icon)
I've gone through groups and talk and the dropdowns i've come across (there are many) seem to be up to spec now, but there may be some other non-standard ones with icon hacks i've missed.
=> groups: dropdown audit

ui/src/components/References/WritReference.tsx
For #1169 
We can just use useWritByFlagAndId for all writ references, no need for a separate component for unsubbed/subbed writ references, and fixes the issue described.
=> chat: fix for unloaded writ refs

ui/src/dms/MessagesList.tsx, ui/src/state/settings.ts
With recent change to `useAllBriefs` using nests, message sort need to be adjusted as well. Also threw in persisted talk filter because it's really annoying to watch it change lol.
=> talk: fix sort and persist filter

ui/src/chat/ChatMessage/__snapshots__/ChatMessage.test.tsx.snap, ui/src/chat/ChatReactions/ChatReaction.tsx, ui/src/components/EmojiPicker.tsx, ui/src/styles/components.css
see: #1154. also includes a blue background on emoji reacts you've selected
the latest version of emoji-mart seems notoriously difficult to self-style for width https://github.com/missive/emoji-mart/issues/634 so i'm using a hack with "show per line" to make it somewhat responsive. Also bumping up the font size on mobile to prevent mobile browsers from auto-zooming on the search input field.
=> chat: emoji react selector mobile fixes

ui/src/components/Sidebar/GroupList.tsx
We had another z-index issue with the "You are currently joining this group" popover.
=> groups: Add zindex to 'joining group' popover

ui/src/chat/ChatScroller/ChatScroller.tsx, ui/src/chat/ChatScroller/IChatScroller.ts, ui/src/chat/ChatThread/ChatThread.tsx, ui/src/chat/ChatUnreadAlerts.tsx, ui/src/chat/ChatWindow.tsx
This refactors the scroller to use a provided ref, which subsequently allows other components (such as the Unread banner) to control the scroll index. This is then used to scrollback the index to the first unread message when clicking on the banner. Further, a useEffect hook is no longer used; instead, virtuoso's `initialTopMostIndex` is used on load if there is a `msg` param in the URL.
This resolves #1200
=> scroller: refactor scrollTo behavior

ui/src/groups/NewGroup/NewGroup.tsx
by setting a definite width on the dialog.
Fixes #1236
=> groups: Fix overflow issue in New Group modal in safari 

ui/src/dms/DMOptions.tsx, ui/src/groups/GroupSidebar/ChannelList.tsx, ui/src/logic/useDismissChannelNotifications.ts, ui/src/logic/useIsChannelUnread.ts
OTT, basically each time dismiss channel marked read it updated the brief, which updated the deps in its useEffect which in turn did it again.
=> channel: prevent brief marking from triggering infinite loop

desk/app/diary.hoon, desk/app/heap.hoon
Similar to fix for chat, always use the last post's time + 1. Fixes #1042
=> heap, diary: use correct time for marking read

ui/src/chat/ChatMessage/ChatMessageOptions.tsx, ui/src/chat/ChatMessage/__snapshots__/ChatMessage.test.tsx.snap
Fixes #1259 
Users should not be able to copy chat refs from DMs, this is not intended functionality. We happen to be using chat refs for "replies" in groups right now, so I can see why Zach attempted to use it in DMs, but refs were never intended to be used in DMs.
We *will* have replies in DMs, but that will come when we add proper replies for both groups and talk.
=> chat: prevent users from copying refs in dm

desk/app/chat.hoon, desk/app/diary.hoon, desk/app/heap.hoon
Adds versions to marks, so that updates to permissions are handled correctly, instead of being dropped on the floor.
Fixes #1245
=> various: add version to %group-action mark

ui/src/groups/ChannelIndex/ChannelIndex.test.tsx, ui/src/groups/ChannelIndex/ChannelIndex.tsx, ui/src/groups/ChannelIndex/__snapshots__/ChannelIndex.test.tsx.snap, ui/src/groups/GroupSidebar/ChannelList.tsx, ui/src/groups/GroupSidebar/__snapshots__/ChannelList.test.tsx.snap, ui/src/logic/useFilteredSections.ts
This also updates channelIndex to hide sections full of admin-only channels from users, and handles the "section full of unjoined channels" issue
=> groups: hide empty sections from sidebar

ui/src/components/EmojiPicker.tsx
see: #1253.
I had a lot of trouble recreating this locally, though I could get it to show up sometimes after checking out a pre-version bump commit – I think the version bump may have solved it?
=> changed emoji picker popover to come out of left side of trigger

ui/src/heap/HeapBlock.tsx, ui/src/heap/HeapDetail/HeapDetailBody.tsx, ui/src/heap/NewCurioForm.tsx
For #1182 
Also, rather than returning `undefined` for titles we should just show the URL.
=> heap: store links as link content type

ui/src/chat/ChatContent/ChatContent.tsx, ui/src/chat/ChatMessage/ChatMessage.tsx, ui/src/chat/ChatScroller/ChatScroller.tsx, ui/src/components/References/AppReference.tsx, ui/src/components/References/ContentReference.tsx, ui/src/components/References/CurioReference.tsx, ui/src/components/References/GroupReference.tsx, ui/src/components/References/NoteReference.tsx, ui/src/components/References/WritReference.tsx, ui/src/heap/HeapLoadingBlock.tsx, ui/src/state/chat/chat.ts
For #1216 
Notice that this does introduce some visual noise (switching from loading state to refs).
I tried to extract the scrolling state out into a hook, but the other components didn't seem to pick up on the changes in scrolling state from the hook so I ended up prop-drilling.
Might still be some jank in here. Please pull it down and play with it and feel free to make suggestions.
Also note that virtuoso has a built-in affordance for this type of behavior but it's meant to apply to all items in the list: https://virtuoso.dev/scroll-seek-placeholders/
=> groups: Prevent refs from loading while scrolling

ui/index.html, ui/src/app.tsx, ui/src/assets/chatmanifest.json, ui/src/components/Sidebar/MobileSidebar.tsx, ui/src/styles/base.css
this makes sure PWAs open into the app you actually added to the home screen, and adds bottom padding to the body and mobile navbars to make up for the lack of browser UI.
=> groups/talk: updated PWA manifests, added bottom spacing for standalone mode

ui/src/chat/ChatContent/ChatContent.tsx, ui/src/chat/ChatInputMenu/ChatInputMenuToolbar.tsx, ui/src/components/MessageEditor.tsx, ui/src/components/icons/CodeBlockIcon.tsx
For #1283 
We need a way to differentiate inline code formatting vs code block formatting in the toolbar, @urcades . For now I used a right caret to indicate inline.
Video demo:
https://user-images.githubusercontent.com/1221094/204890576-d2c25220-e3ce-47bd-8eb7-0210f9e7170f.mov
=> chat: Handle code block input/display

ui/src/chat/ChatScroller/ChatScroller.tsx
fixes #1291 
404s are expected to happen when fetching newer/older messages in clubs, it seems, and we were not setting `fetching` to `'initial'` again after those failed calls in ChatScroller.
=> chat: fix persistent loading spinner in multiDMs

ui/src/groups/FindGroups.tsx
for #1294 
Note that if the host ship isn't in the user's contact store we won't have much to show here. This raises another issue: are we storing new contacts in the contact store at all via groups/talk? Doesn't look like it. cc @arthyn 
https://user-images.githubusercontent.com/1221094/205385771-a068330f-f178-4727-91d7-1ca636a73b98.mov
=> groups: allow user to see host ship profile from find groups

desk/app/chat.hoon, desk/app/diary.hoon, desk/app/groups.hoon, desk/app/heap.hoon, desk/lib/chat-graph.hoon, desk/lib/cite-json.hoon, desk/sur/cite.hoon, ui/src/components/References/BaitReference.tsx, ui/src/components/References/ContentReference.tsx, ui/src/logic/utils.ts, ui/src/state/chat/chat.ts, ui/src/types/chat.ts, ui/src/types/diary.ts
Adds a `%bait` field to `%cite` representing an imported reference.
a `%bait` will only appear through the migrate flow and only when the
group being imported is not the same as the group holding the referenced
source. This disctinction must be made because `%cite` may not contain
enough information to reconstruct the imported reference, since the host
of the given reference may not have migrated yet.
Thus, `%bait` is primarily a placeholder for a potentially unresolvable
reference that will be handled at a later date by the `%nark` app. This
will allow us to begin the migration without losing the necessary data
needed to reconstruct refs.
(This will be available to anyone who migrates, so an enterprising
developer could theoretically create custom reference types for
imported instances.)
=> migration: %bait placeholder

desk/app/chat.hoon, desk/app/diary.hoon, desk/app/heap.hoon, desk/mar/migrate-map.hoon, ui/src/groups/GroupSidebar/ChannelList.tsx, ui/src/logic/useMigrationInfo.ts, ui/src/logic/usePendingImports.ts, ui/src/logic/utils.ts, ui/src/state/chat/chat.ts, ui/src/state/chat/type.ts, ui/src/state/diary/diary.ts, ui/src/state/diary/type.ts, ui/src/state/heap/heap.ts, ui/src/state/heap/type.ts
Deleting the flags was removing a key piece of information so instead I changed it to work as a map and we just mark a boolean flag once import is complete. This way we know when to ignore migration guards for groups/channels. 
As it stands before this pr, if you were to make a completely new group/channel they would show as pending migration.
=> migration: changing import flag tracking for better logic

desk/app/groups.hoon, desk/mar/migrate-map.hoon
This fixes the issue with cover values other than `0x0` and also fix the mark conversion.
=> migration: fix cover values and bad mark

ui/src/components/References/BaitReference.tsx
=> refs: show when content has not been migrated yet

ui/src/groups/ChannelIndex/ChannelIndex.test.tsx, ui/src/groups/ChannelIndex/ChannelIndex.tsx, ui/src/groups/GroupSidebar/ChannelList.test.tsx, ui/src/groups/GroupSidebar/ChannelList.tsx, ui/src/logic/useMigrationInfo.ts, ui/src/state/local.ts
This gives us a capability of detecting if previously unjoined channels before the migration have effectively migrated over by reusing our channel preview mechanism. This is somewhat intensive depending on the channel size so it only happens inside the group itself not in the group list. Addresses #1333 as best we can. 
Please don't approve without running locally and looking at either the testnet or livenet.
=> migration: detect unjoined migrations

ui/src/chat/ChatThread/ChatThread.tsx
see: #1396.
the object being passed down to ChatScroller when the thread was changed was always correct, even when the issue was triggered (often when switching between threads quickly), so this was likely an issue with react being unable to tell that the thread being referred to by the thread component was actually different.
i've been clicking around for a while trying to trigger this and don't seem to be able to, but i highly recommend pulling this branch and testing yourself as part of the review.
=> chat/threads: added key to chatscroller in thread

ui/src/chat/ChatInput/ChatInput.tsx
For #1398 
Disables post the send button and the editor while a the frontend is disconnected.
=> chat: prevent user from sending messages while disconnected

ui/src/api.ts, ui/src/app.tsx, ui/src/components/DisconnectNotice.tsx, ui/src/logic/subscriptionTracking.ts, ui/src/logic/useFileUpload.ts, ui/src/logic/useMigrationInfo.ts, ui/src/state/chat/chat.ts, ui/src/state/diary/diary.ts, ui/src/state/groups/groups.ts, ui/src/state/heap/heap.ts
This makes sure that we aren't attempting to initiate multiple requests for the same content at once. That state lives outside of the react state lifecycle so that it is immediately updated. This currently puts all retries at 10 mins. Fixes #1406 and #1354
=> subs: reduce ref fetching (again)

ui/src/components/Avatar.tsx, ui/src/dms/MessagesList.tsx, ui/src/dms/MessagesScrollingContext.ts, ui/src/dms/MessagesSidebar.tsx, ui/src/dms/MessagesSidebarItem.tsx, ui/src/dms/MobileMessagesSidebar.tsx, ui/src/dms/MultiDmAvatar.tsx, ui/src/groups/GroupAvatar.tsx, ui/src/logic/useMessageSort.ts, ui/src/logic/useSidebarSort.ts, ui/src/state/avatar.ts, ui/src/state/contact.ts, ui/src/state/groups/groups.ts, ui/src/state/settings.ts, ui/src/state/storage/storage.tsx
Changes talk sidebar to be virtualized. Also introduces the ability for us to control when avatars load their images, like when scrolling. This should make going from channel back to all messages much faster.
Also threw in a fix for #1397 by removing fleet from persisted groups and fixed a few things with localStorage, like bad keys being saved or the fact that storage was named setting which was overriding persisted settings.
=> talk: perf part 1 and local storage cleanup

ui/src/groups/GroupAvatar.tsx, ui/src/groups/GroupInfoFields.tsx, ui/src/groups/NewGroup/GroupInfoPreview.tsx
see: #1423.
This may still break if people use the multi-emoji sequences that display as one emoji (like the families where they all have different user-selectable skin tones) but it'll fall back relatively gracefully
=> groups: updated GroupAvatar to handle emoji + other unicode

desk/app/chat.hoon, desk/app/diary.hoon, desk/app/heap.hoon
We weren't protecting from rejoins. If you already have the channel, it would get bunted and then try to sub, but since it's a duplicate sub you're just left with an empty channel. This prevents part of #1452 still not sure how ted got in this state in the first place though.
=> channels: protect from accidental rejoins

desk/app/groups.hoon
OTT, this is a fix for #1386 it just loops through all groups on load and makes sure that we have a subscription if one isn't there. Need to double check that this is safe.
=> groups: restore missing subs from migration

ui/src/chat/ChatScroller/ChatScroller.tsx
We're sometimes rendering Virtuoso without setting a firstItemIndex because the keys haven't loaded yet. We need to make sure we have keys before rendering Virtuoso.
Fixes #1437
=> chat: fix issue with chat scroller not loading older messages

desk/app/groups.hoon
we were accidentally sending group invites from every member that heard the person getting added to the group... Fixes #1464
=> groups: only let host send invites

desk/app/chat.hoon, desk/app/diary.hoon, desk/app/heap.hoon
Somewhere in the process of migration we lost subscriptions to the updates for certain channels. This should safely restore them if missing. Fixes #1478
=> channels: restore lost subscriptions

ui/src/chat/ChatMessage/ChatMessage.tsx, ui/src/chat/ChatUnreadAlerts.tsx
Fixes #1453 
Shows a blue "unread" dot next to a thread if it contains the last unread message.
Also allows for a user to click "Click to view" button in the unread banner and get taken to the parent (replied-to message) in the chat scroller if the last unread message is in a thread under that message.
tl;dr: makes unread threads less annoying.
=> chat: better handling of thread unreads

ui/src/state/groups/groups.ts, ui/src/state/groups/groupsReducer.ts
We weren't defaulting the vessel if it's not found, but it should be there. Should fix #1513 #1502, but maybe not the root cause of why it isn't there in the first place.
=> groups: default vessel

ui/src/components/MigrationTooltip.tsx, ui/src/components/Sidebar/GroupList.tsx
see: #1457.
changed the "tooltip" to a "popover", as having an item that now has an interactable element that disappears when not hovering over the trigger is no fun.
=> groups: added leave button to unmigrated group popover

ui/src/chat/ChatScroller/ChatScroller.tsx
Should fix the issue we were seeing with scroll between chats. Please test it out and let me know if you still see it in some particular situation.
Only issue I see is if you add an emoji, remove it, and add it back the emoji will be hidden below the chat input.
=> chat: fix issue with scroll position on channel switch

ui/src/components/IconButton.tsx
addresses concern bought up by ~poldec-tonteg and expanded on by @urcades 
added a delay before showing the tooltip, and disabled the ability to hover over it (the double-nested hover states allowed you to enter a state where only the tooltip was open)
=> chat: tooltip durability

ui/src/components/ColorPicker.tsx, ui/src/components/ImageOrColorField.tsx, ui/src/components/ImageURLUploadField.tsx, ui/src/dms/MultiDMEditModal.tsx, ui/src/dms/MultiDMInfoForm.tsx
Un-squishes the MultiDmInfoForm and adds adaptive sizing to the ImageOrColorField input elements such that they don't shrink or over-expand unexpectedly.
Also sizes the image URL field such that the value and the button don't occlude.
fixes #1503
fixes #1239
=> talk: correct width for multi-DM info modal

ui/src/chat/ChatInput/ChatInput.tsx, ui/src/chat/ChatInput/__snapshots__/ChatInput.test.tsx.snap, ui/src/components/icons/ArrowNIcon16.tsx
Reduces the mobile chat input as per #1269, makes room for the attachment button such that the message input doesn't collide with the icon, and bottom-aligns the sigil and input on desktop.
Desktop:
Mobile:
fixes tloncorp/landscape-apps#1269
=> chat: reduced treatment on mobile, alignment issues

ui/src/groups/ChannelIndex/ChannelIndex.tsx, ui/src/groups/ChannelIndex/__snapshots__/ChannelIndex.test.tsx.snap, ui/src/groups/GroupSidebar/ChannelList.tsx, ui/src/groups/GroupSidebar/MobileGroupSidebar.tsx, ui/src/groups/MobileGroupActions.tsx
Restores the in-group options menu on mobile and adds a link in the mobile channel selection for All Channels.
fixes #1266
=> groups:  in-group options, all channels on mobile

ui/src/chat/ChatThread/ChatThread.tsx
- Currently when the writ data is still loading, an obnoxiously large 'No thread found' is rendered; this removes it in favor of rendering nothing until it's ready. Eventually we should consider a thread loading state
- Limit the scope of the Escape keydown listener to the containing div element. This addresses the issue where the user opens a thread, types a message, then clicks a user's profile within the thread to view their info modal, then hits escape to close the modal but also closes the thread, losing the drafted post. Now it will require re-focusing the thread context after dismissing the modal. Eventually we should add an `onunload` to prevent losing the drafted message, and / or restoring the save draft feature.
=> ux: ChatThread enhancements

ui/src/diary/DiaryChannel.tsx, ui/src/diary/DiaryList/DiaryGridItem.tsx, ui/src/diary/DiaryList/DiaryGridView.tsx, ui/src/logic/utils.ts, ui/src/state/diary/diary.ts, ui/src/state/diary/type.ts
see: #1458.
also fixes an issue with the `sampleQuippers` hook
note that the autoloading in the grid view is still somewhat janky, but it does work
=> notebooks: virtualize list of notes

ui/src/chat/ChatWindow.tsx
see: #1426 
when the chat channel unmounts, if there's an "unread clear timer", we just mark the whole thing read.
=> clearing notifications upon leaving chat even if timer hasn't finished

desk/app/chat.hoon
Fixes #1528, which was also an issue for *any* link to a mention.
=> chat: fix notification links for mentions

ui/src/app.tsx, ui/src/dms/TalkHead.tsx, ui/src/logic/useIsChannelUnread.ts
talk: reflects unread message count (based on filter selection) in browser title
fixes #642
=> talk: unread message count in title

ui/src/channels/ChannelHeader.tsx, ui/src/chat/ChatChannel.tsx
Currently we show a blue "unread indicator" dot for groups for which a user has an unread non-new-message/meta notification (~sampel-palnet mentioned you, ~sampel-palnet joined, new channel added, etc). This PR allows us to mark those notifications as read upon viewing the associated channel in that group (or the group itself) so that the user doesn't have to individually mark-as-read or click on each notification on the notifications view.
Note that we don't show blue notification dots next to the channels themselves for this sort of thing. Should we?
Alternatively, we could *only* show the blue notification dot on groups for unread messages (and not these other types of notifications).
Fixes #1475 #1427 and maybe a few others.
=> chat: mark group notifications read on viewing group channels

desk/app/groups.hoon
This is a bandaid that resolves #1599 by addressing the symptomatic behavior. With this change, the "sampel-palnet sent you an invite" notification will not be sent if one is already a member of the group.
I have yet to be able to reliably repro this issue, but I did see it once on mainnet. Tested this by monkey-patching my mainnet ship and have not experienced it since. 
As part of the troubleshooting for this task, I reviewed the invite flow in the backend (as well as my novice hoon proficiency allows for). Given the observed behavior I experienced while attempting to repro with local fakezods and comets, it appears there is an upstream issue somewhere in the flow. It appears that somehow the group host is occasionally generating a `vit.gang` for the joining user. This then triggers the …
=> hark: suppress extraneous invite notification

desk/lib/dm.hoon
This fixes #1606 at least the immediate issue. There may be more crashes lurking. We need to do an audit for anything surrounding taking facts and remove any crashes.
=> chat: prevent a fact update from host crashing

.github/workflows/bump.yml
fixes sed syntax and and adds a commit message so it doesn't trigger the deploy action
=> ops: fix version bump action

ui/src/chat/ChatMessage/ChatMessage.tsx
Should fix #1643 (and its dupe, #1644)
Also attempted to fix the issue where some threads were still displaying the wrong "last reply" time, but those threads seem to still show the wrong time. That will require further investigation.
=> chat: use lodash function to fix issue with last reply time on some browsers (port)

ui/src/notifications/Notifications.tsx
On the tin. Only shows the "Mark All as Read" button in groups/notifications if there are any actual unread notifications.
After clicking:
=> groups: only show 'mark as read' if unreads exist

desk/app/chat.hoon, desk/app/diary.hoon, desk/app/groups.hoon, desk/app/hark.hoon, desk/app/heap.hoon, ui/src/logic/useMigrationInfo.ts
This removes the manual checking we were doing for unjoined channels now that the migration has stabilized. It also changes the verb flag to be off so that we aren't filling people's dojos with spam. Should help with urbit/urbit#6176
=> groups: remove extraneous migration checks

ui/package-lock.json, ui/package.json, ui/src/components/MessageEditor.tsx, ui/src/logic/useFileUpload.ts, ui/src/state/storage/upload.tsx, ui/src/types/storage.ts
1. Adds a getImageSize promise to the useFileUpload hook and stores the dimensions of the uploaded image in the FileStore
2. Only updates the attachment blocks in MessageEditor when these sizes are resolved
3. Passes the correct width and height of the story to the back-end when the images are posted
As an end result, images are properly sized in the chat view, which fixes #1557.
=> chat: get and store dimensions of uploaded images

desk/app/chat.hoon, desk/app/diary.hoon, desk/app/groups.hoon, desk/app/heap.hoon, ui/src/components/References/GroupReference.tsx, ui/src/env.d.ts, ui/src/global.d.ts, ui/src/groups/GroupJoinList.tsx, ui/src/groups/Join/JoinGroupModal.tsx, ui/src/logic/utils.ts
This fixes #1593 on the backend and also displays messages on the frontend explaining that you can't join a group if they have banned you or your rank.
This should cover the joining from the frontend, but also anyone trying to be sneaky from the terminal whether they are trying to join a group or a channel since this also updates the can-read/can-write checks to include a check for banned status.
=> groups/channels: rank level bans

ui/src/logic/tiptap.test.ts, ui/src/logic/tiptap.ts
The previous fix didn't carry the `codeWithLang` flag through the entire parsing so would break on notebooks. Also for some reason the code block editor does not give a default language and our JSON parser on the backend expects a non-empty string so I added a default.
=> tiptap: fix small codeblock issues

desk/lib/chat-json.hoon, ui/src/groups/ChannelIndex/ChannelIndex.tsx, ui/src/logic/useIsChannelUnread.ts, ui/src/state/chat/chat.ts, ui/src/types/chat.ts
This fixes the scenario where a channel has gone admin only but still has unreads. It also fixes a small issue where trying to update a channel after just creating it was failing because the chat had not been added to state yet.
There's a larger issue here with how ships receive facts about changing permissions that I started to explore but dropped. Essentially sometimes as it stands right now the existing permissions can interfere with hearing about updates to permissions themselves causing the host and subscriber to get out of sync. This was mostly unrelated to what I was trying to fix so deferred for later, but should make into an issue.
=> talk: ignore channel unreads that I can no longer read

ui/src/chat/ChatInput/ChatInput.tsx, ui/src/components/MessageEditor.tsx, ui/src/logic/utils.ts
For #1679 
I *think* this is caused by both a peculiarity in the way focus works on Android when pasting and the newish onPaste handler we used for chatblock images.
Using the tiptap commands was the much more straightforward way of handling the href issue (not clear how to correctly update or replace a node without a specific selection in ProseMirror).
=> chat: fix paste issues on mobile chrome

ui/src/diary/DiaryCommentField.tsx
Was unable to repro this locally or via SHIP_URL. This resolves #1439 by changing the order in the Diary quip submit handler to match the submit handler in ChatInput
=> quips: prevent double submit of Diary comments

ui/src/logic/utils.ts
Fixes #1677. This should only ever match a string that is entirely an image URL not a partial of a string.
=> utils: correct image url regex

ui/src/dms/MultiDm.tsx
Fixes #1696 
The useSendMultiDm hook was causing a re-render. We don't need to use a special sendMessages function for multiDMs after we've already created the multiDM, so I pulled it out.
=> chat: use normal sendMessage in MultiDm

ui/src/chat/ChatScoller/ChatScrollerPlaceholder.tsx, ui/src/chat/ChatScroller/ChatScroller.tsx
For #1728 
Improves experience for #1665 but doesn't address the issue with using `bap` on line 99 of lib/dm.hoon, or change the load order on the frontend.
Screenshots:
https://user-images.githubusercontent.com/1221094/213242478-01102c14-b0ea-4198-a2b5-9eb4e2d76cdd.mov
https://user-images.githubusercontent.com/1221094/213242497-3257589c-61e2-4640-ad0e-cdb4d1a6615d.mov
=> chat: add placeholder for chat scroller

ui/src/chat/ChatInput/ChatInput.tsx, ui/src/components/MessageEditor.tsx
Fixes #1729 
It turns out this was caused by including `onReference` in the dependency array of the useCallback in handlePaste.
I also removed the useEffect we originally had in ChatInput for clearing text if no draft exists (didn't cause the issue we were seeing, but it was useless anyway and could cause other issues, I imagine).
=> chat: fix chat input focus loss

desk/mar/clubs.hoon
This fixes a compilation error when bouncing a fresh fakezod from `master`.
=> clubs: fix compilation err

ui/src/chat/ChatInput/ChatInput.tsx
For #1749 
Switching from onClick to onMouseDown and throwing in an e.preventDefault() prevents the button from stealing focus from the input.
This also makes the explicit messageEditor focus() command unnecessary.
to test: log out messageEditor.isFocused in the main body of the ChatInput component, note that it stays focused when you click the button.
=> chat: fix keyboard and input focus issues on android

ui/src/chat/ChatInput/ChatInput.tsx, ui/src/logic/tiptap.ts
for #1679 
Fixes both pasting of refs and regular links from gboard in Android.
Google's gboard supports "pastes" while composing within an input. These pastes don't register because the user is actually in composition mode, it's as if the user just typed the content in, so a paste event never fires and therefore never gets caught by our existing paste rules.
=> chat: handle gboard pastes on android

desk/app/groups.hoon
Not sure if we have an issue about this but getting kicked or having the group deleted from the host doesn't properly cleanup subscriptions.
=> groups: properly cleanup subs after leave/kick/etc

ui/src/chat/ChatChannel.tsx, ui/src/chat/ChatScroller/ChatScroller.tsx, ui/src/chat/ChatScroller/IChatScroller.ts, ui/src/chat/ChatWindow.tsx, ui/src/state/chat/chat.ts
For #1763 
We need to check to see if we actually initialized chat state for the channel, empty channels always have zero keys.
=> chat: don't show placeholder for empty chat channels

ui/src/components/References/AppReference.tsx
Typographic fix for app title, no margins (even as descendent of prose styling, as in #1678), reasonable line-break for button (most evident in Gallery views).
fixes #1678
=> refs/app: display fixes

desk/app/groups.hoon, ui/src/groups/GroupAdmin/GroupMemberItem.tsx
For #1765 
Prevent group host from being removed as an admin of a group, on both the frontend and backend.
Actual hoon changes are on lines 1285 and 1415. If I missed something obvious on the hoon, let me know.
=> groups: do not allow group host to be demoted from admin

desk/mar/ship.hoon
Before this change, compilation was failing with:
```
[%error-validating /desk/ship]
[%validate-page-fail /desk/ship %from %mime]
/mar/ship/hoon:<[15 38].[15 55]>
/mar/ship/hoon:<[15 42].[15 55]>
```
Now it compiles successfully
=> desk: fix ship mark

ui/src/chat/ChatChannel.tsx, ui/src/chat/ChatScroller/ChatScroller.tsx, ui/src/chat/ChatScroller/IChatScroller.ts, ui/src/chat/ChatWindow.tsx, ui/src/diary/DiaryChannel.tsx, ui/src/heap/HeapChannel.tsx, ui/src/heap/HeapDetail.tsx, ui/src/state/chat/chat.ts, ui/src/state/diary/diary.ts, ui/src/state/diary/type.ts, ui/src/state/heap/heap.ts, ui/src/state/heap/type.ts
For #1655 
Also 
- Eliminated the prop-drilling for the chat loading state (which I did, idk why) and cleaned up the ChatChannel component.
- We were using zustand's create/persist for heap and diary state and for some reason it wasn't actually persisting, this fixes that.
- We weren't actually scrying for perms when initializing heap, also fixed that.
~~I can't seem to figure out a way to actually load just-joined the channel content into the store without doing a page refresh. Any idea what I'm missing here? Try it out by commenting out the `window.location.reload()` in one of the useEffects.~~
=> groups: auto join channels in same group after clicking a reference

ui/src/components/References/NoteReference.tsx, ui/src/constants.ts
This PR resolves a couple known issues with Note references in chat.
https://user-images.githubusercontent.com/16504501/214521730-a0220dbb-7f16-45db-87cc-0570b4943321.mp4
=> chat: Note reference fixes

ui/src/groups/FindGroups.tsx
When the search times out, it could be due to multiple root causes.
This clarifies the message as it has caused confusion in UC Help a few times now:
Resolves #1666.
=> ux: clearer Find Groups copy when Not Found

ui/src/components/ShipSelector.tsx
for #1157 
Had a lot of trouble getting onInputChange to do what we wanted here before I realized that we could pass inputValue as a prop to the CreatableSelect component itself (and thus have onInputChange fire at appropriate times). Passing this prop doesn't seem to change any other functionality, but please test and let me know if you find something.
=> keep input text on blur in ship selector

ui/src/state/hark.ts
This is a followup to #1798 to ensure the spinner is rendered when marking all notifications as read.
=> hark: await mark read call

ui/src/logic/useSidebarSort.ts
For #1812 
Both channel list sorting and group sorting settings were not persisting, it looks like we just weren't passing the mode into the sort function.
I also discovered that we were wiping the groupSideBarSort key each time we saved individual group channel sort options, so you could only have one group's sidebar sort settings saved at a time. This also fixes that.
=> groups: fix sidebar sort persistence issues

ui/src/groups/GroupAdmin/GroupPendingManager.tsx, ui/src/groups/GroupInviteDialog.tsx, ui/src/state/groups/groups.ts
for #1366 
adds subscription tracking and relevant UI changes for `addMembers`, `invite` and `revoke` (which is both "cancel" and "reject" in secret/private groups)  in both the "Members" and "Pinned" views.
demo:
https://user-images.githubusercontent.com/1221094/215186214-bd68a788-c404-457e-af6b-9b99ac68ff79.mov
=> groups: add loading spinner for group invite dialog and pending screen

ui/src/components/ShipSelector.tsx, ui/src/dms/Dm.tsx, ui/src/dms/MessageSelector.tsx, ui/src/dms/MultiDm.tsx
- improved mobile styles
- remove popover guidance
=> ux: MessageSelector styling and clean up

ui/src/chat/ChatThread/ChatThread.tsx
For #1541 
Also removes the unnecessary space between "Thread" and the colon.
=> talk: show multi-dm titles in threads

desk/app/chat.hoon, desk/lib/chat-json.hoon, desk/mar/club/action.hoon, ui/src/chat/ChatChannel.tsx, ui/src/chat/ChatMessage/ChatMessageOptions.tsx, ui/src/chat/ChatMessage/__snapshots__/ChatMessage.test.tsx.snap, ui/src/chat/ChatReactions/ChatReaction.tsx, ui/src/chat/ChatReactions/ChatReactions.tsx, ui/src/components/EmojiPicker.tsx, ui/src/diary/DiaryChannel.tsx, ui/src/dms/MessagesList.tsx, ui/src/heap/HeapChannel.tsx, ui/src/logic/useMedia.ts, ui/src/state/bootstrap.ts, ui/src/state/chat/chat.ts, ui/src/state/chat/clubReducer.ts, ui/src/types/chat.ts
This fixes #1565 by ensuring that we hear facts about club's membership and meta even if we haven't visited said club and also by loading all clubs initially so that we can reconcile with whatever is stored in local storage.
This does change our subscriptions so this needs to be communicated with external parties.
Also threw in a fix for the issue of channels on refresh not loading, some console errors about nested buttons with chat reactions, and the issue with media query listeners disappearing #1529.
=> clubs: only accept once

ui/src/chat/ChatChannel.tsx, ui/src/diary/DiaryChannel.tsx, ui/src/heap/HeapChannel.tsx
I don't know if we have an issue for this, but users were being redirected to /groupflag/actvity (regardless of app) if they didn't have read permissions on a channel.
I had thought we already fixed this, but apparently we didn't.
=> Fix navigation on lack of read perms on channels

ui/package-lock.json, ui/package.json, ui/src/app.tsx, ui/src/components/AboutDialog.tsx, ui/src/components/Sidebar/Sidebar.tsx, ui/src/components/UpdateNotice.tsx, ui/src/dms/MessagesSidebar.tsx, ui/src/groups/MobileGroupsActions.tsx, ui/src/state/bootstrap.ts, ui/src/state/kiln.ts
This is for #1733, but also includes some other nice features.
I added a kiln state (required updated @urbit/api) that we can use to get info about desks the user has installed (same as in %garden/landscape). For now, we can use this to surface the base hash of the app that the user is currently looking at, but we could use it in the future to check for the existence of other apps that we could interoperate with.
This PR adds:
1) A way to poll the backend to find out if we have an update:
https://user-images.githubusercontent.com/1221094/215599321-af9a025d-1d23-4e54-b3d1-b8709d872487.mov
2) An "About Groups" (or Talk) modal that shows basic information:
https://user-images.githubusercontent.com/1221094/215598995-472cd514-4f69-4776-b730-ce0c26ba60ec.mov
=> support improvement omnibus

ui/src/heap/HeapDetail.tsx, ui/src/heap/HeapDetail/HeapDetailEmbed.tsx
This resolves #1543 by tweaking the layout to prevent long embeds from being occluded by the heap detail header
=> heap: fix occlusion of long tweets

desk/app/chat.hoon
Fixes #1693 by moving read marker to after my message if I post in a chat.
=> chat: don't mark self unread

ui/src/chat/ChatInput/ChatInput.tsx
This was a cause for the "broken images" appearing in chat. Users could just hit enter on the input and it would send the non-uploaded image url.
=> chat: do not allow send on submit if send is disabled on chatinput

ui/src/logic/utils.test.ts, ui/src/logic/utils.ts, ui/src/profiles/EditProfile/ProfileFields.tsx
This resolves #1390 by changing how `@ux` values are normalized in the frontend. When a color hex such as `#00FFFF` is persisted in the backend, it is converted to a `@ux` (unsigned hexadecimal). The extraneous 0 values are not saved, which then requires them to be restored when loaded in the frontend. See the comments in #1390 for more detail.
Also:
- debounce the color picker's state updating (previously it was firing rapidly as the user dragged the picker cursor)
- add test coverage for `normalizeUrbitColor`
https://user-images.githubusercontent.com/16504501/216297458-a18e8886-b75e-4404-b54f-6b209e18dd2c.mov
=> ux: profile supports color hexes starting with 0

ui/src/heap/HeapDetail/HeapDetailSidebar/HeapDetailComments.tsx, ui/src/heap/HeapTextInput.tsx
This resolves #1576 by clearing the editor input before poking the curio. Previously, it would be cleared after submission, which would allowed a brief window to double post by spamming Enter (before the component could process the state update). I tried other approaches (e.g., do not send if isPending), but they were causing weird side effects or extraneous renders.
Also, add keys to mapped comments in HeapDetail view to suppress console error.
https://user-images.githubusercontent.com/16504501/216317586-6e287363-b332-4b58-94cb-1838c818c58a.mov
=> heap: prevent double comments on Curios

talk/app/talk-cli.hoon, talk/lib/graph-store.hoon, talk/lib/migrate.hoon, talk/lib/resource.hoon, talk/lib/shoe.hoon, talk/sur/chat-0.hoon, talk/sur/chat.hoon, talk/sur/cite.hoon, talk/sur/epic.hoon, talk/sur/graph-store.hoon, talk/sur/group-store.hoon, talk/sur/group.hoon, talk/sur/groups.hoon, talk/sur/meta.hoon, talk/sur/metadata-store.hoon, talk/sur/post.hoon, talk/sur/pull-hook.hoon, talk/sur/resource.hoon
What with the incoming release of session support for the (web)terminal, it'd be a shame if we didn't have an app for which that feature made some sort of sense. So here it is, chat-cli updated to work with groups 2's chat.
The good:
- Supports most of the features chat-cli supported.
- Includes session support.
- Pays respects to times long past: `/app/talk`.
- Tries its best to gracefully render gui-oriented contents such as `%img` and `%cite`.
The bad:
- No DMs or group DMs support.
- Does not even attempt to resolve message references, except for user-prompted history lookup with `;123` commands. We can scry for messages, but cannot scry for an _existence check_ of messages, so the content scry may crash if we don't know the message the reference points to.
- Took a somewhat shoehorn …
=> talk: minimal viable chat-cli for groups 2

ui/src/chat/ChatChannel.tsx, ui/src/components/References/CurioReference.tsx, ui/src/components/References/NoteReference.tsx, ui/src/components/References/ReferenceBar.tsx, ui/src/components/References/WritBaseReference.tsx, ui/src/diary/DiaryNote.tsx, ui/src/groups/Join/JoinGroupModal.tsx, ui/src/groups/useGroupJoin.ts, ui/src/heap/HeapDetail.tsx, ui/src/logic/useNavigateByApp.ts, ui/src/profiles/ProfileModal.tsx
Fixes #1841 
Using the group join modal and some URL parameters to give users the option to join a (public, otherwise they wouldn't be able to see the ref anyway) group from a ref and then automatically navigating the user to the content from the ref after the join completes.
Demo video (excuse the confusion after I click through the first ref, I used the browser back button instead of the app nav):
https://user-images.githubusercontent.com/1221094/216381861-8ca124cc-ae9d-4a18-865c-ba9ea03304f9.mov
=> groups: allow group joins from references

ui/patches/usehooks-ts+2.6.0.patch
Have a feeling Safari is blocking writing to local storage so should fix #1893, but need more info. This is a bug in our dep: juliencrn/usehooks-ts#124
=> uselocalstorage: gracefully fail if localstorage errors

desk/app/chat.hoon, desk/app/diary.hoon, desk/app/groups.hoon, desk/app/heap.hoon, desk/mar/channel-join.hoon, desk/sur/chat.hoon, desk/sur/diary.hoon, desk/sur/heap.hoon, ui/src/channels/Channel.tsx, ui/src/chat/ChatChannel.tsx, ui/src/diary/DiaryChannel.tsx, ui/src/groups/ChannelIndex/ChannelIndex.tsx, ui/src/heap/HeapChannel.tsx, ui/src/state/chat/chat.ts, ui/src/state/chat/type.ts, ui/src/state/diary/diary.ts, ui/src/state/diary/type.ts, ui/src/state/heap/heap.ts, ui/src/state/heap/type.ts, ui/src/types/chat.ts, ui/src/types/diary.ts, ui/src/types/heap.ts
OTT, this is an extensive change but should ensure that we always have the group populated in `perm`. This crops up in issues like #1891
=> channels: guarantee we always have group flag immediately upon join

ui/src/components/ShipSelector.tsx, ui/src/logic/useMessageSelector.ts, ui/src/state/chat/chat.ts
There were two bugs here. Fixes #1927 and also ensures that ship selector always outputs valid @p's, because if you were typing a patp without one and selecting it when it was an exact match (not in contact store) this would pass a bad `whom` along.
=> chat: fix new dms

ui/src/dms/MessagesList.tsx, ui/src/dms/MessagesSidebar.tsx
Applying the same fix applied to the mobile messages list (only show the "Pinned" section if we have pinned channels/DMs, not pinned groups, which won't render anyway), and fix a separate issue where a blank row could appear in the list if a user has left a group/channel or that group/channel was deleted (not sure how we missed this before).
=> Only show pinned if we have talk pins, filter out left/deleted group channels from briefs

ui/src/heap/HeapChannel.tsx, ui/src/heap/NewCurioForm.tsx
Fixes #1928 
Add VirtuosoGrid, fetch 50 new items when we reach the bottom of the current list. Had to create a fake curio and prepend it to the sortedCurio array (and then replace it) in order to get the NewCurioForm to render in the list.
https://user-images.githubusercontent.com/1221094/218874834-cf4f1e41-cb4b-4a86-b5e9-d335f5946c4e.mov
=> gallery: virtualize list, fetch new items at bottom

ui/src/components/References/GroupReference.tsx
Fixes #1910 
Still not clear on why these are showing up as gang invites, but for now we can hide the button if we know that you're in the group.
=> groups: hide reject button on group refs for joined groups

ui/src/chat/ChatInput/ChatInput.tsx
fixes #1942 
Focus was apparently lost because we were passing a prop directly into sendMessage, which caused a re-render.
=> chat: fix chat input loss of focus

ui/src/channels/ChannelHeader.tsx, ui/src/components/DisconnectNotice.tsx, ui/src/components/LandscapeWayfinding.tsx, ui/src/nav/MobileRoot.tsx, ui/src/notifications/Notification.tsx, ui/src/notifications/Notifications.tsx
- Adjusts the group home header (fixes #1930, sorry about the confusion there)
- No multiply for @mention tags in notifications, fixes #1929
- Back button in channel header on mobile sends you back to the channel list, fixes #1930 
- Finally re-aligns the Groups menu on mobile (no issue)
- Hides the Wayfinding bug in channels and DMs on mobile, fixes #1924 
- Stops the disconnect/reconnect banner from jumping in height between states (no issue)
=> v2.7.0 cosmetics

ui/src/chat/ChatChannel.tsx, ui/src/chat/ChatInput/ChatInput.tsx, ui/src/chat/ChatThread/ChatThread.tsx, ui/src/components/MessageEditor.tsx, ui/src/dms/Dm.tsx, ui/src/dms/MultiDm.tsx
This changes how we handle the `ChatInput` around the app. Since we really want distinct breaks between one chat or another I added keys to force remount between chats, similar to the scroller. This makes the initialization of the input much cleaner since we know that we won't have states lingering between. To combat any kind of wiping this now stores typed messages in local storage. Fixes #1953, fixes #1925
=> chat: drafts reborn

ui/src/components/EmojiPicker.tsx
Fixes #1950 
Was caused by the new way we handle hover state in chat messages. As soon as we leave the div for the message we'll lose its children that depend on hover. There was enough space between the message options and the emoji picker for the onOut to fire. Had to sacrifice some space between the picker and the chat message options.
=> chat: fix emoji picker disappearing on subsequent messages

ui/src/chat/ChatReactions/ChatReaction.tsx, ui/src/chat/ChatScroller/ChatScroller.tsx, ui/src/components/References/ReferenceBar.tsx, ui/src/components/References/WritBaseReference.tsx, ui/src/logic/subscriptionTracking.ts, ui/src/logic/useConnectionChecker.ts, ui/src/state/chat/chat.ts, ui/src/state/chat/type.ts, ui/src/state/chat/writs.ts
**scroll to:**
I thought we had this, but the scroller has been through so many changes not sure what happened to it. This adds back in the ability to detect `scrollTo` changes and scroll appropriately. All the dependencies in the `useEffect`'s are very carefully set here. Also found that we weren't always using the correct time for scrolling back so I added that as well.
**stuck at top**
I think recent changes I made made this more likely to happen or maybe it was always this way. Either way, this alters the atTop threshold so that we can escape the "top" on small screens if there's not enough messages to trigger a state change and also ensures that if we initially load at the top because of a `scrollTo` that we manually start loading older messages since `atTopChange` won't fire. …
=> chat: prevent stuck at top and add scroll to message

ui/src/chat/ChatInput/ChatInput.tsx
fixes #1741 
normalizeInline will produce an object like this { break: null } when we upload an image because tiptap sends an empty paragraph object when no text has been added in the chat input.
=> chat: prevent extra break/space on messages with uploaded images

ui/src/diary/DiaryInlineEditor.tsx
This should solve #1840 temporarily until we can actually support blocks in lists.
=> notebooks: disable blocks in lists

desk/app/groups.hoon, ui/src/groups/GroupAdmin/GroupMemberItem.tsx, ui/src/logic/utils.ts, ui/src/state/chat/chat.ts, ui/src/state/diary/diary.ts, ui/src/state/heap/heap.ts
Although there are no real technical issues with removing channel hosts there are some UX concerns. Given that this removes the UI for kicking/banning channel hosts and also guards against it on the backend. Fixes #1807
=> groups: prevent channel host removal

ui/src/notifications/Notifications.tsx, ui/src/types/groups.ts
Adds a GroupSummary instance on the home page of a group.
=> groups: add groupsummary to group home

ui/src/chat/ChatInput/ChatInput.tsx, ui/src/components/MessageEditor.tsx, ui/src/logic/useMessageSelector.ts
Fixes #1982, my previous change for drafts in #1954 basically made the tiptap editor act in a controlled manner which was mostly fine except that since it was constantly recreating the editor it was pulling focus off and reapplying it in places where we have `autoFocus` on. However, in the new DM situation we don't want the input to pull focus over the ship selector so we saw this bug. This switches things around so that we only set the draft on first mount. We need to put this through it's paces though I'm worried about some kind of async bug where the draft gets applied repeatedly or after submitting, etc.
=> chat: using tiptap editor in a 'controlled' way is bad

ui/src/app.tsx, ui/src/components/References/GroupReference.tsx, ui/src/components/Sidebar/Sidebar.tsx, ui/src/dms/MessagesSidebar.tsx, ui/src/groups/FindGroups.tsx, ui/src/groups/GroupSidebar/GroupSidebar.tsx, ui/src/groups/GroupSidebar/MobileGroupSidebar.tsx, ui/src/notifications/Notifications.tsx
- Removes GroupSummary from the group home
- Renames group home to "Activity" and uses bell icon:
- Cleans up overlapping GroupReference layout
- Sets the default app route to Find Groups
- De-emphasizes the empty activity notices
- Adds suggested groups in Find Groups:
=> groups: various first-run fixes

ui/src/components/Leap/MenuOptions.tsx, ui/src/components/Leap/useLeap.ts, ui/src/constants.ts, ui/src/state/bootstrap.ts, ui/src/state/pals.ts
After using preview Leap, noticed I was using it to primarily jump between my unreads and pins. So, this PR bakes in some of this behavior.
=> ux: Leap sorts by pinned, unreads, and pals

ui/src/diary/DiaryContent/DiaryContent.test.tsx, ui/src/diary/DiaryContent/DiaryContent.tsx
This parses our breaks so that they form paragraphs fixing #1959. We could probably refine this further with code blocks and blockquotes (these should probably not be part of the inline type anyway).
Fixes #1959
=> diary: breaking up paragraphs correctly

desk/app/chat.hoon, desk/app/diary.hoon, desk/app/heap.hoon
OTT I don't think we have this issue recorded, but joining any channel with a large backlog gives an ungodly amount of unreads. This sanely sets the last read time to the join time.
=> channels: avoid ungodly unread backlog

ui/src/channels/EditChannelForm.tsx, ui/src/groups/ChannelsList/SectionNameEditInput.tsx
Fixes #2000 
We had some weird logic in the SectionNameEditInput component that was causing the first issue. 
We were also re-adding channels to a section each time we updated the title, which appears to be unnecessary (maybe a previous hack to deal with the state not updating?), which was causing the channels to reorder when renaming a section.
The channel permissions state not updating was due to the relevant calls not being awaited.
=> New channel manager fixes

ui/src/components/References/GroupReference.tsx
- Adds a fixed with to group refs of 250px
- Sets font-size to text-sm
- Puts "by ShipName" on a separate line.
- Hides overflowing text with ellipsis.
- Makes it so the button text doesn't wrap.
=> Group refs: add fixed with, make text small, wrap it

ui/src/groups/ChannelsList/ChannelsListSearch.tsx, ui/src/groups/GroupActions.tsx, ui/src/groups/GroupAdmin/GroupInfo.tsx, ui/src/groups/GroupAdmin/GroupMemberItem.tsx, ui/src/groups/GroupAdmin/GroupMemberManager.tsx, ui/src/groups/GroupAdmin/MemberScroller.tsx
Adjusts the layout of the invite/member search field in the admin/member manager to follow the button/filter pattern in #1995. 
Also removes the ability for non-admins to invite members to a group.
Also makes some UX fixes to the member manager itself that have been bothering me for a while:
- Adds row striping and mouseover backgrounds to each member row for more accurate editing
- Moves the member count to inside the filter field to eliminate a disconnected layout element
- Adds a very obvious "HOST" badge for channel and group hosts
- Makes the role change dropdown a button, moves the check-marks to the left
- Lists everyone as a member
- Gracefully overflows 3+ roles
- Unifies ancillary action styles for each row
- Wraps the members list in a card for non-admins
- Fixes the filter …
=> admin: fixes invite button/search field alignment, various improvements

ui/src/heap/HeapDetail/HeapDetailSidebar/HeapDetailCommentField.tsx, ui/src/heap/HeapTextInput.tsx, ui/src/heap/NewCurioForm.tsx
- Allows the comment input box to expand vertically forever
- Moves the "Post" button out of the text area to prevent overlapping
- Adds a spinner during posting
- Changes "Post" to an up arrow to conserve some space in comments
fixes #2006, partially fixes #2045
=> heap: comment-specific text input layout

ui/src/components/References/GroupReference.tsx, ui/src/groups/FindGroups.tsx
Adds a button-only mode to GroupReference, hard-codes our suggested groups.
Fixes #2027
=> groups: hard-code suggested groups

ui/src/components/References/AppReference.tsx, ui/src/components/References/BaitReference.tsx, ui/src/components/References/CurioReference.tsx, ui/src/components/References/GroupReference.tsx, ui/src/components/References/NoteCommentReference.tsx, ui/src/components/References/NoteReference.tsx, ui/src/components/References/WritBaseReference.tsx, ui/src/components/References/WritChanReference.tsx
Fixes #1970 
We don't need to initialize the relevant channel, we were still doing that for curios/notes.
I also memoized all of the reference components.
=> refs: improve reference perf

desk/lib/mop-extensions.hoon
Fixes #2042 
Example usage:
```
/+  mop-extensions
=/  longer  |=([a=tape b=tape] (gth (lent a) (lent b)))
=/  mymop  ((mop tape @) longer)
=/  myon   ((on tape @) longer)
=/  mope  ((mop-extensions tape @) longer)
=/  letters  (put:myon (put:myon (put:myon (put:myon (put:myon *foo "a" 1) "bb" 2) "ccc" 3) "dddd" 4) "eeeeee" 5)
:*  (top:mope letters 4)
(bot:mope letters 4)
(bat:mope letters `"bb" 2)
==
```
=> More mop functions: top, bot, and bat

ui/src/chat/ChatEmbedContent/ChatEmbedContent.tsx, ui/src/heap/HeapBlock.tsx, ui/src/heap/HeapRow.tsx
Also, don't make calls to noembed on heap items if remote content has been disabled.
No issue created for this one, just something that occurred to me this morning.
=> Prevent unnecessary calls to noembed on chat embed

ui/src/app.tsx
Simply a stop the bleeding measure until we can figure out a method that works better with ships that are under heavy load
=> app: temporarily disable disconnect checks until further work

ui/src/state/chat/chat.ts
Avoid object checking in useEffect dep array
=> Prevent excess scries for DMs on ships without DMs/MultiDMs

desk/app/groups.hoon
OTT this fixes the infinite loading in empty group state and when trying to create a group from said state, mentioned in #2023 at the end.
=> groups: fix bad logic in light groups scry

ui/src/components/Sidebar/GangItem.tsx
There isn't an issue for this afaik, but romi saw this and I've actually seen this on one of my dev moons. If something is wrong with the host ship for the group you're trying to join you could get into a state where you're just stuck with the pending group item in your sidebar.
This adds a cancel button so you can get rid of the pending group item.
=> Add cancel button for stuck group joins

talk/desk.docket-0, ui/src/app.tsx, ui/src/components/LoadingSpinner/LoadingSpinner.tsx, ui/src/components/Sidebar/Sidebar.tsx, ui/src/dms/MessagesSidebar.tsx, ui/src/groups/GroupSidebar/GroupSidebar.tsx
Relocates the reconnecting spinner to the sidebar (desktop only, mobile channel header PR forthcoming). 
At the Groups and Talk app level:
In groups of various customization:
#2077
=> groups, talk: use loading spinner in sidebar for reconnected state

ui/src/components/Mention/MentionPopup.tsx
Thought I'd knock one off instead of always logging them :)
Fixes #2020 where your DM partner was labeled "Not in message" in private DMs, and your own ship was always labeled "Not in message" or "Not in group"
=> mentions: fix dm patp marked as not in message

ui/src/logic/useChannelSort.ts, ui/src/logic/useGroupSort.ts, ui/src/logic/useSidebarSort.ts, ui/src/state/settings.ts
Fixes #2103 
Also fixes an issue where the sidebar would rerender on each update to the settings store (such as the connection checker getting called).
=> sidebar sort issues

ui/src/chat/ChatEmbedContent/SpotifyEmbed.tsx, ui/src/chat/ChatEmbedContent/YouTubeEmbed.tsx
I don't think there's an issue for it, just noticed it this morning.
=> Make sure youtube/spotify links open in new tabs

ui/src/chat/ChatContent/ChatContentImage.tsx, ui/src/chat/ChatEmbedContent/ChatEmbedContent.tsx, ui/src/chat/ChatMessage/ChatMessage.tsx, ui/src/chat/useChatStore.ts
This fixes #2112 
It turns out that chrome was forcing this content to load via HTTPS and palfun's minio instance doesn't have an HTTPS cert. When the image fails to load the height of the message changes, causing the scroller to re-render, which causes the image to load again, resulting in a loop.
To fix it we need to handle the error when the image doesn't load, store that state globally in the chat store, and display some static content in the scroller.
This also fixes an issue where we were missing a key for the list of thread reply authors in the ChatMessage component and adds a missing cleanup function to the useEffect in the ChatEmbedContent component.
=> chat: fix image flickering

ui/src/diary/DiaryChannel.tsx
Check if channel is initialized.
Also, limit total placeholder boxes to five.
Fixes #2113
=> notebooks: Don't show placeholder on empty channel

ui/src/app.tsx, ui/src/channels/ChannelHeader.tsx, ui/src/groups/GroupSidebar/MobileGroupSidebar.tsx
This makes some similar changes as #2119.
- If you're on a mobile device, as you navigate into the group, you get dropped into the Channels list. Tapping into a channel and "back out" navigates you to the group root, rather than the named `/channellist` route (in case we change this in the future).
- If you're *not* on a mobile device, as you navigate into the group, you're either navigated to the most recent channel or Activity (current behavior).
=> groups: sane intra-group nav

ui/src/app.tsx
I got sick of having to hit Groups in the nav every time I opened the app on my phone.
For `/apps/groups`:
- If you aren't in any groups, you get routed to Find Groups, no matter what kind of device you're on. This should cover the first-run/newbie case.
- If you're in at least one group and you're on a mobile device, you get routed to the list of groups you're in.
- If you're in at least one group and you're **not** on a mobile device, you get routed to Activity ("All Notifications"), since there's a list of groups within view in the sidebar. @ashelkovnykov said something about this last week/the week before.
For `/apps/groups/notifications`:
- If you aren't in any groups, you get routed to Find Groups, which theoretically prevents us from showing the empty list at all for …
=> groups: appropriate null-groups routing

ui/src/chat/ChatMessage/ChatMessageOptions.tsx
It looks like we forgot to take out the CSS hover stuff when we switched to a controlled hover state for the chat message options, so we had both the JS hover state and the CSS hover state clashing with each other. Now we just use the JS state.
Fixes #2108
Also fixes the issue where the message options wouldn't appear on first hover.
=> emoji picker: use only controlled hover, no css

desk/app/groups-ui.hoon, talk/app/talk-ui.hoon, talk/mar/dummy.hoon
This should fix the issue @patosullivan saw earlier about the missing mark. The state transition didn't work for ships who previously had the groups/talk ui agents. Too much fakezod juggling meant this didn't happen locally when I was developing it.
=> vita: account for ships with previous ~ state

ui/src/groups/useGroupJoin.ts
Fixes #2148
We used to route mobile users to the notifications screen by default when they navigated to a group, and we didn't want that to happen after a group join so we would navigate them to the channel list. Now that the channel list is the default route for a group on mobile, we don't need this special logic for group joins.
=> groups: fix route after group join on mobile.

ui/src/chat/ChatContent/ChatContent.tsx, ui/src/chat/ChatEmbedContent/ChatEmbedContent.tsx
Fixes #2146 
Passes custom content from `Link` inline story type to the embed renderer so the `<a>` tag can render it. Does not address the issue when the URL is a supported embed site, logged that separately in #2161
=> chat: show link custom content when rendering as plain link

ui/src/app.tsx, ui/src/state/settings.ts
This fixes #2159 by making sure that updates to the calm settings from groups/talk are persisted using the "garden" desk key in the settings store. 
Doing this ensures that we are actually making the setting "global". 
On initialization, groups/talk loads the settings store and merges the settings for the current desk with the landscape (garden) desk. If we have a setting for the current desk that is different than what is set for the landscape desk, we override it. Since we were updating the calm settings for *just* the groups/talk desk, it was being overridden by the landscape setting (which was `false`).
=> calm: respect calm settings for wayfinding button

ui/src/components/Grid/appmodal.tsx
Some apps (like %pals) don't explicitly set a background color and just expect the default white background color in the browser. I originally set the background color for the iframe to white using tailwind's `bg-white`, this caused the background to change to black automatically in dark mode. Apps like %pals then became unusable because they were using black text on our black background.
This change explicitly sets the background to `#fff` so that apps like %pals will render properly. Apps that set their own background (like groups or talk) will be unaffected.
=> app modal: fix dark mode issue

ui/src/components/Grid/appmodal.tsx, ui/src/components/Grid/grid.tsx, ui/src/components/Leap/useLeap.tsx
This makes some changes that ensure that the user is always redirected to the background location upon closing an AppModal (which seems more natural, less annoying than having to go back through Grid and Leap).
It does the same thing for closing Grid.
Also fixes the app links in Leap for opening a new tab for groups/talk.
=> app modal: always close to background location

ui/src/groups/GroupActions.tsx, ui/src/groups/GroupAdmin/GroupMemberManager.tsx, ui/src/groups/GroupSidebar/MobileGroupSidebar.tsx
This hides invite actions for non-admins while we figure out why invites to public groups from non-admins are failing.
=> groups: Disable invites for non-admins

ui/src/chat/ChatEmbedContent/ChatEmbedContent.tsx
Fixes #2161
If a user specifically formats some text as a link we should just show that, even if it's a link to embed-able content.
=> chat: fix for embeds overriding formatted links.

ui/src/heap/HeapDetail.tsx, ui/src/heap/HeapDetail/HeapDetailBody.tsx, ui/src/heap/HeapDetail/HeapDetailEmbed.tsx, ui/src/heap/HeapDetail/HeapDetailHeader.tsx, ui/src/heap/HeapDetail/HeapDetailSidebar/HeapComment.tsx, ui/src/heap/HeapDetail/HeapDetailSidebar/HeapCommentReactions.tsx, ui/src/heap/HeapDetail/HeapDetailSidebar/HeapDetailCommentField.tsx, ui/src/heap/HeapDetail/HeapDetailSidebar/HeapDetailComments.tsx, ui/src/heap/HeapDetail/HeapDetailSidebar/HeapDetailSidebarInfo.tsx
Cleans a bunch of things up w/r/t layout in the curio detail view.
- Stacks content and comments vertically for smaller viewports.
- Uses the window scroll in Virtuoso for smaller viewports (eliminates any scroll-within-scroll problems).
- Realigns the comment content.
- Brings the sidebar metadata up to spec (https://www.figma.com/file/sCFYLlAGjehlYXUkT2rarg/Product-Handoffs?node-id=2799-114533&t=v23dQDf7A7iGe9BC-4).
- Manually truncates the "back" button in the header to avoid the line-clamp bug which destroys the layout on smaller screenss.
https://user-images.githubusercontent.com/748181/227311717-533ee2b5-aa31-4459-b3d9-ab251ae0ec5e.mov
https://user-images.githubusercontent.com/748181/227311731-8117dbb1-c01d-466d-b540-a9d829e7ab9e.mov
=> curio: detail view fixes

ui/index.html, ui/src/app.tsx, ui/src/assets/chatmanifest.json, ui/src/assets/manifest.json, ui/src/components/Sidebar/MobileSidebar.tsx, ui/src/logic/useIsIOSSfari.ts, ui/src/logic/useIsStandaloneMode.ts
Fixes the issue where non-IOS PWAs were getting extra bottom padding, also ensure that we *always* have bottom padding on iOS PWA to avoid colliding with the home bar.
Also fixes an issue where navigating back to the "home" route would appear as navigating to an external route in the PWA (by updating manifest settings and making sure our basename in app.tsx includes a trailing slash).
=> Fix bottom spacing issues on PWAs

ui/src/groups/GroupSidebar/GroupSidebar.tsx
I don't work at night enough to notice these things, I guess.
Before:
After:
=> groups: fix group header color in dark mode

ui/src/app.tsx
Fixes #2193 by only using a trailing slash in the router basename while we're in a PWA.
Also moved previous PWA check logic into the RoutedApp component.
=> Fix trailing slash issue

ui/src/groups/GroupSidebar/GroupSidebar.tsx
All together now.
Light mode, with cover image:
Dark mode, with cover image:
Light mode, no cover image, light color:
Dark mode, no cover image, light color:
Light mode, no cover image, dark color:
Dark mode, no cover image, dark color:
=> groups: proper GroupCover text colors

talk/app/talk-ui.hoon
OTT, not handling this causes stuff like this to appear in dojo: https://pastebin.com/zAtDAL8P reported by Luke. We handled in groups but forgot to add to talk.
=> vita: missing handling root wire

ui/src/groups/GroupJoinList.tsx, ui/src/state/groups/groups.ts
This fixes #2041 (needed to specify that we were calling useGroupJoin within a modal) and another issue I found while working on that one (we weren't tracking the right subscription path, so after clicking reject it would just spin).
=> invites: fix blank screen on reject

ui/src/components/Sidebar/Sidebar.tsx, ui/src/dms/MessagesList.tsx, ui/src/dms/MessagesSidebarItem.tsx
- Addresses some misalignments in the Talk sidebar for incoming DM requests
- Addresses a misalignment in the empty Groups sidebar (first run)
- Eliminates the blue [?] box for incoming multi-DM requests
Before:
---
After:
=> groups + talk: sidebar spacing fixes

ui/src/diary/DiaryNoteOptionsDropdown.tsx
Removes disabled (planned) items in context menu and fixes the "Edit" path (we're at the notebook root here, not in the note itself).
fixes #2228
=> notebook: fix kebab menu in index list items

ui/src/groups/GroupSidebar/GroupSidebar.tsx
Hides the blue button for non-admins in secret and private groups.
We already do this in the mobile auxiliary actions sheet with the exact same logic, I think we just missed it here.
Fixes #2261
=> groups: hide 'invite people' button

ui/src/chat/ChatThread/ChatThread.tsx, ui/src/logic/usePathFromHark.ts, ui/src/notifications/Notification.tsx
fixes #2263 by opening up the thread and scrolling to the mention in question.
Also: for normal mentions (i.e., mentions in the main chat window), this routes the user to the mention within the chat window rather than prompting the user to start a new thread for the mention.
=> notifications: fix mention links

ui/src/app.tsx, ui/src/chat/ChatMessage/ChatMessage.tsx, ui/src/chat/ChatMessage/ChatMessageOptions.tsx, ui/src/chat/ChatReactions/ChatReactions.tsx, ui/src/chat/useChatStore.ts, ui/src/components/EmojiPicker.tsx, ui/src/logic/routing.ts
- Fixes the issue where the emoji picker would disappear if you hovered slightly out of/away from the chat message that spawned it by lifting hover state up into the chat store
- Adds 100px of padding on the left and the top of the emoji picker to prevent it from accidentally closing if the user hovers over another message outside of the picker.
- Fixes #2253, the issue where users on latest android couldn't use the emoji picker on mobile
=> chat: lift chat hover state to chat store, use router for emoji picker open state on mobile

ui/src/state/chat/chat.ts
This fixes #2046 by tracking the right subscription and expecting the right event shape.
=> clubs: fix "save" button stuck on loading

ui/src/heap/HeapDetail/HeapDetailEmbed.tsx
Fixes #2279 by providing a definite height/width for twitter embeds like we do in the lightbox (and which safari seems to require).
Also account for scrollable content in the heapdetail (if a user were to link to a tweet in a thread, for instance)
=> Fix twitter embeds in heap detail in safari

ui/src/groups/FindGroups.tsx, ui/src/groups/useGroupJoin.ts
Fixes #1979
Also updates the image for the hardcoded tlon local group ref on the Find Groups page with the new group image.
=> refs: hardcode tlon local ref to open to support

ui/src/components/Leap/useLeap.tsx
Currently in Leap we include ships you've DM'd with previously but aren't yet in your contact store as results. I added this a few weeks back because we had just been including contact-store ships in the results previously.
I forgot to presig the patps :( . If you were to select one of these DM-but-not-in-contact-store ships it would navigate to a blank screen. This presigs the patps and fixes that issue.
=> Add presig to non-contact-store DM ships in Leap.

ui/src/channels/ChannelHeader.tsx
OTT. Issue was caused by an errant `await` (we're already awaiting within `leave`).
=> Fix issue with leaving chat from channel header

desk/lib/diary-json.hoon, ui/src/diary/DiaryChannel.tsx, ui/src/diary/DiaryNote.tsx, ui/src/groups/Groups.tsx, ui/src/heap/HeapChannel.tsx, ui/src/logic/utils.ts, ui/src/state/base.ts, ui/src/state/chat/chat.ts, ui/src/state/contact.ts, ui/src/state/diary/diary.ts, ui/src/state/diary/notes.ts, ui/src/state/groups/groups.ts, ui/src/state/heap/curios.ts, ui/src/state/heap/heap.ts, ui/src/state/settings.ts, ui/src/state/storage/storage.ts
There were multiple issues here. First of all outlines and notes were missing the type property which is what we were using to differentiate between the two. Second of all, we were persisting our rich map types, but those weren't rehydrating when the app opens so we weren't actually getting any benefit from those. 
The main issue though was that the initialize call was not gated anymore because we were implicitly using the "is subbed" flag previously to also prevent subsequent initializations. However to work with the new reconnect behavior we needed allow it to be called multiple times. So to stabilize it, I've made it check to see if it already has all the new values and if it does it simply doesn't update the map and therefore won't trigger new renders.
Also I found a huge source of …
=> diary/heap: fix initialization and stabilize refs

ui/src/state/hark.ts
We were using 'undefined' in cases where we weren't fetching skeins for a whole desk, just a group. We should just use the desk name.
We also weren't invalidating/cancelling existing skeins queries for groups.
The first issue may have been causing some weird behavior, the second issue definitely prevented a user from marking all groups activity updates as read.
Should fix #2320
=> skeins: Use appropriate queryKeys

talk/mar/ui/init.hoon
While building the marks for the new UI init scries I forgot to change the ship gate which oddly converts patps without the sig. Because this didn't error since it's in `enjs:format` I didn't realize, and previous DMs still showed up so everything looked fine. Possibly the cause of #2235 and maybe also Jack's issue in the support email?
=> chat: restore missing DM invites

ui/src/state/groups/groups.ts
PR #2308 fixed some issues around leaves/joins,
This fixes some remaining issues by invalidating the gang-preview associated with the group and properly removing the query for the group from the cache (the queryKey was ['group', flag], should have been ['groups', flag]).
Should fix #2322.
=> groups: properly remove left groups

desk/app/chat.hoon, desk/lib/chat-json.hoon, desk/mar/club/action-0.hoon, ui/src/state/chat/chat.ts
OTT, this helps old clients stay functional by keeping `club-action` using `echo` and we switch new clients to `club-action-0` only for sending. This does introduce somewhat of an asymmetry with the marks since `club-action-0` is only used for clients, and when `club-action` gets encoded to json it uses `uid` not `echo`. However everything still works with just this change so I'd prefer to not alter things further.
=> chat: switch to club-action-0 for backwards compat with old clients

ui/src/app.tsx, ui/src/components/UpdateNotice.tsx, ui/src/main.tsx
Should fix #2328 by only requiring you to interact once. This changes the behavior so that we only look for service worker updates which should indicate that the app has updated. The language also now reflects more clearly that you need to click update and can't just reload.
=> app: better update banners

ui/src/logic/utils.ts
Switches to usehooks-ts's useCopyToClipboard copy function rather than our own writeText function (which didn't account for safari weirdness) within our useCopy hook.
Fixes #2346
Fixes #1767
=> bugfix: Fix copy to clipboard in safari.

ui/src/components/ShipSelector.tsx, ui/src/dms/DmInviteDialog.tsx, ui/src/groups/GroupInviteDialog.tsx
react-select's built in 'menuPortal' feature somehow prevented the user from being able to click on items in the menu.
I added the menuPortal changes because the menu's opening would cause the dialogs containing the ShipSelector to move, causing the ShipSelector itself to move out of view.
Rather than use the menuPortal feature, we can just add bottom margin to the dialog container. This fixes both issues.
Fixes #2341
=> bugfix: Fix for clicking on names in ship ShipSelector

ui/src/heap/HeapDetail.tsx
A previous change to heap detail styles made it so that the div containing the CaretRightIcon/previous button was occluding the send button in heap detail. The div containing the left/right carets (next/prev buttons) should have had group and relative classes in order for the child divs to render/behave properly, i.e., set opacity to 100 on hover and appear on the sides of the HeapDetailBody (and not occlude the items on the far left of the screen, including the send button).
Fixes #2342
=> bugfix: make send button in heap detail clickable

ui/src/groups/Groups.tsx, ui/src/logic/useReactQueryScry.ts, ui/src/logic/useReactQuerySubscription.tsx, ui/src/state/bootstrap.ts, ui/src/state/chat/chat.ts, ui/src/state/groups/groups.ts, ui/src/state/hark.ts, ui/src/state/scheduler.ts, ui/src/state/settings.ts
This PR addresses some issues around reconnecting seen recently where things get locked up or take too long. Turns out we were doing too much here. React query handles a lot of this for us. However, because we do some of the work in the `init` scry we should turn off reconnect handling for queries updated by that.
Also when reconnecting we have a possibility of getting a large number of facts in a row. With the subscription handling as written this would cause an enormous amount of scries to happen. To combat this the subscription handling will now use a debounce that fires both on the leading and trailing edge so we get immediate response, but if a lot more is happening they all get delayed until the final call.
=> groups: reconnect and perf

ui/package-lock.json, ui/package.json, ui/src/logic/utils.ts
The regex we were using before didn't account for Emoji ZWJ sequences (more detail on those here: https://emojipedia.org/emoji-zwj-sequence/), so there were some cases where a single emoji would not render in the scroller with the appropriate large font size.
I added the emoji-regex package which accounts for every type of emoji or emoji sequence. I also used lodash's `split` function to ensure that the message contains just a single rendered emoji (which the split function itself will detect as one element in the string, not multiple, even if it's actually a sequence, a feature added in lodash 4.9.0).
=> bugfix: properly detect all emojis

ui/src/components/ImageURLUploadField.tsx
We weren't setting unique keys for useUploader in ImageURLUploadField.
Fixes #1880
=> bugfix: fix image uploads in profile edit view

ui/src/components/References/GroupReference.tsx
Fixes #2218, we clamp the lines that could wrap to one line.
=> bugfix: don't allow text to wrap on group refs

ui/src/components/SettingDropdown.tsx, ui/src/components/SettingsDialog.tsx, ui/src/state/settings.ts
this was branched off of master, with the changes from #2377 cherry-picked onto it.
This PR allows us to set the landscape (garden) desk settings as default by using useMergedSettings().
If a user already has a setting set in %garden, it will be honored in groups/talk until the user overrides it.
This also adds a dropdown to set the theme (auto, light, dark).
https://user-images.githubusercontent.com/1221094/234275998-7824e33b-9bb4-46ee-9530-6d15ebe3c4e0.mov
=> settings: use landscape settings by default

desk/app/grouper.hoon, ui/src/groups/GroupAdmin/GroupInfoEditor.tsx, ui/src/groups/GroupInviteDialog.tsx
This fixes the lure invites for private/secret groups. We should likely change the flow of invites so that they all flow through the group-invite mark instead of forcing people to know about the cordon add-ships stuff. Also re-enables lure on the frontend.
Also adds resubscribing to reel in case it gets dropped.
=> grouper: use add-ships for shut cordon

.github/helpers/deploy.sh
I think something changed in the develop branch of urbit/urbit which triggered our issue. This should ensure we pull only from stable releases fixes #2392 hopefully.
=> ops: ensure we pull from master

ui/package-lock.json, ui/package.json, ui/src/api.ts, ui/src/groups/GroupAdmin/GroupInfoEditor.tsx, ui/src/state/groups/groups.ts
This fixes a latent race condition in @urbit/http-api that causes an error when `subscribeOnce` tries to unsubscribe because the fact came in too quickly. This also fixes our group mutations so that they all use the same key and adjusts the validator for the edit group mutation so that it actually looks for the correct status.
=> groups: fix group editing

ui/src/state/chat/chat.ts
Fixes #2375 
Updates the `delMessage` handler to allow for deleting messages from multi-party DMs
=> chat: fix handler for deleting club messages

ui/src/chat/ChatMessage/ChatMessage.tsx
Fixes #1868 by sorting replies by time client-side.
=> bugfix: use correct lastReply for chat reply time

ui/src/chat/ChatMessage/ChatMessage.tsx
We need to check whether the message we're rendering is a thread OP and not allow for it to display message options unless it's being rendered in the main chat scroller, otherwise ChatMessageOptions renders twice and the user won't be able to react to the message.
Fixes #2383
=> bugfix: no duplicate message options on thread OPs

.github/workflows/deploy-groups.yml, .github/workflows/deploy-talk.yml
This PR updates our base deploy workflows to improve organization and maintainability.
This new approach splits the existing single-job workflows into three separate jobs `build-frontend`, `glob`, and `deploy`. This change provides better separation of concerns and makes it easier to understand the purpose of each job.
Right now this doesn't get us much other than better organization and maintainability, but in the future we could run jobs in parallel (one workflow for both talk and groups deploys, or other future apps) or introduce better error handling based on job failures.
Key changes in this PR:
- Extracted build-frontend job to handle frontend building steps for both deploy-talk and deploy-groups.
- Created a separate glob job for generating and committing glob files.
- Updated the …
=> ops: split deploy workflow steps into jobs

.github/workflows/deploy-groups.yml, .github/workflows/deploy-talk.yml
Avoids uploading JS source and node modules to github artifacts.
=> ops: upload only necessary files to artifacts

.github/workflows/deploy-groups.yml, .github/workflows/deploy-talk.yml
Those were unnecessary (and invalid in that context)
=> ops: remove working-directory keys from uploads

ui/src/state/chat/chat.ts
This PR modifies the useWritByFlagAndWritId to first check to see if we already have the writ loaded in local state (within a pact) before calling subscribeOnce to fetch the writ.
May fix #2196, will definitely make the writ references load faster throughout the app.
=> refs: use writs from pacts before calling subscribeOnce

ui/src/heap/HeapBlock.tsx
Fixes #2376 by skipping the loading indicator if remote content is disabled.
Also renames/refactors "notEmbed" to "maybeEmbed" for better readability.
=> gallery: don't show loading indicator if remote content is disabled.

ui/src/app.tsx, ui/src/dms/Dm.tsx, ui/src/dms/MessagesSidebar.tsx, ui/src/dms/MultiDm.tsx, ui/src/logic/useMessageSelector.ts
This fixes #1883 by only allowing the message selector to handle navigation if we're within a 'new' route (i.e., `/dms/new/~finned-palmer` or `/dms/new/0v4.00000.qcmja.49khd.1pb08.64jei`), allowing the user to navigate between normal dm routes and the new dm they're constructing without an issue.
Also updates Dm and MultiDm components to only show selecting-related components if that dm/multiDm itself is the one currently selected by useMessageSelector.
=> bugfix: message selector aggressively rerouting

ui/src/notifications/GroupNotification.tsx
tlon.network implemented a content security policy that did not allow for setting a base64 string as a src on an image, this caused the groups icon to look broken on notifications on tlon hosted ships.
=> fix for group icon svg that wasn't compliant with CSP on tlon.network

ui/src/chat/useChatStore.ts, ui/src/state/chat/chat.ts
This PR optimizes initialization by reducing the time taken to iterate over the briefs map and update the state in ChatStore.
I replaced the forEach with a filter/map, which should be more performant.
I also added a new batchUnread action to the ChatStore that uses produce() to update unread state in one shot, rather than calling unread on each unread brief.
This particular issue effected ships that were subscribed to a lot of channels, so it wasn't easily caught in development where we use fakezods and dev moons. On my personal ship, this saved about 15 seconds of loading time for the initial data.
=> Optimize unread initialization

desk/app/groups.hoon, ui/src/groups/ChannelsList/ChannelsList.tsx
Fixes #2226 by filtering the channels passed to `join-channels` on the backend to those the user actually has read-access to. Also fixes ChannelList so that it doesn't display channels a user can't read.
=> groups: respect permissions before auto join

ui/src/components/References/ReferenceBar.tsx
Fixes #2433 
Removes `max-width` property on reference bar that was keeping it from filling up the same width as the reference content
=> fix max-width on reference bar

native-android/package-lock.json, native-android/package.json, native-android/src/App.tsx, native-android/src/Login.tsx, native-android/src/lib/notifications.ts, native-android/src/state/store.ts, native-android/tailwind.css, native-android/tailwind.json
- Fixes React version peer dependency mismatch
- Fixes broken `lint:format` command because of missing package
- Fixes `api` helper not being initialized upon login
- Refactors state management and flow for login and returning to app on relaunch
I discovered that the `api` helper was only being initialized when you relaunched the app from storage, it was not initialized after manual login so the push notification registration request wasn't being sent through. I ended up doing a major refactor of the state management to make it a bit simpler, particularly around only allowing one ship at a time to be configured.
=> android: fix login state mgmt and api init

ui/src/logic/useGroupPrivacy.ts, ui/src/state/groups/groups.ts
Fixes #2478
We weren't properly checking the privacy of groups returned from the group index. useGroupPrivacy defaulted to `public` if we didn't have group or gang data for a particular flag, which means that we didn't show the accurate privacy setting for groups we only knew of via group index (i.e., groups we had found by searching for a ship in Find Groups).
This PR updates useGangs so that it will insert gang indexes into the cached gangs data. Also fixes an issue we had with usePendingGangs and usePendingGangsWithoutClaim returning gangs without an invite key at all.
=> groups: fix issue with private groups in find groups

ui/src/app.tsx, ui/src/components/Grid/grid.tsx
Fixes #2483
Settings store may send us a tile order including a desk name that we don't have a charge for. We need to filter these desk names out by checking against the charges we actually have.
Also fixed an issue with the SuspendedModal fallback component looking weird since it was still using DialogContent.
=> leap: only show tiles we have charges for

ui/src/app.tsx, ui/src/chat/ChatInput/__snapshots__/ChatInput.test.tsx.snap, ui/src/chat/ChatMessage/ChatMessage.test.tsx, ui/src/chat/ChatMessage/ChatMessage.tsx, ui/src/chat/ChatMessage/ChatMessageOptions.tsx, ui/src/chat/ChatMessage/__snapshots__/ChatMessage.test.tsx.snap, ui/src/components/EmojiPicker.tsx, ui/src/components/Layout/__snapshots__/Layout.test.tsx.snap, ui/src/components/Sidebar/Sidebar.test.tsx, ui/src/components/Sidebar/__snapshots__/Sidebar.test.tsx.snap, ui/src/groups/ChannelsList/ChannelsList.tsx, ui/src/groups/GangPreview/__snapshots__/GangPreview.test.tsx.snap, ui/src/groups/GroupSidebar/__snapshots__/ChannelList.test.tsx.snap, ui/src/mocks/chat.ts
Fixes #2445 by accounting for routing to the emoji picker from within a thread on mobile.
Also adds some RTL tests around ChatMessageOptions. Attempted to test for showing/hiding the emoji picker itself, but it ended up being a rabbit hole. Going to attempt to write those tests using playwright in another PR.
=> emojis: fix route issue on mobile

ui/src/components/References/BaitReference.tsx, ui/src/components/References/ContentReference.tsx, ui/src/components/References/NoteReference.tsx, ui/src/diary/DiaryContent/DiaryContent.tsx, ui/src/logic/utils.ts
Fixes #2230
This PR updates the NoteReference component to use DiaryContent to render a truncated version of the content of a note, including formatting and block content.
=> bugfix: properly render note references

ui/src/chat/ChatInput/__snapshots__/ChatInput.test.tsx.snap, ui/src/chat/ChatMessage/__snapshots__/ChatMessage.test.tsx.snap, ui/src/components/Layout/__snapshots__/Layout.test.tsx.snap, ui/src/components/References/NoteReference.tsx, ui/src/components/Sidebar/__snapshots__/Sidebar.test.tsx.snap, ui/src/groups/GangPreview/__snapshots__/GangPreview.test.tsx.snap, ui/src/groups/GroupSidebar/__snapshots__/ChannelList.test.tsx.snap, ui/src/logic/utils.ts
This fixes several issues with the new note references:
1) node types can be nested, so we need to ensure that we are truncating an actual string before calling slice. 
2) list items need to be truncated.
3) `not-prose` class should not be used on the NoteReference container as this will cause weird issues with the way we render the note (also...it is prose).
=> note reference cleanup

ui/e2e/auth.setup.ts
We need to make sure the tiles actually load on landscape, this seems like a good place to do that. 
Note that this will only tell us if landscape/garden is working *with the version installed on the fake ships*, which is not updated before running this test. Also note that landscape/garden lives in a different repo, so I'm not sure how we want to handle copying/building landscape on these fake ships.
cc @jamesacklin
=> tests: check for tiles after login in auth setup

ui/src/profiles/FavoriteGroup.tsx, ui/src/state/groups/groups.ts
Resolves #2457 
Loads favorite Group metadata using gang preview if Group data is not present
=> chat: load favorite groups preview data when not available

ui/src/chat/ChatMessage/ChatMessage.tsx, ui/src/chat/ChatScroller/ChatScroller.tsx, ui/src/components/EmojiPicker.tsx
Fixes #2489 by removing the extra top padding around the picker.
I added the top padding in an attempt to prevent the picker from disappearing when a user accidentally moved their mouse above the picker while the picker was rendered *above* the message they are trying to react to, but didn't account for the fact that the picker sometimes renders below the message. When it appears below the message, this extra padding just pushes the picker too far and allows for a user to hover over another message and thus closes the picker.
=> emojis: fix issue when picker appears below message

ui/src/channels/EditChannelForm.tsx, ui/src/channels/NewChannel/NewChannelForm.tsx, ui/src/groups/ChannelsList/ChannelPermsSelector.tsx, ui/src/logic/utils.ts, ui/src/types/groups.ts
Fixes #2499
Also removes the "Members can read only" privacy type and sets the equivalent of that as the default when selecting "Custom" (user can then add/remove roles from that as necessary).
=> roles: Fake out the "members" role on the frontend for channel perms

ui/src/chat/ChatContent/ChatContent.tsx, ui/src/styles/base.css
Resolves #2429 
Streamlines the text selection and code block background colors for both light and dark mode to enable the following:
- Code block background colors are not the same color as the on-hover message state
- Selection color is not the same color as code block background color
This enables visible selection in code blocks for both light and dark modes:
https://github.com/tloncorp/landscape-apps/assets/1013230/7c94358c-5250-4628-a9fb-b656a0ca8de8
=> chat: streamline text selection colors; fix code block selection

ui/src/channels/EditChannelForm.tsx
Fixes #2511 by ensuring that we remove all sects from channel writer perms if "members" are allowed to write to a channel (e.g., putting us back in to "Open to All").
=> roles: fix issue with 'members' in channel writers

ui/src/chat/ChatInput/ChatInput.tsx
Not clear why this isn't always triggered on desktop, but adding `chatInfo.blocks` to the dependency array for the onSubmit useCallback was causing the ChatInput to lose focus after send on mobile after every message. I changed the dependency to `chatInfo.blocks.length` and that seems to have solved it. I also cleaned up the if statements at the top of onSubmit.
Fixes #2506
=> chat input: fix focus loss on mobile.

desk/app/chat.hoon
When receiving a dm the `wire` in `+di-agent` (`app/chat.hoon`) is `/hark`.  When sending a dm the `wire` is `/proxy`.  You can see there were two `[%proxy ~]` cases in the `?+` when one of them should have been `[%hark ~]`.  (Shouldn't the compiler detect this?)
I tested this with a recent _released_ version of `%groups` (`fu6ca`), not the `HEAD` of the repository.  I wasn't able to `npm install` in `ui/`.
```
$ npm install
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: landscape-apps@2.3.2
npm ERR! notsup Not compatible with your version of node/npm: landscape-apps@2.3.2
npm ERR! notsup Required: {"node":"16.19.1","npm":"8.19.3"}
npm ERR! notsup Actual:   {"npm":"9.6.4","node":"v20.0.0"}
```
This addresses …
=> chat: fix duplicate %proxy cases in +di-agent

desk/app/heap.hoon
Fixes #1872 by making sure that we emit a yarn in this particular instance. They would receive notifications if they were to follow up to the comment, but they weren't getting notified on the initial comment because their patp wasn't in the replies. Now they'll always be notified on any comment on their heap posts.
One question for @arthyn about why it's necessary to return he-core twice for this to compile.
=> heap: fix for authors not receiving notifications for comments

.github/workflows/deploy-canary-groups.yml, .github/workflows/deploy-canary-talk.yml, .github/workflows/deploy-external-groups.yml, .github/workflows/deploy-external-talk.yml, .github/workflows/deploy-groups.yml, .github/workflows/deploy-internal-groups.yml, .github/workflows/deploy-internal-talk.yml, .github/workflows/deploy-livenet-groups.yml, .github/workflows/deploy-livenet-talk.yml, .github/workflows/deploy-talk.yml
We're not using the janeway service account anymore, so this changes out the references to be more generic.
=> update workflows to not reference janeway

native-android/src/lib/notifications.ts
Resolves #2521 
Removes the "You have received a new message" notification and simply skips the local notification send if the notification contents could not be retrieved (i.e., yarn details scry fails)
=> android: skip local notification when yarn contents scry fails

desk/app/groups.hoon, desk/mar/hi-ship.hoon, ui/src/channels/EditChannelForm.tsx, ui/src/components/Sidebar/GroupListPlaceholder.tsx, ui/src/groups/GroupSidebar/ChannelList.test.tsx, ui/src/groups/GroupSidebar/ChannelList.tsx, ui/src/groups/Groups.tsx, ui/src/state/groups/groups.ts
fixes #2414
looks like this:
I added a new subscription path just for `hi`ing a ship, returns the ship name if it's successful, also added some UI state around disconnected ships (using zustand on the frontend).
=> groups: add "host offline" state

ui/src/channels/ChannelHeader.tsx, ui/src/channels/EditChannelForm.tsx, ui/src/channels/NewChannel/NewChannelForm.tsx
This fixes #2476 by surfacing up channel descriptions in the channel headers and the new/edit channel forms.
=> groups: add channel descriptions

ui/src/diary/DiaryContent/DiaryContent.tsx, ui/src/logic/utils.ts
This fixes #2526 by preventing refs from being rendered within a notebook reference, also: 
- fixes some issues around the way we were calculating remainingChars (it was getting reset early)
-  limits the number of images that can be rendered in a ref (to one) 
- handles header text (which users can apparently add by pasting in content from somewhere else, this is not available directly in our UI)
- adds an ellipsis to the last inline string in the truncated text
- fixes the "missing keys in list" issue in DiaryContent.
You can test this by making some fake notes with lots of text, images, references, etc., and then embedding it as a reference somewhere.
=> notebook refs: more fixes

ui/src/components/EmojiPicker.tsx
Resolves https://github.com/tloncorp/talk-android/issues/7
Uses value from `useCurrentTheme` hook to set the emoji picker's theme
=> set emoji picker theme based on current theme

desk/lib/curios.hoon, desk/lib/dm.hoon, desk/lib/notes.hoon, desk/lib/quips.hoon
This addresses #2544 by ensuring we have unique timestamps and we're not overriding previous messages.
=> channels: make sure we use unique timestamps

ui/src/dms/Dm.tsx, ui/src/dms/MultiDMPendingIndicator.tsx, ui/src/dms/MultiDm.tsx, ui/src/dms/MultiDmHero.tsx
Unifies the Talk headers to match what I did in #2543.
Also (finally) lists the ships that are pending in a club behind the blue "Pending" label.
=> talk: unify DM and club headers

desk/app/notify.hoon
We were unnecessarily encoding params before creating a base64 string to use as a signature to post to twilio. This didn't matter in the past because the device IDs sent by apple devices didn't include any special characters. Android device IDs include a colon, and the url encoding was replacing the `:` character, which caused the signature created by using `data` to not match the one twilio expected.
=> notify: fix issue with encoded params in post to twilio

ui/src/chat/ChatMessage/Author.tsx, ui/src/components/RoleBadges.tsx
Adds visible role badges to the Author component. Ignores 'member' and overflows 3+ roles with a tooltip.
=> groups: adds role badges to Author component

ui/src/state/diary/diary.ts
Fixes crash when someone shares a diary reference to a group you don't have access to. `data` is `null` in this case, so `data === undefined` doesn't catch it
=> chat: fix crash on private group diary references

ui/src/app.tsx, ui/src/components/Leap/MenuOptions.tsx, ui/src/components/ShipSelector.tsx, ui/src/components/Sidebar/ActivityIndicator.tsx, ui/src/components/Sidebar/Sidebar.tsx, ui/src/components/Sidebar/__snapshots__/Sidebar.test.tsx.snap, ui/src/groups/FindGroups.tsx, ui/src/groups/GroupSidebar/GroupSidebar.tsx, ui/src/groups/GroupSidebar/MobileGroupSidebar.tsx, ui/src/notifications/Notification.tsx, ui/src/notifications/Notifications.tsx, ui/src/profiles/EditProfile/ProfileFields.tsx
- Fixes #2554 by adjusting the in-group Activity feed to include the group summary, description, and an edit info button for admins. Also brings the notification list up to current design spec.
- Fixes #1369 by setting a height to the profile bio field somewhere around the max character count (1000).
- Fixes #2276 in Discover (ne Find) by adjusting the not-found error message and adding syntactic samples to the helper text above the field.
- Fixes an untracked bug brought about by #2492 where the Group Info nav item on mobile would not pop the group info dialog.
Preview of the group home for an admin (members don't see the "Edit Group Info" button):
---
Fixes LAND-235
Fixes LAND-277
=> groups: add group home, assorted fixes

ui/src/diary/DiaryChannel.tsx
Fixes behavior seen in the video of an infinite loop while marking a notebook as read due to non-memoized `markRead` function triggering the `useDismissChannelNotifications` hook on every re-render
https://github.com/tloncorp/landscape-apps/assets/1013230/99ce499a-033d-4dd8-89b4-61d923775beb
Fixes LAND-556
=> groups: fix infinite loop when marking diary as read

desk/app/groups.hoon
We were still sending the old URL in the notification.
Fixes LAND-477
=> Fix link to members view in join notification

ui/src/state/diary/diary.ts
fixes LAND-544
We were inserting a letter rather than an outline into the cache, so if we attempted to load from the cache before the update came back from the backend we wouldn't have quips. Fixes other type issues around letter vs outline.
=> fix missing quips issue

ui/src/chat/ChatScroller/ChatScroller.tsx, ui/src/state/base.ts, ui/src/state/chat/chat.ts, ui/src/state/chat/type.ts, ui/src/state/chat/writs.ts
This fixes issues seen in recent updates that prevent reacts from showing up or being deleted until refresh. This seems to also improve the performance of sending/receiving chats based on the `ChatScroller` changes.
Fixes LAND-585
=> chat: fix reaction/deletion updates

ui/src/diary/diary-add-note.tsx
The useEffect we were using to load initial text into the note was overriding the user's ability to clear out all of the note text. This PR adds some local state to prevent that from happening. Also switches to using tiptap's isEmpty property to check if the notebook is empty, rather than checking for an empty string, which is what tiptap's docs suggest.
Fixes LAND-591
=> diary: fix issue with clearing all note text

ui/src/notifications/Notifications.tsx
Apparently the `meta` property returned on a Group from useGroups could be undefined in some cases.
Fixes LAND-601
=> groups: fix cannot read properties of undefined (title) issue

ui/src/main.tsx
Added the buster param to PersistQueryClientProvider, if any client doesn't have `${window.our}-landscape-4.0.1` as their buster string their cache will be cleared. Will fix the bad notebook cache issue.
=> fix bad cache issue with buster param

ui/tailwind.config.js
=> notebooks: make links blue and underlined

ui/src/components/SettingsDialog.tsx
Fixes typo in settings dialog that said "helper menu menu"
=> fix simple typo in settings dialog text

ui/src/state/diary/diary.ts
fixes LAND-604
This PR fixes an issue where if a user were to create a new note and then attempt to navigate back to the notebook before the note was saved, they would get an error about quipCount being an invalid integer (or similar).
This was happening because we weren't properly inserting an outline into the cache optimistically (data had the wrong shape).
It wasn't noticed on the last pass of this code because the cached outline would get replaced by the real one when the mutation was completed (fact comes back and we refetch).
Note that while this will allow for the outline to be displayed in the notebook itself, if the user were to then try to *immediately* visit the note they just added (before the fact returns on the subscription), they won't be able to since the time we used to …
=> notebooks: fix caching edge case for saving a new note

ui/src/diary/DiaryCiteNode.tsx, ui/src/diary/DiaryImageNode.tsx, ui/src/diary/DiaryInlineEditor.tsx, ui/src/diary/PrismCodeBlock.tsx, ui/src/diary/plugins/actionmenu.tsx
- fixes LAND-389 with consistent "Remove" buttons for all blocks
- fixes LAND-599 by making sure we always have a cursor available after inserting a block (i.e., after the code block in particular), and making sure the image block replaces the current empty block.
- Some more style fixes (language selector dropdown in code blocks matches our other dropdowns).
=> notebooks: more block content fixes

ui/src/components/PalIcon.tsx, ui/src/profiles/ProfileModal.tsx
Includes the same `PalIcon` that's displayed in chat, and includes add/remove pal buttons if pals is installed.
Putting it by the rest of the actions felt most natural. The "remove" action gets a light red color because it's destructive. But I'm open to other options. Maybe we want a gray "Remove Pal..." instead that asks for confirmation?
I suspect we may find the color in these elements clashing with the customization in the profile modal. Maybe it's fine? Maybe it's not?
(Targeting #2665 because this builds on top of that, but once that merges we can just target develop as normal.)
=> profiles: include pals icon & actions in modal

ui/src/state/chat/chat.ts, ui/src/state/chat/writs.ts
At the point at which we create a new dm, a writWindow does not yet exist in state. In that case, we can just show the writs we have.
Fixes LAND-630.
I could not repro the DM not appearing in the sidebar, but it would be a separate issue afaict.
=> dms: fix empty scroller on new DMs

ui/src/app.tsx, ui/src/components/LandscapeWayfinding.tsx, ui/src/groups/PrivacyNotice.tsx, ui/src/state/settings.ts
Adds a deep explainer for our PostHog analytics. This is a generally triggerable modal so we can use it in whatever context we need; at the moment, I threw a simple trigger in the "?" wayfinding menu.
This isn't the option itself, which we'll need to add to App Settings - this is just to explain the what and why.
fixes LAND-552
=> groups: add privacy notice

talk/desk.docket-0, ui/src/profiles/ProfileModal.tsx
The conditional for this was implemented incorrectly. Additionally, the styling would not account for it.
Alongside the fix, we refactor the `!contacts` branch into a single main rendering branch, within which we check that condition to decide whether to include a component. Doing so prevents us from duplicating the now slightly more complex button rendering logic, and will make additions and modifications easier going forward.
This seems to behave correctly now, but please scrutinize closely. This is the best factoring I could come up with, but maybe it was deliberately not done like this initially.
Fixes LAND-643.
=> profiles: hide pals action if not installed

ui/src/logic/analytics.ts
I though that opt-ins were more session based, but they are persistent and also span the origin. So that means that the talk check that I moved was incorrect and needed to stay since once you're cookied the captures will fire no matter what. 
In addition I've made some attempts at limiting the URL properties that get sent, it seems to be working, but I'm unsure if it was the `unset` or the `setOnce` that did it. Either way we seem to properly hide that information now.
=> analytics: limit capturing even further

ui/src/components/References/BaitReference.tsx, ui/src/components/References/ContentReference.tsx, ui/src/components/References/CurioReference.tsx, ui/src/components/References/GroupReference.tsx, ui/src/components/References/NoteCommentReference.tsx, ui/src/components/References/NoteReference.tsx, ui/src/components/References/ReferenceInHeap.tsx, ui/src/components/References/WritBaitReference.tsx, ui/src/components/References/WritBaseReference.tsx, ui/src/components/References/WritChanReference.tsx, ui/src/heap/HeapBlock.tsx, ui/src/heap/HeapContent.tsx, ui/src/heap/HeapDetail.tsx, ui/src/heap/HeapDetail/HeapDetailBody.tsx, ui/src/heap/HeapLoadingBlock.tsx, ui/src/heap/HeapRow.tsx, ui/src/styles/components.css, ui/tailwind.config.js
- Adds a gradient mask to text HeapBlock items
- Reformats the attribution row to HeapBlock items to show poster (sigil), time, and comment count
- Refactors the HeapRow component to behave more like the HeapBlock and brings into alignment with design
- Adds a `contextApp` prop and `children` to all content references in order to:
- Reformat group references to conform with LAND-366 in both Block and List views
- Reformat all other references to match in both Block and List views
- Add isomorphic curio reference rendering to Gallery (the source and destination presentation appear the same in the Block and List views; click through to see reference in situ)
Fixes LAND-366
Fixes LAND-387
=> gallery: generalized cleanup, better refs

ui/src/components/Sidebar/Sidebar.tsx
This avoids confusion around Find Groups vs Discovery for new users.
Resolves GRO-591
=> ui: align naming for smoother onboarding

ui/src/chat/ChatMessage/ChatMessageOptions.tsx
Fixes LAND-644
Ensures the react/thread/etc. menu is always visible if a message extends off the screen.
https://github.com/tloncorp/landscape-apps/assets/90741358/5068ffc1-2dc1-45d9-952b-a1de728ba8ff
=> groups/chat: show message options when content is larger than screen height

ui/src/components/References/GroupReference.tsx
Also cleans up the layout of group references. Group refs now appear at 100% width in Notebook cite nodes and are capped at 600px wide in Chat messages. The appearances in Gallery views are unchanged.
Fixes LAND-658
=> groups: remove description from group refs

desk/app/chat.hoon, desk/app/diary.hoon, desk/app/groups.hoon, desk/app/heap.hoon
fixes LAND-671
Prevents anyone other than ourselves or a group host from joining our ship to a channel.
=> groups: only allow self or host to join a channel

ui/src/components/References/GroupReference.tsx
=> gallery: fixes squished groupref images in block view

desk/app/chat.hoon, desk/app/diary.hoon, desk/app/groups.hoon, desk/app/heap.hoon, desk/lib/dm.hoon, desk/mar/group/action-2.hoon, desk/mar/group/action-3.hoon, desk/mar/group/init-2.hoon, desk/mar/group/init-3.hoon, desk/mar/group/log-2.hoon, desk/mar/group/log-3.hoon, desk/mar/group/update-2.hoon, desk/mar/group/update-3.hoon, desk/sur/groups.hoon, ui/src/mocks/handlers.ts, ui/src/state/groups/groups.ts
We weren't checking whether or not a channel existed before scrying so this caused any updates that deleted roles to crash, causing a kick-resubscribe loop. This should fix the resubscribe loop for those who are receiving updates.  
Fixes LAND-675
=> groups: use existence checks to ensure we can scry

ui/src/app.tsx, ui/src/components/Sidebar/GroupsSidebarItem.tsx, ui/src/groups/autoJoinLureInvites.tsx
Our sidebar items were using useGroup rather than useGroups, and there were some situations where data did not exist for useGroup that did exist in useGroups. I'm not certain, but I think this may fix LAND-650. Either way, this implementation makes more sense.
=> groups: use useGroups in sidebar rather than useGroup

ui/src/diary/DiaryMarkdownEditor.tsx, ui/src/state/settings.ts
This updates the conditions for hydrating the markdown editor which fixes an issue where if the user started writing a new note using tiptap and then switched to markdown they wouldn't see anything in the markdown editor.
Also fixes another issue in a settings.ts hook where we attempted to parse diary.settings when it didn't exist because we didn't need to check that before (if we didn't have a diary key in settings before, we would just early return, if we did then we assumed we had the settings key within it, now there can be cases where wee don't have the settings key because we can have {diary: { markdown: true }}, which exists outside of the per-notebook {diary: {settings: ['flag', 'settingName', 'value']}} structure).
=> notebooks: fix two issues from markdown work

desk/app/groups.hoon
Fixes the primary issue with LAND-700 by preventing us from crashing on missing data.
Fixes LAND-700
=> groups: don't crash on missing data

ui/src/chat/ChatThread/ChatThread.tsx
Fixes LAND-682
We were previously initializing chat threads by calling `useChatState().initialize()`. This wasn't an issue if
a) you clicked into the thread on desktop, so we already loaded the relevant messages b) you navigated to it directly on mobile (via notification or similar) and the thread happened to be included in the first 50 messages in the channel
It *was* an issue if you navigated to the thread directly on mobile and the thread wasn't included in the initial 50 messages.
We actually need to fetch the messages around the thread parent ID to initialize the channel in that instance.
=> chat: fix issue with loading old threads on mobile

ui/src/chat/ChatMessage/ChatMessage.test.tsx, ui/src/chat/ChatMessage/__snapshots__/ChatMessage.test.tsx.snap, ui/src/diary/DiaryMarkdownEditor.tsx, ui/src/diary/diary-add-note.tsx, ui/src/diary/schema.ts
Fixes all issues in LAND-707, also fixes an issue with navigating back from a new note to the notebook and issues with jest tests failing around posthog imports.
The react suspense/lazy routing thing I mentioned in standup was a red herring, the issue was actually caused by a bad schema spec (and somehow we only hit this error in safari, which is odd).
=> notebooks: various fixes (and fix tests)

desk/app/groups-ui.hoon, desk/app/groups.hoon
This makes sure we ignore invalid sects attempting to be added to someone. Also makes sure we accept fleet adds from the host even if they aren't in our pending state and makes sure we save activity modal state.
=> groups: no-op on invalid sect adds 

ui/package-lock.json, ui/package.json, ui/src/app.tsx, ui/src/components/SettingsDialog.tsx, ui/src/state/settings.ts
This PR stores a persistent UUID in the ship's setting store for use with posthog (we generate the UUID client-side and then store it, we can't grab the user's existing posthog ID AFAICT).
It also gives the user the ability to manually reset the UUID via a button in the Settings modal.
The latter looks like this:
https://github.com/tloncorp/landscape-apps/assets/1221094/bb472c97-14b0-4c2c-9c1e-50529beb348b
=> posthog: use persistent anonymous UUID

ui/src/logic/utils.test.ts, ui/src/logic/utils.ts
Currently if a URL ends in a supported extension, it's embedded. However if there are query-string parameters afterward, e.g. `https://image-host.com/image.jpg?quality=high`, the regex fails (because the URL doesn't _end_ with an image extension) and the image is not embedded. It is not always feasible to simply remove the `?` and subsequent characters as some hosts have functional values in the query string (resulting in e.g. a 404 if the value is removed). In these cases the only option is to re-host the image elsewhere or to append a junk `&.jpg` to trick the regex.
This PR amends the regexes used to detect image/audio/video URLs to allow them to also end with an extension followed by a `?` and 0 or more other characters. That is, the following would now work: …
=> utils: support query-string parameters on image/audio/video references

ui/src/components/NavTab.tsx, ui/src/styles/base.css
- Removes the gray box on touch for iOS
- Removes the double-tap-to-zoom gesture to make taps to fire faster
- Adds focus color to the mobile tab bar items for immediate feedback
- Smooths the font rendering
=> groups: iOS touch tweaks

ui/src/state/diary/diary.ts
We weren't handling the case where arranged notes were undefined.
=> notes: fix useArrangedNotes map of undefined crash

desk/app/diary.hoon, ui/src/groups/ChannelsList/ChannelsListItem.tsx, ui/src/state/vitals.ts
This makes saga tracking more explicit and constant so we can know at all times if we're mismatched or in sync.
=> diary: better saga tracking

ui/src/components/ShipConnection.tsx, ui/src/diary/DiaryHeader.tsx, ui/src/diary/DiaryNote.tsx, ui/src/diary/DiaryNoteHeader.tsx, ui/src/diary/DiaryNoteOptionsDropdown.tsx
Hides Add, Edit, Pin, Delete, and Comment capabilities for notebooks where you are not in sync with the host's version.
Also fixes the ShipConnection component to show the tooltip correctly.
=> notebook: prevent create/editing on saga mismatch

ui/src/channels/ChannelTitleButton.tsx, ui/src/state/vitals.ts
This was using the wrong ship for channels, the group host instead of the channel host, and also it wasn't properly subscribing to new ships when still mounted. This fixes the issue where I was only ever seeing "Checking connection...", and now properly gives us the updates.
Should go out with 4.2
=> channels: fix channel checking

ui/src/chat/ChatMessage/Author.tsx, ui/src/components/References/CurioReference.tsx, ui/src/components/References/NoteReference.tsx, ui/src/components/References/ReferenceBar.tsx, ui/src/components/References/ReferenceInHeap.tsx, ui/src/components/References/WritBaseReference.tsx, ui/src/heap/HeapContent.tsx, ui/src/heap/HeapDetail/HeapDetailSidebar/HeapComment.tsx
Styles the refs so that they can be displayed sanely in heap comments.
Fixes LAND-718.
Looks like this on desktop:
Looks like this on mobile:
https://github.com/tloncorp/landscape-apps/assets/1221094/399f7ec8-6357-4d1a-b565-3aa322a4e306
=> gallery: fix refs in gallery comments

ui/src/groups/LureInviteBlock.tsx
fixes GRO-600
Addresses the following feedback on #2738:
> A simple idea here, if I understand this problem correctly (ignore the greater context, focus on the form field itself)
> 
> ![Lure Link Generation](https://user-images.githubusercontent.com/1195363/256929848-fc47d517-ba51-4062-b785-05c812f0090e.png)
> 
> This recommendation basically splits up the lure link generation process into three discrete steps:
> 
> 1. Disabled form, indicating that it must be enabled to show a link
> 2. If enabled, Lure Link is "generated" and indicates it needs time before it can display
> 3. Only when we've able to render a link that actually works, do we complete the "generation" process and show a working link that can be copied
> 4. If the generation process fails, or we can't reliably surface a …
=> lure: UI updates to checking interaction

ui/src/diary/diary-add-note.tsx
Apparently using destructuring to pull values out of this ref could be interpreted as attempting to assign a value to the ref. Eliminated the destructuring and added a check to make sure we have a ref.
=> bugfix: land-736

ui/src/diary/DiaryNote.tsx, ui/src/diary/DiaryNoteOptionsDropdown.tsx
We were passing flag rather than nest into useChannel, which expects a nest, so it returned undefined and the components assumed there was a saga issue and hid the appropriate elements (comment input, dropdown options on notes for the author/admins).
=> bugfix: missing saga issues in notebooks

ui/package-lock.json, ui/package.json, ui/public/mockServiceWorker.js, ui/src/chat/ChatEmbedContent/ChatEmbedContent.tsx, ui/src/chat/ChatEmbedContent/TwitterEmbed.tsx
No more opening a modal to view the full tweet (since our old embed would tend to garble them if they included mentions, pictures, or videos).
Requires react-18, so this is currently based on hunter's branch.
Fixes LAND-741
=> chat: use vercel's react-tweet to improve twitter embeds

ui/src/groups/Groups.tsx, ui/src/logic/useReactQuerySubscription.tsx, ui/src/state/settings.ts
Wait until user has opened groups a second time.
Separately: there is something wrong with the %settings initialization. showActivityMessage is not getting initialized to `true`, so I've hacked around that for now.
=> groups: don't ask for tracking on first run

ui/src/logic/DragAndDropContext.tsx
I originally had an unnecessary early return before we get to the setIsDragging(false) and setIsOver(false) calls.
This removes that.
=> bugfix: drag and drop could get stuck in "drag" mode

ui/src/nav/GroupsNav.tsx, ui/src/nav/TalkNav.tsx
Fixes LAND-702
Small update that fixes the position of the container components that wrap Talk and Groups. Apart from hopefully resolving the scroll issue referenced, this should help the mobile app feel more native by ensuring navigational elements can't be dragged out of position. 
Give it a spin and let me know what y'all think. If we want to preserve the existing feel on desktop, I can add a mobile check.
=> Fix position of Talk/Groups containers

desk/desk.docket-0, ui/src/channels/ChannelActions.tsx, ui/src/channels/ChannelHeader.tsx, ui/src/chat/ChatChannel.tsx, ui/src/chat/ChatThread/ChatThread.tsx, ui/src/components/Divider.tsx, ui/src/components/Mention/MentionPopup.tsx, ui/src/components/MobileHeader.tsx, ui/src/components/Sidebar/MobileSidebar.tsx, ui/src/components/Sidebar/SidebarItem.tsx, ui/src/diary/DiaryChannel.tsx, ui/src/diary/DiaryHeader.tsx, ui/src/diary/DiaryNoteHeader.tsx, ui/src/diary/diary-add-note.tsx, ui/src/dms/Dm.tsx, ui/src/dms/MobileMessagesSidebar.tsx, ui/src/dms/MultiDm.tsx, ui/src/groups/ChannelsList/GroupChannelManager.tsx, ui/src/groups/FindGroups.tsx, ui/src/groups/GroupSidebar/MobileGroupSidebar.tsx, ui/src/groups/MobileGroupChannelList.tsx, ui/src/groups/NewGroup/NewGroupView.tsx, ui/src/heap/HeapChannel.tsx, ui/src/heap/HeapDetail/HeapDetailHeader.tsx, ui/src/heap/HeapHeader.tsx, ui/src/nav/MobileRoot.tsx, ui/src/notifications/Notifications.tsx, ui/src/profiles/Profile.tsx, ui/src/styles/components.css
General mobile-readiness cleanup.
- Unifies the position of all MobileHeader elements between views
- Adds a secondaryTitle prop to the MobileHeader. This allows for longer titles than what the center-half column previously allowed by introducing a second row of the header
- Adds MobileHeader to the mobile thread view in Chat
- Knocks the font-size of mobile sidebar items down; uses system-sans
- Uses MobileHeader in Dm and MultiDm
- Uses an ActionMenu for ChannelActions (tap on channel name)
- Modifies MobileHeader to use children for channel-specific actions (add, sort)
- Removes the text labels in the in-group bottom nav 
- Uses MobileHeader in Notebook items (view + edit)
- Uses MobileHeader in Gallery detail headers
- Uses ActionMenus for display options in Notebooks and Galleries
- …
=> groups: mobile cleanup

ui/src/chat/ChatThread/ChatThread.tsx, ui/src/chat/ChatWindow.tsx, ui/src/groups/ChannelsList/GroupChannelManager.tsx
Fixes LAND-769
also resolves the issue where the gray chat messages loading animation overflows into the input.
=> Groups: fix channel manager width & loading placeholder overflow

ui/src/chat/ChatEmbedContent/ChatEmbedContent.tsx, ui/src/heap/HeapBlock.tsx, ui/src/heap/HeapDetail/HeapDetailBody.tsx, ui/src/heap/HeapRow.tsx, ui/src/state/embed.ts
Updates our embed lookups to run through `react-query` which causes them to get cached using IndexedDB.
Fixes LAND-438
=> Cache embeds

ui/e2e/005-accept-group-invite.spec.ts, ui/src/components/References/GroupReference.tsx, ui/src/groups/GroupJoinList.tsx, ui/src/groups/GroupSummary.tsx, ui/src/groups/Join/JoinGroupModal.tsx, ui/src/groups/useGroupJoin.ts, ui/src/notifications/Notification.tsx
fixes LAND-647 to force all group joins to go through the group join modal flow. Also does not redirect the user to the joined group until the data for the group has already been loaded.
=> groups: all group joins must be via join modal

ui/src/chat/ChatContent/ChatContentImage.tsx, ui/src/chat/ChatEmbedContent/SpotifyEmbed.tsx, ui/src/diary/DiaryCommentOptions.tsx, ui/src/diary/QuipReactions/QuipReactions.tsx, ui/src/heap/HeapDetail.tsx, ui/src/heap/HeapDetail/HeapDetailSidebar/HeapCommentOptions.tsx, ui/src/heap/HeapDetail/HeapDetailSidebar/HeapCommentReactions.tsx
- Restricts image height in chat
- Fixes always open emoji picker issue in mobile Gallery/Notebooks detail views (by hiding for now)
- Makes the next/previous block navigation buttons visible in Gallery detail view
All of these changes are small and should be low risk additions to the upcoming release.
Fixes LAND-778
=> groups: a few small fixes

ui/src/chat/ChatMessage/ChatMessage.tsx, ui/src/chat/ChatReactions/ChatReaction.tsx
Kills text selection in Chat messages on mobile, which interferes with the long-tap action menu.
Note that this doesn't disable long-tap gestures on things like images, links, or other elements (so you can still long-tap to preview a link on iOS, long-tap to save an image, etc.).
=> chat: disable user-select on messages for mobile

ui/e2e/005-accept-group-invite.spec.ts, ui/package.json, ui/src/app.tsx, ui/src/components/LandscapeWayfinding.tsx, ui/src/components/References/GroupReference.tsx, ui/src/groups/useGroupJoin.ts
Fixes LAND-786. Was caused by the "Help & Support" button in the wayfinding bug menu. Also cleaned up a few other group join spots and prevented the wayfinding bug from appearing while the profile modal is open.
Found another issue in the process, when the wayfinding modal is closed the user is unable to click anything. Will fix that before merging.
=> groups: fix re-routing issue on some modals

ui/src/groups/GroupActions.tsx
This fails in build because we require it everywhere but only use it in one place (on mobile).
=> groups: makes saga optional in GroupActions

desk/app/chat.hoon
When adding or deleting a feel `her` is the writ author rather than the emoji feeler. Since that's the case, we were returning %.n early and the writ is never updated. This removes the early return, and instead adds the check to the appropriate branches in the `?-`.
=> chat: fix emoji reactions not sticking

ui/src/chat/ChatInput/ChatInput.tsx, ui/src/chat/ChatMessage/ChatMessage.tsx, ui/src/logic/DragAndDropContext.tsx, ui/src/logic/useLongPress.ts, ui/src/logic/utils.ts
Fixes both LAND-801 and LAND-802, in addition to switching to a normal long press for long presses (rather than mouseUp).
Also cleans up a few errant console.logs().
Drag and drop still works normally on desktop.
Fixes LAND-801
Fixes LAND-802
=> chat: fix various clicking issues

ui/src/chat/ChatEmbedContent/ChatEmbedContent.tsx
Needed to pass an explicit `fluid={false}` prop and set a width on the video player itself.
Fixes LAND-810
Test it by posting a tall video followed by another message.
=> chat: fix video player size bug

ui/src/logic/useReactQuerySubscription.tsx
Fixes LAND-750
The fix is to set `staleTime` _(20 mins)_ to prevent infinite loop of refetching/re-rendering
Please, feel free to say your arguments against it or the potential drawbacks of this approach.
=> groups: react-query on-mount refresh not scrying for settings

ui/src/diary/DiaryCommenters.tsx, ui/src/diary/DiaryNoteHeadline.tsx
Fixes the invisible comment button as well as a few edge cases introduced with the recent style/spacing fine tuning pass. Tried to follow the spirit of those changes while adapting them to be more resilient to dark vs light mode and note with image vs no image.
Fixes LAND-823
=> Notebooks: Fix note headline button & date colors

ui/src/state/groups/groups.ts
Updates our gang preview to check for existing data before issuing a new fetch. 
Believe this is what was slowing down refs in the "Local Directory" channel, but let me know if you guys are still seeing lag there.
Fixes LAND-794
=> Gallery: Speed up group refs

ui/src/app.tsx
OTT
We just needed to move the picker paths for DMs over to the Groups router now that chat is embedded there for mobile.
Fixes LAND-835
=> Chat: Fix DM reacts on mobile

ui/src/heap/HeapBlock.tsx, ui/src/heap/HeapDetail.tsx, ui/src/heap/HeapDetail/HeapDetailSidebar/HeapDetailComments.tsx
Updates the `HeapDetail` view to use existing data from the main grid query as an initial value while fetching the full curio with comments in the background. This should make sure it's always snappy when clicking into a block from the channel view.
Fixes LAND-841
=> gallery: Use existing curios as initial data in HeapDetail

ui/src/diary/DiaryChannel.tsx, ui/src/heap/HeapChannel.tsx, ui/src/logic/useDismissChannelNotifications.ts, ui/src/state/diary/diary.ts, ui/src/state/heap/heap.ts
markRead was getting fired in an infinite loop via the useEffect in useDismissChannelNotifications. We need to prevent it from firing while the initial call is still loading and we need to invalidate the cache on success to keep it from firing again after the first call completes.
Also, mutateAsync was unnecessary here, mutate is fine.
Fixes LAND-842
=> groups: fix infinite loop on mark read in diaries/heaps

ui/src/components/Layout/__snapshots__/Layout.test.tsx.snap, ui/src/components/References/ReferenceBar.tsx, ui/src/groups/GangPreview/__snapshots__/GangPreview.test.tsx.snap, ui/src/groups/GroupSidebar/__snapshots__/ChannelList.test.tsx.snap, ui/src/heap/HeapChannel.tsx
They get crowded too easily imo and you can always click the person's profile.
=> refs: don't show roles in bar

desk/app/chat.hoon, desk/app/diary.hoon, desk/app/heap.hoon
Fixes the issue with our recheck functions actually leaving users from channels that shouldn't be left.
Fixes various issues with the leave-old-channels poke that also caused incorrect channels to be left.
Fixes LAND-853.
=> groups: fix state wipe on load from recheck/leave-old-channels pokes

ui/src/components/RadioGroup.tsx
Adjusts the structure of the `RadioGroup` component and ensures left-alignment of all options in all cases. (The Radix primitive renders a `<button>`, which had a center-aligned label.) Also knocks the size of the helper text down a bit to better fit the entire label on a small screen in its non-selected state.
Previews:
**Channel settings with an unset group**
**Channel settings with a group set**
**Group settings with unset global**
**Group settings with set global**
Fixes LAND-887
=> radiogroup: ensure left-aligned options

ui/src/groups/GroupInviteDialog.tsx
Part of GRO-615
Review notes:
* Scrollbar still appears at small resolutions near the mobile breakpoint but gone at most window sizes in between.
* I don't know this app enough to tell if removing that margin-bottom class has other side effects.
* The main issue of the flickering is still in progress. More in comment later.
=> groups: eliminate scrollbars in invite dialog on desktop

ui/src/chat/ChatReactions/ReactionsWidget.tsx
Believe this was just a bad import.
Fixes LAND-889
=> reactions widget: fix crashing error

desk/app/heap.hoon, ui/src/components/ConfirmationModal.tsx, ui/src/heap/EditCurioForm.tsx, ui/src/heap/HeapBlock.tsx, ui/src/state/heap/heap.ts
A few fixes to ensure curio deletion works as expected:
- make sure you always have permission to delete if the option is shown in the UI
- properly track the delete and spin while waiting
- successful delete triggers consistent removal from cache and query invalidation
Also updates the delete curio modal to close when you click outside of it.
Fixes LAND-839
=> heap: consistent curio delete behavior

ui/src/state/lure/lure.ts
Fixes issue with lure link toggling / popping in and out on the "invite people" dialog, which was occurring because the API call would time out and default to `false`. Now it will default to the previously returned value if a timeout occurs.
=> fix lure link toggling when check request times out

ui/src/chat/ChatInput/ChatInput.tsx, ui/src/chat/ChatSearch/ChatSearch.tsx, ui/src/components/MobileHeader.tsx, ui/src/components/Sidebar/MobileSidebar.tsx, ui/src/groups/GroupSidebar/MobileGroupSidebar.tsx, ui/src/logic/native.ts, ui/src/window.ts
This PR is one half of a fix for safe area insets in the webapp. The other half involves changes to the native app repo here: https://github.com/tloncorp/talk-android/pull/31.
In order to properly render modals and various headers and footers, the webapp needs to have total control over the rendering surface. To make that possible, I've removed the native `SafeAreaView` wrapping the entire app and instead opted to inject safe area values into the webapp. The safe area values are accessed through a hook, and default to `0` values if nothing has been injected. This PR contains plumbing for that, as well as application to headers/footers where necessary.
Fixes LAND-900
=> groups: fix native safe area insets

ui/src/app.tsx, ui/src/components/Sidebar/Sidebar.tsx, ui/src/nav/MobileRoot.tsx, ui/src/state/groups/groups.ts
This fixes both LAND-902 and LAND-897 by removing the redirects. For 902 we also add in a prompt to go to the find tab since we no longer have a redirect. This is a stopgap until we have a better empty state.
Fixes LAND-902
Fixes LAND-897
=> groups: remove mobile redirects

ui/src/state/storage/upload.ts
Fixes the "Take a Photo" flow in mobile Safari (and therefore the Groups app webview) by appending the file input to the DOM during file selection
=> fix take photo flow in mobile safari

ui/src/app.tsx, ui/src/logic/analytics.ts, ui/src/main.tsx
Adds a PostHog `error` event, triggered by the app `ErrorBoundary` or the global window error event.
=> groups+talk: add basic error logging

ui/src/components/About/AboutView.tsx, ui/src/components/Settings/SettingsView.tsx
=> mobile: fix padding in about and settings views

ui/src/logic/tiptap.ts
Actually fixes LAND-928, our tiptapToString function was unfortunately unsafe.
=> gallery: changing tiptapToString to not have side effects

ui/src/dms/NewDm.tsx
Fixes LAND-933 again by adding a MobileHeader to the new DM screen (if you're in the mobile app). The Back button goes back to the Messages index.
=> messages: adds MobileHeader

ui/src/chat/ChatMessage/Author.tsx
Changes the `Author` component to use useNavigate instead of useModalNavigate. This fixes LAND-953 (where the useModalNavigate hook would direct you to the profile modal without the matching backgroundState, resulting in a blank white screen). 
Note that this is global to `Author`. I checked it everywhere I could possibly find an `Author` with no regression, but would appreciate a second look.
=> author: useNavigate() for profile modal

ui/src/dms/MessagesSidebarItem.tsx
Fixes LAND-952 by adding an active state to sidebar items in the Talk desktop sidebar. This bypasses the strict path-checking regex and lights up the sidebar item as active when navigating into a Chat thread.
=> talk: add inexact prop to desktop MessagesSidebarItem

ui/src/components/NavTab.tsx, ui/src/components/Sidebar/MobileSidebar.tsx, ui/src/logic/useIsGroupUnread.ts
- Reformats the navbar slightly to accommodate tap targets with the intended margins, which fixes LAND-894
- Adds useIsAnyGroupUnread, a superset of what is returned by useIsGroupUnread
- Uses a variety of methods (useIsAnyGroupUnread, useChannelUnreadCounts, useNotifications) to show or hide a blue dot under the Groups, Messages, and Activity navigation items
- Converts the Activity navigation item to a DoubleClickableNavTab, since we will want to support linking to the notification context relative to the activity stream (both events are the same now, which might be premature)
Fixes LAND-945
=> groups: activity indicators in mobile navbar

ui/src/components/Sidebar/SidebarItem.tsx, ui/src/dms/MobileMessagesSidebar.tsx, ui/src/groups/FindGroups.tsx, ui/src/groups/GroupJoinList.tsx, ui/src/nav/MobileRoot.tsx
- Reuses GroupJoinList in MobileRoot, which fixes LAND-947
- Shifts GroupJoinItem to use SidebarItem to allow them to slot in to the Groups list with uniform appearance
- Adds an optional highlightAll prop to GroupJoinList, which is passed down to GroupJoinItem to show a blue-soft background
- Adds an optional "preload" prop to GroupJoinItem for pre-filling the group item with static data until the gang data arrives; used in the "Find Groups" screen for the UF, door, and Tlon Local suggestions
- Unifies the separators in the Messages list with the Groups list
- Does NOT remove the "Find Groups" screen from the nav or invites from the Activity stream; meant to be an incremental change
=> groups: echo invites in groups list

ui/.env
This updates branch vars so we use the right urls. Fixes LAND-957
=> branch: use correct URLS

ui/src/chat/ChatScroller/ChatScroller.tsx, ui/src/logic/useScrollerMessages.ts, ui/src/state/chat/writs.ts
We were missing a few stops so that we didn't just continuously fetch.
=> chat: prevent overfetching from scroller

ui/e2e/auth.setup.ts, ui/src/components/References/AppReference.tsx, ui/src/components/Sidebar/Sidebar.tsx, ui/src/dms/MessagesSidebar.tsx
In light of the recent migration from `/grid` --> `/landscape` for 412k, this updates remaining path references throughout the project. 
- `AppReference` - when rendering a link to an app, it now deep links to Landscape instead of Grid
- `Sidebar` & `MessagesSidebar` - both have a 'Back to Landscape' button that now points to `/apps/landscape`  instead of `/apps/grid`
If we're lucky, this might also be a step in the direction of fixing e2e tests (currently broken on `develop`)
=> landscape: update /grid paths --> /landscape

ui/src/chat/ChatScroller/ChatScroller.tsx, ui/src/state/chat/writs.ts
Fixes LAND-963
Two issues here:
- We were attempting to scroll to an undefined index in empty channels
- `hasLoadedOldest` wasn't properly set for empty channels
=> Fix scroller crash in empty channels

ui/src/logic/useMedia.ts
This fixes LAND-910 by making sure that our `useMedia` hooks actually call `matchMedia` to get the actual value in the case where the query hasn't been setup yet.
=> use-media: correctly initialize value

ui/src/profiles/EditProfile/EditProfile.tsx
This PR adds a style tweak to ensure that the Edit Profile view renders at full width on larger screens. Previously (on `0vp.gv2u9.9hg31.7jgob.84vt5.jobhe.he7k6.kfnia.95i4b.00vu4.eaocr`) it was rendering the content at the mobile width, with extraneous space to the right like so:
=> ui: Edit Profile layout for large devices

ui/src/chat/ChatInput/ChatInput.tsx
Fixes [LAND-803](https://linear.app/tlon/issue/LAND-803/chat-apparent-flicker-between-chat-channels-on-mobile)
The message editor is initially null when rendering the input, which means that the input is never rendered on the first pass. Currently, this causes content to jump up immediately after the first render. This PR fixes that by rendering the input HTML before the editor is initialized.
=> groups: fix chat input jump

ui/src/chat/ChatMessage/ChatMessageOptions.tsx
This PR fixes the placement of message options on desktop post-new-scroller.
The issue was that `position: sticky` behaves differently inside the inverted scroller. We were only using `sticky` to ensure that options remained visible when a message was scrolled off the page, so for now I've replaced that with a simple hack to correct position after render.
A more comprehensive + performant solution would be to move options rendering outside of the message and deal with positioning there. I started down that route, but it looked like fully extracting options from message was a bigger change than it made sense to make just for this. I think it is worth doing, but holding off for now.
=> groups: fix message options placement

ui/src/state/bootstrap.ts, ui/src/state/local.ts
Changes the behavior of our airlock to always start a new channel instead of reconnecting after a minute on mobile or an hour on desktop.
Should fix LAND-968 also address instances where the urbit channel gets reaped aka after 12hrs of no events which currently isn't handled by the @urbit/js-http-api package. This is super hard to test in dev, so I think it's best just to ship and test in real conditions.
=> reconnects: make sure we restart channel if too much time has passed

ui/src/components/Sidebar/MobileSidebar.tsx, ui/src/state/chat/chat.ts
This should make unread state in the nav match user action for the messages tab.
Also this makes the non-native nav and native nav the same so people can get the same experience.
=> nav: use more accurate unread state, and unify native nav and non-native

ui/src/state/settings.ts
=> mobile: don't show superfluous telemetry notice in the app

ui/src/chat/ChatMessage/ChatMessageOptions.tsx, ui/src/components/References/AppReference.tsx
Fixes LAND-974, which was caused by:
1) the parent div for chat message options had height set to 100%, so they created an invisible box blocking the content underneath.
2) the app reference was set to width 100%, unlike our other refs which have a max width of 600px.
Tagging @dnbrwstr since I noticed you had set the h-full on the chat message options. Did this solve some particular problem? Can we safely set it to min-h-fit?
=> chat: fix issue with clicking on app references in chat

ui/src/chat/ChatMessage/ChatMessageOptions.tsx, ui/src/components/ActionMenu.tsx
Adds a "Copy Text" button to the ActionMenu on mobile, fixes LAND-972. Also applies 'select-none' to the actions in the ActionMenu so that users don't accidentally select the button text rather than just pressing the button (not sure if we have an issue for that, couldn't find one).
I intentionally did not add it to desktop since a) it's superfluous b) we would be using a duplicate icon without an easily apparent label.
=> mobile: show copy text button on chat message options

desk/app/chat.hoon, desk/lib/chat-json.hoon, desk/lib/dm.hoon, desk/mar/writ-response.hoon, desk/mar/writ.hoon, desk/sur/chat.hoon, ui/src/chat/ChatChannel.tsx, ui/src/chat/ChatMessage/ChatMessage.tsx, ui/src/chat/ChatThread/ChatThread.tsx, ui/src/chat/ChatUnreadAlerts.tsx, ui/src/chat/ChatWindow.tsx, ui/src/dms/Dm.tsx, ui/src/dms/MultiDm.tsx, ui/src/state/chat/chat.ts, ui/src/state/chat/type.ts, ui/src/state/chat/writs.ts, ui/src/types/chat.ts
Fixes LAND-970 and LAND-977. This involved adding a few things to the backend: 
- Times on the subscription fact of all "added" writs. This ensures that times for new messages exist and are correct.
- A scry endpoint for fetch around id, since briefs only gives us an ID we needed a way to make sure we can get messages near the unread
- Changing when we give updates about writs so that it's always after we've resolved the pact
- Adding a missing mark for a single writ, there's a few places we ask for a single writ which were relying on the messages existing already, instead we just scry for them
So now if you have an unread:
- we fetch around the message
- if it's in a thread we also fetch around the thread OP
=> chat: fix unread banner

ui/src/app.tsx, ui/src/chat/ChatChannel.tsx, ui/src/chat/ChatSearch/ChatSearch.tsx, ui/src/chat/ChatSearch/ChatSearchResults.tsx, ui/src/chat/ChatSearch/MobileChatSearch.tsx, ui/src/chat/ChatSearch/SearchBar.tsx, ui/src/state/chat/chat.ts, ui/src/state/chat/search.ts
- Updates search on mobile to take up the whole page
- Displays previous few queries and the last set of results
- Changes the search function to fetch fewer results for faster initial load and populates more infinitely as you scroll
- Works across channels, DMs, and group chats
Fixes LAND-923
https://github.com/tloncorp/landscape-apps/assets/90741358/bb1fdacc-e3df-4742-ae1c-e1fdbeabf3f3
* note in the vid it hesitates on loading the thread when the search result is clicked. This is normally instantaneous, investigating
=> chat: mobile search overhaul

ui/src/components/MobileHeader.tsx, ui/src/groups/NewGroup/NewGroup.tsx, ui/src/groups/NewGroup/NewGroupDialog.tsx, ui/src/groups/NewGroup/NewGroupView.tsx
Fixes LAND-987
https://github.com/tloncorp/landscape-apps/assets/1221094/ae1f07ef-f7de-4da1-a544-563e58312e20
Note that this modifies the mobile header to allow the arbitrary back function, which touches on the general "back button" discussion.
=> mobile: create group refinements

ui/src/logic/analytics.ts
When the app initially loads posthog fires off a request to their `/decide` endpoint.  This is just a check to see if the analytics client supports certain features (none of which we use). No user data is sent with the request, but this may make users worry. We can safely disable this.
More details here: https://posthog.com/docs/libraries/js#disable-decide-endpoint
=> analytics: disable posthog decide check

ui/src/components/Mention/MentionPopup.tsx
Fixes mentions to appear above the input bar on mobile and reverses result order so the best suggestion is easier to click.
Fixes LAND-929
https://github.com/tloncorp/landscape-apps/assets/90741358/8f6632de-8da3-4834-b4d4-832e57756957
=> mobile: fix mention suggestion positioning

desk/app/chat.hoon, ui/src/dms/MessagesList.tsx, ui/src/dms/MessagesSidebarItem.tsx
Fixes LAND-1001 and possibly other issues.
The reason the blue dot wasn't going away on the Messages icon was because we were still getting briefs for a club we already left. This PR updates briefs so that when we scry for briefs we just send an empty brief for a club that we're neither a member of or invited to. It also makes sure we don't hear about writ updates for the club if we're not invited or a member.
There were two other issues I found while working on this:
1) If you rejected a club invite this would actually cause the messages list to not render at all, since the MessagesSideBarItem would return null and the virtualscroller wouldn't be able to calculate heights. A user might just assume that they lost all of their messages. (I'm currently effected by this bug on my ship, I …
=> chat: fix issues with leaving clubs

ui/src/app.tsx
Currently, the wayfinding block on mobile:
- Overlaps with the bottom nav
- Has stale content
- Duplicates content in settings + discover tabs
We could fix some of these things, but I don't think we lose much by just removing it for now.
=> groups: disable wayfinding block on mobile

ui/src/chat/ChatScroller/ChatScroller.tsx, ui/src/components/EmptyPlaceholder.tsx, ui/src/dms/MessagesList.tsx
Adds basic empty states for DMs tab and new channels. DM list empty state is not shown on desktop.
Empty channel (desktop)
Empty channel (mobile)
<kbd><img width="200" style="display: block" src="https://github.com/tloncorp/landscape-apps/assets/357216/83059c82-610d-4d6a-b60f-28ffb76efbfc"> </kbd>
No DMs (mobile)
<kbd><img width="200" src="https://github.com/tloncorp/landscape-apps/assets/357216/17f58b6b-f6ad-4ea0-ab63-e9116ccd7d3a"></kbd>
Fixes LAND-1036
=> groups: channel and dm list empty states

ui/src/components/Sidebar/GroupList.tsx, ui/src/logic/channel.ts, ui/src/logic/useGroupSort.ts, ui/src/logic/useLongPress.ts, ui/src/logic/useSidebarSort.ts, ui/src/state/groups/groups.ts
I noticed that when scrolling the main list of groups on both mobile + desktop, we were sending new requests for all group avatars on pretty much each scroll event.
After some investigation, it turned out that this was related to the `Head` component being passed to the `Virtuoso` scroller. Because that component was being dynamically generated, every time its children changed the whole tree under it was getting wiped and recreated, rather than just updated as we'd really want. 
In order to prevent recreating all the list items, I replumbed the list to display child content as an element in the list, rather than using the header component prop. It would be a little more elegant to just pass all the individual pinned groups as list items and render all items + section headers in …
=> groups: improve group list rendering performance

ui/src/components/Sidebar/GroupList.tsx, ui/src/nav/MobileRoot.tsx
This PR fixes the rendering of the groups list when the user has no pinned items or pending invitations. Previously, that would result in an empty header being rendered, which, since it was 0px high, would cause Virtuoso's render cycle to fail. 
This PR deals with that in two ways:
- It prevents `MobileRoot` from passing in an empty header component. 
- It wraps any header element in a 1px min-height dive, to ensure that whatever is passed in will have some height.
=> groups: fix rendering of group list with no pins

ui/src/chat/ChatInput/ChatInput.tsx
We weren't properly clearing the chat input focus context on unmount of the chat input component, this makes sure the chat input context is properly reset if the component unmounts.
Fixes LAND-1032
=> mobile: fix stuck chat input focus state on navigate away

ui/src/logic/branch.ts
Fixes LAND-1047
Apparently branch.io appears on many adblock lists. (see https://github.com/BranchMetrics/web-branch-deep-linking-attribution/issues/538)
We were only returning a lure link if we could successfully create a deep link. We should return the normal/non-branch lure link if we fail to contact branch.io.
=> lure: provide a fallback url if branch.io is blocked (or down)

ui/src/notifications/useNotifications.tsx
Missed this earlier.
Fixes LAND-1042
=> notifications: make sure we don't see club notifications on desktop groups

ui/src/state/chat/writs.ts
This fixes bottom anchoring of the chat scroller by ensuring that it doesn't flip into "newer" loading mode when a new message arrives.
=> scroller: fix bottom anchoring for new messages

.github/workflows/deploy-external-groups.yml, .github/workflows/deploy-external-talk.yml, .github/workflows/deploy-kernel-groups.yml, .github/workflows/deploy-kernel-talk.yml, .github/workflows/glob-and-deploy-kernel-groups.yml, .github/workflows/glob-and-deploy-kernel-talk.yml
Refactors our actions a bit so we have more flexibility around kernel integration deploys and also combines the "external" step to also deploy to kernel moon as the default case. IF we're in the middle of a kernel integration then we can run that step with the deploy off (since it will fail).
=> ops: sync bosdev and doznec simultaneously

desk/app/diary.hoon, desk/lib/notes.hoon, ui/src/notifications/Notification.tsx
This should fix LAND-1061 by safely accessing notes when we try to make notifications. I'm not sure however of the cause of why one might not have the note being commented on, but seems highly possible with funny permissions.
Also put a little rider in here to fix the notification dot color.
=> diary: dont crash in update path

ui/package-lock.json, ui/package.json, ui/src/api.ts, ui/src/state/bootstrap.ts
This should resolve both LAND-844 and LAND-996. It updates the http-api to the latest 3.0 version which has channel reap handling. It also adds a delay to scrying all "auxiliary" data like contacts, storage, kiln, docket, etc. when reconnecting so that opening your phone and constant reconnects doesn't incur as much fetching.
=> connection: update http api

ui/src/logic/branch.ts
Skips the branch deep link look-up and creation flow if the specified `canonicalUrl` (the web lure flow URL) is empty. This prevents a situation where a deep link is created without a custom desktop redirect URL, resulting in the user being able to land on a Branch-hosted app download page.
=> skip branch deep linking if no lure web link provided

DEVELOPMENT.md, README.md
Updates the README.md and DEVELOPMENT.md docs to reflect the current state of the world.
@bonbud-macryg, would be thrilled to have a once-over.
=> docs: garden is now landscape

ui/src/components/Sidebar/MobileSidebar.tsx, ui/src/components/icons/BellIcon.tsx, ui/src/components/icons/NavigateIcon.tsx
OTT
Also: 
- updates the "Discover" icon to match the Figma mock 
- fixes touch targets for Discover & Profile (were unintentionally smaller than the others)
Fixes LAND-1074
=> groups: fix icon position/size for mobile nav

desk/lib/diary-json.hoon, ui/src/api.ts, ui/src/diary/DiaryNoteOptionsDropdown.tsx, ui/src/diary/diary-add-note.tsx, ui/src/logic/tiptap.ts, ui/src/state/diary/diary.ts
This fixes LAND-1075 LAND-1076 and LAND-1077. Tasks were missing from the incoming json parser so that was added in. We also missed a place where we let people try to edit a pending note. The biggest chunk here was letting notes actually error out so that people can at least save a backup somewhere else (or change the content), previously we were just navigating away.
=> notebook: tasks bug and misc

ui/src/channels/NewChannel/NewChannelForm.tsx
fixes LAND-1051
We don't actually get a status change from the add channel mutation unless we're adding a channel to a zone. Rather than check statuses on each type of mutation here, we can just use react-hook-form's form state (and not allow the user to click the button while we're submitting).
=> channels: don't allow multiple form submissions in new channel form

ui/src/state/storage/reducer.ts, ui/src/state/storage/storage.ts
This fixes LAND-1096 by making sure we default the new values even if Landscape doesn't send them to us. This ensures that uploads still work until Landscape is updated. This also clears credentials from being stored in local storage.
=> storage: don't break existing functionality if landscape not up to date

ui/package-lock.json, ui/package.json, ui/src/state/storage/upload.ts
fixes LAND-1092
I added a new library called `browser-image-compression` that uses web workers to compress images in a performant way. It also removes all exif data by default.
To test just upload a large image with exif data, then download the image after uploading/posting it and notice that it's much smaller and doesn't have exif data.
The library: https://github.com/Donaldcwl/browser-image-compression
=> images: compress images (and strip exif data) prior to upload

ui/src/env.d.ts, ui/src/logic/utils.ts, ui/src/state/local.ts, ui/src/state/storage/reducer.ts, ui/src/state/storage/storage.ts
We're going to add a hardcoded URL so that we don't have to poke all ships with the presigned URL endpoint. This makes it so that any hosted ship which has not set S3 credentials gets defaulted to the presigned flow. Will mimic these changes in Landscape.
This also improves hosting checks so that we can specifically target staging vs prod based on the vite ship url you pass and persists show/hide dev tools.
=> storage: hardcode s3 url

ui/src/groups/LureInviteBlock.tsx, ui/src/state/lure/lure.ts
Adjusts the timeouts for checking if lure links are enabled and fetching the url to 30 seconds.
Also add diagnostic logging for invite screen
Fixes LAND-1105
=> groups: bump lure fetch timeouts

ui/src/logic/branch.ts, ui/src/profiles/Profile.tsx, ui/src/state/lure/lure.ts
If branch links are initially malformed when created, they can never be automatically updated. We make no attempt to do so right now, and changing our logic to fix them would need to happen elsewhere since it requires the Branch private key.
This means it's really important not to create one with bad data. This PR adds checks to `createDeepLink` to ensure it has a valid `lure` or `wer` link before attempting creation. It also updates the lure logic to avoid calling `createDeepLink` altogether unless we have the requisite info to do so.
If your reviewing this, please confirm you can still create both types locally.
Fixes LAND-1106
=> deeplinks: defend against Branch link poisoning 

ui/src/state/storage/upload.ts
fixes LAND-1117 by disabling the web worker for compression.
Tlon Hosting's CSP doesn't allow for blobs from a web worker. Other browsers fallback to just using the main thread if the web worker fails, Safari does not for some reason, so hosted users either using Safari (or using the mobile app) could not upload images.
=> images: turn off webworker, fixes issue on safari on hosted ships

ui/src/state/storage/upload.ts
Since we determined the web worker wasn't the issue (it was the CSP changes on the hosting platform not playing nicely with Safari) we ought to go back to using the web worker for better performance on image uploads.
=> images: flip usewebworker back on

ui/src/diary/DiaryCommentField.tsx, ui/src/diary/DiaryNote.tsx, ui/src/heap/HeapDetail.tsx, ui/src/heap/HeapTextInput.tsx
Fixes LAND-1118. Looks like the issue with the nav still appearing on a new DM was already fixed, but I removed it from the comment input on gallery items and diary notes.
=> mobile: hide nav on gallery item and diary note comment input focus

ui/src/state/storage/upload.ts
Fixes LAND-1120 (hopefully) by catching more rejected promises. At this point every potential rejection should be covered. These promises specifically have to do with image size, which we know is somehow related to the issue with Safari and the new CSP on hosting.
=> images: catch more failed promises in image uploads

ui/src/logic/DragAndDropContext.tsx
Fixes LAND-1110. We weren't using the currentTargetId in the handleDropWithTarget handler, we were just using whichever targetId we received in the parameters for the hook itself.
=> images: fix drag and drop in chat threads

ui/e2e/001-create-group.spec.ts, ui/e2e/005-accept-group-invite.spec.ts, ui/rube/index.ts, ui/src/notifications/Notification.tsx
Tests were not running because the tar files with the fake ships images had the same groups and talk hashes as after committing desks, which we use to verify if the ships are ready to start testing.
Fixed by uploading new tars.
This commit also updates a couple of locators.
=> LAND-1138 Fix e2e tests (update fakes tars and outdated locators)

ui/src/app.tsx, ui/src/diary/DiaryNote.tsx, ui/src/diary/diary-add-note.tsx, ui/src/heap/EditCurioForm.tsx, ui/src/heap/HeapChannel.tsx, ui/src/heap/HeapDetail/HeapDetailSidebar/HeapDetailComments.tsx, ui/src/state/channel/channel.ts, ui/src/types/channel.ts
Fixes LAND-1154
Fixes LAND-1156
Fixes LAND-1151
Fixes LAND-1152
Fixes LAND-1153
Also fixes issues with type names and comment ordering.
Most of this fell out from the changes around using page cursors from the backend in useInfinitePosts.
I also tried to simplify things a bit and remove some dead code. We could still stand to reduce some duplicate code, but this should fix all of the above issues for now.
Please pull it down and test against a ship running the `hm/hackweek` branch.
=> channels: fix various cache issues, and then some.

ui/src/components/References/WritBaseReference.tsx
Currently, clicking on a post ref while metadata for its group is loading will navigate to a join dialog for `~zod/test`. Clicking `join` on that dialog will attempt to join the test group, creating a 'pending' group in the sidebar.
This PR fixes the issue by short-circuiting navigation if group metadata is not yet loaded.
A minor issue with this fix is that it'll make clicking the ref unresponsive while group metadata is loading. We could hold off on rendering the whole thing until metadata is loaded, but that'll add a potentially significant amount of time to the load. We could also pop an error message, but that too could be confusing. 
I think this fix is a pretty reasonable compromise for now. If we want to make this better, we should probably look at adding group metadata to the ref …
=> refs: prevent joining placeholder group

ui/src/state/chat/chat.ts
OTT, this should fix LAND-1181
=> chat: make sure we don't override existing saga values

ui/src/replies/ReplyMessage.tsx, ui/src/replies/ReplyMessageOptions.tsx
=> replies: add hide/show to replies

ui/src/logic/useReactQuerySubscription.tsx, ui/src/state/groups/groups.ts
We have a hack in place to account for the situation where the frontend loses track of a group if it's been removed from the gang list, but is taking a long time to join. The way it's implemented right now means that we're invalidating the groups query too frequently which can trigger loops.
This update just adjusts that groups invalidation logic to only fire if we believe a gang was removed rather than every time the query is fetched.
Fixes LAND-1208
=> groups: fix query invalidation loop

ui/src/app.tsx, ui/src/components/ActivityModal.tsx, ui/src/logic/analytics.ts
Fixes an issue where the current browser URL was logged to the analytics provider on the opt in event (updated on the identify event as well for good measure)
=> analytics: fix url info logged during opt in event

ui/src/chat/ChatMessage/ChatMessageOptions.tsx, ui/src/diary/DiaryNoteOptionsDropdown.tsx, ui/src/diary/useDiaryActions.ts, ui/src/heap/HeapBlock.tsx, ui/src/heap/HeapRow.tsx, ui/src/heap/useCurioActions.ts, ui/src/replies/ReplyMessageOptions.tsx
Fixes LAND-1173
Note the todos related to DMs.
=> hackweek: use isLoading from useMutations for loading indicator in delete modal

desk/app/chat.hoon, desk/app/diary.hoon, desk/app/heap.hoon
When joining channels for the first time, these agents were failing to keep version negotiation state for their host around properly. Here, we make a couple of changes that help them keep the channel status straight. (`/app/diary` already had many of these changes. Now they're all consistent with each other.)
- During `+*-join`, explicitly initialize the $net as appropriate, instead of always bunting it to be %pub.
- During `+*-join`, do not subscribe to the channel right away, instead send an /epic version negotiation subscription first. Only once versions match do we open the subscription for the channel (in `+*-make-chi`).
- When receiving an `/epic` `%fact`, always call into `+*-take-epic` for all affected channels, regardless of what the state of the new epic is.
- In …
=> chat, heap, diary: tighter epic logic

ui/src/state/chat/chat.ts, ui/src/state/chat/utils.ts
Should fix the issue on the latest hackweek deploy where joining and leaving DMs and multi DMs succeed, but doesn't update the interface.
Fixes LAND-1225
=> dms: smoother joins & leaves

ui/src/channels/HostConnection.tsx, ui/src/components/ShipConnection.tsx, ui/src/dms/Dm.tsx, ui/src/dms/MultiDm.tsx, ui/src/logic/channel.ts, ui/src/state/negotiation.ts
Makes `isLoading` and other react query goodies accessible from the `useNegotiation` hook. We need this for DMs where we're initially showing an erroneous mismatch warning. Now it will display normally if the negotiation is still loading.
Fixes LAND-1224
=> version negotiation: make additional info accessible in the hooks

ui/src/components/References/ContentReference.tsx
Fixes LAND-1226 by papering over the issue on the frontend in the notebook comments case and fixing a bug in the gallery comments case (we were looking at the wrong position in the segments array).
=> references: fix issue with reference paths causing notebook/gallery comment references to display improperly

ui/src/chat/ChatScroller/ChatScroller.tsx, ui/src/dms/DmWindow.tsx
We'd moved this into ChatScroller, but the logic was broken. After fixing the logic, there are still display issues with it overlapping content that's set in the parent component. Clawing back the placeholder to it's original location in `DmWindow`.
Fixes LAND-1234
=> dms: fix loading placeholder

desk/app/chat.hoon, desk/app/greeting.hoon, desk/doc/dev/chat.udon, desk/gen/chat/dm-react.hoon, desk/gen/chat/dm.hoon, desk/gen/chat/new-club.hoon, desk/gen/chat/rsvp-club.hoon, desk/gen/chat/send-club.hoon, desk/mar/chat/club/action-0.hoon, desk/mar/chat/club/action.hoon, desk/mar/chat/club/create.hoon, desk/mar/chat/club/crew.hoon, desk/mar/chat/club/delta.hoon, desk/mar/chat/club/invite.hoon, desk/mar/chat/club/rsvp.hoon, desk/mar/chat/dm/action.hoon, desk/mar/chat/dm/archive.hoon, desk/mar/chat/dm/diff.hoon, desk/mar/chat/dm/rsvp.hoon, desk/mar/chat/dm/unarchive.hoon, desk/mar/club/action.hoon, ui/src/mocks/handlers.ts, ui/src/state/chat/chat.ts
Implements least-effort (20-80) backwards compatibility with the old chat backend for dms and clubs. To get there, we make the following changes:
- Rename the new dm- and club- marks to be prefixed with chat- (resulting in chat-dm- and chat-club-), so that the new codebase may distinguish between new and old-style nouns unambiguously.
- Re-includes json-less versions of the old marks.
- Make chat accept & process old-style dm and club pokes. These operate at 100% compatibility. iow, old chat talking to new chat will always work.
- Add conditional retry logic where, if sending a new-style poke fails, we may in some cases retry with an old-style poke instead. Due to dms and clubs not storing a log of events*, this comes with two caveats:
- For dms, reacts added/removed by new chat will not …
=> chat: backwards compatibility with pre-hw dms

ui/src/channels/HostConnection.tsx, ui/src/logic/channel.ts
We were assuming it was fine to allow DMs to the old world, but we shouldn't do it for group hosts.
=> negotiation: host connection should always be matched, shouldn't assume

desk/app/channels-server.hoon, desk/app/chat.hoon, desk/app/diary.hoon, desk/app/heap.hoon, ui/src/components/References/ContentReference.tsx
Chat was migrating refs largely correctly, but wasn't accounting for
cases where the referenced message lives outside of the channel where
the reference was posted.
Heap and diary were not migrating refs correctly at all. Since
converting old chat ids into new ones requires chat's lookup maps, we
expose those for old chat state through a new /old scry endpoint in
chat. We cache the scry, to avoid overhead for large/reference-heavy
backlogs.
Diary was not modifying references in top-level posts at all, which we
also correct for here.
All the above fixes LAND-1245. We also tack on two small, unrelated patches.
=> chat, heap, diary: migrate chat refs properly

ui/src/logic/useScrollerMessages.ts
Updates the `newAuthor` logic to always consider a chat message to be a new author if the last post was a notice type
=> always show author avatar if last post was notice

ui/src/chat/ChatWindow.tsx, ui/src/dms/DmWindow.tsx, ui/src/state/channel/channel.ts, ui/src/state/chat/chat.ts
This should fix LAND-1258. We ensure that we de-dupe messages at all times. We also guard against any fetching while other fetching is happening.
=> chat: fixing duplicate message issues

ui/src/app.tsx, ui/src/dms/MobileDmSearch.tsx, ui/src/state/channel/channel.ts, ui/src/state/chat/search.ts
- Ensure decToUd() receives a string type arg
- Default to '0' (decToUd returns empty string when a '0' is passed)
- Avoid running query if search term is empty
before:
=> Land-1253 chat search doesn't work

ui/src/chat/ChatChannel.tsx, ui/src/chat/ChatThread/ChatThread.tsx, ui/src/logic/ChatInputFocusContext.tsx
fixes LAND-1254 by ~throttling the setChatInputFocus setter in the chat input focus context. Also applied some useMemos along the way and fixed an issue where we were never detecting if we were in a thread in ChatChannels.~ by no-op'ing on chat input state changes on desktop.
=> perf: fix cpu pegging issue in chat threads

ui/src/state/channel/channel.ts, ui/src/state/channel/keys.ts
Fixes LAND-1248 and LAND-1257 by adding more dynamic invalidation based on event type. Also starts to unify channel keys...
=> channels: better refetch handling

ui/src/chat/ChatMessage/ChatMessage.tsx, ui/src/diary/DiaryChannel.tsx, ui/src/diary/DiaryList/DiaryGridItem.tsx, ui/src/diary/DiaryList/DiaryListItem.tsx, ui/src/diary/DiaryNoteHeadline.tsx, ui/src/heap/AddCurioModal.tsx, ui/src/heap/HeapBlock.tsx, ui/src/heap/HeapDetail.tsx, ui/src/heap/HeapDetail/HeapDetailHeader.tsx, ui/src/heap/HeapRow.tsx, ui/src/state/channel/channel.ts
Hides actions (threading, copying, replying, etc.) on posts which aren't yet delivered. Since we're updating all post types optimistically right now, this PR takes a totalizing blunt approach rather than targeting specific problematic interactions.
In the common case, the change shouldn't be noticeable for end users. If performance issues cause delayed delivery, this will defend against any unexpected hiccups interacting with manually cached posts.
Fixes LAND-1264
=> posts: prevent actions on undelivered posts

desk/app/channels-server.hoon, desk/app/channels.hoon, desk/app/chat.hoon, desk/app/diary.hoon, desk/app/heap.hoon, desk/lib/channel-utils.hoon, desk/sur/channels.hoon
During migration, chat identifiers change. As a consequence, references
to chat messages must change if they want to stay pointing to the same
message. However, the old ref alone is not sufficient for constructing
the new ref: you need to know the message being referenced.
Previously, we were doing this transformation during migration strictly
locally. This meant that chat hosts, not uncommonly only aware of the
messages in their own channels, were unable to migrate the chat
references correctly. Newcomers joining the channels would find "bad"
chat references in the backlog, and would be stuck with these forever.
The fix implemented herein depends on the assumption that the author of
a message containing a reference is the one most likely to be able to
resolve the reference successfully. …
=> chat, heap, diary: send migration edits to hosts

ui/src/components/Sidebar/SystemChrome.tsx
- Hooks up the Leap launch button in the sidebar again
- Updates OS detection to drop deprecated `navigator.platform` check
=> fix leap launch button in sidebar

ui/src/types/channel.ts
Fixes LAND-1287 by adding 'cite' to the list of types we consider blocks in constructStory.
=> notebook: fix issue with creating notes with refs

ui/src/chat/ChatScroller/ChatScroller.test.tsx, ui/src/chat/ChatScroller/ChatScroller.tsx, ui/src/chat/ChatScroller/ChatScrollerDebugOverlay.tsx, ui/src/chat/ChatThread/ChatThread.tsx, ui/src/chat/ChatWindow.tsx, ui/src/dms/DMThread.tsx, ui/src/dms/DmWindow.tsx, ui/src/logic/useScrollerMessages.ts
This PR fixes scroller jumps inside threads. The root issue was that `hasLoadedNewest` and `hasLoadedOldest` didn't match reality in thread contexts. While fixing that, I realized it'd be simpler to track load direction by just passing loading parameters in directly and updating state when they change. That way, we only invert the scroller if we're *actually* loading a new page. 
Fixes LAND-1295
=> scroller: fix jumping in threads

desk/lib/channel-utils.hoon, ui/src/state/channel/channel.ts
Fixes LAND-1273
Count was not updating because of the use of useMemo on `posts` in useInfinitePosts. React doesn't do a deep comparison on objects passed into the dependency array. I assume we want to keep the useMemo here, so I stringified the object and used that in the useMemo.
And we weren't getting more than one avatar for threads because last-repliers always returned just one ship, this was due to a bug in `get-last-repliers` in channel-utils. We weren't actually modifying the replyers face.
=> chat: thread fix omnibus

ui/src/types/channel.ts
fixes LAND-1297 by removing code blocks from the list of content types we expect to store as "block" content (confusingly, these are stored and rendered as inlines).
=> channels: fix issue with posting code blocks

ui/src/components/References/CurioReference.tsx, ui/src/components/References/NoteReference.tsx, ui/src/components/References/ReferenceBar.tsx, ui/src/components/References/WritBaitReference.tsx, ui/src/components/References/WritBaseReference.tsx, ui/src/components/References/WritChanReference.tsx, ui/src/state/channel/channel.ts
fixes LAND-1262 by showing the UnavailableReference component when we get an error on fetching the referenced post.
=> refs: show user when reference content is unavailable

desk/app/chat.hoon
Fixes LAND-1282 by adjusting which ship is in the noticed based on who the join is coming from
=> chat: use correct ship for notice

desk/app/chat.hoon, desk/mar/chat/negotiate.hoon, ui/src/dms/NewDm.tsx, ui/src/logic/useMessageSelector.ts, ui/src/state/negotiation.ts
Previously, you could not set up a new multi DM if you hadn't already messaged with the ships in question because they wouldn't have negotiation status and we're blocking the input if we don't have a match.
This PR updates the backend to allow a poke that initiates negotiation and updates the frontend to send that poke when attempting to create a new multi dm. The UI will indicate that it's loading while that negotiation happens and inform the user if they can't create the DM because of a version mismatch.
Fixes LAND-1307
=> dms: fix new multidm negotiation blocking

desk/app/channels.hoon, ui/src/app.tsx, ui/src/chat/ChatChannel.tsx, ui/src/notifications/Notification.tsx, ui/src/replies/ReplyMessageOptions.tsx
This fixes LAND-1271, which was an issue where clicking on a reply notification would route the user to either a blank page (for notebooks and galleries) or the parent chat channel (without opening the thread pane).
The backend was sending a generic path that looks like this:
`/post/{postId}/{replyId}`
This was a problem for the frontend for two reasons:
1) The router does not expect anything at /post/ in any channel.
2) The router also doesn't expect anything after the {postId} token.
This PR updates the backend to send a path that includes the appropriate post type in the path (e.g., `note`, `curio`, `message`) for reply notifications.
It also updates the router to allow an optional param after the {postId}, which I called `idReplyTime`. We currently don't use it on the frontend, but we …
=> notifications: make sure user is routed to appropriate path from a reply notification

desk/app/channels-server.hoon
We were only allowing a post to be deleted if the ship attempting to delete it was the author, we need to allow admins to delete posts too.
Fixes LAND-1317
=> channels: allow admins to delete posts

ui/src/state/channel/channel.ts, ui/src/types/channel.ts
We were ignoring updates about showing/hiding posts, and we were also failing on hearing an update that didn't match the ChannelsResponse type.
Fixes LAND-1321
=> channels: update cache when we hear a fact about showing/hiding a post

ui/src/state/channel/channel.ts
fixes LAND-1322
This onSettled method was unnecessary and was causing cached sent posts to be dropped from the cache.
=> replies: don't refetch in onsettled, caused rescry that squashed cached sent message

talk/app/talk-cli.hoon
Otherwise, post-migration, it imports the new chat types, which are slightly different.
=> talk-cli: import chat structures v2 always

ui/src/state/chat/chat.ts, ui/src/state/chat/keys.ts
Right now you can get a double "joined the chat" message if you accept a DM invite in multiple places (on your phone and on desktop for example). This is because the `chat` agent isn't sending an update on the `dm/invited` subscription when an rvsp is processed.
We do however emit an unread notification for the chat. This PR just updates the unread logic to check if the message we received corresponds to a pending DM and invalidate pending data if it does. This causes the pending state to update successfully across clients.
Fixes LAND-1281
=> dms: ensure rsvp'ing for a pending dm triggers an update

ui/src/replies/ReplyReactions/ReplyReaction.tsx, ui/src/state/channel/channel.ts
This fixes LAND-1309.
There were several issues:
1) ReplyReaction's call to addReplyFeel was broken due to a bad nest. This caused adding +1 reactions to fail.
2) We were calling onSettled in useAddPostReact, which would cause an unnecessary re-scry which could temporarily make it look as if your reaction was not successful in the main chat window.
3) We weren't appropriately highlighting *your* reaction, which may make it look like the reaction didn't go through.
=> emojis: fix issues with adding emojis in chat

ui/src/groups/Join/JoinGroupModal.tsx
When you join a group through a reference in Talk, it navigates to a blank page since the path only works in Groups. 
This updates it to not navigate automatically. Instead the group modal will stop spinning and show a "Go" button which navigates correctly.
Fixes LAND-1320
=> join modal: don't automatically navigate after join if in Talk

ui/src/components/References/CurioReference.tsx, ui/src/heap/HeapBlock.tsx
We explode in dev and silently error in prod for curio references right now. In HeapBlock, a nest is required as part of the logic but is only loaded from nav params. This fails when we're not actually in the correct channel.
This updates the cite nest to be passed along as an optional prop to HeapBlock which it can use instead in the case of references.
Fixes LAND-1330
=> curio ref: pass cite nest along since we cant get it from the nav params

desk/app/channels.hoon
fixes LAND-1313
If the user selects "All messages" in the notification settings for a channel, they will now receive notifications for all messages.
=> notifications: add support for receiving a notification for all messages in a channel

ui/src/diary/DiaryCommentField.tsx
fixes LAND-1285 by allowing users to paste in refs in notebook and gallery comments (following the same pattern we use in ChatInput). Note that DiaryCommentField is used as the input in both diary comments and heap comments.
=> refs: allow posting of refs in notebook and gallery comments

ui/src/components/References/CurioReference.tsx, ui/src/components/References/NoteReference.tsx, ui/src/components/References/WritBaitReference.tsx, ui/src/components/References/WritChanReference.tsx, ui/src/state/channel/channel.ts
Fixes LAND-1346. The backend will return `null` for our `said` requests if we're requesting a post from a private group that we don't have access to. This change accounts for that.
=> refs: show as unavailable when remote post data is null

ui/src/logic/utils.ts
Fixes LAND-1349. I had thought useCopyToClipboard did this for us, but apparently not.
=> clipboard: add fallback function for non-secure contexts

ui/src/chat/ChatEmbedContent/ChatEmbedContent.tsx
Currently, users can post links with `javascript:` URLs. Although links open in a new tab by default, there are several tricky ways to turn this into XSS. Viz,
This change borrows a [regex from dompurify](https://github.com/cure53/DOMPurify/blob/main/src/regexp.js#L9-L11) to only allow safe protocols in links. "Bad" protocols are simple replaced with a blank link. Even when Tlon implements a stronger CSP, it's worthwhile to prevent `javascript:` links, because some users run Landscape apps outside of Tlon (eg red horizon). They should be protected, even if their hosting environment lacks a strong CSP.
Really this PR is a chance for me to practice interacting with this repo, so I invite any criticism you may have. I'm excited to tackle bigger bugs, thanks!
=> chat: only allow "safe" URL protocols in links

ui/src/state/channel/channel.ts
Sometimes (such as viewing a thread in mobile, after you've directly navigated to it via a notification or similar), we don't get updates via the subscription in useInfinitePosts, but we do via the subscription in useChannels. This PR adds a call to infinitePostsUpdater in the onEvent handler in useChannels so that we can be sure to update the cache appropriately when we hear these facts.
Calling it in both places shouldn't cause an issue, and doesn't seem to in my testing.
Fixes LAND-1338
=> threads: account for the fact that we sometimes only hear facts via the subscription in useChannels

ui/src/chat/ChatWindow.tsx, ui/src/dms/DmWindow.tsx
Fixes LAND-1331 (and any other case where our scrollTo message falls outside of currently loaded messages).
Previously, the scroller would just scroll to the top of what we currently have and useInfinitePosts wouldn't refetch to get messages around the message in question.
I also added a comment to another, related useEffect to make things a bit clearer.
=> chat: make sure we load in appropriate data when scrolling to a message outside of our current messages

ui/src/state/channel/channel.ts, ui/src/state/chat/chat.ts
Fixes LAND-1354 by marking a chat as read via useChatStore's read method if we hear a fact telling us that the chat is read. Previously we just called the `unread` function from useChatStore no matter what on hearing an unread fact about a chat channel.
=> unreads: mark a chat as read when we hear that fact on unreads subscription

ui/src/dms/DMOptions.tsx
Fixes LAND-1362. We were using the dm `markRead` function even if it was a chat channel, previously.
=> talk: fix issue with marking read from sidebar

ui/src/chat/ChatSearch/ChatSearchResult.tsx
I think this was caused by an unnecessary useMemo that had the writ object in the dependency array. React can't diff an object like that. If we need a useMemo here we could stringify the object.
fixes LAND-1368.
=> chat: remove useMemo, make sure reacts is defined before calling object.keys() in ChatSearchResult

ui/src/chat/ChatMessage/ChatMessage.tsx
Can't recreate Pat's report of sent time hover still wrapping, but just to be safe.
=> chat: defensively prevent sent time from wrapping

ui/src/chat/ChatThread/ChatThread.tsx, ui/src/chat/ChatUnreadAlerts.tsx, ui/src/chat/ChatWindow.tsx, ui/src/chat/DMUnreadAlerts.tsx, ui/src/dms/DMThread.tsx, ui/src/dms/DmWindow.tsx, ui/src/state/channel/channel.ts, ui/src/state/chat/chat.ts
Fixes LAND-1364, the scrollTo refetch bug issue. This was caused by the use of the `msg` param in the case of a message we wanted to highlight within a thread. We used the same param for scrollTo in the ChatWindow, and since we couldn't find the scrollTo in the existing messages (and never would since it exists outside of the main chat window, in a thread) the new useEffect that fixed search was firing in a loop. This was fixed by changing the url param for finding a thread message to `thread-msg`.
Also fixes LAND-1331 by adding the useEffect back in, this time with a new dependent variable that uses either the parent ID in the router or the id from the `msg` param. This same variable is also used to scroll to the thread parent in the main window, which is something that wasn't working on …
=> chat: fix infinite refetch bug with scrollTo, fix chat bug, navigate to thread parent

ui/src/chat/ChatInput/ChatInput.tsx
We have a bug right now where if you're replying in Chat and a new message comes in, the hook that sets the editor mention is always firing which clears away any other text you already had. 
This PR just checks to see if we actually need to set the mention before doing so.
Fixes LAND-1340
=> chat: when replying, only reset the message editor if we don't already have the mention

ui/src/components/Avatar.tsx, ui/src/components/ShipName.tsx, ui/src/components/Sidebar/GroupsSidebarItem.tsx, ui/src/components/Sidebar/Sidebar.tsx, ui/src/components/Sidebar/SidebarItem.tsx, ui/src/groups/GroupAvatar.tsx, ui/src/groups/GroupSidebar/ChannelList.tsx, ui/src/groups/GroupSidebar/GroupSidebar.tsx, ui/src/logic/channel.ts, ui/src/state/groups/groups.ts
(partially) Fixes LAND-1360 by reducing re-rendering throughout the Sidebar and GroupSidebar components and their children. 
One major source of re-rendering was the data from useGroup() getting wiped on navigating away from a group, which caused the GroupSidebar itself to re-render and show loading state/skeleton on the way out. I added `keepPreviousData` to the useGroup() query to keep current data *until* we want to load in a new group.
I also memoized as much as seemed appropriate throughout.
I played around with animationConfig settings in GroupsNav, but nothing stood out as actually improving the perceived speed.
I also attempted to use framer-motion's `useIsPresent` hook to prevent certain components from rendering (including preventing group images from loading in the sidebar), …
=> perf: tweaks to speed up sidebar transition on desktop

ui/src/groups/GroupActions.tsx
We were passing the wrong identifier to check the host connection from the group action menu causing it to always show a connection failure. Status there will now match what's displayed in the top nav.
Fixes LAND-1381
=> group actions: fix broken connection status

ui/src/chat/ChatSearch/ChatSearchResult.tsx, ui/src/dms/DmWindow.tsx, ui/src/logic/utils.ts
In `DmWindow` when refetching to get a "scroll to" message, we can get stuck in a refetch loop if for some reason we get a successful scry but still don't see the message we're looking for in the result. This can happen in DM threads where we sometimes check against the wrong key to determine whether or not we have the message in question.
This PR avoids the refetch loop in these situations by making the logic for determining whether or not we have a message more robust.
Fixes LAND-1416
To test this, run two ships against `develop` and have a DM between them which exceeds the single page limit of 50 messages (needed to trigger the conditional). If you navigate to a thread in the DM, you'll get the loop.
=> dm threads: account for mismatched keys when checking if we have a message after refetching

ui/src/logic/utils.ts
Updates regular expressions to treat `.webm` links as videos. This fixes an issue where when a message is just a single `.webm` URL, it wasn't posting at all. It also allows `.webm` videos to be rendered in embedded `<video>` tags on the front-end.
=> treat webm urls as videos

ui/package-lock.json, ui/src/chat/ChatEmbedContent/TwitterEmbed.tsx, ui/src/components/icons/TwitterXIcon.tsx
- Updates `react-tweet` API fallback to display the tweet contents that we got from `noembed.com`
- Updates `react-tweet` module to the latest version
- Updates icon to use new X logo
Before
After
=> add fallback rendering of tweet content

ui/src/components/WelcomeCard.tsx, ui/src/nav/MobileRoot.tsx, ui/src/notifications/Notifications.tsx, ui/src/state/settings.ts
This brings the welcome card up to date with the copy and styling in Figma. Adapts it to be shown on desktop views as well, positioned above the activity feed on the home screen.
Closed status is no longer stored locally on the frontend, instead its tracked in the settings agent. This means closing the card once will hide it on all clients.
Fixes LAND-1399
=> welcome card: update style, copy, and behavior

ui/src/replies/ReplyMessage.tsx, ui/src/replies/ReplyMessageOptions.tsx
Fixes crash when you click into an activity notification for a thread reply that was deleted. It still navigates you to a weirdly empty thread, but that can be addressed with better UX at a different time
=> fix crash when navigating to deleted reply from activity

ui/src/state/chat/chat.ts
Fixes LAND-1426 because we forgot to create the unread state after initializing DM unreads, would happen both for refresh and reconnects.
=> chat: make sure we make blue dots on refresh

ui/src/heap/EditCurioForm.tsx, ui/src/heap/useCurioActions.ts, ui/src/state/channel/channel.ts
- Fixes issue with gallery item not able to be deleted from the item details page
- Fixes the `useDeletePostMutation` hook never firing `onSuccess` because of mismatched time formats
=> groups: fix issue with deleting gallery item from item page

ui/src/chat/ChatMessage/ChatMessage.tsx
Fixes LAND-1406, we shouldn't need to take into account the dialogs on mobile since `ChatMessageOptions` is rendered always on mobile.
=> chat: prevent action menu from covering image dialog

ui/src/replies/ReplyMessageOptions.tsx
Fixes positioning of reply message options on long thread replies
=> fix positioning of options on long reply messages

ui/src/heap/HeapDetail.tsx, ui/src/state/channel/channel.ts
Simplifies gallery navigation logic and fixes issue with navigating to empty/deleted detail page
=> fix gallery next and prev navigation

ui/src/channels/HostConnection.tsx, ui/src/components/ActionMenu.tsx, ui/src/components/ShipConnection.tsx, ui/src/groups/GroupActions.tsx, ui/src/groups/GroupSidebar/ChannelList.tsx, ui/src/logic/utils.ts, ui/src/styles/components.css
Fixes LAND-1397. 
Brings GroupActions into alignment with the design linked in LAND-1397:
- Adds a "row" mode to HostConnection to fit the sheet design
- Groups common actions together and adds spacing between groups
- Adds subtitles to each action
- Conditionally hides/shows the "Leave group" option for members (vs admins, who should 'delete' the group or ask to have their role removed)
- Removes the "Channels" | "Members" | "Invite People" items from the top of the mobile ChannelList and adds a TODO to add the welcome bubble for admins who have created a new group.
Note that this PR converts all ActionMenus to use the "sheet" treatment on mobile (full-width, no gutter, attached to screen bottom). This PR also only touches the contents of the GroupActions dropdown/sheet.
This PR does …
=> groups: redesign group options sheet

ui/src/heap/HeapRow.tsx
- Fixes issue with gallery image thumbnails not loading in list view
- Fixes issue with gallery item delete button not working in list view
https://github.com/tloncorp/landscape-apps/assets/1013230/df7b75df-9261-4474-9577-0d3d6259900f
=> groups: fix gallery image view and delete button in list mode

desk/app/groups.hoon
These changes fix a bug reported by `~darted-laster` in `~tommur-dostyn/tlon-studio/~tommur-dostyn/support` about new ships being unable to join groups containing a custom channel.
Please note that I've only tested the following workflows:
1. Joining a group containing a custom channel (i.e. `~hiddev-dannut/new-hooniverse`) on the livenet from a comet
2. Leaving the same group on the livenet from a comet
Please let me know if other workflows should be testing before merging.
=> fix issue with joining/leaving groups containing custom channels

ui/package-lock.json, ui/package.json, ui/src/dms/DmInviteDialog.tsx
- Fixes the dropdown getting cut off on the multi-party DMs invite dialog
- Adds `lint-staged` to `devDependencies` because the pre-commit hook using `npx` was grabbing v15 by default, which is not compatible with Node v16
=> talk: fix dropdown on multi-dms invite dialog

desk/app/channels-server.hoon, desk/app/diary.hoon, desk/app/groups.hoon, desk/app/heap.hoon, desk/lib/channel-utils.hoon
The groups agents (channels-server, diary, heap) do some dumb stuff. Specifically, whenever permissions change _at all_, they re-run permission checks for _all subscribers_ to _all channels_ in the group where the change happened.
This is dumb, and they should be smarter about it, but urbit is fast, it shouldn't be a _huge_ deal. Except, "running a permission check" involves scrying into the groups agent, which has non-trivial overhead.
The fix is equally dumb: don't improve the logic, just remove the overhead. This brings us down from "tens of milliseconds per subscriber" to "tens of _microseconds_ per subscriber".
Instead of only exposing a per-channel per-ship scry endpoint for checking read permissions, groups now also exposes a generic endpoint that produces a gate. This gate can be …
=> groups: expose "can-read" as gate through scry

desk/app/groups.hoon
+verify-group-cabals was still poking agents using the names given in the nest, but those have been deprecated in favor of channels-server. Here, we make sure to always poke channels-server with a new-style channel-command instead.
Somewhat untested, somehow I couldn't get into this branch of the code (or even get the role deletion to stick). @arthyn this is probably better than "100% certainly broken", but we should probably pair on actually running the new code here.
=> groups: poke %channels-server, not old agents

ui/E2E.md, ui/e2e/001-create-group-channels-invite.spec.ts, ui/e2e/002-non-admin-post-to-channels.spec.ts, ui/e2e/003-post-note-with-markdown.spec.ts, ui/e2e/auth.setup.ts, ui/e2e/shipManifest.json, ui/playwright.config.ts, ui/rube/index.ts, ui/src/components/Settings/Setting.tsx, ui/src/diary/DiaryMarkdownEditor.tsx, ui/src/diary/DiaryNoteHeader.tsx, ui/src/diary/diary-add-note.tsx
This PR:
- Adds configuration to boot two fake planets (from pre-saved piers in gcloud) for e2e tests
- Keeps the two galaxies we were using (~zod and ~bus) to enable "fake" routing between the two planets
- Updates existing tests to use the two new planets instead of ~zod and ~bus
- Adds new specs file 003 to cover markdown and editing notes
- Updates the readme
=> Groups e2e: add/edit note using markdown Land-1240

desk/app/channels.hoon
This addresses an issue from https://github.com/tloncorp/landscape-apps/pull/3169 where poke acks from adding contacts on channel join weren't handled.
=> Handle poke-ack from adding contacts

ui/src/app.tsx, ui/src/components/EmojiPicker.tsx
Resolves LAND-1391
Resolves LAND-1460
Adds a new route to support showing the emoji picker on mobile when deep-linking to a specific message in a thread via activity tab/push notifications
=> add route to support thread reacts

ui/src/app.tsx
This was a regression from when we renamed %garden/grid to %landscape, reported by ~nallux-dozryl
=> app: fix grid/landscape redirects

desk/app/channels.hoon
https://linear.app/tlon/issue/LAND-1058/contacts-on-fetch-of-posts-collect-new-authors-to-register-as-contact
This doesn't check whether we're adding someone we already have as a contact. I think that it's better for %contacts to make that idempotent than checking it here, which it looks it does but I'm not 100%.
=> LAND-1058: Fetch new post authors as contacts

ui/package-lock.json, ui/package.json
Fixes LAND-1481, had too many people affected and wasn't currently broken so I've just reverted to a previous version that doesn't use `color-mix`.
Tested by downloading Chrome 110, the last version that didn't support `color-mix`.
PR Checklist
=> pkgs: revert theme swapper to 0.9.0

ui/src/logic/DragAndDropContext.tsx
The main issue I was able to reproduce while testing was that events would fire more often than expected which prevented us from triggering the logic to end the drag when it detects a `dragleave` event. This updates it to always cancel the drag if it leaves the window. Also prevents a drag from being initiated if the document isn't visible. 
Together this seemed to fix any issues I found locally, but we'll need to see if the bug persists after merging since it presents sporadically.
Tested locally against self & hosted ships.
Fixes LAND-1463
PR Checklist
=> drag & drop: prevent getting stuck in drag state

ui/src/groups/Members.tsx, ui/src/groups/RoleInput/RoleSelector.tsx, ui/src/groups/RoleInput/SetRolesDialog.tsx
When the members view got overhauled for mobile, the desktop version had broken role selection. This adds a corresponding dialog to be used when not on mobile.
Tested locally against a hosted ship.
Fixes LAND-1482
PR Checklist
=> members view: fix role selection on desktop

ui/src/logic/DragAndDropContext.tsx, ui/src/state/storage/upload.ts
This seems to just have been an issue with spaces in the filename as expected. Uploading screenshots on Mac should now work in Safari.
While testing this, I noticed a regression with the drag & drop fix from the other day as well. There's a long outstanding bug with handling a key `dragleave` event property in Safari which was causing the drag hover state to flicker or fail. This PR also smuggles in a way to combat that while leaving in place the fix for other browsers.
Worked locally against a self-hosted ship in Safari & Chrome. Whoever tests  this, please verify drag & drop works in both gallery and chat contexts on both browsers.
Fixes LAND-1446
PR Checklist
=> drag & drop: fix dragging Mac screenshots into galleries

ui/src/state/channel/channel.ts, ui/src/state/channel/util.ts
If a new message comes in while you're viewing a scroll-back (search or message ref clicked), it will be added to the cache directly after the loaded message history. This can lead to a weird gap between new messages and the point in the history you were viewing. An automated refetch is fired which resolves the situation, but it can take a bit depending on network conditions leaving you in a weird state until the refetch completes.
This prevents that scenario by checking to see if you have the newest messages before adding incoming ones to the cache.
Fixes LAND-1478
PR Checklist
=> chat: prevent gap in message history when viewing scrollback

ui/src/logic/utils.ts
This dude had a s3 bucket with urls that always contain a `:` and talk wasn't rendering them inline. This fixes the problem.
Also, `|` is not the or condition inside a character set.
=> utils: better IMAGE_URL_REGEX

desk/app/channels-server.hoon
Fixes LAND-1436, which was an issue where one writer couldn't edit another writer's post. I don't think we actually want writers to be able to edit other writer's posts (at the moment this would mean that anyone who has write access to the notebook at all, such as commenters, could edit the post, it would also mean that we couldn't use %edit for editing chat messages with the perms as-is, as it would allow anyone to edit anyone else's messages).
Instead of allowing writers to edit other writers' posts we can allow admins to edit any post.
In general, notebook perms need to be fleshed out a bit more (and probably treated separately from chat and gallery perms). This is a bandaid on that problem.
Tested with two livenet moons, locally.
PR Checklist
=> notebooks: allow admins to edit posts they didn't author

desk/app/channels-server.hoon
Currently the delete reply arm asserted that you were the author in order to delete a reply. It should instead also allow the action if you're an admin. This PR just updates that line accordingly.
This also explains why it was working for top level posts, but not replies (the top level post arm already had both checks).
Tested with a local ship, deleting replies from a hosted ship.
Fixes LAND-1483
PR Checklist
=> chat: allow admins to delete replies

ui/src/diary/diary-add-note.tsx, ui/src/types/channel.ts
Fixes LAND-1404 by making sure we send code blocks as `blocks` in notebook posts.
Only handled as blocks in notebook posts, nothing changes for chat posts.
Inline and block code still render correctly in chat messages, and now both render correctly in notebook posts.
Tested locally on a livenet moon.
PR Checklist
=> notebooks: properly handle code blocks

ui/src/components/Sidebar/Sidebar.tsx, ui/src/nav/MobileRoot.tsx
OTT
Tested locally against a hosted ship.
Fixes LAND-1540
PR Checklist
=> groups: make sure segmented groups are filtered from the main list on mobile

ui/src/dms/MobileMessagesSidebar.tsx, ui/src/nav/TalkNav.tsx, ui/src/state/settings.ts
OTT
Tested locally against hosted ship.
Fixes LAND-1541
PR Checklist
=> talk sunset: correctly register if you've already seen the sunset banner & add passive indicator on mobile

ui/src/app.tsx, ui/src/notifications/Notifications.tsx, ui/src/notifications/useNotifications.tsx
Fixes title so it no longer says "undefined", makes sure you can see all activity, and adjusts some copy that was confusing. Tested by opening app locally and looking at title bar, activity indicator, and notifications screen.
PR Checklist
=> app: fix inconsistencies from previous talk/groups split

ui/src/components/Sidebar/MessagesSidebarItem.tsx, ui/src/components/Sidebar/SidebarTopMenu.tsx, ui/src/logic/useMessagesUnreadCount.ts
Accounts for what your messages sidebar filter is. Displays number of unread channels/DMs, not total message count.
Tested locally against a hosted ship.
Fixes LAND-1417
PR Checklist
=> desktop nav: display unread count on messages tab

ui/src/logic/useMessagesUnreadCount.ts
OTT
Was noticing a bug with the new nav messages tab count PR that sometimes causes a crashing bug on desktop. Need to check that pins have an actual unread before reading their `count` prop
PR Checklist
=> desktop nav: fix crashing error in new messages nav tab count

.github/workflows/deploy-canary-groups.yml, .github/workflows/deploy-groups.yml
=> ops: better defaulting github action input

ui/src/logic/useAppUpdates.ts
Fixes LAND-1550 by adding in a large delay if only hashes have been detected as being different. Otherwise if the service worker detection it will pop the banner immediately.
PR Checklist
=> updates: prevent update banner from showing multiple times

ui/src/chat/ChatChannel.tsx, ui/src/chat/ChatThread/ChatThread.tsx, ui/src/dms/Dm.tsx, ui/src/dms/MultiDm.tsx, ui/src/env.d.ts, ui/src/logic/utils.ts
OTT
Talk ripout removed an env var causing navbar padding insertion checks to fail. Removes the env var from our types and updates the checks.
Fixes LAND-1546
PR Checklist
=> chat: fix missing message input on mobile

desk/app/channels.hoon
Scrying for a reply message would produce a noun marked with the %channel-reply mark, but the noun itself wouldn't nest in the type of that mark.
Here, we add a cast to the appropriate type, and "unversion" the reply noun that was being produced to coerce it into the correct shape.
Resolves LAND-1531.
=> channels: make reply scry response match mark type

ui/src/app.tsx, ui/src/components/Sidebar/MobileSidebar.tsx, ui/src/components/Sidebar/Sidebar.tsx, ui/src/nav/MobileRoot.tsx
Removes the "Find Groups" or "Discover" tab from the mobile navbar and the desktop sidebar. This also removes the empty-state notices that point the user to said "Discover" tab or "Find Groups" page.
Tested locally with a moon in zero groups and locally with a planet in >50 groups.
The below screenshots show a new, self-hosted moon (the absolute base case). A new hosted planet will be joined to Tlon Studio and Tlon Local; the green banner will still be present.
Fixes LAND-1197
PR Checklist
=> groups: eliminate discover/find interface

ui/src/components/Leap/useLeap.tsx
This changes behavior of leap when selecting a ship so that it brings you to the DM instead of opening the profile in Groups and also keeps you in the Messages tab if you select a channel and were already in the Messages tab.
PR Checklist
=> leap: QoL improvements for Talk expats

ui/src/components/Sidebar/AddGroupSidebarItem.tsx, ui/src/components/Sidebar/GroupList.tsx, ui/src/components/Sidebar/MessagesSidebarItem.tsx, ui/src/components/Sidebar/Sidebar.tsx, ui/src/components/Sidebar/SidebarItem.tsx, ui/src/components/Sidebar/SidebarTopMenu.tsx, ui/src/components/Sidebar/util.tsx, ui/src/nav/GroupsNav.tsx, ui/src/state/settings.ts
Moves search up into the top section of the sidebar to avoid double scroller after adjusting the viewport. Also adds logic to save the navigation state for the groups and messages tabs so you can pick up where you left off when returning to the tab. 
Right now this is only enabled for messages since it's unclear how this should work for groups given the current in-group sidebar transition and back behavior. It's a one line change to add it to groups as well if we figure out a way to go that route.
Fixes LAND-1553
Fixes LAND-1554
PR Checklist
=> desktop sidebar: fix double scrollbar and persist nav location when tab switching

desk/app/profile.hoon, desk/app/profile/widgets.hoon
Removes the horizontal and vertical scrollbars in the public profile view. Also makes some stricter rules about widget width and overflow, thus keeping the right edge of the 'Message me on Tlon' button from getting cut off.
Tested on a local live ship; screenshots attached.
Fixes LAND-1561
PR Checklist
=> profile: fix scrollbars, overflow cutoff

ui/src/components/EmptyPlaceholder.tsx, ui/src/dms/MessagesList.tsx, ui/src/dms/MobileMessagesSidebar.tsx
OTT
Tested against a local ship.
Fixes LAND-1567
PR Checklist
=> mobile DMs: fix missing non-pinned messages header regression

ui/src/logic/useMessagesUnreadCount.ts, ui/src/state/channel/channel.ts, ui/src/state/chat/chat.ts
Fixes LAND-1574.
We were using the unread state synced from the backend for the unread count on the messages tab button. This caused a delay in updating the count due to the delay in the updated state.
If we switch to using the chat store unreads, the count updates immediately (we use this same state to update the unread "blue dots").
Tested locally with livenet moon and planet messaging each other, and with pinning some active group chat channels.
PR Checklist
=> unreads: use chat store unreads for sidebar count

ui/src/chat/ChatContent/ChatContent.tsx, ui/src/chat/ChatEmbedContent/ChatEmbedContent.tsx, ui/src/chat/ChatInput/ChatInput.tsx, ui/src/components/MessageEditor.tsx, ui/src/constants.ts, ui/src/heap/AddCurioModal.tsx, ui/src/heap/HeapChannel.tsx, ui/src/state/storage/upload.ts
This PR fixes LAND-1480 by allowing users to upload videos.
We already supported rendering video content in chat and galleries, we just didn't support user uploads for it.
This PR simply adds similar functionality to what we already had for image uploads, for video. As in, you can pick it from the file picker, drag and drop it, or paste it.
There is on hacky part, you'll see a TODO about it in ChatContent.tsx.
Tested on both a local moon for regular s3 storage, and by distributing from a moon to a hosted ship to test tlon storage.
Not sure that we can test this automatically e2e without some pretty detailed setup to get tlon storage working in our e2e tests.
https://github.com/tloncorp/landscape-apps/assets/1221094/d804e54f-8184-42fd-a9b8-dcbd48fcd7ac
PR Checklist
=> s3: allow video uploads

ui/src/chat/ChatContent/ChatContent.tsx, ui/src/components/References/WritBaseReference.tsx
Fixes LAND-1409.
Fixes the issue where clicking a link within a ref would both follow the link and navigate to the ref.
Fix consists of making sure the user is actually clicking on the ref itself, not the link.
Further explanation in in-line comments.
Tested locally on livenet dev moons by making some refs with links in them.
PR Checklist
=> refs: fix issue with clicking links in refs

desk/app/channels.hoon
PR Checklist
`app/channels.hoon`
Livenet moons
N/A
N/A
=> LAND-1568: Add contact on new post fix

desk/desk.docket-0
Fixes LAND-1573.
Before, in dark mode. Note that you can't really even see the boundaries of the app tile rectangle, much less the T-block inside:
After:
Light mode before/after:
Tested locally with a livenet moon.
PR Checklist
=> docket: better app tile contrast in dark mode

apps/tlon-mobile/metro.config.js, apps/tlon-mobile/src/App.tsx, apps/tlon-mobile/src/tamagui.d.ts, package-lock.json, packages/ui/README.md, packages/ui/package.json, packages/ui/src/components/Button.tsx, packages/ui/src/components/TamaguiProvider.tsx, packages/ui/src/index.ts, packages/ui/src/tamagui.config.ts, packages/ui/src/tamagui.d.ts, packages/ui/tsconfig.json
This PR performs initial setup of tamagui in the native mobile app. Tamagui components are kept in a separate package (`ui`) to help keep it encapsulated, since the longer term goal is to use it in both the web and native apps.
How to test:
- Build the mobile app
- Try using `Button` from `@tloncorp/ui`
=> native: add tamagui

.github/workflows/ci.yml, .github/workflows/deploy-talk.yml, .github/workflows/deploy.yml, .github/workflows/glob-and-deploy-kernel.yml, package.json
Without this you could run into eslint/ts errors on importing the package (until you manually build the package or run the dev script for it).
=> chore: add npm run build:shared to postinstall on root package

apps/tlon-web/src/chat/ChatChannel.tsx
Since the nav bars of groups and talk were combined, when viewing a Group Chat using the Messages tab on desktop, the ChatChannel view does't recognize the search route if  the Search button is clicked. In this case, the URL has a "/dm/groups" portion (instead of "/groups" as when in the Groups nav tab). Chat input should not be focused in those cases to allow the search input to be used.
Fixes LAND-1577
Tested locally with livenet ship
PR Checklist
=> Search: Don't focus ChatInput for /dm/groups/... routes

apps/tlon-web/src/notifications/Notification.tsx
Fixes LAND-1544 by ensuring that we show the alias for a ship name (if we have it) in the notification content in the activity view.
Tested on local livenet dev moon.
PR Checklist
=> activity: show contact alias for ship name in notification content

apps/tlon-web/src/state/bootstrap.ts, apps/tlon-web/src/state/channel/channel.ts, apps/tlon-web/src/state/channel/keys.ts, apps/tlon-web/src/state/chat/chat.ts, apps/tlon-web/src/state/chat/keys.ts
Fixes LAND-1556.
getQueryData was always returning undefined in my testing locally, so rather than only refetching if we have cached data for a query, we just fetch the query if we have an unread for the channel (since we know we *will* use that data later).
I also noticed that channelKey in state/channel/keys.ts was using 'channel' rather than 'channels'. 'channel' isn't used as a queryKey anywhere afaict, I assumed this was supposed to be 'channels', so I changed that.
Tested locally with livenet moons.
PR Checklist
=> channels: make sure channel data is up to date when we have unreads

desk/app/profile.hoon
This way, emoji and other unicode will render as expected.
=> profile: include utf-8 charset tag

desk/app/channels.hoon, desk/app/groups.hoon, desk/lib/subscriber.hoon, desk/tests/app/channels.hoon, desk/tests/app/groups.hoon
Fixes LAND-1527 by adding a library with a mechanism for us to delay resubscriptions by 30 seconds to ensure that we don't take up all CPU/event throughput of a ship when in a kick + resubscribe loop. This was added to only groups and channels, but could stand to be applied elsewhere.
PR Checklist
=> subscriptions: kick resub ddos protection

apps/tlon-web/src/state/storage/upload.ts
Fixes a TypeError in upload.ts when uploading to a S3 bucket without a publicUrlBase set in the %storage config. 
Uploading an image was throwing a `Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL` error. I interpret this to mean that we were failing to instantiate a variable with a URL type because the `new URL()` function takes a single argument (which cannot be null). Open to other, cleaner fixes.
Tested locally with the Vite dev server proxied against my livenet planet.
PR Checklist
=> upload: handle no publicUrlBase

apps/tlon-web/src/chat/ChatScroller/ChatScroller.tsx, apps/tlon-web/src/chat/ChatScroller/ChatScrollerDebugOverlay.tsx, apps/tlon-web/src/chat/ChatThread/ChatThread.tsx
This reverts the changes made to invert the scroller direction based on reading direction, from #3236
Also adds more logging so we can get some more insight into what is changing and when.
Dan and I used the afternoon to try to find what was causing the issue in iOS, couldn't find anything within a reasonable amount of time.
So LAND-1353 is now unresolved.
We ought to pull in the @tanstack/virtual library to our shared packages so we can get some clearer debugging around what's happening in virtual and maybe modify to our needs. I looked at pulling it in, but the package itself uses workspaces and pnpm, so not super straight forward to pull in directly. We should create a ticket for it IMO.
@dnbrwstr let me know if you think we should add logging anywhere else (or feel free to make …
=> scroller: revert reading direction inversion changes

apps/tlon-web/src/components/Leap/LeapRow.tsx, apps/tlon-web/src/components/Leap/MenuOptions.tsx
Changes a few of the default Leap menu items to reflect our current reality:
- Adds "Join a Group"
- Redirects "Create a new Group" to the new, name-only group creation route
- Combines "Profile" and "Tlon Settings" into a single item, "Profile & Settings," which uses the current ship avatar as the icon
- Removes "Find Groups"
- Removes "Tlon"
Also changes the `icon` type to accept a React element (the Avatar component) and handles appropriately in the render of LeapRow.
Fixes LAND-1635
PR Checklist
=> leap: change default menu items, icon type

apps/tlon-web/src/components/ErrorAlert.tsx
Adjusts the error boundary component to send an email to support@tlon.io rather than pre-filling a GitHub issue.
Fixes LAND-1452
PR Checklist
=> errors: send mail to support@tlon.io

apps/tlon-web/src/components/Leap/MenuOptions.tsx
Fixes LAND-1640, a new bug that was introduced on develop yesterday.
Just needed to pass an anonymous function here that returns the component, rather than the component itself.
Tested locally on livenet moons.
PR Checklist
=> leap: fix crash on open

apps/tlon-web/src/channels/ChannelSearch.tsx, apps/tlon-web/src/chat/ChatSearch/ChatSearch.tsx, apps/tlon-web/src/chat/ChatSearch/ChatSearchResults.tsx, apps/tlon-web/src/chat/ChatSearch/MobileChatSearch.tsx, apps/tlon-web/src/chat/ChatSearch/useChatSearchInput.tsx, apps/tlon-web/src/constants.ts, apps/tlon-web/src/dms/DmSearch.tsx, apps/tlon-web/src/dms/MobileDmSearch.tsx, apps/tlon-web/src/logic/utils.ts, apps/tlon-web/src/state/channel/channel.ts, apps/tlon-web/src/state/chat/search.ts, apps/tlon-web/vite.config.ts, desk/app/channels.hoon, desk/app/chat.hoon, desk/lib/dm.hoon, desk/mar/channel/scam.hoon, desk/mar/chat/scam.hoon, desk/sur/channels.hoon, desk/sur/chat.hoon, package-lock.json, packages/shared/package.json, packages/shared/src/urbit/channel.ts, packages/shared/src/urbit/dms.ts
Primarily, we give channels and chat a new search api endpoint, which bounds its requests by messages _searched_, rather than the amount of search results _found_.
The existing search api is bounded by the amount of results returned. This makes searching for something with few results a pathological case: we will continue searching _all_ messages in a channel until we've hit the desired amount of results, or exhausted the entire backlog. This results in search being slow in unpredictable ways.
We add a new search api (that is, a new scry endpoint) where the search is bounded (and paginated) by the total amount of messages searched, rather than the subset that gives results. This way, we can bound the amount of computation that happens for any given "page" of search, making for more …
=> channels, chat: faster search ux

apps/tlon-web/e2e/004-navigate-between-sections.spec.ts, apps/tlon-web/src/chat/ChatChannel.tsx, apps/tlon-web/src/chat/ChatThread/ChatThread.tsx, apps/tlon-web/src/components/About/AboutView.tsx, apps/tlon-web/src/components/Settings/SettingsView.tsx, apps/tlon-web/src/components/Sidebar/AppNav.tsx, apps/tlon-web/src/diary/DiaryNote.tsx, apps/tlon-web/src/dms/DMThread.tsx, apps/tlon-web/src/dms/Dm.tsx, apps/tlon-web/src/dms/MobileDmSearch.tsx, apps/tlon-web/src/dms/MobileMessagesSidebar.tsx, apps/tlon-web/src/dms/MultiDm.tsx, apps/tlon-web/src/dms/NewDm.tsx, apps/tlon-web/src/heap/HeapDetail.tsx, apps/tlon-web/src/logic/position.ts, apps/tlon-web/src/nav/MobileRoot.tsx, apps/tlon-web/src/profiles/EditProfile/EditProfile.tsx, apps/tlon-web/src/profiles/Profile.tsx, apps/tlon-web/src/profiles/ShareDMLure.tsx
Restores the safe area inset for the horizontal (mobile) orientation and compensates for it in each shouldAddPadding check. Has the nice effect of providing two different padding values: one for the native app, one for the mobile PWA.
PR Checklist
=> web/nav: restore safe area inset for mobile nav in native app

apps/tlon-web/package.json, apps/tlon-web/src/state/groups/groups.ts, desk/desk.docket-0
This needs to be tested more thoroughly because it might have far reaching implications. Fixes LAND-1639.
`keepPreviousData` was biting us because if you were coming from another group that would be the data in the query, but then we'd check `canRead` and it would be false because we were comparing against a different group. This caused a redirect to occur to the group home. Then from the group home we try to do the channel redirect and wouldn't find a good candidate so we'd redirect to `${group}/channels`.
Similarly, `placeholderData` didn't seem to be updating every time the flag changed, so I removed entirely in favor of just defaulting to existing data in `useGroups`.
Tested by running locally on both desktop and mobile, navigating to different channels in messages tab and also random …
=> groups: better data loading flow

apps/tlon-web/src/components/Sidebar/AppNav.tsx, apps/tlon-web/src/groups/GroupSidebar/GroupSidebar.tsx
Restores the functionality of the update button on desktop. I was routing to /update-needed, which doesn't exist on mobile and only throws a sheet dialog with _another_ update button.
PR Checklist
=> nav/desktop: wire up update button

apps/tlon-web/e2e/005-mobile-chat-options.spec.ts, apps/tlon-web/src/chat/ChatMessage/ChatMessageOptions.tsx, apps/tlon-web/src/components/ActionMenu.tsx, apps/tlon-web/src/components/EmojiPicker.tsx, apps/tlon-web/src/components/IconButton.tsx
The new nav introduced a z-index issue where the emoji picker wasn't visible on mobile. This simply shuffles where the picker z-index is set ensuring it's again visible.
Also adds a test to make sure we'll catch issues with adding reactions next time.
Tested against a local ship.
Fixes LAND-1641
PR Checklist
=> mobile reactions: fix hidden emoji picker

apps/tlon-web/rube/index.ts
OTT
Updates them to point directly at the vere GitHub release.
Fixes LAND-1658
PR Checklist
=> e2e tests: avoid relying on urbit.org for runtime downloads

apps/tlon-web/e2e/001-create-group-channels-invite.spec.ts, apps/tlon-web/rube/index.ts, apps/tlon-web/src/constants.ts, apps/tlon-web/src/groups/ChannelsList/ChannelManagerHeader.tsx
We still had this value hardcoded to `garden`. It's used in `state/settings.ts` (ultimately used by useMergedSettings, which many other hooks rely on).
=> settings: use %landscape, not %garden

apps/tlon-web/src/logic/useSidebarSort.ts
I was getting annoyed with how slow the sidebar can be, so I did a performance profile and root caused that this particular function was pretty heavy.
Saw a marked improvement in performance for this function by just pre-computing the values for comparison before running the comparison and eliminating the use of .reverse().
Note that this isn't a cure-all, I just decided to take a weed wacker to the tallest weed on a cursory look.
tested locally by running the dev server against my livenet planet.
No idea if there's a linear ticket for sidebar perf.
PR Checklist
=> perf: speed up sidebar sorter

desk/lib/channel-utils.hoon
We were attempting to re-use the `uv-post` arm for `uv-post-without-replies`, but in order to do that we were setting replies to null before calling `uv-post`. This meant that the get-reply-meta arm, when being called from `uv-post`, would show no reply-meta for the post, even if there were replies.
Fixes LAND-1673
Tested locally with livenet moons.
PR Checklist
=> chat: fix missing reply meta on posts in outline requests

apps/tlon-web/src/chat/ChatInput/ChatInput.tsx
~The onUpArrow function being passed into the useMessageEditor hook was causing the chat input to re-render after send.~
~I'm disabling it for now so that it doesn't block getting the edit feature out. We should investigate why it's happening and re-implement later if possible.~
It turns out the re-render is only happening on mobile when `lastMessageId` changes. Not clear why this isn't effecting desktop, but we can effectively fix the issue (and disable onUpArrow) on mobile by setting lastMessageId to always be `''` on mobile.
Fixes LAND-1674
tested locally on livenet moons
PR Checklist
=> chat: fix re-render on chat input

apps/tlon-web/src/chat/ChatInput/ChatInput.tsx
This fixes LAND-1678 by moving lastMessageId into a ref, preventing onUpArrow from changing and thus causing the message editor to re-render.
Tested locally on a livenet moon.
PR Checklist
=> chat input: fix rerendering issue on last message delivered

desk/app/profile/widgets.hoon
While injecting the bio text as raw html isn't against the spirit of profiles, it is inconsistent with the way the bio text gets rendered in groups.
(Yes, this diff is sufficient for escaping the bio text. Normally, it gets handled by the sail->html conversion, but we are manually constructing sail elements here (to get text-only nodes). In doing so, we made the mistake of adding a string (`$tape`) of "one" "character" (the whole `@t`), rather than something sane.)
=> profile: make sure text in the bio gets escaped

apps/tlon-web/src/chat/ChatInput/ChatInput.tsx, apps/tlon-web/src/state/channel/channel.ts
Fixes LAND-1683 ("Edited" not appearing next to posts until we scry again for posts)
Also fixes an annoying issue I found where if you pressed the up arrow key while composing a new message, you would jump to editing your last message and the text you typed into the chat input would disappear temporarily until you returned to the chat input. Instead, we just disable the up arrow key while you're composing a new message.
=> edit: use v1 sub paths for posts and channels updates

apps/tlon-web/src/chat/ChatScroller/ChatScroller.tsx, apps/tlon-web/src/logic/scroll.ts
Fixes LAND-1681.
This was introduced by yesterday's fix in #3325. If we use `useIsEditingMessage` within `useInvertedScrollInteraction`, the `isEditing` value never updates and those listeners are still active.
So the space keydown was getting captured in `useInvertedScrollInteraction` when it shouldn't have been.
=> chat editing: fix issue with inability to add spaces

apps/tlon-web/src/state/channel/channel.ts, desk/app/notify.hoon, desk/sur/notify.hoon
Fixes LAND-1682 by fixing an issue in the state types in %notify.
At one point, the `notification` type changed and was subtly wrong. This went unnoticed because we used to drop old state anytime it didn't match the current state type.
This began to fail when we introduced changes to the %notify agent that included state transitions and there were ships that had not yet had that old state dropped.
This particularly effected the fake ships we use for e2e tests, because they boot with an old version of %groups. This would have also effected any ships that had not yet dropped their old state %3 and replaced it with the "new" state %3 with the bad notification type.
We get around this issue by just accepting any noun for the `notifications` type for base-state-2 and base-state-3, and creating …
=> e2e: fix e2e by fixing state transitions in %notify

apps/tlon-web/src/chat/ChatScroller/ChatScroller.tsx, apps/tlon-web/src/logic/scroll.ts
I'm not sure why the previous fix appeared to work. The event listeners weren't actually getting removed, so the issue persisted. Instead, we should keep isEditing in a ref and use that ref within the event listener, updating the ref when isEditing actually changes.
Fixes LAND-1681 (again).
=> edit: fix the space issue by using a ref for isEditing

apps/tlon-web/src/manifest.ts
This fixes the issue where navigating to `[your ship]/apps/groups` would appear to be outside the scope of the PWA (you'd see the gray bar at the top, indicating you're at an external link).
Fixes LAND-1631
=> pwa: fix the scope/url issue in the manifest

desk/app/profile.hoon
A different %profile agent has been spotted in the wild. It was not compatible with the kelvin at which _this_ agent was first released, made no %passes beyond eyre binding, and the software suit it was a part of (Realm) has since been discontinued.
So here we detect that case, and simply discard the previous state, starting anew with our %profile agent.
Closes LAND-1671.
=> profile: work around clash with realm %profile

.github/helpers/create_moon.sh, .github/workflows/deploy-ephemeral.yml, desk/ted/moon.hoon
Just trying to structure out how we could potentially start up ephemeral moons for development branches. 
To make this work we need a hoon thread to run through click to generate a moon. We then need to write that output to a file, then extract the moon name and key, and then use that to boot the one-off moon. One problem I see with the current approach is that the bash script copied/ran on the VM host is very much a "one shot" type thing where the script is just ran one time, similar to how our current `deploy.sh` script is ran. Need to determine how we can actually see if the moon is successfully booted before moving forward with the deployment script itself.
=> [draft] initial idea for how to structure ephemeral deployment moons

desk/app/groups.hoon
The scry endpoints for a group's channels' permission checks would crash if the channel did not exist in that group. In cases where the channel was deleted, other agents might still know about the channel, and so still try to ask the group about relevant permissions, but the scry handling would crash.
Here we update the scry logic to not crash, and instead produce a "not allowed to read" flag in cases where the asked-about channel doesn't exist in the group.
~~We suspect this will ameliorate at least some of the problems seen around role modifications and permission rechecks, as this crashing scry was causing group fact handling to crash, causing locally-originating kicks, causing resubscribes.~~ Don't get your hopes up.
=> groups: don't crash during "can read" on-peek

apps/tlon-web/src/chat/ChatSearch/ChatSearch.tsx
OTT. 
Was another nested `@radix-ui` issue. Wasn't able to shake it by updating deps, so added a workaround to prevent the bad behavior.
Tested locally against a hosted ship.
Fixes LAND-1577
PR Checklist
=> web: fix search bar closing on click

apps/tlon-web/src/chat/ChatSearch/ChatSearch.tsx
Noticed an issue with my search fix from yesterday where if the results ever gain focus, the search bar can never receive it again. This makes it tricky to do multiple searches.
Radix is pretty intense about it's focus guarding and the way we're using it here doesn't seem in line with what it's designed for. Looks like the click outside tracking was the main feature we were leveraging, so after pulling in a hook for that functionality I was able to remove Radix from the component entirely.
Now behaves as expected without the need for hacks and extra event handling. Keyboard result navigation and escape are maintained as well.
Tested against a local ship.
PR Checklist
=> web: fix search bar click focusing

apps/tlon-web/src/state/channel/channel.ts
found this while working on another bug. we were using both ['diary', 'hidden'] and ['channels', 'hidden'] as query keys, this caused an issue where you sometimes were unable to unhide a message.
fixes LAND-1703
=> hidden message: fix issue with react query key

apps/tlon-web/src/app.tsx, apps/tlon-web/src/chat/ChatChannel.tsx, apps/tlon-web/src/chat/ChatInput/ChatInput.tsx, apps/tlon-web/src/chat/ChatThread/ChatThread.tsx, apps/tlon-web/src/chat/ChatWindow.tsx, apps/tlon-web/src/logic/useIsEditingMessage.tsx, apps/tlon-web/src/replies/ReplyMessage.tsx, apps/tlon-web/src/replies/ReplyMessageOptions.tsx, desk/desk.docket-0
We were setting the scrollToId in the ChatWindow using the `edit` url param, which could include an ID for a reply message. The message would never be found and we'd end up in a re-render. We needed a different url param for editing a reply, `editReply`.
I also used wydr to try to root cause this originally, and found that we were seeing some unnecessary re-renders that could be fixed by moving the useLocation() hook call into the GroupsRoutes component and that we ought to memoize ChatChannel and ChatWindow.
fixes LAND-1701
=> edit: fix issue with re-renders on editing reply message

desk/app/channels.hoon, desk/app/groups.hoon, desk/desk.docket-0
This PR should fix LAND-1698 by doing all our role removals in one event rather than an event for each member of the group. It also prevents channels from attempting to resubscribe to channels that are no longer associated with the group. This is untested, but should fix the issues we've been seeing.
**todos:**
- follow-up PR with proper tests
- follow-up PR to rip out old agent logic (heap/diary) that isn't involved in migration
As far as we understand the issue with role deletion was as follows:
**host**
delete role in UI (1 event) -> verify group cabal(role) data -> check every member's roles for old roles -> poke self for each member that needs a role change (5k events) -> disseminate events -> each event goes to 5k subscribers ... eventually receive resubscribes for channels …
=> groups: fix role deletion DDOS

apps/tlon-web/src/logic/useSidebarSort.ts
Another small perf improvement for the big brain sidebar sorting. Pre-compute and memoize the unreads before sorting. Profiler showed this function was fairly heavy, this reduces the load quite a bit.
=> perf: speed up useRecentSort in useSidebarSort

apps/tlon-web/src/replies/ReplyMessage.tsx
Re-opened with a new branch based off of staging.
Fixes LAND-1731 by making sure we have a nest (we don't in the case of chat, we do in the case of diary/heap, previously we were just appending chat/ to whatever we had in whom).
=> edit: fix issue with editing replies in notebooks and galleries

apps/tlon-web/src/app.tsx, apps/tlon-web/src/components/Sidebar/AddGroupSidebarItem.tsx, apps/tlon-web/src/components/Sidebar/GroupList.tsx, apps/tlon-web/src/components/Sidebar/Sidebar.tsx, apps/tlon-web/src/components/Sidebar/SidebarSorter.tsx, apps/tlon-web/src/groups/GroupSidebar/ChannelList.tsx, apps/tlon-web/src/groups/GroupSidebar/GroupSidebar.tsx
Just added more memoization to prevent "normal" re-renders and used refs to store the group from useGroup() in the relevant components to prevent the skeleton state from loading when we navigate out of a group.
=> Sidebar: reduce re-renders to further minimize jank

desk/lib/test-agent.hoon, desk/tests/lib/negotiate.hoon
Was using this library for my own purposes recently and found that it offered no built-in affordance for modifying state or injecting state wholesale. Since `+on-load` gets called with a `vase`, seems appropriate for `+do-load` to accept that as an argument.
This way, state migrations may be tested, and agent state may be created ex-nihilo instead of needing to come about strictly through the normal lifecycle.
We take a `(unit vase)` so that it remains easy to fall back to `+on-save`'s output.
(Includes some tiny stylistic touch-ups to the library as well.)
=> tests: support loading custom vase in +do-load

packages/ui/src/components/ChannelListItem/ListItemContent.tsx, packages/ui/src/components/ChannelSwitcherSheet.tsx
Saw some type errors that cropped up because the client types work didn't account for the channel switcher pr (and the tests ran before). These changes should fix the type errors we're seeing.
=> Fix channel switcher type errors

apps/tlon-web/src/logic/useSidebarSort.ts
My recent change to useRecentSort() didn't account for the fact that some channels/dms don't have any unreads.
This led to a bizarre looking recent sort order for groups.
This fixes that by defaulting to Number.NEGATIVE_INFINITY if we can't find an unread (rather than only if we can't find recency).
Tested locally on a live ship.
Fixes LAND-1747
PR Checklist
=> sidebar sort: fix issue with recency

apps/tlon-mobile/ios/Podfile.lock, apps/tlon-mobile/package.json, package-lock.json, packages/ui/src/components/ChatMessage/ChatContent.tsx, packages/ui/src/components/ListItem.tsx, packages/ui/src/components/RemoteSvg.tsx, packages/ui/src/core/Image.native.tsx, packages/ui/src/core/Image.tsx, packages/ui/src/core/index.ts, packages/ui/src/core/tamagui.ts, packages/ui/src/index.ts
Replacement for native `Image` with more aggressive caching + performance config: https://github.com/DylanVann/react-native-fast-image.
At some point we should also consider caching svg source for svg images.
=> Add react-native-fast-image

apps/tlon-web/src/queryClient.ts
I think it's worth trying this on wannec to see if it helps with the issue we're seeing of the app getting progressively slower overtime (and also getting much faster when the user clears the cache).
Five minutes is the suggested "sane" cache time by tanstack. We could bump it out to maybe a day or something if five minutes is too noticeable.
=> Perf: set cache time to 5m

desk/lib/negotiate.hoon
Instead of producing the implicitly-unpacked vase, !> the vase, so the result of the scry itself remains a vase.
`/lib/dbug` expects this, and violating it causes agents using this library to not work right it `/app/dbug` or the debug dashboard.
=> negotiate: produce vase for /dbug/state scry

packages/ui/src/components/ChannelListItem/index.web.tsx
I switched the native version of this component to use a default export and didn't do the same with the web version, it was causing the vite build to fail in CI (but it wasn't failing locally, which is pretty weird, looking into that).
=> fix wannec deploy issue

desk/lib/channel-utils.hoon
Apparently the `is-admin` util has been broken. It was scrying into the wrong place to check if a user is an admin. It only appeared to work because of an early return where we check if the ship is also the host of the channel.
If an admin was *not* also the host of the channel, then they were not able to delete messages in that channel.
=> groups: fix issue where admins can't delete if they're not the host

apps/tlon-web/src/chat/ChatInput/ChatInput.tsx, apps/tlon-web/src/chat/ChatMessage/ChatMessage.tsx
fixes LAND-1750 by only attempting to edit inlines
Also fixes (in a hacky way, didn't root cause it) an issue with our drafts sometimes containing empty mentions. You would usually see this after sending a quote reply, leaving the channel, and coming back.
=> edit: allow editing a message with a quoted reply

desk/mar/dummy.hoon
Until recently arvo had a bug where sometimes clay would return a false conversion gate when requesting a mark that is named the same as something in the subject. https://github.com/urbit/urbit/pull/6898 is going out in the next release and will fix this. 
Consider the following code;
https://github.com/tloncorp/tlon-apps/blob/e3f642ee5d5056c59ead51f015ed3e26fb5db0cb/apps/tlon-web/src/state/bootstrap.ts#L84-L88
This causes ships on pre-release arvo to experience this from time to time:
```
clay: read-at-tako fail [desk=%groups care=%c case=[%da p=~2024.4.11..11.30.21..584b] path=/json/ui-vita]
[%no-cast-from %json %ui-vita]
[%error-building-cast %json %ui-vita]
[%error-building-tube %json %ui-vita]
```
This error message is harmless but annoying.
`/mar/ui/vita` calls out to `/mar/dummy` …
=> mar: add dummy json grow

apps/tlon-web/src/groups/GroupActions.tsx
Removes a erroneous check for non-admin status in the "Leave group" GroupAction. Instead, we just look at the flag (is the current ship the host?).
We probably also need to bolster this to prevent channel hosts from leaving the group and orphaning their hosted channels.
PR Checklist
=> GroupActions: don't prevent non-hosting admins from leaving group

packages/shared/src/api/initApi.ts, packages/shared/src/api/unreadsApi.ts, packages/shared/src/db/queries.ts, packages/ui/src/components/ChatList.tsx
1) we should use the new /v1/init endpoint.
2) DMs have a different message id type (patp with a ud that has decimals in it), our unreadsApi didn't account for that. 
3) users may not always have pins, we were failing to insert because we tried to pass an empty array into insertPinnedItems 
4) since we don't always have pins, hide that section in the ui.
=> mobile: misc fixes for init related data.

apps/tlon-web/src/app.tsx
Looks like this (user sees the home screen to the app, with the group preview modal):
(also note that I cut off half of the screen in the screenshot, the modal shows in the middle like it normally does)
=> web: add missing find route back (fixes desktop lure links)

apps/tlon-web/src/heap/HeapDetail/HeapDetailSidebar/HeapDetailSidebarInfo.tsx, apps/tlon-web/src/state/channel/channel.ts
Fixes LAND-1754 and LAND-1764, heap detail wasn't even checking pending and we needed to do the same de-duping with replies as we did with posts. 
PR Checklist
=> channels: remove duplicate replies

apps/tlon-web/src/app.tsx, apps/tlon-web/src/groups/GroupSidebar/GroupSidebar.tsx, apps/tlon-web/tsconfig.json
There was a recent performance optimization targeting sidebar transition lag that updated the sidebar to avoid re-rendering. The caching there seems too aggressive causing missing group metadata when refreshed or navigated to directly (no title or icon). This small fix makes sure we use the correct data there.
Performance wise, I didn't notice an impact. Though the issue was subtle iirc.
Also smuggling in a small change to avoid `tsc` failing to find the tamagui type declarations.
FIxes LAND-1765
=> desktop: fix missing groups sidebar metadata

apps/tlon-mobile/package.json, package-lock.json, package.json, packages/editor/package.json, packages/shared/package.json, packages/ui/package.json
- move post-install logic at app & package level to build scripts (avoiding post-install lifecycle hook)
- add scripts to top level `package.json` for building sub-packages in acceptable order
- call those build scripts in top level post-install hook
Want to make sure this fixes the issues we're observing before we try to build things concurrently. Anecdotally, it spends most of the time waiting for the initial package install anyhow.
Also adds preinstall hook to remove that troublesome `tsconfig.tsbuildinfo` file in `packages/shared`
=> ops: manual build order

apps/tlon-mobile/src/navigation/TabStack.tsx, package.json
Very straightforward; removes the message bubble from the bottom tab navigation bar.
Also fixes the `npm run dev:ios` mega-script.
=> native: remove chat tab from navigation

packages/ui/src/components/MessageInput/MessageInputBase.tsx
Removes the non-functional attachment icons in MessageInputBase. Also switches the send button to ArrowUp.
=> native: eliminate left-side icons in MessageInputBase

packages/ui/src/components/Channel/index.tsx
It turns out this was caused by the KeyboardAvoidingView's `keyboardVerticalOffset` prop, which a) positioned the input box too high on iOS b) causes this weird issue on android when used in combination with the `height` behavior. Removing the offset and setting the behavior to `position` when on android fixes the issue, and iOS still looks/works the same.
Note that we also need to set a `contentContainerStyle` when using the `position` behavior on Android (this does not effect the way the component renders when we're using the `padding` behavior on iOS).
=> android: fix issue with channel view 'wiping away' on keyboard dismiss

packages/shared/src/api/groupsApi.ts, packages/shared/src/db/schema.ts, packages/ui/src/components/ChannelListItem/index.tsx, packages/ui/src/components/ChatList.tsx
Fix duplicate issues in chat list by differentiating between channel items and group items.
=> native: fix pinned group channel rendering

apps/tlon-mobile/cosmos.imports.ts, apps/tlon-mobile/src/fixtures/ActionSheet.fixture.tsx, apps/tlon-mobile/src/fixtures/Channel.fixture.tsx, apps/tlon-mobile/src/screens/ChannelScreen.tsx, packages/ui/src/components/ActionSheet.tsx, packages/ui/src/components/Channel/index.tsx, packages/ui/src/components/GroupOptionsSheet.tsx, packages/ui/src/components/MessageInput/AttachmentButton.native.tsx, packages/ui/src/components/MessageInput/AttachmentButton.tsx, packages/ui/src/components/MessageInput/MessageInputBase.tsx, packages/ui/src/components/MessageInput/index.native.tsx, packages/ui/src/components/MessageInput/index.tsx
I added a generic ActionSheet component and implemented it in the two places (that I'm aware of) that we need it. Also added a fixture for it.
Fixes LAND-1811
=> native: add action sheet component

packages/ui/src/components/Channel/ChatScroll.tsx, packages/ui/src/components/ChatMessage/ChatContent.tsx, packages/ui/src/components/ChatMessage/index.tsx, packages/ui/src/components/IconButton.tsx, packages/ui/src/components/ImageViewerScreenView.tsx
Removes the existing overlay in the ImageViewer in favor of a simpler close icon. Right now it may be a bit too subtle, but I think it'll be more clear when the overlay is open once it's more featureful (save to camera roll action for example)
Also fixes longpress on message images to open the actions. Still has that brief yet annoying resize stutter when we swap in the animated message (I'm coming for you!)
Fixes LAND-1797
=> mobile: use platform/theme neutral overlay for image viewer

packages/editor/src/MessageInputEditor.tsx, packages/editor/src/useMedia.ts, packages/ui/src/components/ActionSheet.tsx, packages/ui/src/components/ChannelListItem/index.tsx
- Uses $tertiaryText on ActionSheet item borders and on channel icons in ChannelListItem.
- Adds the useMedia hook to the editor package and utilizes it to show white text on a dark background in dark mode.
Fixes LAND-1802
Fixes LAND-1803
Fixes LAND-1084
=> native: color fixes

apps/tlon-mobile/src/fixtures/MessageInput.fixture.tsx, packages/editor/src/MessageInputEditor.tsx, packages/ui/src/components/MessageInput/MessageInputBase.tsx, packages/ui/src/components/MessageInput/index.native.tsx
and fix the flex issues with buttons (i.e., they stay at the bottom as the message input container grows)
fixes LAND-1813
=> native: get height from webview to set editor container height in native

package.json, patches/@10play__tentap-editor@0.4.55.patch, pnpm-lock.yaml
Apparently 44px of padding was hardcoded into tentap's RichText component when rendered on android (apparently to account for the OS's bottom nav bar?). I set it to zero, seems fine with both gesture based nav and older button based nav, so I patched tentap with that value set to zero.
Fixes LAND-1795
=> native: fix weird height issue on input on android

packages/shared/src/api/channelsApi.ts, packages/shared/src/api/groupsApi.ts, packages/shared/src/api/initApi.ts, packages/shared/src/db/migrations/0000_chemical_korg.sql, packages/shared/src/db/migrations/meta/0000_snapshot.json, packages/shared/src/db/migrations/meta/_journal.json, packages/shared/src/db/migrations/migrations.js, packages/shared/src/db/queries.ts, packages/shared/src/db/schema.ts, packages/shared/src/store/dbHooks.ts, packages/shared/src/store/sync.ts, packages/ui/src/components/Channel/EmptyChannelNotice.tsx, packages/ui/src/components/Channel/index.tsx, packages/ui/src/utils/channelUtils.tsx
- adds a placeholder for empty groups channels (leaving out DMs since we'll want that sigil block there instead)
- stores channel write permissions on init and checks them before displaying the message input
Fixes LAND-1827
Fixes LAND-1829
=> mobile: empty channel placeholder & hide input when no write permissions

packages/shared/package.json, packages/shared/src/api/postsApi.ts, packages/shared/src/db/queries.ts, packages/shared/src/store/postActions.ts, packages/shared/src/store/sync.ts, packages/shared/src/store/useChannelPosts.ts, pnpm-lock.yaml
This trivially fixes the issue where replies were showing up in the main channel if they're undelivered. Also attempts to fix the issue where messages are getting stuck in pending/sent states.
Repro'ing the stuck states was tricky, so I mostly tested by sending messages to a group on a local ship that I could start/stop at will.
Theoretically we should always be hearing a fact when a message is delivered. If for some reason we miss it, we're more susceptible to getting stuck in the wrong state (compared to Web) since we're using an additional client side cache layer behind `react-query`. We can probably alleviate this with smarter refetching logic + `useChannelPosts` configuration, but refining that will be an ongoing process. 
This PR takes an approach that's more blunt. It adds a …
=> native: message sending fixes

packages/ui/src/components/ChatMessage/ChatContent.tsx, packages/ui/src/components/ContentReference/ChatReference.tsx, packages/ui/src/components/ContentReference/Reference.tsx, packages/ui/src/components/MessageInput/MessageInputBase.tsx
Fixes LAND-1854 by truncating the text in the chat message when it's within a ref that's attached to the input, also adjusts the position/width of the ref preview.
=> native: refine ref preview on input

packages/ui/src/components/ChatMessage/ChatContent.tsx, packages/ui/src/components/ChatMessage/ChatMessageDeliveryStatus.tsx
https://github.com/tloncorp/tlon-apps/assets/90741358/7b659b3e-a550-4e64-a4fb-8e42b7d22b18
Adds back in the arrows instead of plain text and adjusts flex spacing to prevent text colliding with the indicator.
Depending on word breaks, long messages do sometimes adjust their layout when the indicator clears. Ochre seemed to have a pretty narrow right gutter, but if we want to reserve space there to comfortably fit the indicators instead, I can do that. (also fine for now if the indicator may change down the line)
Fixes LAND-1853
=> native: pending arrows

apps/tlon-mobile/src/fixtures/ChannelHeader.fixture.tsx, packages/ui/src/components/Channel/ChannelHeader.tsx, packages/ui/src/components/ChatMessage/ChatContent.tsx
Two small improvements from last week that didn't make it up:
- Truncate long names in channel titles
- Use cached image aspect for initial render (can prevent a layout shift)
Fixes LAND-1849.
=> native: stray polish items

apps/tlon-mobile/src/screens/ChannelScreen.tsx
I should have used `navigation.navigate`, not `navigation.push`. Fixed here.
fixes LAND-1845
Makes it so that we don't transition to a new screen when pressing a ref.
=> native: fix ref navigation

packages/ui/src/components/Channel/Scroller.tsx
- Disables scroll-to-unread for now, since it was causing problems
- Fixes date + unread divider positions -- because the divider + message were wrapped in a dummy element, inverted FlatList transform was being applied to them individually rather than both together, which meant that the divider rendered under the message rather than on top. Resolved by just wrapping both in a view.
=> native: scroller fixes

packages/ui/src/components/ChatMessage/ChatContent.tsx, packages/ui/src/components/ChatMessage/ChatEmbedContent.tsx, packages/ui/src/components/ChatMessage/ChatMessage.tsx
I noticed that in chat messages with multiple inline elements, we ended up with inconsistent line-heights. I also decided to take a crack at the DM join notice.
- Makes all ContactNames in ChatMessages font-weight: 500.
- Removes the blue background from ContactNames in ChatMessages as discussed.
- Removes the AddPerson Icon from the LineRenderer in ChatContent and conditionally wraps ChatContent in ChatMessage with an XStack to align everything vertically.
- Hides the author for the Notice message type.
- Enforces a $m line-height in every inline text element.
=> ChatMessage: consistent line-heights, XStack for notices

apps/tlon-mobile/src/screens/ChannelScreen.tsx, packages/editor/src/MessageInputEditor.tsx, packages/ui/src/components/MessageInput/index.native.tsx
fixes LAND-1871 by removing most of the content parsing (and all of the content replacement) from onContentUpdate.
Instead, we listen for a paste event within the editor in the webview and send a message up to the react native app, then handle the content parsing/updating in a handler.
onContentUpdate is still used for triggering a mention or storing a draft, but we don't manipulate the content there anymore.
=> native: fix input lag

desk/app/channels.hoon, desk/app/chat.hoon, desk/app/groups-ui.hoon, desk/lib/channel-json.hoon, desk/lib/chat-json.hoon, desk/lib/mark-warmer.hoon, desk/mar/channel/heads.hoon, desk/mar/chat/heads.hoon, desk/sur/channels.hoon, desk/sur/chat.hoon, desk/sur/ui.hoon
We add a `/heads` scry endpoint, which returns the latest message for every channel/chat. If the optional date path element is specified, we only include results whose latest message is after that date.
Groups-ui gets a `/heads` endpoint also, which simply merges the channels and chat `/heads` scries. Maybe, arguably, this should go into the init endpoint instead.
For channels, we also implement `/changes`, which gives you all changes made to a channel since the given timestamp. We currently cannot reasonably do this for chats, because those don't track changelogs, so including new replies would require checking all threads in the entire backlog.  
We could track new things in state to make that more performant, but we don't do that right now. Adding that should probably be considered out …
=> channels, chat: /heads endpoint for latest messages

apps/tlon-web/src/channels/ChannelActions.tsx, apps/tlon-web/src/components/References/CurioReference.tsx, apps/tlon-web/src/components/References/NoteReference.tsx, apps/tlon-web/src/components/References/ReferenceBar.tsx, apps/tlon-web/src/components/References/WritBaseReference.tsx, apps/tlon-web/src/components/Sidebar/util.tsx, apps/tlon-web/src/diary/diary-add-note.tsx, apps/tlon-web/src/groups/GroupActions.tsx, apps/tlon-web/src/groups/Join/GroupPreview.tsx, apps/tlon-web/src/groups/LureAutojoiner.tsx, apps/tlon-web/src/groups/NewGroup/NewGroup.tsx, apps/tlon-web/src/groups/useGroupJoin.ts, apps/tlon-web/src/heap/useCurioActions.ts, apps/tlon-web/src/logic/channel.ts, apps/tlon-web/src/logic/useCreateDefaultGroup.ts, apps/tlon-web/src/profiles/FavoriteGroup.tsx, apps/tlon-web/src/replies/ReplyMessageOptions.tsx
This attempts to make a hook that will respect navigations within tabs fixing LAND-1579
PR Checklist
=> nav: make sure we always navigate to right tab

desk/lib/channel-utils.hoon
We mistakenly were clearing the replies before we could compute the meta, fixes LAND-1767
PR Checklist
=> channels: fix missing reply meta in old scries

desk/app/channels.hoon, desk/mar/ui/heads.hoon
Reported by @patosullivan we potentially can crash when doing a read action because we might have a malformed notification thread. Also adds mark that @Fang- forgot.
PR Checklist
=> channels: dont crash on read

apps/tlon-web/src/groups/useGroupJoin.ts, apps/tlon-web/src/logic/useGroupPrivacy.ts, apps/tlon-web/src/state/groups/groups.ts, desk/app/groups.hoon
This fixes two issues I found. One being that we don't actually fetch group previews because we were setting initial data, so they were potentially always using stale data (unless you don't have that group yet). The other issue is that editing a cabal that someone doesn't know about will crash because we use jab by without checking for existence of key.
PR Checklist
=> groups: previewing issues and fact crash fix

packages/ui/src/components/MessageInput/MessageInputBase.tsx, packages/ui/src/components/MessageInput/index.native.tsx, packages/ui/src/components/MessageInput/index.tsx
fixes LAND-1875 by hiding the send arrow when we have nothing to send.
=> native: hide send arrow if editor is empty

packages/shared/src/api/channelsApi.ts, packages/shared/src/store/sync.ts
Fixes LAND-1887.
Also, we don't need to specifically handle edit, that's handled via the `addPost` case (it comes in via postResponse.set).
=> native: handle delete post subscription events

apps/tlon-mobile/src/navigation/NavBarView.tsx, apps/tlon-mobile/src/navigation/TabStack.tsx, apps/tlon-mobile/src/screens/ChatListScreen.tsx, apps/tlon-mobile/src/screens/ProfileScreen.tsx, packages/ui/src/components/ChatList.tsx, packages/ui/src/components/NavBar/NavBar.tsx, packages/ui/src/components/NavBar/NavIcon.tsx, packages/ui/src/components/NavBar/index.ts, packages/ui/src/components/ProfileScreenView.tsx, packages/ui/src/index.ts, packages/ui/src/tamagui.config.ts
Renovates the app navigation to use nested Native Stacks and a custom NavBar component.
- Rather than using createBottomTabNavigator, uses createNativeStackNavigator for all nested "home" screens (ChatList, Channel, Post, ChannelSearch).
- Adds a custom navigation component (NavBar) in packages/ui which seeks to be as generic as possible
- Adds a NavBarView to the app screens themselves, which in turn takes the navigation prop from the parent screen and handles all the navigate() calls itself
Functionality is exactly the same as before but eliminates the gray box on view transition (fixes LAND-1873). Thanks to @patosullivan for the talk-through assist.
Note that this is an absolutely-positioned element, so any screen that uses a scroller that extends below the bottom edge of the screen …
=> native, ui: move from TabStack to new custom NavBar component

apps/tlon-mobile/src/fixtures/Channel.fixture.tsx, apps/tlon-mobile/src/fixtures/FixtureWrapper.tsx, apps/tlon-mobile/src/fixtures/PostScreen.fixture.tsx, apps/tlon-mobile/src/screens/ChannelScreen.tsx, apps/tlon-mobile/src/screens/PostScreen.tsx, packages/shared/src/store/index.ts, packages/shared/src/store/storage/utils.ts, packages/shared/src/store/useNegotiation.ts, packages/ui/src/components/Channel/index.tsx, packages/ui/src/components/PostScreenView.tsx
Fixes LAND-1828. We skip the db and just query the api directly. We'd have to sync regularly and write to/read from the db anyway, this saves a step and squeaks out a little performance.
We assume there is a match until we hear otherwise. Users shouldn't see the message about a mismatch unless we know that one exists.
Reuses/adapts logic from tlon-web.
=> native: version negotiation for channels

desk/app/groups.hoon
Likely to have caused a loop for some reason with group previews?
PR Checklist
=> groups: dont leave subscriptions locally

apps/tlon-web/src/chat/ChatContent/ChatContent.tsx, apps/tlon-web/src/heap/HeapContent.tsx
Realized that we don't render mentions in text gallery posts in the old web app after making a mention in a gallery post in the new mobile app. This fixes that. Also removes the throw on hitting unhandled message content.
=> web: Fix issue with rendering mentions in gallery content

desk/app/chat.hoon
Chat was already sending some updates (block & msg toggle changes) to the top-level subscription path (and surprisingly isn't sending those anywhere else), but wasn't doing the same for updates about individual chats.
Here, we chuck `/` into the list of paths to update for most response-level subscription updates, to mirror the "firehose" style that channels' `/` endpoint has.
Closes LAND-1880.
=> chat: send more facts to / subscriptions

apps/tlon-web/src/app.tsx
Fixes issue seen in demo where notification settings modal didn't work in messages tab. 
PR Checklist
=> app: add routes for msgs tab notification settings

packages/shared/src/urbit/utils.ts
OTT
If a legacy custom channel type is found (`quorum` for example), we treat it as a chat channel and move on. When we do type checking for nests, it doesn't influence app logic beyond logging an error if they're invalid.
To be less disruptive, if we detect a custom channel this simply describes the behavior vs logging an error which pops up in the simulator.
=> native: don't error on custom channel types

apps/tlon-mobile/src/fixtures/ChannelDivider.fixture.tsx, apps/tlon-mobile/src/fixtures/ChatMessage.fixture.tsx, packages/ui/src/components/Channel/ChannelDivider.tsx, packages/ui/src/components/ChatMessage/ChatContent.tsx, packages/ui/src/components/ChatMessage/ChatMessage.tsx
Adjusts the ChannelDivider and the isNotice variant of ChatMessage to be full-width with a pill in the center. Also adds fixtures for both.
=> native: fix isNotice variant of ChatMessage, ChannelDivider

desk/lib/channel-json.hoon
We were seeing a cast fail on attempting to send a (notebook) post with task items because we weren't actually decoding the %tasks in channel-json.
=> notebooks: add %task to inline for dejs, fix issue with posting task lists

packages/ui/src/components/Channel/index.tsx, packages/ui/src/components/FloatingActionButton.tsx, packages/ui/src/components/GalleryPost/GalleryPost.tsx
Modifies the FloatingActionButton slightly:
- Uses a Button component in the FAB
- Uses the Icon component when passing in an icon to actually render the icon the way Button wants it
- Absolutely positions the button in the channel at the bottom/center to conform with latest designs
- Adds a secondaryBackground to pure-text Gallery posts in the channel to help with visual structure (@urcades, feel free to weigh in)
@patosullivan The FAB was also showing up post-upload in the gallery image upload view, maybe the logic there was placeholder? Double-check that for me please. This doesn't show the FAB in the confirm step.
=> native: center-aligned FloatingActionButton for galleries/notebooks

desk/app/chat.hoon, desk/lib/chat-json.hoon, desk/mar/writ-response.hoon, desk/tests/app/chat.hoon
This lets us specify the chat that the writ response happened in/for, which cannot otherwise be known if you're subscribing to the / "firehose" endpoint as opposed to an individual, specific chat.
We expect to get away with just tacking it on, because nothing on our backend listens for this mark, it's not used in scry endpoints, and the json is "backwards compatible" in the sense that it just has an additional field on the top-level object now.
Closes TLON-1880 again.
=> chat: include $whom in %writ-response mark

packages/ui/src/components/Channel/EmptyChannelNotice.tsx
Changes the EmptyChannelNotice (A) in textual content and (B) to sit directly on the channel, rather than in a card. (New design calls for this.) This resolves an issue where the notice text was unreadable in dark mode.
Fixes TLON-1954
Before:
After:
=> native: darkmode-safe EmptyChannelNotice

packages/ui/src/components/Channel/Scroller.tsx, packages/ui/src/components/GalleryPost/GalleryPost.tsx
Fixes TLON-1945. We were seeing some posts appear as if they were in a "single column" per row in ed's product group because the posts actually had no content, so the GalleryPost component just returned null. We need to filter out posts like this before we pass them into FlatList.
I also added a "Unsupported content type" component we can return if we run into this again, so we'll know what's going on (it shouldn't happen again, but just in case).
=> native: don't pass empty posts to scroller, fixes gallery grid issue

packages/ui/src/components/Channel/index.tsx
Follow-up PR to #3551 where the view was blocking touch-events beneath it. Applies a temporary visual trick until we move to a full-on ChannelFooter component. Apologies for the oversight.
=> native: FAB positioning

packages/shared/src/logic/utils.ts, packages/ui/src/components/BigInput.tsx, packages/ui/src/components/ContentRenderer.tsx
Fixes TLON-1958 by making sure we always interleave rendered content for notes (as opposed to chat where blocks should always appear before the text/inline content, or galleries where the content is either text or an image).
=> native: render interleaved content for notes

desk/app/activity.hoon
Migration logic was calling into `+update-index` for each entry we imported, which in turn calls `+refresh-summary`. Of course, we know we'll likely be adding more things, so this is unnecessary (and slow) work.
Here, we add an `importing` flag into the context, and set it to true for the duration of migration logic. The `should-notify` hidden parameter we had added to the `+add` arm previously gets replaced by this, and if it's set to true, we don't run `+refresh-summary` for every invocation of `+update-index`.
This brings upgrade wall-clock time down from "idk, didn't finish in a reasonable timeframe" to a minute and a half, of which a full minute is spent on the activity agent's migration logic.
We could probably bring that down further, or at least reduce variance, by capping the …
=> activity: when migrating, refresh summaries *once*

.github/workflows/ci.yml
As discussed out of band, these "seemingly just started failing due to timeouts at some point". We ignored this and got used to the red X's.
It seems preferable to disable the tests until we have time to re-enable them and investigate their failures properly, rather than get used to CI failures.
=> ci: disable e2e tests (for now)

packages/shared/src/api/initApi.ts, packages/shared/src/store/sync.ts, packages/ui/src/components/ChannelListItem/index.tsx
This pr contains a few small fixes/improvements.
- Re-enables the old unreads api for now, which fixes chat list order, unread counts, and a number of other things.
- Refactors sync methods so that we're attempting to load the next request while the last one is persisting to the database.
- Adds a background tint to text icons that don't have a background color set (minor visual thing that's been bugging me).
Before:
After:
=> native: fix chat list order and more

apps/tlon-mobile/src/navigation/NavBarView.tsx, packages/ui/src/components/NavBar/NavIcon.tsx
Fixes TLON-1967 by showing the default, unstyled sigil in the bottom nav until we get the contact details for the logged-in user (rather than just not showing the button at all).
=> native: show user sigil in bottom nav while contacts is still loading in

apps/tlon-web/src/chat/ChatThread/ChatThread.tsx, apps/tlon-web/src/dms/DMOptions.tsx, apps/tlon-web/src/dms/DMThread.tsx
This fixes TLON-2001. Pinning/unpinning channels was broken because we were using wrong identifier. Creating message keys every render was causing the `markRead` function to change every render which was causing us to infinitely loop, which made pinned items unclickable.
PR Checklist
=> sidebar: unclickable pins and unable to pin chats

apps/tlon-web/src/components/Leap/useLeap.tsx, apps/tlon-web/src/state/chat/chat.ts
We were using entry.string, which couldn't split out to [ship, nickname] appropriately anymore. `whom` passed to useCheckDmUnread was always `${ship}{nickname}`, which we'll never find an unread for. We can just pull the ship and the nickname out of the entry.original property instead. I also updated useCheckDmUnread() so that unreads[whom] is optional.
Fixes TLON-2029
=> web: fix leap crashing issue

packages/shared/src/api/postsApi.ts, packages/shared/src/store/postActions.ts
Fixes LAND-1997. We were using %channels pokes where we should have been using %chat.
=> native: fix issues with reactions in DMs

packages/ui/src/components/MessageInput/AttachmentButton.native.tsx, packages/ui/src/components/MessageInput/AttachmentButton.tsx, packages/ui/src/components/MessageInput/MessageInputBase.tsx, packages/ui/src/components/MessageInput/index.native.tsx, packages/ui/src/components/MessageInput/index.tsx
Fixes TLON-2032 by blurring the message input when we pop the attachment sheet open.
=> native: blur message input when adding an attachment

packages/ui/src/components/Channel/Scroller.tsx, packages/ui/src/components/Channel/index.tsx, packages/ui/src/components/DetailView/DetailView.tsx, packages/ui/src/components/PostScreenView.tsx
Fixes TLON-1995
Fixes TLON-1996
This fixes the keyboard focus jankiness we've been seeing by relying on the native OS rather than react state to dismiss the keyboard. On iOS, if the user interacts with the scroller the keyboard will automatically be dismissed. On Android, it won't, but Android has the hide keyboard button built-into the keyboard itself, and this is a normal interaction on Android.
=> native: fix keyboard focus issues by relying on the OS

apps/tlon-mobile/src/screens/ChatListScreen.tsx, packages/ui/src/components/Channel/UploadedImagePreview.tsx, packages/ui/src/components/Channel/index.tsx, packages/ui/src/components/ChannelListItem/index.tsx, packages/ui/src/components/ChannelNavSections.tsx, packages/ui/src/components/ListItem.tsx, packages/ui/src/components/ProfileScreenView.tsx
- Removes superfluous items from the profile/settings screen (Fixes TLON-2054)
- Shows the full @p on the profile/settings screen (Fixes TLON-2068)
- Eliminates empty sections in ChannelNavSections (Fixes TLON-2038)
- Ensures we always get the channel type icon in channel listings (Fixes TLON-2039)
- Rounds the corners of multi-DMs (Fixes TLON-2040)
- Eliminates bottom padding in Gallery + Notebook root views (Fixes TLON-2065)
- Disable long-press on ChatListScreen for now (Fixes TLON-1966)
=> native: low-priority omnibus

apps/tlon-mobile/src/hooks/useCalmSettings.ts, apps/tlon-mobile/src/screens/ChatListScreen.tsx, packages/ui/src/components/Avatar.tsx, packages/ui/src/components/GroupListItem/GroupListItemContent.tsx, packages/ui/src/utils/channelUtils.tsx
- Adds a useCalmSettings hook we can use outside of the channel context
- Wraps ChatListScreen in a CalmProvider (and gets the Calm settings using said hook)
- Disables group icons in GroupListItemContent if disableAvatars is set
- Changes the getChannelTitle util to use a useChannelMemberName hook, which respects disableNicknames (and gives us bare @ps for DMs in ChatList)
Calm disabled:
Calm enabled:
Fixes TLON-2070
=> native: support CalmEngine in ChatList

packages/ui/src/components/Channel/index.tsx
Fixes TLON-1913, which asks that we remove all loading spinners from the channel view.
=> native: remove loading spinner from channel view

packages/shared/src/db/modelBuilders.ts
Fixes TLON-2043. We were just taking the first part of a split string to determine post type on an optimistically created message, which won't work for dms or multiDms
=> native: fix missing author row on DMs and multiDMS

packages/shared/src/logic/utils.ts
It looks like we could have posts with inline links where the total inlines could be one rather than two, we need to account for both.
Fixes TLON-2048
=> native: better handle linked images in gallery posts
